/** 标准库帮助的精确文案表：仅替换已完整审阅的段落；未知或新增文档保留原文，避免按函数名误配重载。 */
import {RHAI_API_SIGNATURES} from '../visual/rhaiApiSignatures'
import {graphStandardApiLongHelp} from './graphStandardApiLongCopy'
import type {GraphCopyLocale} from './graphSyntaxCopy'
const rows:readonly (readonly [string,string,string])[]=[
['Return the absolute value of the floating-point number.','返回浮点数的绝对值。','Gibt den Absolutwert der Gleitkommazahl zurück.'],
['Return the absolute value of the number.','返回数值的绝对值。','Gibt den Absolutwert der Zahl zurück.'],
['Return the arc-cosine of the floating-point number, in radians.','返回浮点数的反余弦，结果单位为弧度。','Gibt den Arkuskosinus der Gleitkommazahl im Bogenmaß zurück.'],
['Return the arc-hyperbolic-cosine of the floating-point number, in radians.','返回浮点数的反双曲余弦。','Gibt den inversen hyperbolischen Kosinus der Gleitkommazahl zurück.'],
['Return the arc-sine of the floating-point number, in radians.','返回浮点数的反正弦，结果单位为弧度。','Gibt den Arkussinus der Gleitkommazahl im Bogenmaß zurück.'],
['Return the arc-hyperbolic-sine of the floating-point number, in radians.','返回浮点数的反双曲正弦。','Gibt den inversen hyperbolischen Sinus der Gleitkommazahl zurück.'],
['Return the arc-tangent of the floating-point number, in radians.','返回浮点数的反正切，结果单位为弧度。','Gibt den Arkustangens der Gleitkommazahl im Bogenmaß zurück.'],
['Return the arc-tangent of the floating-point numbers `x` and `y`, in radians.','返回浮点参数 `x` 和 `y` 的二参数反正切，结果单位为弧度。','Gibt den Zweiparameter-Arkustangens der Gleitkommaparameter `x` und `y` im Bogenmaß zurück.'],
['Return the arc-hyperbolic-tangent of the floating-point number, in radians.','返回浮点数的反双曲正切。','Gibt den inversen hyperbolischen Tangens der Gleitkommazahl zurück.'],
['Return a new, empty BLOB.','返回一个新的空二进制数据块（BLOB）。','Gibt einen neuen, leeren Binärdatenblock (BLOB) zurück.'],
['Return the smallest whole number larger than or equals to the floating-point number.','向上取整，返回大于或等于该浮点数的最小整数值。','Rundet auf den kleinsten ganzzahligen Wert auf, der mindestens so groß wie die Gleitkommazahl ist.'],
['Clear the array.','清空数组。','Leert das Array.'],
['Clear the BLOB.','清空二进制数据块（BLOB）。','Leert den Binärdatenblock (BLOB).'],
['Clear the object map.','清空对象映射。','Leert die Objekt-Map.'],
['Clear the string, making it empty.','清空字符串，使其长度为零。','Leert die Zeichenfolge.'],
['Return `true` if the range contains a specified value.','如果范围包含指定值，返回 `true`。','Gibt `true` zurück, wenn der Bereich den angegebenen Wert enthält.'],
['Return the cosine of the floating-point number in radians.','返回余弦值；浮点参数表示弧度。','Gibt den Kosinus zurück; der Gleitkommaparameter ist ein Winkel im Bogenmaß.'],
['Return the hyperbolic cosine of the floating-point number in radians.','返回浮点数的双曲余弦。','Gibt den hyperbolischen Kosinus der Gleitkommazahl zurück.'],
['Convert the unit into a string in debug format.','将单元值转换为调试格式字符串。','Wandelt den Unit-Wert in eine Zeichenfolge im Debugformat um.'],
['Return the empty string.','返回空字符串。','Gibt die leere Zeichenfolge zurück.'],
['Convert the array into a string.','将数组转换为字符串。','Wandelt das Array in eine Zeichenfolge um.'],
['Convert the boolean value into a string in debug format.','将布尔值转换为调试格式字符串。','Wandelt den booleschen Wert in eine Zeichenfolge im Debugformat um.'],
['Convert the string into debug format.','将字符串转换为调试格式。','Wandelt die Zeichenfolge in das Debugformat um.'],
['Convert the value of the `item` into a string in debug format.','将 `item` 的值转换为调试格式字符串。','Wandelt den Wert von `item` in eine Zeichenfolge im Debugformat um.'],
['Convert the value of `number` into a string.','将 `number` 的值转换为字符串。','Wandelt den Wert von `number` in eine Zeichenfolge um.'],
['Convert the function pointer into a string in debug format.','将函数指针转换为调试格式字符串。','Wandelt den Funktionszeiger in eine Zeichenfolge im Debugformat um.'],
['Convert the object map into a string.','将对象映射转换为字符串。','Wandelt die Objekt-Map in eine Zeichenfolge um.'],
['Return the natural number _e_.','返回自然常数 _e_。','Gibt die Eulersche Zahl _e_ zurück.'],
['Return the end of the exclusive range.','返回不包含末端的范围的结束值。','Gibt den Endwert des rechts offenen Bereichs zurück.'],
['Return the end of the inclusive range.','返回包含末端的范围的结束值。','Gibt den Endwert des geschlossenen Bereichs zurück.'],
['Return the exponential of the floating-point number.','返回以自然常数 e 为底、该浮点数为指数的值。','Gibt e hoch der Gleitkommazahl zurück.'],
['Return the largest whole number less than or equals to the floating-point number.','向下取整，返回小于或等于该浮点数的最大整数值。','Rundet auf den größten ganzzahligen Wert ab, der höchstens so groß wie die Gleitkommazahl ist.'],
['Return the fractional part of the floating-point number.','返回浮点数的小数部分。','Gibt den Nachkommaanteil der Gleitkommazahl zurück.'],
['Return an array of object maps containing metadata of all script-defined functions.','返回对象映射数组，包含所有脚本定义函数的元数据。','Gibt ein Array von Objekt-Maps mit den Metadaten aller im Skript definierten Funktionen zurück.'],
['Return an array of object maps containing metadata of all script-defined functions\nmatching the specified name.','返回对象映射数组，包含名称匹配的所有脚本定义函数的元数据。','Gibt ein Array von Objekt-Maps mit den Metadaten aller im Skript definierten Funktionen mit dem angegebenen Namen zurück.'],
['Return an array of object maps containing metadata of all script-defined functions\nmatching the specified name and arity (number of parameters).','返回对象映射数组，包含名称和参数数量均匹配的脚本定义函数的元数据。','Gibt ein Array von Objekt-Maps mit den Metadaten der im Skript definierten Funktionen mit passendem Namen und passender Parameteranzahl zurück.'],
['Return the hypotenuse of a triangle with sides `x` and `y`.','返回直角边为 `x` 和 `y` 的直角三角形的斜边长度。','Gibt die Hypotenusenlänge eines rechtwinkligen Dreiecks mit den Katheten `x` und `y` zurück.'],
['Return the integral part of the floating-point number.','返回浮点数的整数部分。','Gibt den ganzzahligen Anteil der Gleitkommazahl zurück.'],
['Return true if the array is empty.','如果数组为空，返回 true。','Gibt true zurück, wenn das Array leer ist.'],
['Return true if the BLOB is empty.','如果二进制数据块为空，返回 true。','Gibt true zurück, wenn der BLOB leer ist.'],
['Return true if the map is empty.','如果映射为空，返回 true。','Gibt true zurück, wenn die Map leer ist.'],
['Return true if the range contains no items.','如果范围不包含任何项，返回 true。','Gibt true zurück, wenn der Bereich keine Elemente enthält.'],
['Return true if the string is empty.','如果字符串为空，返回 true。','Gibt true zurück, wenn die Zeichenfolge leer ist.'],
['Return true if the number is even.','如果数值为偶数，返回 true。','Gibt true zurück, wenn die Zahl gerade ist.'],
['Return `true` if the range is exclusive.','如果范围不包含末端，返回 `true`。','Gibt `true` zurück, wenn der Bereich rechts offen ist.'],
['Return `true` if the floating-point number is finite.','如果浮点数为有限值，返回 `true`。','Gibt `true` zurück, wenn die Gleitkommazahl endlich ist.'],
['Return `true` if the range is inclusive.','如果范围包含末端，返回 `true`。','Gibt `true` zurück, wenn der Bereich geschlossen ist.'],
['Return `true` if the floating-point number is infinite.','如果浮点数为无穷值，返回 `true`。','Gibt `true` zurück, wenn die Gleitkommazahl unendlich ist.'],
['Return `true` if the floating-point number is `NaN` (Not A Number).','如果浮点数为 `NaN`（非数值），返回 `true`。','Gibt `true` zurück, wenn die Gleitkommazahl `NaN` (keine Zahl) ist.'],
['Return true if the number is odd.','如果数值为奇数，返回 true。','Gibt true zurück, wenn die Zahl ungerade ist.'],
['Return true if the floating-point number is zero.','如果浮点数为零，返回 true。','Gibt true zurück, wenn die Gleitkommazahl null ist.'],
['Return true if the number is zero.','如果数值为零，返回 true。','Gibt true zurück, wenn die Zahl null ist.'],
['Number of elements in the array.','数组中的元素数量。','Anzahl der Elemente im Array.'],
['Return the number of properties in the object map.','返回对象映射中的属性数量。','Gibt die Anzahl der Eigenschaften in der Objekt-Map zurück.'],
['Return the natural log of the floating-point number.','返回浮点数的自然对数。','Gibt den natürlichen Logarithmus der Gleitkommazahl zurück.'],
['Return the log of the floating-point number with base 10.','返回浮点数以 10 为底的对数。','Gibt den Zehnerlogarithmus der Gleitkommazahl zurück.'],
['Return the log of the floating-point number with `base`.','返回浮点数以 `base` 为底的对数。','Gibt den Logarithmus der Gleitkommazahl zur Basis `base` zurück.'],
['Return the number π.','返回圆周率 π。','Gibt die Kreiszahl π zurück.'],
['Return the boolean value into a string.','将布尔值转换为字符串。','Wandelt den booleschen Wert in eine Zeichenfolge um.'],
['Return the character into a string.','将字符转换为字符串。','Wandelt das Zeichen in eine Zeichenfolge um.'],
['Convert the value of the `item` into a string.','将 `item` 的值转换为字符串。','Wandelt den Wert von `item` in eine Zeichenfolge um.'],
['Return the `string`.','返回 `string`。','Gibt `string` zurück.'],
['Return the nearest whole number closest to the floating-point number.\nRounds away from zero.','舍入到最近的整数值；恰好位于两个整数之间时向远离零的方向舍入。','Rundet auf den nächsten ganzzahligen Wert; bei gleichem Abstand wird von null weg gerundet.'],
['Return the sign (as an integer) of the number according to the following:\n* `0` if the number is zero\n* `1` if the number is positive\n* `-1` if the number is negative','返回数值符号对应的整数：零返回 `0`，正数返回 `1`，负数返回 `-1`。','Gibt das Vorzeichen als Ganzzahl zurück: `0` für null, `1` für positive und `-1` für negative Zahlen.'],
['Return the sine of the floating-point number in radians.','返回正弦值；浮点参数表示弧度。','Gibt den Sinus zurück; der Gleitkommaparameter ist ein Winkel im Bogenmaß.'],
['Return the hyperbolic sine of the floating-point number in radians.','返回浮点数的双曲正弦。','Gibt den hyperbolischen Sinus der Gleitkommazahl zurück.'],
['Return the square root of the floating-point number.','返回浮点数的平方根。','Gibt die Quadratwurzel der Gleitkommazahl zurück.'],
['Return the start of the exclusive range.','返回不包含末端的范围的起始值。','Gibt den Anfangswert des rechts offenen Bereichs zurück.'],
['Return the start of the inclusive range.','返回包含末端的范围的起始值。','Gibt den Anfangswert des geschlossenen Bereichs zurück.'],
['Return the tangent of the floating-point number in radians.','返回正切值；浮点参数表示弧度。','Gibt den Tangens zurück; der Gleitkommaparameter ist ein Winkel im Bogenmaß.'],
['Return the hyperbolic tangent of the floating-point number in radians.','返回浮点数的双曲正切。','Gibt den hyperbolischen Tangens der Gleitkommazahl zurück.'],
['Convert the `value` into a string in binary format.','将 `value` 转换为二进制格式字符串。','Wandelt `value` in eine Zeichenfolge im Binärformat um.'],
['Convert radians to degrees.','将弧度转换为角度。','Wandelt Bogenmaß in Grad um.'],
['Convert the 32-bit floating-point number to 64-bit.','将 32 位浮点数转换为 64 位浮点数。','Wandelt die 32-Bit-Gleitkommazahl in eine 64-Bit-Gleitkommazahl um.'],
['Convert the `value` into a string in hex format.','将 `value` 转换为十六进制格式字符串。','Wandelt `value` in eine Zeichenfolge im Hexadezimalformat um.'],
['Convert the floating-point number into an integer.','将浮点数转换为整数。','Wandelt die Gleitkommazahl in eine Ganzzahl um.'],
['Convert the `value` into a string in octal format.','将 `value` 转换为八进制格式字符串。','Wandelt `value` in eine Zeichenfolge im Oktalformat um.'],
['Convert degrees to radians.','将角度转换为弧度。','Wandelt Grad in Bogenmaß um.'],
]
const translations=new Map(rows.map(/** 完整原文作为键，避免同名函数不同重载的帮助互相覆盖。 */ row=>[row[0],row]))
const signatures=new Map(RHAI_API_SIGNATURES.filter(/** 只处理 WASM 节点库实际公开的标准库函数。 */ signature=>signature.available&&signature.profiles.includes('wasm')&&!signature.internal&&!signature.operator&&signature.origin==='standard-package').map(/** 以稳定签名编号查回未经改写的原始文档。 */ signature=>['rhai-api.'+signature.id,signature]))
/** 返回已审核的整段译文；未覆盖条目交回调用者原样显示，英文始终保留调用者提供的帮助。 */
export function graphStandardApiHelp(type:string,locale:GraphCopyLocale,fallback:string):string|undefined{
  const signature=signatures.get(type)
  if(!signature)return undefined
  const row=translations.get(signature.documentation)
  if(locale==='en')return fallback
  if(!row)return graphStandardApiLongHelp(signature.documentation,locale)
  return row[locale==='zh'?1:2]
}
