/** 对象所有权及继承关系界面的多语言说明。 */
export const objectOwnershipCopy = {
  en: {
    otherChoices:'Other choices',prefabLayer:'Prefab layer',baseEvents:'Base Event Sheet',logicSource:'Behavior source',
    eventDestroy:'Destroy',eventTask:'Task',destroyHint:'When this lifetime is removed, before its resources are released.',taskHint:'When the named scheduled task becomes due.',taskName:'Task name',callbackLocationFailed:'Cannot locate one unambiguous callback author in this draft.',
    title:'Object ownership',sources:'Source assets',properties:'Property ownership',events:'Event authors',composition:'Component requirements',runtime:'Runtime',authored:'Authored',baseline:'Source value',origin:'Origin',local:'Local',inherited:'Inherited',overridden:'Overridden',unresolved:'Unresolved',changed:'Changed during Play',search:'Find a property, callback or source',refresh:'Refresh runtime snapshot',runtimeHint:'Authored values are captured before Play. Runtime values are detached observations; editing them here is disabled.',scene:'Scene-authored instance','runtime-spawned':'Spawned during Play',inactive:'Editor values; runtime is stopped',noRows:'No matching entries',openSource:'Open source',openLogic:'Open callback author',openEvents:'Open Event Sheet author',locateProperty:'Find property in Inspector',missingSource:'The authoring asset is missing or invalid.',sourceChanged:'The source changed; refresh ownership before navigating.',subscriptions:'Active signal subscriptions',timers:'Timers and tasks',anySource:'Any source',allSignals:'All signals',primary:'Primary behavior',behavior:'Inherited behavior',current:'Current',generation:'Lifetime generation',required:'Required',excluded:'Excluded',snapshot:'Snapshot',blueprint:'Object Blueprint',newBlueprint:'Create from selected object',editBlueprint:'Edit blueprint',derive:'Derive child blueprint',instantiate:'Instantiate saved blueprint',name:'Name',base:'Base blueprint',prefab:'Prefab composition',eventSheet:'Event Sheet',tags:'Tags (one per line)',groups:'Groups (one per line)',save:'Save blueprint',close:'Close',cancel:'Cancel',discard:'Discard',saveFirst:'Save this draft before creating an instance.',invalid:'Correct the listed problems before saving.',saveFailed:'The blueprint could not be saved. Your draft is retained.',saved:'Blueprint saved.',instanceCreated:'Blueprint instance created.',instantiateFailed:'Instantiation failed; the scene was left unchanged.',confirmClose:'Unsaved blueprint changes',saveQuestion:'Save this blueprint draft before closing?',discardQuestion:'Discard this blueprint draft and close?',conflict:'The saved blueprint changed. Review both versions before saving.',disabledDuringPlay:'Blueprint authoring is available after Stop.',cannotCreate:'Select an object while editing to create a blueprint.',deriveName:'Child blueprint',count:'Entries',pending:'Draft',asset:'Asset',noRuntime:'No active runtime data',componentDefaults:'Component requirements describe composition ownership. Per-property values are compared with the actual prefab source.',
  },
  de: {
    otherChoices:'Weitere Optionen',prefabLayer:'Prefab-Ebene',baseEvents:'Basis-Ereignisblatt',logicSource:'Verhaltensquelle',
    eventDestroy:'Zerstören',eventTask:'Aufgabe',destroyHint:'Beim Entfernen dieser Lebenszeit, vor der Ressourcenfreigabe.',taskHint:'Wenn die benannte geplante Aufgabe fällig ist.',taskName:'Aufgabenname',callbackLocationFailed:'Kein eindeutiger Callback-Autor in diesem Entwurf gefunden.',
    title:'Objektursprung',sources:'Quelldateien',properties:'Eigenschaftsursprung',events:'Ereignisautoren',composition:'Komponentenanforderungen',runtime:'Laufzeit',authored:'Gespeicherter Entwurf',baseline:'Quellwert',origin:'Ursprung',local:'Lokal',inherited:'Geerbt',overridden:'Überschrieben',unresolved:'Ungeklärt',changed:'Während Play geändert',search:'Eigenschaft, Callback oder Quelle suchen',refresh:'Laufzeitaufnahme aktualisieren',runtimeHint:'Entwurfswerte werden vor Play erfasst. Laufzeitwerte sind getrennte Beobachtungen und hier nicht bearbeitbar.',scene:'In der Szene erstellt','runtime-spawned':'Während Play erzeugt',inactive:'Editorwerte; Laufzeit angehalten',noRows:'Keine passenden Einträge',openSource:'Quelle öffnen',openLogic:'Callback-Autor öffnen',openEvents:'Ereignisautor öffnen',locateProperty:'Eigenschaft im Inspektor finden',missingSource:'Die Quelldatei fehlt oder ist ungültig.',sourceChanged:'Die Quelle wurde geändert. Aktualisieren Sie die Ansicht.',subscriptions:'Aktive Signalabonnements',timers:'Timer und Aufgaben',anySource:'Jede Quelle',allSignals:'Alle Signale',primary:'Primärverhalten',behavior:'Geerbtes Verhalten',current:'Aktuell',generation:'Lebenszeitgeneration',required:'Erforderlich',excluded:'Ausgeschlossen',snapshot:'Aufnahme',blueprint:'Objektvorlage',newBlueprint:'Aus ausgewähltem Objekt erstellen',editBlueprint:'Vorlage bearbeiten',derive:'Abgeleitete Vorlage erstellen',instantiate:'Gespeicherte Vorlage instanziieren',name:'Name',base:'Basisvorlage',prefab:'Prefab-Zusammensetzung',eventSheet:'Ereignisblatt',tags:'Tags (eines je Zeile)',groups:'Gruppen (eine je Zeile)',save:'Vorlage speichern',close:'Schließen',cancel:'Abbrechen',discard:'Verwerfen',saveFirst:'Speichern Sie den Entwurf vor dem Instanziieren.',invalid:'Beheben Sie die aufgeführten Probleme vor dem Speichern.',saveFailed:'Speichern fehlgeschlagen. Der Entwurf bleibt erhalten.',saved:'Vorlage gespeichert.',instanceCreated:'Vorlageninstanz erstellt.',instantiateFailed:'Instanziieren fehlgeschlagen; die Szene blieb unverändert.',confirmClose:'Ungespeicherte Vorlagenänderungen',saveQuestion:'Vorlagenentwurf vor dem Schließen speichern?',discardQuestion:'Vorlagenentwurf verwerfen und schließen?',conflict:'Die gespeicherte Vorlage wurde geändert. Prüfen Sie beide Versionen.',disabledDuringPlay:'Vorlagenbearbeitung ist nach Stop verfügbar.',cannotCreate:'Wählen Sie im Bearbeitungsmodus ein Objekt.',deriveName:'Abgeleitete Vorlage',count:'Einträge',pending:'Entwurf',asset:'Datei',noRuntime:'Keine aktiven Laufzeitdaten',componentDefaults:'Komponentenanforderungen zeigen den Ursprung der Zusammensetzung. Eigenschaftswerte werden mit der tatsächlichen Prefab-Quelle verglichen.',
  },
  zh: {
    otherChoices:'其他选项',prefabLayer:'预制体层',baseEvents:'父事件表',logicSource:'行为来源',
    eventDestroy:'销毁',eventTask:'任务',destroyHint:'此生命周期移除时、释放资源前执行。',taskHint:'命名的定时任务到期时执行。',taskName:'任务名称',callbackLocationFailed:'无法在此草稿中找到唯一的回调作者。',
    title:'对象来源',sources:'来源资源',properties:'属性来源',events:'事件作者',composition:'组件要求',runtime:'运行时',authored:'编辑值',baseline:'来源值',origin:'来源',local:'本地',inherited:'继承',overridden:'已覆盖',unresolved:'未确定',changed:'运行期间已改变',search:'查找属性、回调或来源',refresh:'刷新运行时快照',runtimeHint:'编辑值在运行前记录。运行时值为独立的只读快照，不能在此修改。',scene:'场景中创建的实例','runtime-spawned':'运行时生成',inactive:'编辑器值；运行已停止',noRows:'没有匹配项',openSource:'打开来源',openLogic:'打开回调作者',openEvents:'打开事件作者',locateProperty:'在检查器中查找属性',missingSource:'来源资源缺失或无效。',sourceChanged:'来源已改变，请刷新后再跳转。',subscriptions:'当前信号订阅',timers:'计时器与任务',anySource:'任意来源',allSignals:'所有信号',primary:'主要行为',behavior:'继承行为',current:'当前值',generation:'生命周期代数',required:'必需',excluded:'排除',snapshot:'快照',blueprint:'对象蓝图',newBlueprint:'从选中对象创建',editBlueprint:'编辑蓝图',derive:'派生子蓝图',instantiate:'实例化已保存的蓝图',name:'名称',base:'基础蓝图',prefab:'预制体组成',eventSheet:'事件表',tags:'标签（每行一个）',groups:'组（每行一个）',save:'保存蓝图',close:'关闭',cancel:'取消',discard:'放弃',saveFirst:'请先保存草稿，再创建实例。',invalid:'请修正列出的问题后再保存。',saveFailed:'蓝图保存失败，草稿已保留。',saved:'蓝图已保存。',instanceCreated:'已创建蓝图实例。',instantiateFailed:'实例化失败，场景未改变。',confirmClose:'蓝图尚未保存',saveQuestion:'关闭前保存此蓝图草稿？',discardQuestion:'放弃此蓝图草稿并关闭？',conflict:'已保存的蓝图发生改变，请先比较两个版本。',disabledDuringPlay:'停止运行后可以编辑蓝图。',cannotCreate:'请在编辑模式中选择一个对象以创建蓝图。',deriveName:'子蓝图',count:'条目',pending:'草稿',asset:'资源',noRuntime:'没有活动的运行时数据',componentDefaults:'组件要求表示组成来源。每个属性的值均与实际预制体来源比较。',
  },
} as const
