import { preferencesState } from '../store/preferences'

const copy = {
  en: { amount:'Amount', emissionShape:'Emission shape', type:'Type', end:'End', operator:'Comparison operator', interruption:'Transition interruption', solo:'Solo audio bus', wet:'Wet effect mix', reduction:'Ducking reduction (dB)', importCsv:'Import localization CSV', exportCsv:'Export localization CSV', importPo:'Import localization PO', exportPo:'Export localization PO', eventKind:'Event kind', trackKind:'Track kind', enabledExit:'Enable exit time', translation:'Translation', triggerBus:'Ducking trigger bus', targetBus:'Ducking target bus', previewPreset:'Preview device preset', draftTitle:'Unsaved Event Sheet', draftMessage:'Save this Event Sheet before opening or creating another document?', saveContinue:'Save and continue', otherChoices:'Discard or cancel…', discardTitle:'Discard Event Sheet changes?', discardMessage:'Discard the current draft and continue? Cancel keeps this draft open.', discard:'Discard and continue', draftInvalid:'The Event Sheet could not be saved. Resolve its validation issues or cancel the switch.', draftStale:'The Event Sheet changed while confirmation was open. Review the current draft and try again.' },
  de: { amount:'Anteil', emissionShape:'Emissionsform', type:'Typ', end:'Ende', operator:'Vergleichsoperator', interruption:'Übergangsunterbrechung', solo:'Audiobus solo schalten', wet:'Effektanteil', reduction:'Ducking-Absenkung (dB)', importCsv:'Lokalisierungs-CSV importieren', exportCsv:'Lokalisierungs-CSV exportieren', importPo:'Lokalisierungs-PO importieren', exportPo:'Lokalisierungs-PO exportieren', eventKind:'Ereignisart', trackKind:'Spurart', enabledExit:'Ausstiegszeit aktivieren', translation:'Übersetzung', triggerBus:'Ducking-Auslöserbus', targetBus:'Ducking-Zielbus', previewPreset:'Vorschau-Geräteprofil', draftTitle:'Ungespeicherte Ereignistabelle', draftMessage:'Diese Ereignistabelle vor dem Öffnen oder Erstellen eines anderen Dokuments speichern?', saveContinue:'Speichern und fortfahren', otherChoices:'Verwerfen oder abbrechen…', discardTitle:'Änderungen der Ereignistabelle verwerfen?', discardMessage:'Aktuellen Entwurf verwerfen und fortfahren? Abbrechen lässt den Entwurf geöffnet.', discard:'Verwerfen und fortfahren', draftInvalid:'Die Ereignistabelle konnte nicht gespeichert werden. Validierungsprobleme beheben oder den Wechsel abbrechen.', draftStale:'Die Ereignistabelle wurde während der Bestätigung geändert. Aktuellen Entwurf prüfen und erneut versuchen.' },
  zh: { amount:'强度', emissionShape:'发射形状', type:'类型', end:'结束', operator:'比较运算符', interruption:'过渡中断方式', solo:'独奏音频总线', wet:'效果湿声比例', reduction:'闪避衰减（dB）', importCsv:'导入本地化 CSV', exportCsv:'导出本地化 CSV', importPo:'导入本地化 PO', exportPo:'导出本地化 PO', eventKind:'事件类型', trackKind:'轨道类型', enabledExit:'启用退出时间', translation:'译文', triggerBus:'闪避触发总线', targetBus:'闪避目标总线', previewPreset:'预览设备预设', draftTitle:'事件表尚未保存', draftMessage:'是否先保存此事件表，再打开或创建其他文档？', saveContinue:'保存并继续', otherChoices:'放弃或取消…', discardTitle:'放弃事件表更改？', discardMessage:'放弃当前草稿并继续？取消将保留当前草稿。', discard:'放弃并继续', draftInvalid:'事件表无法保存。请解决验证问题，或取消切换。', draftStale:'确认期间事件表已发生更改。请检查当前草稿后重试。' }
} as const

export type PanelControlCopyKey = keyof typeof copy.en
export function panelControlLabel(key: PanelControlCopyKey, context?: string | number): string {
  const label = copy[preferencesState.locale][key]
  return context === undefined || context === '' ? label : `${label} · ${context}`
}
