import { apiEntry } from './scriptApi'

export type RhaiTypeName = 'Unknown' | 'Unit' | 'Boolean' | 'Integer' | 'Number' | 'String' | 'Vec2' | 'Entity' | 'Resource' | 'Array' | 'Map' | 'Data' | string
export interface ScriptTypeField { name: string; type: RhaiTypeName; optional: boolean }
export interface ScriptStructure { name: string; line: number; fields: ScriptTypeField[]; documentation: string }
export interface ScriptTypeInfo { name: string; line: number; type: RhaiTypeName; declared: boolean; confidence: 'declared' | 'inferred' | 'unknown'; source: string }
export interface ScriptGenericHelper { functionName: string; parameters: string[]; constraints: Record<string, RhaiTypeName[]>; line: number }
export type ScriptStatementKind = 'declaration' | 'assignment' | 'branch' | 'loop' | 'return' | 'throw' | 'call' | 'expression'
export interface ScriptStatement { id: string; line: number; column: number; endColumn: number; depth: number; functionName: string; kind: ScriptStatementKind; normalized: string }
export interface RichScriptAnalysis { types: ScriptTypeInfo[]; structures: ScriptStructure[]; genericHelpers: ScriptGenericHelper[]; statements: ScriptStatement[]; annotationDiagnostics: Array<{ code: string; line: number; column: number; message: string }> }
export interface ModuleGraphDocument { uri: string; dependencies: string[] }
export interface ModuleGraphDiagnostic { code: 'NOVA-MODULE-002'; uri: string; dependency: string; cycle: string[]; message: string }

const TYPE_ALIASES: Record<string, RhaiTypeName> = { any:'Unknown',unknown:'Unknown',unit:'Unit',null:'Unit',bool:'Boolean',boolean:'Boolean',int:'Integer',integer:'Integer',float:'Number',number:'Number',string:'String',vec2:'Vec2',entity:'Entity',resource:'Resource',array:'Array',map:'Map',data:'Data' }
function normalizedType(value: string): RhaiTypeName { const clean=value.trim().replace(/[^A-Za-z0-9_<>,|\[\]]/g,'').slice(0,80); return TYPE_ALIASES[clean.toLowerCase()] ?? (clean || 'Unknown') }
function stableHash(value: string): string { let hash=0x811c9dc5; for(let index=0;index<value.length;index++){hash^=value.charCodeAt(index);hash=Math.imul(hash,0x01000193)} return (hash>>>0).toString(16).padStart(8,'0') }
function stripComment(line:string):string{let quote='',escaped=false;for(let index=0;index<line.length-1;index++){const character=line[index];if(escaped){escaped=false;continue}if(character==='\\'&&quote){escaped=true;continue}if(quote){if(character===quote)quote='';continue}if(character==='"'||character==="'"){quote=character;continue}if(character==='/'&&line[index+1]==='/')return line.slice(0,index)}return line}
function inferExpressionType(expression:string,known:Map<string,RhaiTypeName>):RhaiTypeName{const value=expression.trim().replace(/;$/,'').trim();if(!value)return'Unknown';if(/^(true|false)$/.test(value))return'Boolean';if(/^-?\d+$/.test(value))return'Integer';if(/^-?(?:\d+\.\d*|\d*\.\d+)(?:e[+-]?\d+)?$/i.test(value))return'Number';if(/^["'](?:\\.|[^"'])*["']$/.test(value))return'String';if(value.startsWith('#{'))return'Data';if(value.startsWith('['))return'Array';if(/^(?:vec2|position|velocity)\s*\(/i.test(value))return'Vec2';const call=value.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*\(/)?.[1];if(call){const signature=apiEntry(call)?.signature??'',result=signature.match(/->\s*([A-Za-z][A-Za-z0-9_<>,\[\]]*)/)?.[1];if(result)return normalizedType(result);if(/^(find_|spawn_|instantiate)/.test(call))return'Entity';if(/^(load_|resource_)/.test(call))return'Resource'}const identifier=value.match(/^([A-Za-z_][A-Za-z0-9_]*)$/)?.[1];if(identifier)return known.get(identifier)??'Unknown';if(/[<>]=?|==|!=|&&|\|\|/.test(value))return'Boolean';if(/[+\-*/%]/.test(value))return/\./.test(value)?'Number':'Integer';return'Unknown'}
function statementKind(code:string):ScriptStatementKind{if(/^(?:@export(?:\([^)]*\))?\s+)?let\b/.test(code))return'declaration';if(/^(?:if|else\s+if|switch)\b/.test(code))return'branch';if(/^(?:for|while|loop)\b/.test(code))return'loop';if(/^return\b/.test(code))return'return';if(/^throw\b/.test(code))return'throw';if(/^[A-Za-z_][A-Za-z0-9_.\[\]]*\s*(?:[+\-*/%]?=)/.test(code))return'assignment';if(/^[A-Za-z_][A-Za-z0-9_]*\s*\(/.test(code))return'call';return'expression'}

/** Additive 26.03 analysis. Annotations are Rhai-safe comments and never change runtime behavior.
 * `/// @struct Damage amount:Number, source:Entity?`
 * `/// @type speed: Number`
 * `/// @generic T: Entity|Resource` */
export function analyzeScript26(sourceInput:string):RichScriptAnalysis{
  const source=sourceInput.slice(0,2_000_000),lines=source.split(/\r?\n/),types:ScriptTypeInfo[]=[],structures:ScriptStructure[]=[],genericHelpers:ScriptGenericHelper[]=[],statements:ScriptStatement[]=[],annotationDiagnostics:RichScriptAnalysis['annotationDiagnostics']=[],declaredTypes=new Map<string,{type:RhaiTypeName;line:number}>(),known=new Map<string,RhaiTypeName>(),statementOccurrences=new Map<string,number>()
  let depth=0,functionName='',pendingGeneric:{parameters:string[];constraints:Record<string,RhaiTypeName[]>;line:number}|null=null
  for(let index=0;index<lines.length;index++){
    const raw=lines[index],line=index+1,typeDirective=raw.match(/^\s*\/\/\/?\s*@type\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*([^\s,;]+)/)
    if(typeDirective)declaredTypes.set(typeDirective[1],{type:normalizedType(typeDirective[2]),line})
    const structDirective=raw.match(/^\s*\/\/\/?\s*@struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*(.*)$/)
    if(structDirective){const fields:ScriptTypeField[]=[];for(const token of structDirective[2].split(',').map(value=>value.trim()).filter(Boolean).slice(0,128)){const match=token.match(/^([A-Za-z_][A-Za-z0-9_]*)(\?)?\s*:\s*([^\s]+)$/);if(!match){annotationDiagnostics.push({code:'NOVA-TYPE-002',line,column:Math.max(1,raw.indexOf(token)+1),message:`Malformed structure field “${token}”. Use name:Type.`});continue}fields.push({name:match[1],optional:Boolean(match[2]),type:normalizedType(match[3])})}structures.push({name:structDirective[1],line,fields,documentation:`Rhai map data contract with ${fields.length} field${fields.length===1?'':'s'}.`})}
    const genericDirective=raw.match(/^\s*\/\/\/?\s*@generic\s+(.+)$/)
    if(genericDirective){const constraints:Record<string,RhaiTypeName[]>={};for(const item of genericDirective[1].split(',').map(value=>value.trim()).filter(Boolean).slice(0,16)){const match=item.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.+)$/);if(!match){annotationDiagnostics.push({code:'NOVA-TYPE-003',line,column:1,message:`Malformed generic helper constraint “${item}”.`});continue}constraints[match[1]]=match[2].split('|').map(normalizedType).slice(0,16)}pendingGeneric={parameters:Object.keys(constraints),constraints,line}}
    const codeWithIndent=stripComment(raw),code=codeWithIndent.trim(),fn=code.match(/^fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(/)
    if(fn){functionName=fn[1];if(pendingGeneric){genericHelpers.push({functionName,...pendingGeneric});pendingGeneric=null}}
    const variable=code.match(/^(?:@export(?:\([^)]*\))?\s+)?let\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?::\s*([A-Za-z][A-Za-z0-9_<>,\[\]]*))?\s*=\s*(.+)$/)
    if(variable){const declared=variable[2]?normalizedType(variable[2]):declaredTypes.get(variable[1])?.type,inferred=inferExpressionType(variable[3],known),type=declared??inferred;known.set(variable[1],type);types.push({name:variable[1],line,type,declared:Boolean(declared),confidence:declared?'declared':inferred==='Unknown'?'unknown':'inferred',source:variable[3].trim().slice(0,160)});if(variable[2])annotationDiagnostics.push({code:'NOVA-TYPE-004',line,column:raw.indexOf(':')+1,message:'Inline type syntax is editor-only and not valid Rhai. Use /// @type name: Type on the preceding line.'});if(declared&&inferred!=='Unknown'&&declared!==inferred&&!(declared==='Number'&&inferred==='Integer'))annotationDiagnostics.push({code:'NOVA-TYPE-001',line,column:Math.max(1,raw.indexOf(variable[1])+1),message:`Declared ${declared} but the initializer is inferred as ${inferred}.`})}
    const executable=code&&!/^\s*(?:\/\/|\/\*|\*|use\s+["']|fn\b)/.test(code)&&!/^[{}]+;?$/.test(code)&&code!=='else {'
    if(executable){const normalized=code.replace(/\s+/g,' ').replace(/;$/,'').trim(),key=`${functionName}|${normalized}`,occurrence=(statementOccurrences.get(key)??0)+1;statementOccurrences.set(key,occurrence);const column=Math.max(1,raw.indexOf(code)+1);statements.push({id:`stmt-${stableHash(`${key}|${occurrence}`)}`,line,column,endColumn:column+code.length,depth:Math.max(0,depth),functionName,kind:statementKind(normalized),normalized})}
    const structural=code.replace(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'/g,'');depth=Math.max(0,depth+[...structural].filter(value=>value==='{').length-[...structural].filter(value=>value==='}').length);if(functionName&&depth===0)functionName=''
  }
  for(const[name,declaration]of declaredTypes)if(!types.some(item=>item.name===name))annotationDiagnostics.push({code:'NOVA-TYPE-005',line:declaration.line,column:1,message:`Type annotation targets unknown variable “${name}”.`})
  return{types:types.slice(0,50_000),structures:structures.slice(0,2_000),genericHelpers:genericHelpers.slice(0,2_000),statements:statements.slice(0,100_000),annotationDiagnostics:annotationDiagnostics.slice(0,5_000)}
}

function moduleCandidates(uri:string,dependency:string):string[]{const normalized=dependency.replace(/\\/g,'/').replace(/^\.\//,''),direct=normalized.endsWith('.rhai')?normalized:`${normalized}.rhai`,parent=uri.replace(/\\/g,'/').replace(/\/[^/]*$/,'');return[normalized,direct,`${parent}/${normalized}`,`${parent}/${direct}`,`Assets/Scripts/${normalized}`,`Assets/Scripts/${direct}`].map(value=>value.replace(/\/+/g,'/'))}
export function analyzeModuleGraph(documentsInput:ModuleGraphDocument[]):ModuleGraphDiagnostic[]{const documents=documentsInput.slice(0,10_000),byUri=new Map(documents.map(item=>[item.uri.replace(/\\/g,'/'),item])),edges=new Map<string,string[]>();for(const document of documents){const uri=document.uri.replace(/\\/g,'/'),resolved:string[]=[];for(const dependency of document.dependencies.slice(0,256)){const target=moduleCandidates(uri,dependency).map(candidate=>byUri.has(candidate)?candidate:[...byUri.keys()].find(key=>key.endsWith(`/${candidate}`))).find(Boolean);if(target)resolved.push(target)}edges.set(uri,[...new Set(resolved)])}const diagnostics:ModuleGraphDiagnostic[]=[],visited=new Set<string>(),active:string[]=[];const visit=(uri:string):void=>{const index=active.indexOf(uri);if(index>=0){const cycle=[...active.slice(index),uri];diagnostics.push({code:'NOVA-MODULE-002',uri,dependency:cycle[1]??uri,cycle,message:`Module cycle: ${cycle.join(' → ')}`});return}if(visited.has(uri))return;active.push(uri);for(const dependency of edges.get(uri)??[])visit(dependency);active.pop();visited.add(uri)};for(const uri of[...edges.keys()].sort())visit(uri);return[...new Map(diagnostics.map(item=>[item.cycle.join('|'),item])).values()].slice(0,2_000)}
export function remapStatementLines(previous:ScriptStatement[],next:ScriptStatement[],lines:number[]):Array<{from:number;to:number;statementId:string;exact:boolean}>{const nextById=new Map(next.map(item=>[item.id,item])),previousByLine=new Map(previous.map(item=>[item.line,item]));return[...new Set(lines.map(value=>Math.max(1,Math.round(value))))].map(line=>{const before=previousByLine.get(line),exact=before?nextById.get(before.id):undefined;if(exact)return{from:line,to:exact.line,statementId:exact.id,exact:true};const candidates=next.filter(item=>!before?.functionName||item.functionName===before.functionName),nearest=candidates.sort((first,second)=>Math.abs(first.line-line)-Math.abs(second.line-line)||first.line-second.line)[0];return{from:line,to:nearest?.line??line,statementId:nearest?.id??'',exact:false}})}
export function statementAtLine(analysis:RichScriptAnalysis,line:number,functionName=''):ScriptStatement|null{return analysis.statements.find(item=>item.line===line&&(!functionName||item.functionName===functionName))??null}
