import { preferencesState } from '../store/preferences'
const labels = {
  title: ['Physics and world status', 'Physik- und Weltstatus', '物理与世界状态'],
  authored: ['Authored settings', 'Bearbeitete Einstellungen', '编辑设置'],
  authoredHint: ['Distances use meters, time uses seconds, mass uses kilograms. Collider rotation uses radians internally; the main Inspector angle uses degrees. Runtime observations are read-only.', 'Abstände in Metern, Zeit in Sekunden, Masse in Kilogramm. Collider-Winkel sind intern im Bogenmaß; der Hauptinspektor zeigt Grad. Laufzeitwerte sind schreibgeschützt.', '距离单位为米，时间为秒，质量为千克。碰撞体内部角度为弧度，主检查器角度为度。运行观测值只读。'],
  runtime: ['Runtime observations', 'Laufzeitbeobachtungen', '运行观测'],
  bodies: ['Retained bodies', 'Erhaltene Körper', '保留刚体'],
  builds: ['Configuration rebuilds', 'Konfigurations-Neuaufbauten', '配置重建次数'],
  bake: ['Bake navigation', 'Navigation berechnen', '烘焙导航'],
  cancel: ['Cancel', 'Abbrechen', '取消'],
  retry: ['Retry failed or cancelled streams', 'Fehlgeschlagene oder abgebrochene Streams wiederholen', '重试失败或取消的流送'],
  cancelStreams: ['Cancel pending streams', 'Ausstehende Streams abbrechen', '取消待处理流送'],
  ready: ['Ready', 'Bereit', '就绪'],
  cancelled: ['Cancelled — retry when ready', 'Abgebrochen — bei Bedarf wiederholen', '已取消，可再次重试'],
  baking: ['Baking', 'Wird berechnet', '正在烘焙'],
  cells: ['Cells', 'Zellen', '网格单元'],
  loaded: ['Loaded / active scene cells', 'Geladene / aktive Szenenzellen', '已加载／活动场景区块'],
  origin: ['Absolute origin offset (m)', 'Absoluter Ursprungsversatz (m)', '绝对原点偏移（米）'],
  shift: ['Shift origin to selected entity', 'Ursprung zum gewählten Objekt verschieben', '将原点移至选中实体'],
  shiftHint: ['Play mode only. Preserves relative positions, native handles and velocities. Absolute coordinates equal local world position plus this offset.', 'Nur im Spielmodus. Relative Positionen, native Kennungen und Geschwindigkeiten bleiben erhalten. Absolute Koordinaten = Weltposition + Versatz.', '仅在运行模式可用，保留相对位置、原生句柄和速度。绝对坐标等于当前世界位置加此偏移。'],
  repair: ['Correct the named source, dependency or memory limit, then retry. Cancelled work does not restart automatically.', 'Die genannte Quelle, Abhängigkeit oder Speichergrenze korrigieren, dann wiederholen. Abgebrochene Arbeit startet nicht automatisch neu.', '请修复提示的源数据、依赖或内存限制后重试。取消的任务不会自动重启。'],
  bounds: ['Enter a finite number within the displayed limits. The previous value has been restored.', 'Eine endliche Zahl innerhalb der angezeigten Grenzen eingeben. Der vorherige Wert wurde wiederhergestellt.', '请输入范围内的有限数值，已恢复上一个有效值。'],
  bidirectional: ['Bidirectional link', 'Verbindung in beide Richtungen', '双向连接'],
  linkStart: ['Link start (m)', 'Verbindungsstart (m)', '连接起点（米）'],
  linkEnd: ['Link end (m)', 'Verbindungsende (m)', '连接终点（米）'],
  memory: ['Estimated memory (MiB)', 'Geschätzter Speicher (MiB)', '估算内存（MiB）'],
  trace: ['Recorded / skipped AI traces', 'Aufgezeichnete / ausgelassene KI-Spuren', '记录／跳过的 AI 跟踪'],
  query: ['Last path query (ms)', 'Letzte Pfadsuche (ms)', '最近寻路时间（毫秒）'],
  more: ['Showing the first 64 cells; use the Inspector for a selected cell.', 'Die ersten 64 Zellen werden angezeigt; einzelne Zellen im Inspektor prüfen.', '显示前 64 个区块，可在检查器中查看选中区块。'],
  ropeUnits: ['Rope radius uses meters; linear density uses kg/m. Segment count selects3–32 simulated points. Saving explicitly rebuilds the rope and rearms break state; Cancel leaves the original connection intact.', 'Seilradius in Metern, lineare Dichte in kg/m. Die Segmentzahl wählt3–32 simulierte Punkte. Speichern baut das Seil neu auf und setzt den Bruchzustand zurück; Abbrechen erhält die Verbindung.', '绳索半径单位为米，线密度为 kg/m。分段数选择3–32个模拟点。保存会显式重建绳索并重置断裂状态，取消则保留原连接。'],
  radiusHint: ['Child shape size contains the full width and height. The legacy radius field is retained for project compatibility; use size to edit a circle or ellipse.', 'Die Größe einer Teilform enthält volle Breite und Höhe. Das alte Radiusfeld bleibt zur Projektkompatibilität erhalten; Kreis oder Ellipse über Größe bearbeiten.', '子形状尺寸表示完整宽高。旧版 radius 字段仅为项目兼容而保留，请使用尺寸编辑圆或椭圆。'],
} as const
export type SimulationLabel17 = keyof typeof labels
export function simulationLabel17(key: SimulationLabel17): string { return labels[key][preferencesState.locale === 'de' ? 1 : preferencesState.locale === 'zh' ? 2 : 0] }
