/** 组件原始类型契约：列出各持久化字段允许的基本类型，供写入前校验使用。 */
// Generated by scripts/generate-v26.22-component-primitives.mjs; verify with --check.
// Declared authored primitive fields only; structured values retain their specific owners.
export const componentPrimitiveTypes: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>> = {
  "ShapeRenderer2D": {
    "enabled": [
      "boolean"
    ],
    "shape": [
      "string"
    ],
    "radiusX": [
      "number"
    ],
    "radiusY": [
      "number"
    ],
    "opacity": [
      "number"
    ],
    "strokeOpacity": [
      "number"
    ],
    "strokeWidth": [
      "number"
    ],
    "material": [
      "string"
    ],
    "filterMode": [
      "string"
    ],
    "textureAsset": [
      "null",
      "string"
    ],
    "texture": [
      "null",
      "string"
    ],
    "sortingLayer": [
      "number"
    ],
    "orderInLayer": [
      "number"
    ]
  },
  "SpriteRenderer2D": {
    "enabled": [
      "boolean"
    ],
    "spriteAsset": [
      "null",
      "string"
    ],
    "opacity": [
      "number"
    ],
    "flipX": [
      "boolean"
    ],
    "flipY": [
      "boolean"
    ],
    "sortingLayer": [
      "number"
    ],
    "orderInLayer": [
      "number"
    ],
    "material": [
      "string"
    ],
    "filterMode": [
      "string"
    ],
    "normalMapAsset": [
      "null",
      "string"
    ],
    "lightMask": [
      "number"
    ]
  },
  "TextRenderer2D": {
    "enabled": [
      "boolean"
    ],
    "text": [
      "string"
    ],
    "fontAsset": [
      "null",
      "string"
    ],
    "fontFamily": [
      "string"
    ],
    "fontSize": [
      "number"
    ],
    "fontWeight": [
      "number"
    ],
    "lineHeight": [
      "number"
    ],
    "align": [
      "string"
    ],
    "opacity": [
      "number"
    ],
    "maxWidth": [
      "number"
    ],
    "sortingLayer": [
      "number"
    ],
    "orderInLayer": [
      "number"
    ],
    "material": [
      "string"
    ]
  },
  "Camera2D": {
    "enabled": [
      "boolean"
    ],
    "active": [
      "boolean"
    ],
    "orthographicSize": [
      "number"
    ],
    "nearSortingLayer": [
      "number"
    ],
    "farSortingLayer": [
      "number"
    ],
    "pixelPerfect": [
      "boolean"
    ],
    "zoom": [
      "number"
    ],
    "previewInEditor": [
      "boolean"
    ],
    "followTargetUuid": [
      "null",
      "string"
    ],
    "priority": [
      "number"
    ],
    "stackOrder": [
      "number"
    ],
    "cullingMask": [
      "number"
    ],
    "clearColor": [
      "boolean"
    ],
    "renderTexture": [
      "string"
    ]
  },
  "Script2D": {
    "enabled": [
      "boolean"
    ],
    "scriptAsset": [
      "null",
      "string"
    ],
    "eventSheetAsset": [
      "null",
      "string"
    ],
    "objectBlueprintAsset": [
      "null",
      "string"
    ]
  },
  "Animator": {
    "enabled": [
      "boolean"
    ],
    "controllerAsset": [
      "null",
      "string"
    ],
    "speed": [
      "number"
    ],
    "autoplay": [
      "boolean"
    ]
  },
  "Skeleton2D": {
    "enabled": [
      "boolean"
    ],
    "rigAsset": [
      "null",
      "string"
    ],
    "skinAsset": [
      "null",
      "string"
    ],
    "previewEnabled": [
      "boolean"
    ]
  },
  "TimelinePlayer": {
    "enabled": [
      "boolean"
    ],
    "timelineAsset": [
      "null",
      "string"
    ],
    "autoplay": [
      "boolean"
    ],
    "loop": [
      "boolean"
    ],
    "speed": [
      "number"
    ],
    "currentTime": [
      "number"
    ],
    "playing": [
      "boolean"
    ],
    "skipped": [
      "boolean"
    ]
  },
  "AudioSource": {
    "enabled": [
      "boolean"
    ],
    "audioClip": [
      "null",
      "string"
    ],
    "volume": [
      "number"
    ],
    "pitch": [
      "number"
    ],
    "loop": [
      "boolean"
    ],
    "autoplay": [
      "boolean"
    ],
    "spatialBlend": [
      "number"
    ],
    "minDistance": [
      "number"
    ],
    "maxDistance": [
      "number"
    ],
    "bus": [
      "string"
    ],
    "attenuationCurve": [
      "string"
    ],
    "voicePriority": [
      "number"
    ],
    "polyphony": [
      "number"
    ],
    "randomPitch": [
      "number"
    ],
    "randomVolume": [
      "number"
    ],
    "virtualizeWhenLimited": [
      "boolean"
    ],
    "streamOverride": [
      "string"
    ],
    "startOffsetSeconds": [
      "number"
    ],
    "fadeInSeconds": [
      "number"
    ],
    "fadeOutSeconds": [
      "number"
    ],
    "dopplerScale": [
      "number"
    ],
    "playlistMode": [
      "string"
    ],
    "playlistIndex": [
      "number"
    ]
  },
  "AudioListener": {
    "enabled": [
      "boolean"
    ],
    "active": [
      "boolean"
    ]
  },
  "Canvas": {
    "enabled": [
      "boolean"
    ],
    "scaleWithScreen": [
      "boolean"
    ],
    "sortingOrder": [
      "number"
    ],
    "safeArea": [
      "boolean"
    ],
    "dpiScale": [
      "number"
    ],
    "localePreview": [
      "string"
    ],
    "themeAsset": [
      "null",
      "string"
    ],
    "themeVariant": [
      "string"
    ]
  },
  "RectTransform": {
    "enabled": [
      "boolean"
    ],
    "layoutMode": [
      "string"
    ],
    "anchorPreset": [
      "string"
    ],
    "horizontalPolicy": [
      "string"
    ],
    "verticalPolicy": [
      "string"
    ],
    "aspectRatio": [
      "number"
    ],
    "aspectConstraint": [
      "string"
    ],
    "mirrorInRtl": [
      "boolean"
    ],
    "zOrder": [
      "number"
    ],
    "componentSource": [
      "null",
      "string"
    ],
    "componentVariant": [
      "string"
    ],
    "focusable": [
      "boolean"
    ],
    "tabIndex": [
      "number"
    ],
    "focusUp": [
      "null",
      "string"
    ],
    "focusDown": [
      "null",
      "string"
    ],
    "focusLeft": [
      "null",
      "string"
    ],
    "focusRight": [
      "null",
      "string"
    ],
    "accessibilityRole": [
      "string"
    ],
    "accessibilityLabel": [
      "string"
    ],
    "accessibilityDescription": [
      "string"
    ],
    "accessibilityState": [
      "string"
    ],
    "accessibilityValue": [
      "string"
    ],
    "accessibilityLive": [
      "string"
    ],
    "accessibilityHidden": [
      "boolean"
    ],
    "readingOrder": [
      "number"
    ],
    "skipNavigation": [
      "boolean"
    ],
    "remapAction": [
      "string"
    ],
    "remapBindingIndex": [
      "number"
    ]
  },
  "Panel": {
    "enabled": [
      "boolean"
    ],
    "opacity": [
      "number"
    ],
    "cornerRadius": [
      "number"
    ],
    "layout": [
      "string"
    ],
    "gap": [
      "number"
    ],
    "columns": [
      "number"
    ],
    "wrap": [
      "boolean"
    ],
    "align": [
      "string"
    ],
    "justify": [
      "string"
    ],
    "clipChildren": [
      "boolean"
    ],
    "maskChildren": [
      "boolean"
    ],
    "scrollHorizontal": [
      "boolean"
    ],
    "scrollVertical": [
      "boolean"
    ],
    "showScrollbars": [
      "boolean"
    ],
    "scrollSpeed": [
      "number"
    ],
    "behavior": [
      "string"
    ],
    "visible": [
      "boolean"
    ],
    "closeOnOutside": [
      "boolean"
    ],
    "draggable": [
      "boolean"
    ],
    "dropGroup": [
      "string"
    ],
    "tooltipText": [
      "string"
    ],
    "tooltipDelay": [
      "number"
    ],
    "styleClass": [
      "string"
    ]
  },
  "Image": {
    "enabled": [
      "boolean"
    ],
    "spriteAsset": [
      "null",
      "string"
    ],
    "opacity": [
      "number"
    ],
    "preserveAspect": [
      "boolean"
    ]
  },
  "Text": {
    "enabled": [
      "boolean"
    ],
    "text": [
      "string"
    ],
    "fontAsset": [
      "null",
      "string"
    ],
    "fontFamily": [
      "string"
    ],
    "fontSize": [
      "number"
    ],
    "fontWeight": [
      "number"
    ],
    "align": [
      "string"
    ],
    "opacity": [
      "number"
    ],
    "localizationKey": [
      "string"
    ],
    "wrap": [
      "string"
    ],
    "overflow": [
      "string"
    ],
    "inputPromptAction": [
      "string"
    ],
    "captionCategory": [
      "string"
    ]
  },
  "Button": {
    "enabled": [
      "boolean"
    ],
    "interactable": [
      "boolean"
    ],
    "onPressed": [
      "string"
    ],
    "onHoverEnter": [
      "string"
    ],
    "onHoverExit": [
      "string"
    ],
    "pressAudio": [
      "null",
      "string"
    ],
    "hoverAudio": [
      "null",
      "string"
    ],
    "focusAudio": [
      "null",
      "string"
    ],
    "styleClass": [
      "string"
    ]
  },
  "Slider": {
    "enabled": [
      "boolean"
    ],
    "min": [
      "number"
    ],
    "max": [
      "number"
    ],
    "value": [
      "number"
    ],
    "wholeNumbers": [
      "boolean"
    ],
    "interactable": [
      "boolean"
    ],
    "styleClass": [
      "string"
    ]
  },
  "ProgressBar": {
    "enabled": [
      "boolean"
    ],
    "min": [
      "number"
    ],
    "max": [
      "number"
    ],
    "value": [
      "number"
    ],
    "styleClass": [
      "string"
    ]
  },
  "Checkbox": {
    "enabled": [
      "boolean"
    ],
    "checked": [
      "boolean"
    ],
    "interactable": [
      "boolean"
    ],
    "label": [
      "string"
    ],
    "localizationKey": [
      "string"
    ],
    "styleClass": [
      "string"
    ]
  },
  "TextInput": {
    "enabled": [
      "boolean"
    ],
    "value": [
      "string"
    ],
    "placeholder": [
      "string"
    ],
    "maxLength": [
      "number"
    ],
    "interactable": [
      "boolean"
    ],
    "password": [
      "boolean"
    ],
    "styleClass": [
      "string"
    ]
  },
  "TileMap2D": {
    "enabled": [
      "boolean"
    ],
    "tileSetAsset": [
      "null",
      "string"
    ],
    "width": [
      "number"
    ],
    "height": [
      "number"
    ],
    "chunkSize": [
      "number"
    ],
    "opacity": [
      "number"
    ],
    "sortingLayer": [
      "number"
    ],
    "orderInLayer": [
      "number"
    ],
    "material": [
      "string"
    ],
    "filterMode": [
      "string"
    ],
    "physicsLayer": [
      "number"
    ],
    "collisionMask": [
      "number"
    ],
    "activeLayer": [
      "number"
    ],
    "streamingEnabled": [
      "boolean"
    ],
    "streamingRadius": [
      "number"
    ],
    "bakeCollision": [
      "boolean"
    ],
    "bakeNavigation": [
      "boolean"
    ],
    "bakeOccluders": [
      "boolean"
    ],
    "revision": [
      "number"
    ]
  },
  "CharacterBody2D": {
    "enabled": [
      "boolean"
    ],
    "maxSlopeAngle": [
      "number"
    ],
    "stepHeight": [
      "number"
    ],
    "floorSnap": [
      "number"
    ],
    "safeMargin": [
      "number"
    ],
    "maxSlides": [
      "number"
    ],
    "coyoteTime": [
      "number"
    ],
    "applyPlatformVelocity": [
      "boolean"
    ],
    "collisionMask": [
      "number"
    ]
  },
  "Area2D": {
    "enabled": [
      "boolean"
    ],
    "shape": [
      "string"
    ],
    "radius": [
      "number"
    ],
    "collisionMask": [
      "number"
    ],
    "monitorable": [
      "boolean"
    ]
  },
  "AreaEffector2D": {
    "enabled": [
      "boolean"
    ],
    "priority": [
      "number"
    ]
  },
  "NavigationRegion2D": {
    "enabled": [
      "boolean"
    ],
    "cellSize": [
      "number"
    ],
    "navigationMode": [
      "string"
    ],
    "algorithm": [
      "string"
    ],
    "allowDiagonal": [
      "boolean"
    ],
    "dynamic": [
      "boolean"
    ],
    "rebakeInterval": [
      "number"
    ],
    "navigationLayer": [
      "number"
    ],
    "navigationMask": [
      "number"
    ],
    "traversalCost": [
      "number"
    ],
    "source": [
      "string"
    ],
    "sourceEntityUuid": [
      "null",
      "string"
    ],
    "agentRadius": [
      "number"
    ],
    "clusterSize": [
      "number"
    ],
    "bakedRevision": [
      "number"
    ]
  },
  "NavigationObstacle2D": {
    "enabled": [
      "boolean"
    ],
    "shape": [
      "string"
    ],
    "radius": [
      "number"
    ],
    "dynamic": [
      "boolean"
    ],
    "navigationLayer": [
      "number"
    ]
  },
  "NavigationAgent2D": {
    "enabled": [
      "boolean"
    ],
    "targetEntityUuid": [
      "null",
      "string"
    ],
    "speed": [
      "number"
    ],
    "acceleration": [
      "number"
    ],
    "radius": [
      "number"
    ],
    "stoppingDistance": [
      "number"
    ],
    "avoidance": [
      "boolean"
    ],
    "avoidanceRadius": [
      "number"
    ],
    "pathSmoothing": [
      "boolean"
    ],
    "repathInterval": [
      "number"
    ],
    "navigationLayer": [
      "number"
    ],
    "navigationMask": [
      "number"
    ],
    "avoidancePriority": [
      "number"
    ],
    "maximumAvoidanceNeighbors": [
      "number"
    ]
  },
  "BehaviorTree2D": {
    "enabled": [
      "boolean"
    ],
    "treeAsset": [
      "null",
      "string"
    ],
    "tickRate": [
      "number"
    ]
  },
  "StateMachine2D": {
    "enabled": [
      "boolean"
    ],
    "machineAsset": [
      "null",
      "string"
    ]
  },
  "GridMover2D": {
    "enabled": [
      "boolean"
    ],
    "action": [
      "string"
    ],
    "repeatDelay": [
      "number"
    ],
    "allowDiagonal": [
      "boolean"
    ],
    "localSpace": [
      "boolean"
    ]
  },
  "PlatformController2D": {
    "enabled": [
      "boolean"
    ],
    "moveAction": [
      "string"
    ],
    "jumpAction": [
      "string"
    ],
    "speed": [
      "number"
    ],
    "acceleration": [
      "number"
    ],
    "airControl": [
      "number"
    ],
    "jumpImpulse": [
      "number"
    ],
    "maximumFallSpeed": [
      "number"
    ]
  },
  "TopDownController2D": {
    "enabled": [
      "boolean"
    ],
    "moveAction": [
      "string"
    ],
    "speed": [
      "number"
    ],
    "acceleration": [
      "number"
    ],
    "rotateToMovement": [
      "boolean"
    ]
  },
  "Health2D": {
    "enabled": [
      "boolean"
    ],
    "maximum": [
      "number"
    ],
    "current": [
      "number"
    ],
    "invulnerabilitySeconds": [
      "number"
    ],
    "destroyOnZero": [
      "boolean"
    ],
    "damagedSignal": [
      "string"
    ],
    "diedSignal": [
      "string"
    ]
  },
  "DamageHitbox2D": {
    "enabled": [
      "boolean"
    ],
    "damage": [
      "number"
    ],
    "knockback": [
      "number"
    ],
    "targetTag": [
      "string"
    ],
    "hitCooldown": [
      "number"
    ],
    "destroyOnHit": [
      "boolean"
    ],
    "hitSignal": [
      "string"
    ]
  },
  "Collectible2D": {
    "enabled": [
      "boolean"
    ],
    "collectorTag": [
      "string"
    ],
    "score": [
      "number"
    ],
    "destroyOnCollect": [
      "boolean"
    ],
    "collectedSignal": [
      "string"
    ]
  },
  "Projectile2D": {
    "enabled": [
      "boolean"
    ],
    "speed": [
      "number"
    ],
    "damage": [
      "number"
    ],
    "ownerUuid": [
      "string"
    ],
    "destroyOnImpact": [
      "boolean"
    ],
    "lifetime": [
      "number"
    ]
  },
  "Spawner2D": {
    "enabled": [
      "boolean"
    ],
    "prefabAsset": [
      "null",
      "string"
    ],
    "interval": [
      "number"
    ],
    "initialDelay": [
      "number"
    ],
    "burst": [
      "number"
    ],
    "maximumAlive": [
      "number"
    ],
    "autoStart": [
      "boolean"
    ],
    "inheritRotation": [
      "boolean"
    ]
  },
  "Cooldown2D": {
    "enabled": [
      "boolean"
    ],
    "duration": [
      "number"
    ],
    "autoStart": [
      "boolean"
    ],
    "readySignal": [
      "string"
    ]
  },
  "Lifetime2D": {
    "enabled": [
      "boolean"
    ],
    "seconds": [
      "number"
    ],
    "useDespawn": [
      "boolean"
    ]
  },
  "MouseFollower2D": {
    "enabled": [
      "boolean"
    ],
    "maximumSpeed": [
      "number"
    ]
  },
  "CameraFollow2D": {
    "enabled": [
      "boolean"
    ],
    "targetUuid": [
      "string"
    ],
    "targetTag": [
      "string"
    ],
    "smoothing": [
      "number"
    ],
    "followX": [
      "boolean"
    ],
    "followY": [
      "boolean"
    ]
  },
  "WorldChunk2D": {
    "enabled": [
      "boolean"
    ],
    "loadDistance": [
      "number"
    ],
    "unloadDistance": [
      "number"
    ],
    "preloadPriority": [
      "number"
    ],
    "memoryEstimateMb": [
      "number"
    ],
    "sceneUuid": [
      "string"
    ],
    "initiallyLoaded": [
      "boolean"
    ],
    "ownership": [
      "string"
    ],
    "prefetchDistance": [
      "number"
    ],
    "cachePolicy": [
      "string"
    ],
    "saveStateKey": [
      "string"
    ]
  },
  "Portal2D": {
    "enabled": [
      "boolean"
    ],
    "targetSceneUuid": [
      "string"
    ],
    "targetPortal": [
      "string"
    ],
    "triggerRadius": [
      "number"
    ],
    "preload": [
      "boolean"
    ]
  },
  "ObjectPool2D": {
    "enabled": [
      "boolean"
    ],
    "prefabAsset": [
      "null",
      "string"
    ],
    "prewarm": [
      "number"
    ],
    "capacity": [
      "number"
    ],
    "autoExpand": [
      "boolean"
    ],
    "resetContract": [
      "string"
    ],
    "maximumLifetime": [
      "number"
    ],
    "createdCount": [
      "number"
    ],
    "reusedCount": [
      "number"
    ],
    "leakedCount": [
      "number"
    ]
  },
  "ParticleEmitter2D": {
    "enabled": [
      "boolean"
    ],
    "particleSystemAsset": [
      "null",
      "string"
    ],
    "simulationBackend": [
      "string"
    ],
    "textureAsset": [
      "null",
      "string"
    ],
    "emissionRate": [
      "number"
    ],
    "burst": [
      "number"
    ],
    "lifetime": [
      "number"
    ],
    "rotationMin": [
      "number"
    ],
    "rotationMax": [
      "number"
    ],
    "angularVelocityMin": [
      "number"
    ],
    "angularVelocityMax": [
      "number"
    ],
    "startScale": [
      "number"
    ],
    "endScale": [
      "number"
    ],
    "startOpacity": [
      "number"
    ],
    "endOpacity": [
      "number"
    ],
    "maxParticles": [
      "number"
    ],
    "autoplay": [
      "boolean"
    ],
    "looping": [
      "boolean"
    ],
    "worldSpace": [
      "boolean"
    ],
    "sortingLayer": [
      "number"
    ],
    "orderInLayer": [
      "number"
    ],
    "material": [
      "string"
    ],
    "blendMode": [
      "string"
    ],
    "emissionShape": [
      "string"
    ],
    "shapeRadius": [
      "number"
    ],
    "subEmitterUuid": [
      "null",
      "string"
    ],
    "subEmitterCount": [
      "number"
    ],
    "previewInEditor": [
      "boolean"
    ],
    "collisionMode": [
      "string"
    ],
    "collisionRestitution": [
      "number"
    ],
    "collisionLayerMask": [
      "number"
    ],
    "eventSignal": [
      "string"
    ],
    "trailEnabled": [
      "boolean"
    ],
    "trailLength": [
      "number"
    ],
    "trailWidth": [
      "number"
    ]
  },
  "Light2D": {
    "enabled": [
      "boolean"
    ],
    "lightType": [
      "string"
    ],
    "intensity": [
      "number"
    ],
    "range": [
      "number"
    ],
    "innerAngle": [
      "number"
    ],
    "outerAngle": [
      "number"
    ],
    "layerMask": [
      "number"
    ],
    "castsShadows": [
      "boolean"
    ],
    "shadowSoftness": [
      "number"
    ]
  },
  "ShadowCaster2D": {
    "enabled": [
      "boolean"
    ],
    "layerMask": [
      "number"
    ],
    "selfShadows": [
      "boolean"
    ],
    "opacity": [
      "number"
    ]
  },
  "FixedJoint2D": {
    "enabled": [
      "boolean"
    ],
    "targetEntityUuid": [
      "null",
      "string"
    ],
    "collideConnected": [
      "boolean"
    ],
    "distance": [
      "number"
    ],
    "stiffness": [
      "number"
    ],
    "damping": [
      "number"
    ],
    "limitsEnabled": [
      "boolean"
    ],
    "lowerLimit": [
      "number"
    ],
    "upperLimit": [
      "number"
    ],
    "motorEnabled": [
      "boolean"
    ],
    "motorSpeed": [
      "number"
    ],
    "maxMotorForce": [
      "number"
    ],
    "breakForce": [
      "number"
    ],
    "breakTorque": [
      "number"
    ],
    "referenceAngle": [
      "number"
    ],
    "initialized": [
      "boolean"
    ]
  },
  "WeldJoint2D": {
    "enabled": [
      "boolean"
    ],
    "targetEntityUuid": [
      "null",
      "string"
    ],
    "collideConnected": [
      "boolean"
    ],
    "distance": [
      "number"
    ],
    "stiffness": [
      "number"
    ],
    "damping": [
      "number"
    ],
    "limitsEnabled": [
      "boolean"
    ],
    "lowerLimit": [
      "number"
    ],
    "upperLimit": [
      "number"
    ],
    "motorEnabled": [
      "boolean"
    ],
    "motorSpeed": [
      "number"
    ],
    "maxMotorForce": [
      "number"
    ],
    "breakForce": [
      "number"
    ],
    "breakTorque": [
      "number"
    ],
    "referenceAngle": [
      "number"
    ],
    "initialized": [
      "boolean"
    ]
  },
  "DistanceJoint2D": {
    "enabled": [
      "boolean"
    ],
    "targetEntityUuid": [
      "null",
      "string"
    ],
    "collideConnected": [
      "boolean"
    ],
    "distance": [
      "number"
    ],
    "stiffness": [
      "number"
    ],
    "damping": [
      "number"
    ],
    "limitsEnabled": [
      "boolean"
    ],
    "lowerLimit": [
      "number"
    ],
    "upperLimit": [
      "number"
    ],
    "motorEnabled": [
      "boolean"
    ],
    "motorSpeed": [
      "number"
    ],
    "maxMotorForce": [
      "number"
    ],
    "breakForce": [
      "number"
    ],
    "breakTorque": [
      "number"
    ],
    "referenceAngle": [
      "number"
    ],
    "initialized": [
      "boolean"
    ]
  },
  "RopeJoint2D": {
    "enabled": [
      "boolean"
    ],
    "targetEntityUuid": [
      "null",
      "string"
    ],
    "collideConnected": [
      "boolean"
    ],
    "distance": [
      "number"
    ],
    "stiffness": [
      "number"
    ],
    "damping": [
      "number"
    ],
    "limitsEnabled": [
      "boolean"
    ],
    "lowerLimit": [
      "number"
    ],
    "upperLimit": [
      "number"
    ],
    "motorEnabled": [
      "boolean"
    ],
    "motorSpeed": [
      "number"
    ],
    "maxMotorForce": [
      "number"
    ],
    "breakForce": [
      "number"
    ],
    "breakTorque": [
      "number"
    ],
    "referenceAngle": [
      "number"
    ],
    "initialized": [
      "boolean"
    ]
  },
  "RevoluteJoint2D": {
    "enabled": [
      "boolean"
    ],
    "targetEntityUuid": [
      "null",
      "string"
    ],
    "collideConnected": [
      "boolean"
    ],
    "distance": [
      "number"
    ],
    "stiffness": [
      "number"
    ],
    "damping": [
      "number"
    ],
    "limitsEnabled": [
      "boolean"
    ],
    "lowerLimit": [
      "number"
    ],
    "upperLimit": [
      "number"
    ],
    "motorEnabled": [
      "boolean"
    ],
    "motorSpeed": [
      "number"
    ],
    "maxMotorForce": [
      "number"
    ],
    "breakForce": [
      "number"
    ],
    "breakTorque": [
      "number"
    ],
    "referenceAngle": [
      "number"
    ],
    "initialized": [
      "boolean"
    ]
  },
  "MotorJoint2D": {
    "enabled": [
      "boolean"
    ],
    "targetEntityUuid": [
      "null",
      "string"
    ],
    "collideConnected": [
      "boolean"
    ],
    "distance": [
      "number"
    ],
    "stiffness": [
      "number"
    ],
    "damping": [
      "number"
    ],
    "limitsEnabled": [
      "boolean"
    ],
    "lowerLimit": [
      "number"
    ],
    "upperLimit": [
      "number"
    ],
    "motorEnabled": [
      "boolean"
    ],
    "motorSpeed": [
      "number"
    ],
    "maxMotorForce": [
      "number"
    ],
    "breakForce": [
      "number"
    ],
    "breakTorque": [
      "number"
    ],
    "referenceAngle": [
      "number"
    ],
    "initialized": [
      "boolean"
    ]
  },
  "PrismaticJoint2D": {
    "enabled": [
      "boolean"
    ],
    "targetEntityUuid": [
      "null",
      "string"
    ],
    "collideConnected": [
      "boolean"
    ],
    "distance": [
      "number"
    ],
    "stiffness": [
      "number"
    ],
    "damping": [
      "number"
    ],
    "limitsEnabled": [
      "boolean"
    ],
    "lowerLimit": [
      "number"
    ],
    "upperLimit": [
      "number"
    ],
    "motorEnabled": [
      "boolean"
    ],
    "motorSpeed": [
      "number"
    ],
    "maxMotorForce": [
      "number"
    ],
    "breakForce": [
      "number"
    ],
    "breakTorque": [
      "number"
    ],
    "referenceAngle": [
      "number"
    ],
    "initialized": [
      "boolean"
    ]
  },
  "SpringJoint2D": {
    "enabled": [
      "boolean"
    ],
    "targetEntityUuid": [
      "null",
      "string"
    ],
    "collideConnected": [
      "boolean"
    ],
    "distance": [
      "number"
    ],
    "stiffness": [
      "number"
    ],
    "damping": [
      "number"
    ],
    "limitsEnabled": [
      "boolean"
    ],
    "lowerLimit": [
      "number"
    ],
    "upperLimit": [
      "number"
    ],
    "motorEnabled": [
      "boolean"
    ],
    "motorSpeed": [
      "number"
    ],
    "maxMotorForce": [
      "number"
    ],
    "breakForce": [
      "number"
    ],
    "breakTorque": [
      "number"
    ],
    "referenceAngle": [
      "number"
    ],
    "initialized": [
      "boolean"
    ]
  },
  "RigidBody2D": {
    "enabled": [
      "boolean"
    ],
    "bodyType": [
      "string"
    ],
    "massMode": [
      "string"
    ],
    "density": [
      "number"
    ],
    "mass": [
      "number"
    ],
    "autoInertia": [
      "boolean"
    ],
    "inertia": [
      "number"
    ],
    "gravityScale": [
      "number"
    ],
    "localGravity": [
      "number"
    ],
    "angularVelocity": [
      "number"
    ],
    "linearDamping": [
      "number"
    ],
    "angularDamping": [
      "number"
    ],
    "torque": [
      "number"
    ],
    "continuousCollision": [
      "string"
    ],
    "sleepingAllowed": [
      "boolean"
    ],
    "freezeRotation": [
      "boolean"
    ],
    "transformOwnership": [
      "string"
    ]
  },
  "BoxCollider2D": {
    "enabled": [
      "boolean"
    ],
    "rotation": [
      "number"
    ],
    "radiusX": [
      "number"
    ],
    "radiusY": [
      "number"
    ],
    "shapeModel": [
      "string"
    ],
    "sensor": [
      "boolean"
    ],
    "physicsLayer": [
      "number"
    ],
    "collisionMask": [
      "number"
    ],
    "oneWay": [
      "boolean"
    ],
    "materialAsset": [
      "null",
      "string"
    ]
  },
  "EllipseCollider2D": {
    "enabled": [
      "boolean"
    ],
    "rotation": [
      "number"
    ],
    "radiusX": [
      "number"
    ],
    "radiusY": [
      "number"
    ],
    "shapeModel": [
      "string"
    ],
    "sensor": [
      "boolean"
    ],
    "physicsLayer": [
      "number"
    ],
    "collisionMask": [
      "number"
    ],
    "oneWay": [
      "boolean"
    ],
    "materialAsset": [
      "null",
      "string"
    ]
  },
  "PolygonCollider2D": {
    "enabled": [
      "boolean"
    ],
    "rotation": [
      "number"
    ],
    "radiusX": [
      "number"
    ],
    "radiusY": [
      "number"
    ],
    "shapeModel": [
      "string"
    ],
    "sensor": [
      "boolean"
    ],
    "physicsLayer": [
      "number"
    ],
    "collisionMask": [
      "number"
    ],
    "oneWay": [
      "boolean"
    ],
    "materialAsset": [
      "null",
      "string"
    ]
  }
}
