/** 组件枚举契约：列出各组件字段允许的离散值，供输入及项目校验使用。 */
// Generated by scripts/generate-v26.22-component-enums.mjs; verify with --check.
// Authored scalar string enums only. Nested/asset schemas keep their own contracts.
export const componentEnumValues: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>> = {
  "ShapeRenderer2D": {
    "shape": [
      "Rectangle",
      "Ellipse",
      "Polygon",
      "Line"
    ],
    "filterMode": [
      "Nearest",
      "Linear"
    ]
  },
  "SpriteRenderer2D": {
    "filterMode": [
      "Nearest",
      "Linear"
    ]
  },
  "TextRenderer2D": {
    "align": [
      "center",
      "end",
      "left",
      "right",
      "start"
    ]
  },
  "AudioSource": {
    "attenuationCurve": [
      "Linear",
      "Inverse",
      "Exponential",
      "Custom"
    ],
    "streamOverride": [
      "ImportSetting",
      "Stream",
      "Buffer"
    ],
    "playlistMode": [
      "Single",
      "Sequential",
      "Random"
    ]
  },
  "RectTransform": {
    "layoutMode": [
      "Responsive",
      "Fixed"
    ],
    "anchorPreset": [
      "center",
      "left",
      "right",
      "top-left",
      "top",
      "top-right",
      "bottom-left",
      "bottom",
      "bottom-right",
      "stretch"
    ],
    "horizontalPolicy": [
      "Fixed",
      "Fill",
      "Content"
    ],
    "verticalPolicy": [
      "Fixed",
      "Fill",
      "Content"
    ],
    "aspectConstraint": [
      "None",
      "Fit",
      "WidthControlsHeight",
      "HeightControlsWidth"
    ],
    "accessibilityLive": [
      "Off",
      "Polite",
      "Assertive"
    ]
  },
  "Panel": {
    "layout": [
      "None",
      "Row",
      "Column",
      "Grid",
      "Flow",
      "Overlay",
      "Center",
      "Margin",
      "Aspect",
      "Split",
      "Horizontal",
      "Vertical"
    ],
    "align": [
      "Center",
      "Start",
      "End",
      "Stretch"
    ],
    "justify": [
      "Center",
      "Start",
      "End",
      "SpaceBetween"
    ],
    "behavior": [
      "Normal",
      "Modal",
      "Popup",
      "Tooltip"
    ]
  },
  "Text": {
    "align": [
      "center",
      "end",
      "left",
      "right",
      "start"
    ],
    "wrap": [
      "None",
      "Word",
      "Character"
    ],
    "overflow": [
      "Clip",
      "Ellipsis",
      "Visible"
    ],
    "captionCategory": [
      "None",
      "Dialogue",
      "Effects",
      "Music"
    ]
  },
  "TileMap2D": {
    "filterMode": [
      "Nearest",
      "Linear"
    ]
  },
  "Area2D": {
    "shape": [
      "Box",
      "Circle"
    ]
  },
  "NavigationRegion2D": {
    "navigationMode": [
      "Polygon",
      "Grid"
    ],
    "algorithm": [
      "AStar",
      "HierarchicalAStar",
      "FlowField"
    ],
    "source": [
      "SceneGeometry",
      "TileMap",
      "Manual"
    ]
  },
  "NavigationObstacle2D": {
    "shape": [
      "Box",
      "Circle"
    ]
  },
  "WorldChunk2D": {
    "cachePolicy": [
      "Release",
      "Retain",
      "LRU"
    ]
  },
  "ObjectPool2D": {
    "resetContract": [
      "TransformAndPhysics",
      "FullSerializedState",
      "CustomSignal"
    ]
  },
  "ParticleEmitter2D": {
    "simulationBackend": [
      "Auto",
      "CPU",
      "GPU"
    ],
    "blendMode": [
      "Alpha",
      "Additive"
    ],
    "emissionShape": [
      "Box",
      "Circle",
      "Point",
      "Edge"
    ],
    "collisionMode": [
      "None",
      "Bounce",
      "Stop"
    ]
  },
  "Light2D": {
    "lightType": [
      "Point",
      "Spot",
      "Directional",
      "Area"
    ]
  },
  "RigidBody2D": {
    "bodyType": [
      "Dynamic",
      "Kinematic",
      "Static"
    ],
    "massMode": [
      "Manual",
      "Automatic"
    ],
    "continuousCollision": [
      "Discrete",
      "Continuous"
    ],
    "transformOwnership": [
      "Physics",
      "Animation"
    ]
  },
  "BoxCollider2D": {
    "shapeModel": [
      "Box",
      "Circle",
      "Capsule",
      "Segment",
      "Chain",
      "WorldBoundary",
      "ConvexPolygon",
      "ConcavePolygon"
    ]
  },
  "EllipseCollider2D": {
    "shapeModel": [
      "Box",
      "Circle",
      "Capsule",
      "Segment",
      "Chain",
      "WorldBoundary",
      "ConvexPolygon",
      "ConcavePolygon"
    ]
  },
  "PolygonCollider2D": {
    "shapeModel": [
      "Box",
      "Circle",
      "Capsule",
      "Segment",
      "Chain",
      "WorldBoundary",
      "ConvexPolygon",
      "ConcavePolygon"
    ]
  }
}
