import { assetState, createTextAsset, readTextAsset, updateTextAsset } from '../assets/AssetDatabase'
import { SCRIPT_API_V2_MANIFEST } from '../editor/scriptApi'
import { compileGraph } from './graphCompiler'
import { createGraphNode, defaultVisualGraph, graphNodeDefinition } from './graphCatalog'
import { parseGraphDocument, serializeGraphDocument, type GraphCanvasScope, type GraphNode, type GraphPin, type GraphValue, type NovaGraphDocument } from './graphTypes'

export const GRAPH_LINK_PREFIX = '// @nova-graph-link '
const NODE_MARKER = /\s*\/\/ @nova-node ([0-9a-f-]{36})\s*$/i
const VARIABLE_MARKER = /\s*\/\/ @nova-variable ([0-9a-f-]{36})\s*$/i
const GENERATED_HEADER = /^\/\/ Generated by Nova_A Visual Scripting/

export interface GraphCodeSyncResult {
  graphAssetUuid: string
  graph: NovaGraphDocument
  changedNodes: string[]
  changedVariables: string[]
  rawModuleChanged: boolean
}

export interface EnsuredGraphCodeSyncResult extends GraphCodeSyncResult {
  created: boolean
  linkedScriptUuid: string
}

function graphScopes(graph: NovaGraphDocument): GraphCanvasScope[] { return [graph, ...graph.routines] }
function safeIdentifier(value: string): string { return value.replace(/[^A-Za-z0-9_]/g, '_').replace(/^[^A-Za-z_]+/, '') || 'value' }
function meaningful(lines: string[]): string[] { return lines.filter(line => line.trim() && !line.includes('__nova_graph_trace(')) }
function withoutMarker(line: string): string { return line.replace(NODE_MARKER, '').replace(VARIABLE_MARKER, '').replace(/\s+$/, '') }

function linkedGraphUuid(source: string): string {
  return source.match(/^\/\/ @nova-graph-link ([0-9a-f-]{36})\s*$/im)?.[1]?.toLowerCase() ?? ''
}

function variableLine(graph: NovaGraphDocument, line: string): string | null {
  const match = line.match(/(?:^|\s)let\s+([A-Za-z_][A-Za-z0-9_]*)\s*=/)
  if (!match) return null
  return graph.variables.find(variable => safeIdentifier(variable.name) === match[1])?.uuid ?? null
}

/** A deterministic Rhai projection. Marker comments are valid Rhai comments,
 * so the exact source is also the runtime source and can be edited normally. */
export function createLinkedRhaiSource(graphInput: NovaGraphDocument): string {
  const result = compileGraph(graphInput)
  if (!result.valid) return ''
  const mapping = new Map(result.mappings.filter(item => item.nodeUuid).map(item => [item.generatedLine, item.nodeUuid]))
  const lines = result.source.replace(/\s+$/, '').split('\n')
  const marked = lines.map((line, index) => {
    const nodeUuid = mapping.get(index + 1)
    if (nodeUuid) return `${line} // @nova-node ${nodeUuid}`
    const variableUuid = variableLine(result.graph, line)
    return variableUuid ? `${line} // @nova-variable ${variableUuid}` : line
  })
  return `${GRAPH_LINK_PREFIX}${result.graph.uuid}\n// Bidirectional projection: save this file to update the linked graph; save the graph to regenerate this file.\n${marked.join('\n')}\n`
}

interface Regions { nodes: Map<string, string[]>; variables: Map<string, string[]>; unowned: string[] }
function sourceRegions(source: string): Regions {
  const nodes = new Map<string, string[]>(), variables = new Map<string, string[]>(), unowned: string[] = []
  let currentNode = ''
  for (const raw of source.replace(/\r\n?/g, '\n').split('\n')) {
    const node = raw.match(NODE_MARKER)?.[1]?.toLowerCase() ?? ''
    const variable = raw.match(VARIABLE_MARKER)?.[1]?.toLowerCase() ?? ''
    const line = withoutMarker(raw)
    if (node) {
      currentNode = node
      nodes.set(node, [...(nodes.get(node) ?? []), line])
      continue
    }
    if (variable) {
      currentNode = ''
      variables.set(variable, [...(variables.get(variable) ?? []), line])
      continue
    }
    if (line.startsWith(GRAPH_LINK_PREFIX) || /^\/\/ Bidirectional projection:/.test(line) || GENERATED_HEADER.test(line)) continue
    if (!line.trim()) { currentNode = ''; continue }
    if (currentNode && /^\s+/.test(raw) && !/^\s*\/\//.test(line)) nodes.set(currentNode, [...(nodes.get(currentNode) ?? []), line])
    else if (!/^\s*\/\//.test(line)) { currentNode = ''; unowned.push(line) }
  }
  return { nodes, variables, unowned }
}

function splitArguments(source: string): string[] {
  const values: string[] = []
  let quote = '', escaped = false, depth = 0, start = 0
  for (let index = 0; index < source.length; index++) {
    const character = source[index]
    if (quote) {
      if (escaped) escaped = false
      else if (character === '\\') escaped = true
      else if (character === quote) quote = ''
      continue
    }
    if (character === '"' || character === "'") quote = character
    else if ('([{'.includes(character)) depth++
    else if (')]}'.includes(character)) depth--
    else if (character === ',' && depth === 0) { values.push(source.slice(start, index).trim()); start = index + 1 }
  }
  values.push(source.slice(start).trim())
  return values.filter(Boolean)
}

function parseValue(source: string): GraphValue | undefined {
  const value = source.trim()
  if (value === '()' || value === 'null') return null
  if (value === 'true') return true
  if (value === 'false') return false
  if (/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(value)) {
    const number = Number(value)
    return Number.isFinite(number) ? number : undefined
  }
  if (/^"(?:[^"\\]|\\.)*"$/.test(value)) {
    try { return JSON.parse(value) as string } catch { return undefined }
  }
  if (value.startsWith('[') && value.endsWith(']')) {
    const members = splitArguments(value.slice(1, -1)).map(parseValue)
    return members.every(member => member !== undefined) ? members as GraphValue[] : undefined
  }
  return undefined
}

interface RhaiFunctionRegion { name: string; start: number; end: number; body: string }

function matchingBrace(source: string, opening: number): number {
  let quote = '', escaped = false, lineComment = false, blockComment = false, depth = 0
  for (let index = opening; index < source.length; index++) {
    const character = source[index], next = source[index + 1]
    if (lineComment) { if (character === '\n') lineComment = false; continue }
    if (blockComment) { if (character === '*' && next === '/') { blockComment = false; index++ }; continue }
    if (quote) { if (escaped) escaped = false; else if (character === '\\') escaped = true; else if (character === quote) quote = ''; continue }
    if (character === '/' && next === '/') { lineComment = true; index++; continue }
    if (character === '/' && next === '*') { blockComment = true; index++; continue }
    if (character === '"' || character === "'") { quote = character; continue }
    if (character === '{') depth++
    else if (character === '}' && --depth === 0) return index
  }
  return -1
}

function rhaiFunctionRegions(source: string): RhaiFunctionRegion[] {
  const result: RhaiFunctionRegion[] = [], matcher = /\bfn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\([^)]*\)\s*\{/g
  for (let match = matcher.exec(source); match; match = matcher.exec(source)) {
    const opening = source.indexOf('{', match.index), closing = matchingBrace(source, opening)
    if (closing < 0) break
    result.push({ name: match[1], start: match.index, end: closing + 1, body: source.slice(opening + 1, closing) })
    matcher.lastIndex = closing + 1
  }
  return result
}

function rhaiStatements(source: string): string[] {
  const result: string[] = []
  let quote = '', escaped = false, lineComment = false, blockComment = false, depth = 0, start = 0
  const push = (end: number) => { const value = source.slice(start, end).trim(); if (value) result.push(value); start = end }
  for (let index = 0; index < source.length; index++) {
    const character = source[index], next = source[index + 1]
    if (lineComment) { if (character === '\n') lineComment = false; continue }
    if (blockComment) { if (character === '*' && next === '/') { blockComment = false; index++ }; continue }
    if (quote) { if (escaped) escaped = false; else if (character === '\\') escaped = true; else if (character === quote) quote = ''; continue }
    if (character === '/' && next === '/') { lineComment = true; index++; continue }
    if (character === '/' && next === '*') { blockComment = true; index++; continue }
    if (character === '"' || character === "'") { quote = character; continue }
    if ('([{'.includes(character)) depth++
    else if (')]}'.includes(character)) depth = Math.max(0, depth - 1)
    if (character === ';' && depth === 0) push(index + 1)
    else if (character === '}' && depth === 0) {
      const remainder = source.slice(index + 1)
      if (!/^\s*else\b/.test(remainder)) push(index + 1)
    }
  }
  push(source.length)
  return result
}

function connectExecution(scope: GraphCanvasScope, from: GraphNode, to: GraphNode): void {
  const output = from.pins.find(pin => pin.direction === 'output' && pin.kind === 'execution' && ['next', 'completed'].includes(pin.key))
    ?? from.pins.find(pin => pin.direction === 'output' && pin.kind === 'execution')
  const input = to.pins.find(pin => pin.direction === 'input' && pin.kind === 'execution')
  if (output && input) scope.edges.push({ uuid: crypto.randomUUID().toLowerCase(), from: { nodeUuid: from.uuid, pinUuid: output.uuid }, to: { nodeUuid: to.uuid, pinUuid: input.uuid } })
}

function statementNode(statement: string, x: number, y: number, graph: NovaGraphDocument): GraphNode {
  const callableMatch = statement.match(/^(?:let\s+[A-Za-z_][A-Za-z0-9_]*\s*=\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*\(([\s\S]*)\)\s*;?$/)
  const callable = callableMatch?.[1] ?? '', definition = callable ? graphNodeDefinition(`api.${callable}`, graph, null) : null
  if (definition?.pins.some(pin => pin.kind === 'execution' && pin.direction === 'input')) {
    const node = createGraphNode(definition.type, x, y, graph)
    const inputs = node.pins.filter(pin => pin.direction === 'input' && pin.kind === 'data'), argumentsList = splitArguments(callableMatch?.[2] ?? '')
    if (argumentsList.length === inputs.length && inputs.every((pin, index) => assignInput(graph, node, pin, argumentsList[index]))) return node
    node.config.rhaiSourceOverride = statement.slice(0, 64_000)
    return node
  }
  const node = createGraphNode('code.statement', x, y, graph)
  node.config.source = statement.slice(0, 64_000)
  node.title = callable && SCRIPT_API_V2_MANIFEST.entries.some(entry => entry.callable === callable) ? callable.replace(/_/g, ' ') : 'Rhai block'
  node.category = callable ? 'Code' : 'Flow'
  return node
}

function eraseRanges(source: string, ranges: Array<{ start: number; end: number }>): string {
  const characters = source.split('')
  for (const range of ranges) for (let index = range.start; index < range.end; index++) if (characters[index] !== '\n') characters[index] = ' '
  return characters.join('')
}

/** Converts ordinary Rhai into an editable graph without discarding source.
 * Recognized lifecycle/API statements become typed blocks; unsupported syntax
 * remains a bounded Rhai block and therefore round-trips with the same behavior. */
export function createGraphFromRhaiSource(sourceInput: string, name = 'Visual Script', requestedUuid = ''): NovaGraphDocument {
  const source = sourceInput.replace(/\r\n?/g, '\n').replace(/^\/\/ @nova-graph-link [0-9a-f-]{36}\s*\n/im, '')
  const graph = defaultVisualGraph(name)
  graph.uuid = requestedUuid || graph.uuid; graph.nodes = []; graph.edges = []; graph.comments = []; graph.variables = []
  const functions = rhaiFunctionRegions(source), consumed: Array<{ start: number; end: number }> = []
  let chainIndex = 0
  for (const region of functions) {
    const eventType = `event.${region.name}`
    if (!graphNodeDefinition(eventType, graph, null)) continue
    consumed.push(region)
    const y = 90 + chainIndex * 220, event = createGraphNode(eventType, 70, y, graph)
    graph.nodes.push(event)
    let previous = event, statementIndex = 0
    for (const statement of rhaiStatements(region.body).slice(0, 2_048)) {
      const node = statementNode(statement, 360 + statementIndex * 270, y, graph)
      graph.nodes.push(node); connectExecution(graph, previous, node); previous = node; statementIndex++
    }
    chainIndex++
  }
  let remainder = eraseRanges(source, consumed)
  const variables: Array<{ start: number; end: number }> = [], variableMatcher = /(?:^|\n)([ \t]*(?:@export\([^\n]*\)\s*)?let\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^;\n]+);)/g
  for (let match = variableMatcher.exec(remainder); match; match = variableMatcher.exec(remainder)) {
    const value = parseValue(match[3]); if (value === undefined) continue
    const declarationStart = match.index + (match[0].startsWith('\n') ? 1 : 0), exposed = /@export\(/.test(match[1])
    graph.variables.push({ uuid: crypto.randomUUID().toLowerCase(), name: match[2], valueType: typeof value === 'boolean' ? 'Boolean' : typeof value === 'number' ? 'Number' : typeof value === 'string' ? 'String' : Array.isArray(value) && value.length === 2 && value.every(item => typeof item === 'number') ? 'Vec2' : 'Data', defaultValue: value, exposed, serialized: true, group: 'Graph', tooltip: '', minimum: null, maximum: null, step: typeof value === 'number' ? .01 : null, resourceType: null })
    variables.push({ start: declarationStart, end: declarationStart + match[1].length })
  }
  remainder = eraseRanges(remainder, variables).replace(/^\/\/ (?:Generated by Nova_A Visual Scripting|Bidirectional projection:|Linked \.rhai).*$/gm, '').trim()
  if (remainder) { const module = createGraphNode('code.module', 70, Math.max(360, 90 + chainIndex * 220), graph); module.config.source = remainder.slice(0, 64_000); graph.nodes.push(module) }
  return parseGraphDocument(serializeGraphDocument(graph))
}

function incomingLiteral(scope: GraphCanvasScope, node: GraphNode, pin: GraphPin): GraphNode | null {
  const edge = scope.edges.find(candidate => candidate.to.nodeUuid === node.uuid && candidate.to.pinUuid === pin.uuid)
  return edge ? scope.nodes.find(candidate => candidate.uuid === edge.from.nodeUuid && candidate.type.startsWith('literal.')) ?? null : null
}

function assignInput(scope: GraphCanvasScope, node: GraphNode, pin: GraphPin, source: string): boolean {
  const value = parseValue(source)
  if (value === undefined) return false
  const literal = incomingLiteral(scope, node, pin)
  if (literal) literal.config.value = value
  else if (!scope.edges.some(edge => edge.to.nodeUuid === node.uuid && edge.to.pinUuid === pin.uuid)) pin.defaultValue = value
  else return false
  return true
}

function applyStructuredNodeEdit(graph: NovaGraphDocument, nodeUuid: string, lines: string[]): boolean {
  const scope = graphScopes(graph).find(candidate => candidate.nodes.some(node => node.uuid === nodeUuid))
  const node = scope?.nodes.find(candidate => candidate.uuid === nodeUuid)
  if (!scope || !node || node.type.startsWith('event.') || node.type.startsWith('custom.event.') || node.type === 'routine.entry') return false
  const source = meaningful(lines).filter(line => !/^\s*[{}]\s*$/.test(line)).join('\n').trim()
  if (!source) return false
  if (node.type === 'code.module' || node.type === 'code.statement') { node.config.source = source.slice(0, 64_000); delete node.config.rhaiSourceOverride; return true }
  const callable = node.type.startsWith('api.') ? node.type.slice(4) : ''
  if (callable) {
    const match = source.match(new RegExp(`(?:let\\s+[A-Za-z_][A-Za-z0-9_]*\\s*=\\s*)?${callable}\\s*\\(([\\s\\S]*)\\)\\s*;?$`))
    if (match) {
      const inputs = node.pins.filter(pin => pin.direction === 'input' && pin.kind === 'data')
      const args = splitArguments(match[1])
      if (args.length === inputs.length && inputs.every((pin, index) => assignInput(scope, node, pin, args[index]))) {
        delete node.config.rhaiSourceOverride
        return true
      }
    }
  }
  if (node.type === 'variable.set' || node.type === 'local.set') {
    const match = source.match(/^[A-Za-z_][A-Za-z0-9_]*\s*=\s*([\s\S]+?)\s*;?$/)
    const input = node.pins.find(pin => pin.key === 'value' && pin.direction === 'input')
    if (match && input && assignInput(scope, node, input, match[1])) { delete node.config.rhaiSourceOverride; return true }
  }
  node.config.rhaiSourceOverride = source.slice(0, 64_000)
  return true
}

function applyVariableEdit(graph: NovaGraphDocument, uuid: string, lines: string[]): boolean {
  const variable = graph.variables.find(item => item.uuid === uuid)
  const source = meaningful(lines).join(' ').trim()
  const match = source.match(/^(?:@export\([^)]*\)\s*)?let\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([\s\S]+?)\s*;$/)
  if (!variable || !match) return false
  const value = parseValue(match[2])
  if (value === undefined) return false
  variable.name = match[1]
  variable.defaultValue = value
  return true
}

function synchronizeRawModule(graph: NovaGraphDocument, source: string): boolean {
  const value = source.trim().slice(0, 64_000)
  let node = graph.nodes.find(item => item.type === 'code.module')
  if (!value) {
    if (!node) return false
    graph.nodes = graph.nodes.filter(item => item.uuid !== node!.uuid)
    return true
  }
  if (!node) {
    node = createGraphNode('code.module', 80, 360, graph)
    graph.nodes.push(node)
  }
  if (node.config.source === value) return false
  node.config.source = value
  return true
}

export function applyLinkedRhaiSource(graphInput: NovaGraphDocument, source: string): Omit<GraphCodeSyncResult, 'graphAssetUuid'> {
  const graph = parseGraphDocument(serializeGraphDocument(graphInput))
  const baseline = sourceRegions(createLinkedRhaiSource(graph))
  const edited = sourceRegions(source)
  const changedNodes: string[] = [], changedVariables: string[] = []
  for (const variable of graph.variables) {
    const before = meaningful(baseline.variables.get(variable.uuid) ?? []).join('\n').trim()
    const after = meaningful(edited.variables.get(variable.uuid) ?? []).join('\n').trim()
    if (after && after !== before && applyVariableEdit(graph, variable.uuid, edited.variables.get(variable.uuid) ?? [])) changedVariables.push(variable.uuid)
  }
  for (const scope of graphScopes(graph)) for (const node of scope.nodes) {
    const before = meaningful(baseline.nodes.get(node.uuid) ?? []).join('\n').trim()
    const after = meaningful(edited.nodes.get(node.uuid) ?? []).join('\n').trim()
    if (after && after !== before && applyStructuredNodeEdit(graph, node.uuid, edited.nodes.get(node.uuid) ?? [])) changedNodes.push(node.uuid)
  }
  const rawModuleChanged = synchronizeRawModule(graph, edited.unowned.join('\n'))
  return { graph, changedNodes, changedVariables, rawModuleChanged }
}

export function createLinkedScriptName(graph: NovaGraphDocument): string { return `${graph.name} Linked` }

export function synchronizeLinkedScriptsForGraph(graph: NovaGraphDocument): string[] {
  const source = createLinkedRhaiSource(graph)
  if (!source) return []
  const updated: string[] = []
  for (const asset of assetState.records) {
    if (asset.assetType !== 'script') continue
    const current = readTextAsset(asset.uuid) ?? ''
    if (asset.script?.linkedGraphUuid !== graph.uuid && linkedGraphUuid(current) !== graph.uuid) continue
    asset.script ??= { version: 2, apiVersion: 2, breakpoints: [], breakpointDetails: [], tests: [], packageDependencies: [], packageName: '', reloadPolicy: 'preserve', signalConnections: [], recoverySource: '', lastSavedHash: '', linkedGraphUuid: graph.uuid }
    asset.script.linkedGraphUuid = graph.uuid
    if (current !== source && updateTextAsset(asset.uuid, source)) updated.push(asset.uuid)
  }
  return updated
}

export function synchronizeLinkedGraphForScript(scriptUuid: string, source: string): GraphCodeSyncResult | null {
  const script = assetState.records.find(asset => asset.uuid === scriptUuid && asset.assetType === 'script')
  const requestedGraph = script?.script?.linkedGraphUuid || linkedGraphUuid(source)
  if (!script || !requestedGraph) return null
  const graphAsset = assetState.records.find(asset => {
    if (asset.assetType !== 'visualScript') return false
    const graphSource = readTextAsset(asset.uuid)
    if (!graphSource) return false
    try { return parseGraphDocument(graphSource).uuid === requestedGraph } catch { return false }
  })
  if (!graphAsset) throw new Error(`Linked visual graph ${requestedGraph} is missing.`)
  const graphSource = readTextAsset(graphAsset.uuid)
  if (!graphSource) throw new Error('The linked visual graph source is unavailable.')
  const currentGraph = parseGraphDocument(graphSource)
  const synchronized = NODE_MARKER.test(source) || VARIABLE_MARKER.test(source)
    ? applyLinkedRhaiSource(currentGraph, source)
    : { graph: createGraphFromRhaiSource(source, currentGraph.name, currentGraph.uuid), changedNodes: currentGraph.nodes.map(node => node.uuid), changedVariables: currentGraph.variables.map(variable => variable.uuid), rawModuleChanged: true }
  if (!updateTextAsset(graphAsset.uuid, serializeGraphDocument(synchronized.graph))) throw new Error('The linked visual graph could not be saved.')
  script.script!.linkedGraphUuid = synchronized.graph.uuid
  return { graphAssetUuid: graphAsset.uuid, ...synchronized }
}

/** Ensures manual Rhai always has a visual companion. The source itself is not
 * rewritten during first linkage; saving either companion afterwards creates
 * the stable marker projection used for precise incremental synchronization. */
export function ensureLinkedGraphForScript(scriptUuid: string, source: string): EnsuredGraphCodeSyncResult | null {
  const existing = synchronizeLinkedGraphForScript(scriptUuid, source)
  if (existing) return { ...existing, created: false, linkedScriptUuid: scriptUuid }
  const script = assetState.records.find(item => item.uuid === scriptUuid && item.assetType === 'script')
  if (!script) return null
  const graph = createGraphFromRhaiSource(source, script.name.replace(/\.rhai$/i, ''))
  const graphAsset = createTextAsset(`${graph.name} Visual`, 'visualScript', serializeGraphDocument(graph), 'Assets/Visual Scripts')
  script.script ??= { version: 2, apiVersion: 2, breakpoints: [], breakpointDetails: [], tests: [], packageDependencies: [], packageName: '', reloadPolicy: 'preserve', signalConnections: [], recoverySource: '', lastSavedHash: '', linkedGraphUuid: graph.uuid }
  script.script.linkedGraphUuid = graph.uuid
  return { graphAssetUuid: graphAsset.uuid, graph, changedNodes: graph.nodes.map(node => node.uuid), changedVariables: graph.variables.map(variable => variable.uuid), rawModuleChanged: graph.nodes.some(node => node.type === 'code.module'), created: true, linkedScriptUuid: scriptUuid }
}

export function ensureLinkedScriptForGraph(graph: NovaGraphDocument): { scriptUuid: string; created: boolean } | null {
  const existing = assetState.records.find(asset => asset.assetType === 'script' && linkedScriptGraphUuid(asset.uuid) === graph.uuid)
  if (existing) { synchronizeLinkedScriptsForGraph(graph); return { scriptUuid: existing.uuid, created: false } }
  const source = createLinkedRhaiSource(graph); if (!source) return null
  const asset = createTextAsset(createLinkedScriptName(graph), 'script', source, 'Assets/Scripts/Generated')
  if (!linkScriptToGraph(asset.uuid, graph)) return null
  return { scriptUuid: asset.uuid, created: true }
}

export function linkScriptToGraph(scriptUuid: string, graph: NovaGraphDocument): boolean {
  const asset = assetState.records.find(item => item.uuid === scriptUuid && item.assetType === 'script')
  if (!asset?.script) return false
  asset.script.linkedGraphUuid = graph.uuid
  return updateTextAsset(scriptUuid, createLinkedRhaiSource(graph))
}

export function unlinkScriptFromGraph(scriptUuid: string): void {
  const asset = assetState.records.find(item => item.uuid === scriptUuid && item.assetType === 'script')
  if (asset?.script) asset.script.linkedGraphUuid = ''
}

export function linkedScriptGraphUuid(scriptUuid: string): string {
  const asset = assetState.records.find(item => item.uuid === scriptUuid && item.assetType === 'script')
  return asset?.script?.linkedGraphUuid || linkedGraphUuid(readTextAsset(scriptUuid) ?? '')
}
