<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { buildSettings } from '../runtime/buildSettings'
import { ANDROID_PERMISSIONS, androidDeliveryState, androidManifestPreview, captureAndroidLogs, deployAndroidApk, iosDeliveryStatus, refreshAndroidDevices, refreshAndroidToolchain, validateAndroidPermissions } from '../runtime/mobileDelivery'
import { OFFICIAL_ANDROID_PACKAGE_ID, enableOfficialPackage, packageEnabled } from '../runtime/packages'
import { preferencesState } from '../store/preferences'
import { pushHistory } from '../store/physics'

const apkPath=ref('')
const words={
  en:{title:'Android delivery',subtitle:'Optional, local, and explicit. No SDK or device action runs without your click.',package:'Android export package',enable:'Enable package',discover:'Discover toolchain',ready:'Ready',blocked:'Blocked',missing:'Missing',permissions:'Least permissions',purpose:'User-facing purpose',manifest:'Manifest preview',devices:'Devices',refreshDevices:'Refresh devices',apk:'Built APK path',deploy:'Install on selected device',logs:'Capture logcat',output:'Command output',ios:'iOS status',signing:'Signing',debug:'Debug/local',manual:'Manual release',none:'No connected device.',qualified:'Build is enabled only when JDK, SDK 35, build-tools, NDK, and the validated template are present.'},
  de:{title:'Android-Auslieferung',subtitle:'Optional, lokal und ausdrücklich. SDK- oder Geräteaktionen starten nur per Klick.',package:'Android-Exportpaket',enable:'Paket aktivieren',discover:'Toolchain erkennen',ready:'Bereit',blocked:'Blockiert',missing:'Fehlt',permissions:'Minimale Berechtigungen',purpose:'Angezeigter Zweck',manifest:'Manifest-Vorschau',devices:'Geräte',refreshDevices:'Geräte aktualisieren',apk:'Pfad zur gebauten APK',deploy:'Auf ausgewähltem Gerät installieren',logs:'Logcat erfassen',output:'Befehlsausgabe',ios:'iOS-Status',signing:'Signierung',debug:'Debug/lokal',manual:'Manuelle Veröffentlichung',none:'Kein verbundenes Gerät.',qualified:'Build wird nur mit JDK, SDK 35, Build-Tools, NDK und validierter Vorlage freigegeben.'},
  zh:{title:'Android 交付',subtitle:'可选、本地并且明确执行；未点击时不会运行 SDK 或设备操作。',package:'Android 导出包',enable:'启用软件包',discover:'检测工具链',ready:'就绪',blocked:'被阻止',missing:'缺少',permissions:'最小权限',purpose:'向用户说明的用途',manifest:'清单预览',devices:'设备',refreshDevices:'刷新设备',apk:'已构建 APK 路径',deploy:'安装到所选设备',logs:'捕获 logcat',output:'命令输出',ios:'iOS 状态',signing:'签名',debug:'调试/本地',manual:'手动发布',none:'没有已连接的设备。',qualified:'仅当 JDK、SDK 35、Build Tools、NDK 和已验证模板齐全时才允许构建。'}
}as const
function l(key:keyof typeof words.en):string{return(words[preferencesState.locale]??words.en)[key]}
const packageReady=computed(()=>packageEnabled(OFFICIAL_ANDROID_PACKAGE_ID))
const purposes=computed(()=>Object.fromEntries(buildSettings.platform.permissions.map(permission=>[permission,buildSettings.platform.versionMetadata[`permissionPurpose.${permission}`]??''])))
const permissionIssues=computed(()=>validateAndroidPermissions(buildSettings.platform.permissions,purposes.value))
const manifest=computed(()=>androidManifestPreview({identifier:buildSettings.platform.identifier,version:buildSettings.platform.version,orientation:buildSettings.platform.orientation,permissions:buildSettings.platform.permissions}))
const gates=computed(()=>[
  ['JDK',androidDeliveryState.status.jdkReady],['SDK',androidDeliveryState.status.sdkReady],['API 35',androidDeliveryState.status.platformReady],
  ['Build tools',androidDeliveryState.status.buildToolsReady],['NDK',androidDeliveryState.status.ndkReady],['ADB',androidDeliveryState.status.adbReady],['Template',androidDeliveryState.status.templateReady]
]as const)
function hasPermission(id:string):boolean{return buildSettings.platform.permissions.includes(id)}
function togglePermission(id:string,checked:boolean):void{const set=new Set(buildSettings.platform.permissions);checked?set.add(id):set.delete(id);buildSettings.platform.permissions=[...set].sort();pushHistory('Edit Android permissions')}
function purpose(id:string):string{return buildSettings.platform.versionMetadata[`permissionPurpose.${id}`]??''}
function setPurpose(id:string,event:Event):void{const value=(event.target as HTMLInputElement).value.trim().slice(0,500),key=`permissionPurpose.${id}`;if(value)buildSettings.platform.versionMetadata[key]=value;else delete buildSettings.platform.versionMetadata[key];pushHistory('Edit Android permission purpose')}
function enablePackage():void{enableOfficialPackage(OFFICIAL_ANDROID_PACKAGE_ID)}
onMounted(()=>void refreshAndroidToolchain())
</script>

<template>
  <section class="android-delivery">
    <header><div><strong>{{ l('title') }}</strong><p>{{ l('subtitle') }}</p></div><span :class="{ready:androidDeliveryState.status.available}">{{ androidDeliveryState.status.available?l('ready'):l('blocked') }}</span></header>
    <p class="qualification">{{ l('qualified') }}</p>
    <div class="package-row"><span>{{ l('package') }} · {{ packageReady?'✓':'—' }}</span><button v-if="!packageReady" @click="enablePackage">{{ l('enable') }}</button><button :disabled="androidDeliveryState.loading" @click="refreshAndroidToolchain">{{ l('discover') }}</button></div>
    <div class="gates"><span v-for="[name,ready] in gates" :key="name" :class="{ready}">{{ ready?'✓':'×' }} {{ name }}</span></div>
    <p v-if="androidDeliveryState.status.missing.length" class="blocked">{{ l('missing') }}: {{ androidDeliveryState.status.missing.join(' · ') }}</p>
    <details open><summary>{{ l('permissions') }} <b>{{ permissionIssues.length }}</b></summary><div class="permissions"><article v-for="permission in ANDROID_PERMISSIONS" :key="permission.id"><label><input type="checkbox" :checked="hasPermission(permission.id)" @change="togglePermission(permission.id,($event.target as HTMLInputElement).checked)"><span><strong>{{ permission.label }}</strong><small>{{ permission.id }} · {{ permission.risk }}</small></span></label><input v-if="permission.purposeRequired&&hasPermission(permission.id)" :value="purpose(permission.id)" :placeholder="l('purpose')" @change="setPurpose(permission.id,$event)"></article></div><p v-for="issue in permissionIssues" :key="`${issue.code}:${issue.permission}`" :class="issue.severity">{{ issue.code }} · {{ issue.permission }} · {{ issue.message }}</p></details>
    <details><summary>{{ l('manifest') }}</summary><pre>{{ manifest }}</pre></details>
    <details open><summary>{{ l('devices') }}</summary><div class="device-row"><button :disabled="!androidDeliveryState.status.adbReady||androidDeliveryState.loading" @click="refreshAndroidDevices">{{ l('refreshDevices') }}</button><select v-model="androidDeliveryState.selectedSerial"><option value="">{{ l('none') }}</option><option v-for="device in androidDeliveryState.devices" :key="device.serial" :value="device.serial" :disabled="device.state!=='device'">{{ device.serial }} · {{ device.state }} {{ device.description }}</option></select></div><label class="apk">{{ l('apk') }}<input v-model.trim="apkPath" placeholder="…/app-release.apk"></label><div class="device-actions"><button :disabled="!apkPath||!androidDeliveryState.selectedSerial||androidDeliveryState.deploying" @click="deployAndroidApk(apkPath)">{{ l('deploy') }}</button><button :disabled="!androidDeliveryState.selectedSerial||androidDeliveryState.loading" @click="captureAndroidLogs()">{{ l('logs') }}</button></div></details>
    <details v-if="androidDeliveryState.output" open><summary>{{ l('output') }}</summary><pre>{{ androidDeliveryState.output }}</pre></details>
    <p v-if="androidDeliveryState.error" class="error" role="alert">{{ androidDeliveryState.error }}</p>
    <div class="signing"><label>{{ l('signing') }}<select v-model="buildSettings.platform.signingMode"><option value="none">{{ l('debug') }}</option><option value="manual">{{ l('manual') }}</option></select></label><label>Identity<input v-model.trim="buildSettings.platform.signingIdentity" autocomplete="off"></label></div>
    <aside><strong>{{ l('ios') }}</strong><p>{{ iosDeliveryStatus.reason }}</p></aside>
  </section>
</template>

<style scoped>
.android-delivery{margin-top:12px;padding:11px;display:grid;gap:9px;border:1px solid var(--border-subtle);border-radius:11px;background:var(--surface-2)}.android-delivery>header{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.android-delivery>header div{min-width:0}.android-delivery>header strong{font-size:13px}.android-delivery>header p,.qualification{margin:3px 0;color:var(--text-muted);font-size:11px;line-height:1.45}.android-delivery>header>span{padding:4px 8px;border-radius:999px;color:var(--danger);background:color-mix(in srgb,var(--danger) 12%,transparent);font-size:11px}.android-delivery>header>span.ready,.gates span.ready{color:var(--success);border-color:color-mix(in srgb,var(--success) 45%,transparent);background:color-mix(in srgb,var(--success) 10%,transparent)}.package-row,.device-row,.device-actions{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.package-row>span{min-width:150px;flex:1}.android-delivery button{min-height:30px;padding:0 9px;border:1px solid var(--border-subtle);border-radius:7px;background:var(--surface-3)}.gates{display:flex;gap:5px;flex-wrap:wrap}.gates span{padding:4px 7px;border:1px solid color-mix(in srgb,var(--danger) 40%,transparent);border-radius:999px;color:var(--danger);font-size:11px}.blocked,.error{margin:0;color:var(--danger);font-size:11px;overflow-wrap:anywhere}details{border-top:1px solid var(--border-subtle);padding-top:7px}summary{cursor:pointer;font-size:11px;font-weight:650}.permissions{margin-top:7px;display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:5px}.permissions article{min-width:0;padding:6px;border-radius:7px;background:var(--surface-3)}.permissions label{display:flex;align-items:flex-start;gap:6px}.permissions label span{min-width:0;display:grid}.permissions small{overflow-wrap:anywhere;color:var(--text-muted);font-size:11px}.permissions article>input{width:100%;margin-top:5px}.android-delivery pre{max-height:210px;margin:7px 0 0;padding:8px;overflow:auto;border-radius:7px;color:var(--text-secondary);background:var(--input-bg);font:12px/1.5 var(--font-mono);white-space:pre-wrap;overflow-wrap:anywhere}.device-row select{min-width:180px;flex:1}.apk,.signing label{display:flex;flex-direction:column;gap:3px;color:var(--text-muted);font-size:11px}.apk input{width:100%}.signing{display:grid;grid-template-columns:1fr 1fr;gap:7px}.signing input,.signing select{width:100%}.android-delivery aside{padding:8px;border-radius:8px;background:var(--surface-3)}.android-delivery aside p{margin:3px 0 0;color:var(--text-muted);font-size:11px;line-height:1.45}@media(max-width:560px){.permissions,.signing{grid-template-columns:1fr}.device-row select{min-width:100%}}
</style>

