<!-- Android 交付设置：检查工具链、权限及用途，并预览清单。 -->
<script setup lang="ts">
import UiButton from '../ui/components/UiButton.vue'
import EditorIcon from './EditorIcon.vue'
import { computed, onMounted, ref } from 'vue'
import { buildSettings } from '../runtime/buildSettings'
import { ANDROID_PERMISSIONS, androidDeliveryState, androidManifestPreview, captureAndroidLogs, deployAndroidApk, iosDeliveryStatus, refreshAndroidDevices, refreshAndroidToolchain, validateAndroidPermissions } from '../runtime/mobileDelivery'
import { OFFICIAL_ANDROID_PACKAGE_ID, enableOfficialPackage, packageEnabled } from '../runtime/packages'
import { preferencesState } from '../store/preferences'
import { pushHistory } from '../store/physics'

const apkPath=ref('')
const words={
  en:{title:'Android delivery',subtitle:'Optional, local, and explicit. No SDK or device action runs without your click.',package:'Android export package',enable:'Enable package',discover:'Discover toolchain',ready:'Ready',blocked:'Blocked',missing:'Missing',permissions:'Least permissions',purpose:'User-facing purpose',manifest:'Manifest preview',devices:'Devices',refreshDevices:'Refresh devices',apk:'Built APK path',deploy:'Install on selected device',logs:'Capture logcat',output:'Command output',ios:'iOS status',signing:'Signing',debug:'Debug/local',manual:'Manual release',none:'No connected device.',qualified:'Build is enabled only when JDK, SDK 35, build-tools, NDK, and the validated template are present.'},
  de:{title:'Android-Auslieferung',subtitle:'Optional, lokal und ausdrücklich. SDK- oder Geräteaktionen starten nur per Klick.',package:'Android-Exportpaket',enable:'Paket aktivieren',discover:'Toolchain erkennen',ready:'Bereit',blocked:'Blockiert',missing:'Fehlt',permissions:'Minimale Berechtigungen',purpose:'Angezeigter Zweck',manifest:'Manifest-Vorschau',devices:'Geräte',refreshDevices:'Geräte aktualisieren',apk:'Pfad zur gebauten APK',deploy:'Auf ausgewähltem Gerät installieren',logs:'Logcat erfassen',output:'Befehlsausgabe',ios:'iOS-Status',signing:'Signierung',debug:'Debug/lokal',manual:'Manuelle Veröffentlichung',none:'Kein verbundenes Gerät.',qualified:'Build wird nur mit JDK, SDK 35, Build-Tools, NDK und validierter Vorlage freigegeben.'},
  zh:{title:'Android 交付',subtitle:'可选、本地并且明确执行；未点击时不会运行 SDK 或设备操作。',package:'Android 导出包',enable:'启用软件包',discover:'检测工具链',ready:'就绪',blocked:'被阻止',missing:'缺少',permissions:'最小权限',purpose:'向用户说明的用途',manifest:'清单预览',devices:'设备',refreshDevices:'刷新设备',apk:'已构建 APK 路径',deploy:'安装到所选设备',logs:'捕获 logcat',output:'命令输出',ios:'iOS 状态',signing:'签名',debug:'调试/本地',manual:'手动发布',none:'没有已连接的设备。',qualified:'仅当 JDK、SDK 35、Build Tools、NDK 和已验证模板齐全时才允许构建。'}
}as const
/** 按偏好语言读取本面板文案，未知语言回退英文。 */ function l(key:keyof typeof words.en):string{return(words[preferencesState.locale]??words.en)[key]}
const packageReady=computed(/** 判断官方 Android 支持包是否启用。 */ ()=>packageEnabled(OFFICIAL_ANDROID_PACKAGE_ID))
const purposes=computed(/** 将已选权限与对应用途元数据组合为映射。 */ ()=>Object.fromEntries(buildSettings.platform.permissions.map(/** 读取单项权限的用途说明，缺失时使用空文本。 */ permission=>[permission,buildSettings.platform.versionMetadata[`permissionPurpose.${permission}`]??''])))
const permissionIssues=computed(/** 校验已声明权限及用途。 */ ()=>validateAndroidPermissions(buildSettings.platform.permissions,purposes.value))
const manifest=computed(/** 根据标识符、版本、方向和权限生成 Android 清单预览。 */ ()=>androidManifestPreview({identifier:buildSettings.platform.identifier,version:buildSettings.platform.version,orientation:buildSettings.platform.orientation,permissions:buildSettings.platform.permissions}))
const gates=computed(/** 按固定顺序收集 JDK、SDK、平台、构建工具、NDK、ADB 和模板的就绪状态。 */ ()=>[
  ['JDK',androidDeliveryState.status.jdkReady],['SDK',androidDeliveryState.status.sdkReady],['API 35',androidDeliveryState.status.platformReady],
  ['Build tools',androidDeliveryState.status.buildToolsReady],['NDK',androidDeliveryState.status.ndkReady],['ADB',androidDeliveryState.status.adbReady],['Template',androidDeliveryState.status.templateReady]
]as const)
/** 检查平台设置是否已包含指定权限。 */ function hasPermission(id:string):boolean{return buildSettings.platform.permissions.includes(id)}
/** 增删权限后去重排序，并记录设置历史。 */ function togglePermission(id:string,checked:boolean):void{const set=new Set(buildSettings.platform.permissions);checked?set.add(id):set.delete(id);buildSettings.platform.permissions=[...set].sort();pushHistory('Edit Android permissions')}
/** 读取权限用途元数据，缺失时返回空文本。 */ function purpose(id:string):string{return buildSettings.platform.versionMetadata[`permissionPurpose.${id}`]??''}
/** 规范化用途输入并限制长度；空值删除元数据，然后记录历史。 */ function setPurpose(id:string,event:Event):void{const value=(event.target as HTMLInputElement).value.trim().slice(0,500),key=`permissionPurpose.${id}`;if(value)buildSettings.platform.versionMetadata[key]=value;else delete buildSettings.platform.versionMetadata[key];pushHistory('Edit Android permission purpose')}
/** 启用官方 Android 功能包。 */ function enablePackage():void{enableOfficialPackage(OFFICIAL_ANDROID_PACKAGE_ID)}
onMounted(/** 挂载时异步刷新 Android 工具链状态。 */ ()=>void refreshAndroidToolchain())
</script>

<template>
  <section class="android-delivery">
    <header><div><strong>{{ l('title') }}</strong><p>{{ l('subtitle') }}</p></div><span :class="{ready:androidDeliveryState.status.available}">{{ androidDeliveryState.status.available?l('ready'):l('blocked') }}</span></header>
    <p class="qualification">{{ l('qualified') }}</p>
    <div class="package-row"><span>{{ l('package') }} · <EditorIcon :name="packageReady ? 'check' : 'warning'" /></span><button v-if="!packageReady" @click="enablePackage">{{ l('enable') }}</button><UiButton icon="refresh" :label="l('discover')" :disabled="androidDeliveryState.loading" @click="refreshAndroidToolchain" /></div>
    <div class="gates"><span v-for="[name,ready] in gates" :key="name" :class="{ready}"><EditorIcon :name="ready ? 'check' : 'close'" /> {{ name }}</span></div>
    <p v-if="androidDeliveryState.status.missing.length" class="blocked">{{ l('missing') }}: {{ androidDeliveryState.status.missing.join(' · ') }}</p>
    <details data-ui-motion-disclosure open><summary>{{ l('permissions') }} <b>{{ permissionIssues.length }}</b></summary><div class="permissions"><article v-for="permission in ANDROID_PERMISSIONS" :key="permission.id"><label><input type="checkbox" :checked="hasPermission(permission.id)" @change="togglePermission(permission.id,($event.target as HTMLInputElement).checked)"><span><strong>{{ permission.label }}</strong><small>{{ permission.id }} · {{ permission.risk }}</small></span></label><input v-if="permission.purposeRequired&&hasPermission(permission.id)" :value="purpose(permission.id)" :placeholder="l('purpose')" @change="setPurpose(permission.id,$event)"></article></div><p v-for="issue in permissionIssues" :key="`${issue.code}:${issue.permission}`" :class="issue.severity">{{ issue.code }} · {{ issue.permission }} · {{ issue.message }}</p></details>
    <details data-ui-motion-disclosure><summary>{{ l('manifest') }}</summary><pre>{{ manifest }}</pre></details>
    <details data-ui-motion-disclosure open><summary>{{ l('devices') }}</summary><div class="device-row"><button :disabled="!androidDeliveryState.status.adbReady||androidDeliveryState.loading" @click="refreshAndroidDevices">{{ l('refreshDevices') }}</button><select v-model="androidDeliveryState.selectedSerial"><option value="">{{ l('none') }}</option><option v-for="device in androidDeliveryState.devices" :key="device.serial" :value="device.serial" :disabled="device.state!=='device'">{{ device.serial }} · {{ device.state }} {{ device.description }}</option></select></div><label class="apk">{{ l('apk') }}<input v-model.trim="apkPath" placeholder="…/app-release.apk"></label><div class="device-actions"><button :disabled="!apkPath||!androidDeliveryState.selectedSerial||androidDeliveryState.deploying" @click="deployAndroidApk(apkPath)">{{ l('deploy') }}</button><button :disabled="!androidDeliveryState.selectedSerial||androidDeliveryState.loading" @click="captureAndroidLogs()">{{ l('logs') }}</button></div></details>
    <details data-ui-motion-disclosure v-if="androidDeliveryState.output" open><summary>{{ l('output') }}</summary><pre>{{ androidDeliveryState.output }}</pre></details>
    <p v-if="androidDeliveryState.error" class="error" role="alert">{{ androidDeliveryState.error }}</p>
    <div class="signing"><label>{{ l('signing') }}<select v-model="buildSettings.platform.signingMode"><option value="none">{{ l('debug') }}</option><option value="manual">{{ l('manual') }}</option></select></label><label>Identity<input v-model.trim="buildSettings.platform.signingIdentity" autocomplete="off"></label></div>
    <aside><strong>{{ l('ios') }}</strong><p>{{ iosDeliveryStatus.reason }}</p></aside>
  </section>
</template>

<style scoped> .android-delivery{display:grid;gap:var(--ui-space-sm);padding-block:var(--ui-space-sm);border-top:1px solid var(--border-subtle);container:android-delivery/inline-size}.android-delivery>header{display:flex;align-items:flex-start;justify-content:space-between;gap:var(--ui-space-sm)}.android-delivery>header p,.qualification{margin:var(--ui-space-xs) 0;color:var(--text-muted);font-size:var(--type-caption)}.android-delivery>header>span,.blocked,.error{color:var(--danger);overflow-wrap:anywhere}.android-delivery>header>span.ready,.gates span.ready{color:var(--success)}.package-row,.device-row,.device-actions{display:flex;align-items:center;gap:var(--ui-control-gap);flex-wrap:wrap}.package-row>span{flex:1;display:flex;gap:var(--ui-space-xs);align-items:center}.gates{display:flex;gap:var(--ui-space-sm);flex-wrap:wrap}.gates span{display:flex;gap:var(--ui-space-xs);align-items:center;color:var(--danger);font-size:var(--type-caption)}details{border-top:1px solid var(--border-subtle);padding-top:var(--ui-space-xs)}.permissions{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(28ch,100%),1fr));gap:var(--ui-space-sm)}.permissions article{min-width:0;padding-block:var(--ui-space-xs);border-bottom:1px solid var(--border-subtle)}.permissions label{display:flex;align-items:flex-start;gap:var(--ui-control-gap)}.permissions label span{display:grid;min-width:0}.permissions small{overflow-wrap:anywhere;color:var(--text-muted);font-size:var(--type-caption)}.permissions article>input{width:100%;margin-top:var(--ui-space-xs)}.android-delivery pre{max-height:210px;overflow:auto;padding:var(--ui-space-sm);background:var(--input-bg);font-family:var(--font-mono);white-space:pre-wrap;overflow-wrap:anywhere}.device-row select{flex:1;min-width:16ch}.apk,.signing label{display:grid;grid-template-columns:var(--ui-label-width) minmax(0,1fr);gap:var(--ui-space-sm);align-items:center}.signing{display:grid;gap:var(--ui-space-sm)}.android-delivery aside{border-top:1px solid var(--border-subtle);padding-top:var(--ui-space-sm)}.android-delivery aside p{color:var(--text-muted);font-size:var(--type-caption)}@container android-delivery(max-width:360px){.apk,.signing label{grid-template-columns:minmax(0,1fr)}}</style>
