<template><Transition name="context"><div v-if="state.contextMenu.visible" class="context-menu" :style="position" @contextmenu.prevent @click.stop><template v-if="state.contextMenu.type === 'sidebar-entity' || state.contextMenu.type === 'grid-entity'"><button class="danger" @click="handleEntity('delete')">{{ t('deleteObject') }}</button><button v-if="state.contextMenu.type === 'grid-entity'" @click="handleEntity('duplicate')">{{ t('duplicateObject') }}</button><hr><button @click="handleEntity('front')">{{ t('moveFront') }}</button><button @click="handleEntity('back')">{{ t('moveBack') }}</button></template><template v-else-if="state.contextMenu.type === 'layer'"><button @click="handleLayer('show')">{{ t('focusLayer') }}</button><button @click="handleLayer('duplicate')">{{ t('duplicateLayer') }}</button><button class="danger" @click="handleLayer('delete')">{{ t('deleteLayer') }}</button><hr><button @click="handleLayer('front')">{{ t('moveAllFront') }}</button><button @click="handleLayer('back')">{{ t('moveAllBack') }}</button></template></div></Transition></template>
<script setup lang="ts">
import { computed } from 'vue'; import { t } from '../i18n'; import { closeContextMenu, deleteLayer, duplicateLayer, editorState as state, moveLayerToBack, moveLayerToFront, setActiveLayer } from '../store/editor'; import { deleteEntity, duplicateEntity, moveToBack, moveToFront, pushHistory } from '../store/physics'; import { preferencesState } from '../store/preferences'
const position = computed(() => ({ top: `${Math.min(state.contextMenu.y, window.innerHeight - 230)}px`, left: `${Math.min(state.contextMenu.x, window.innerWidth - 210)}px` }))
function handleEntity(action: string) { const id = state.contextMenu.targetId; if (id === null) return; if (action === 'delete') deleteEntity(id); else if (action === 'duplicate') duplicateEntity(id); else if (action === 'front') moveToFront(id); else if (action === 'back') moveToBack(id); pushHistory(); closeContextMenu() }
function handleLayer(action: string) { const layer = state.contextMenu.targetId; if (layer === null) return; if (action === 'show') setActiveLayer(layer); else if (action === 'duplicate') duplicateLayer(layer); else if (action === 'delete') { if (preferencesState.confirmDestructiveActions && !window.confirm(t('confirmLayerDelete'))) return; deleteLayer(layer) } else if (action === 'front') moveLayerToFront(layer); else if (action === 'back') moveLayerToBack(layer); closeContextMenu() }
</script>
<style scoped>
.context-menu { position: fixed; z-index: 2000; min-width: 195px; padding: 6px; display: flex; flex-direction: column; border: 1px solid var(--border-subtle); border-radius: 12px; background: var(--surface-1); backdrop-filter: var(--glass-blur); box-shadow: var(--shadow-lg); }.context-menu button { min-height: 34px; padding: 0 9px; border: 0; border-radius: 7px; color: var(--text-secondary); background: transparent; text-align: left; font-size: 12px; }.context-menu button:hover { color: var(--text-primary); background: var(--accent-soft); }.context-menu button.danger { color: var(--danger); }.context-menu button.danger:hover { background: var(--danger-soft); }.context-menu hr { width: 100%; margin: 5px 0; border: 0; border-top: 1px solid var(--border-subtle); }.context-enter-active, .context-leave-active { transition: opacity 110ms ease, transform 120ms ease; transform-origin: top left; }.context-enter-from, .context-leave-to { opacity: 0; transform: scale(.97); }
</style>
