<!-- 生态工作室：展示扩展能力、平台资格及发布证据。 -->
<template>
  <section class="ecosystem-studio" data-doc="manual/extensions-platform-delivery">
    <UiPanelHeader class="studio-header" :title="t('ecosystemStudio')" :description="t('ecosystemStudioHint')"><template #actions><output>{{ t('localFirst') }} · API {{ NOVA_PLUGIN_API_VERSION }}</output></template></UiPanelHeader>
    <UiTabs :aria-label="t('ecosystemStudio')" :items="tabs.map(tab => ({ id: tab.id, label: t(tab.label) }))" :model-value="activeTab" @update:model-value="activeTab = $event as StudioTab" />

    <main v-if="activeTab === 'extensions'" class="studio-grid extension-grid">
      <section class="card span-two">
        <header><div><strong>{{ t('pluginApiMatrix') }}</strong><small>{{ t('pluginApiMatrixHint') }}</small></div><span>{{ PLUGIN_API_MATRIX.length }}</span></header>
        <div class="api-table"><article v-for="item in PLUGIN_API_MATRIX" :key="item.kind"><b>{{ t(`contribution_${item.kind}`) }}</b><code>{{ item.permission }}</code><span>{{ item.host }}</span><code>{{ item.exportName }}</code></article></div>
      </section>
      <section class="card lifecycle-card">
        <header><strong>{{ t('extensionLifecycle') }}</strong><span>{{ pluginState.active }}/{{ pluginState.manifests.length }}</span></header>
        <dl><div><dt>{{ t('reloads') }}</dt><dd>{{ pluginState.reloads }}</dd></div><div><dt>{{ t('unloads') }}</dt><dd>{{ pluginState.unloads }}</dd></div><div><dt>{{ t('isolatedFailures') }}</dt><dd>{{ pluginState.isolatedFailures }}</dd></div><div><dt>{{ t('generation') }}</dt><dd>{{ pluginState.generation }}</dd></div></dl>
        <label class="toggle"><input :checked="pluginState.safeMode" type="checkbox" @change="setPluginSafeMode(($event.target as HTMLInputElement).checked)"><span>{{ t('pluginSafeMode') }}</span></label>
        <div class="button-row"><UiButton icon="play" :label="t('loadPlugins')" @click="pluginRuntime.start()" /><UiButton icon="refresh" :label="t('reloadAll')" @click="pluginRuntime.reload()" /><UiButton icon="stop" :label="t('unloadAll')" @click="pluginRuntime.stop()" /></div>
      </section>
      <section class="card span-two">
        <header><strong>{{ t('registeredExtensions') }}</strong><span>{{ pluginState.manifests.length }}</span></header>
        <div class="extension-list"><article v-for="manifest in pluginState.manifests" :key="manifest.id"><div><strong>{{ manifest.name }} <small>v{{ manifest.version }}</small></strong><code>{{ manifest.id }} · {{ manifest.entryType }}</code></div><span>{{ manifest.permissions.length }} {{ t('permissions') }}</span><UiButton icon="refresh" :label="t('reload') + ' · ' + manifest.name" :disabled="manifest.entryType !== 'wasm'" @click="pluginRuntime.reload(manifest.id)" /><UiButton icon="stop" :label="t('unload') + ' · ' + manifest.name" :disabled="manifest.entryType !== 'wasm'" @click="pluginRuntime.unload(manifest.id)" /></article><p v-if="!pluginState.manifests.length">{{ t('noExtensionsRegistered') }}</p></div>
      </section>
      <section class="card">
        <header><strong>{{ t('nativeExtensionAbi') }}</strong><span>ABI {{ NOVA_NATIVE_EXTENSION_ABI_VERSION }}</span></header>
        <p>{{ t('nativeExtensionAbiHint') }}</p>
        <ul><li>{{ t('sidecarIsolation') }}</li><li>{{ t('explicitPermissions') }}</li><li>{{ t('heartbeatRecovery') }}</li><li>{{ t('neverImplicitExecution') }}</li></ul>
      </section>
      <section class="card span-three">
        <header><strong>{{ t('activeContributions') }}</strong><span>{{ pluginState.contributions.length }}</span></header>
        <div class="contribution-grid"><article v-for="item in pluginState.contributions" :key="`${item.pluginId}:${item.kind}:${item.id}`"><span>{{ t(`contribution_${item.kind}`) }}</span><strong>{{ item.label }}</strong><small>{{ item.pluginName }}</small><button @click="invoke(item)">{{ t('invoke') }}</button></article><p v-if="!pluginState.contributions.length">{{ t('noActiveContributions') }}</p></div>
      </section>
    </main>

    <main v-else-if="activeTab === 'package'" class="studio-grid package-grid">
      <section class="card span-two">
        <header><div><strong>{{ t('packageWizard') }}</strong><small>{{ t('packageWizardHint') }}</small></div><span>Manifest 1</span></header>
        <div class="field-grid"><label><span>ID</span><input v-model="draft.id"></label><label><span>{{ t('name') }}</span><input v-model="draft.name"></label><label><span>{{ t('version') }}</span><input v-model="draft.version"></label><label><span>{{ t('publisher') }}</span><input v-model="draft.publisher"></label><label><span>{{ t('entryPoint') }}</span><select v-model="draft.entryPointType"><option>editor</option><option>build</option><option>importer</option><option>runtime</option><option>template</option></select></label><label><span>{{ t('license') }}</span><input v-model="draft.license"></label><label class="wide"><span>SHA-256</span><input v-model="draft.archiveSha256" maxlength="64"></label><label class="wide"><span>{{ t('permissions') }}</span><input v-model="permissionText" :placeholder="t('commaSeparated')"></label><label class="wide"><span>{{ t('documentation') }} HTTPS</span><input v-model="draft.documentationUrl" placeholder="https://"></label><label class="wide"><span>{{ t('securityPolicy') }} HTTPS</span><input v-model="draft.securityUrl" placeholder="https://"></label></div>
        <div class="button-row"><button class="primary" @click="downloadSigningRequest">{{ t('createSigningRequest') }}</button><button @click="certifyDraft">{{ t('runCertification') }}</button></div>
      </section>
      <section class="card signing-card">
        <header><strong>{{ t('publisherSigning') }}</strong><span>Ed25519</span></header><p>{{ t('publisherSigningHint') }}</p>
        <label><span>{{ t('publicKeyBase64') }}</span><textarea v-model="publicKey" rows="3"></textarea></label><label><span>{{ t('signatureBase64') }}</span><textarea v-model="signature" rows="3"></textarea></label>
        <button class="primary" :disabled="!publicKey || !signature" @click="verifySignature">{{ t('verifyAndTrust') }}</button><output :class="signatureStatus">{{ t(`signature_${signatureStatus}`) }}</output>
      </section>
      <section class="card span-two">
        <header><strong>{{ t('certificationReport') }}</strong><span :class="certification?.status">{{ certification ? t(certification.status) : t('notRun') }}</span></header>
        <div v-if="certification" class="check-list"><article v-for="check in certification.checks" :key="check.id" :class="check.status"><EditorIcon :name="check.status === 'passed' ? 'check' : 'warning'" /><strong>{{ check.id }}</strong><span>{{ check.detail }}</span></article></div><p v-else>{{ t('certificationNotRunHint') }}</p>
      </section>
      <section class="card">
        <header><strong>{{ t('localRegistry') }}</strong><span>{{ packageState.registryCatalog.length }}</span></header><p>{{ t('localRegistryHint') }}</p>
        <div class="button-row"><button @click="downloadRegistry">{{ t('exportRegistry') }}</button><button @click="registryInput?.click()">{{ t('importRegistry') }}</button></div><input ref="registryInput" hidden type="file" accept="application/json,.json" @change="readRegistry">
        <output v-if="registryResult">{{ registryResult.imported }} {{ t('imported') }} · {{ registryResult.blocked }} {{ t('blocked') }}</output>
      </section>
    </main>

    <main v-else-if="activeTab === 'templates'" class="studio-grid template-grid">
      <section class="card span-three template-toolbar"><div><strong>{{ t('exportTemplateManager') }}</strong><p>{{ t('exportTemplateManagerHint') }}</p></div><button @click="templateInput?.click()">{{ t('installOfflineTemplate') }}</button><input ref="templateInput" hidden type="file" accept="application/json,.json" @change="readTemplate"></section>
      <article v-for="template in exportTemplateState.templates" :key="template.id" class="card template-card"><header><div><strong>{{ template.name }}</strong><small>{{ template.id }}</small></div><span :class="template.installed ? 'passed' : 'pending'">{{ t(template.installed ? 'installed' : 'notInstalled') }}</span></header><dl><div><dt>{{ t('target') }}</dt><dd>{{ template.target }} · {{ template.architectures.join(', ') }}</dd></div><div><dt>{{ t('host') }}</dt><dd>{{ template.host }}</dd></div><div><dt>{{ t('runtimeMode') }}</dt><dd>{{ template.runtimeModes.join(', ') }}</dd></div></dl><p>{{ template.limitations.join(' ') }}</p></article>
<!-- 资格统计过滤回调仅统计状态为 qualified 的平台。 -->      <section class="card span-three qualification-card"><header><strong>{{ t('platformQualification') }}</strong><span>{{ qualifications.filter(item => item.status === 'qualified').length }}/{{ qualifications.length }}</span></header><article v-for="item in qualifications" :key="item.target"><b :class="item.status">{{ item.target }} · {{ t(item.status) }}</b><span v-for="gate in item.gates" :key="gate.id" :class="gate.passed ? 'passed' : gate.external ? 'pending' : 'blocked'"><EditorIcon :name="gate.passed ? 'check' : gate.external ? 'circle' : 'warning'" /> {{ gate.label }}</span></article></section>
    </main>

    <main v-else-if="activeTab === 'delivery'" class="studio-grid delivery-grid">
      <section class="card span-two"><header><div><strong>{{ t('ciMatrix') }}</strong><small>{{ t('ciMatrixHint') }}</small></div><span>v{{ NOVA_CI_MATRIX_VERSION }}</span></header><div class="ci-table"><article v-for="job in deliveryPipelineState.jobs" :key="job.id"><b>{{ job.id }}</b><span>{{ job.host }} → {{ job.target }}/{{ job.architecture }}</span><code>{{ job.templateId }}</code><strong :class="job.status">{{ t(job.status) }}</strong></article></div></section>
      <section class="card"><header><strong>{{ t('contentDelivery') }}</strong></header><label class="toggle"><input v-model="deliveryPipelineState.contentCacheEnabled" type="checkbox"><span>{{ t('contentCache') }}</span></label><label class="toggle"><input v-model="deliveryPipelineState.deltaBuildsEnabled" type="checkbox"><span>{{ t('deltaBuilds') }}</span></label><button @click="refreshKeys">{{ t('refreshCacheKeys') }}</button><code class="cache-key">{{ deliveryPipelineState.jobs[0]?.cacheKey || t('notCalculated') }}</code></section>
      <section class="card connector-editor"><header><strong>{{ t('deploymentConnectors') }}</strong><span>{{ deliveryPipelineState.connectors.length }}</span></header><label><span>{{ t('name') }}</span><input v-model="connectorDraft.name"></label><label><span>{{ t('connectorKind') }}</span><select v-model="connectorDraft.kind"><option value="local-folder">{{ t('localFolder') }}</option><option value="https-webhook">HTTPS webhook</option><option value="external-command">{{ t('externalCommand') }}</option></select></label><label><span>{{ t('destination') }}</span><input v-model="connectorDraft.destination"></label><button @click="addConnector">{{ t('addConnector') }}</button></section>
      <section class="card span-two"><header><strong>{{ t('deploymentConnectors') }}</strong><small>{{ t('neverDeploysAutomatically') }}</small></header><div class="connector-list"><article v-for="connector in deliveryPipelineState.connectors" :key="connector.id"><div><strong>{{ connector.name }}</strong><code>{{ connector.kind }} · {{ connector.destination || t('localOutput') }}</code></div><span :class="connector.permissionGranted ? 'passed' : 'pending'">{{ t(connector.permissionGranted ? 'permissionGranted' : 'permissionRequired') }}</span><button v-if="connector.kind !== 'local-folder' && !connector.permissionGranted" @click="grantConnector(connector)">{{ t('grant') }}</button><button @click="prepare(connector.id)">{{ t('preparePlan') }}</button></article></div><pre v-if="deliveryPipelineState.lastPlan">{{ JSON.stringify(deliveryPipelineState.lastPlan, null, 2) }}</pre></section>
    </main>

    <main v-else-if="activeTab === 'shipping'" class="studio-grid shipping-grid">
      <section class="card span-two publisher-card"><header><div><strong>{{ t('registryPublisherCli') }}</strong><small>{{ t('registryPublisherCliHint') }}</small></div><span>Archive 1</span></header><code>pnpm package:publisher -- pack --root Packages/MyPackage --manifest Packages/MyPackage/package.json --out Builds/MyPackage.nova-package</code><code>pnpm package:publisher -- validate --archive Builds/MyPackage.nova-package --json</code><code>pnpm package:publisher -- mirror Builds/MyPackage.nova-package --out Builds/offline-mirror</code><p>{{ t('publisherNoPrivateKeys') }}</p></section>
      <section class="card"><header><strong>{{ t('solverDiagnostics') }}</strong><span :class="solver.status">{{ t(solver.status) }}</span></header><dl><div><dt>{{ t('roots') }}</dt><dd>{{ solver.roots.length }}</dd></div><div><dt>{{ t('selected') }}</dt><dd>{{ solver.lockfile.length }}</dd></div><div><dt>{{ t('problems') }}</dt><dd>{{ solver.errors.length }}</dd></div></dl><button @click="refreshSolver">{{ t('refresh') }}</button><ul><li v-for="step in solver.steps.slice(-6)" :key="`${step.packageId}:${step.requestedBy}:${step.status}`"><b :class="step.status">{{ step.status }}</b> {{ step.packageId }} <small>{{ step.detail }}</small></li></ul></section>
      <section class="card security-card"><header><strong>{{ t('trustRevocation') }}</strong><span>{{ packageState.lastSecurityBulletin || t('notImported') }}</span></header><dl><div><dt>{{ t('trustedPublishers') }}</dt><dd>{{ packageState.publisherTrust.length }}</dd></div><div><dt>{{ t('revoked') }}</dt><dd>{{ packageState.revocations.length }}</dd></div><div><dt>{{ t('vulnerabilities') }}</dt><dd>{{ packageState.vulnerabilities.length }}</dd></div><div><dt>{{ t('quarantine') }}</dt><dd>{{ packageState.quarantine.length }}</dd></div></dl><label><span>{{ t('bulletinPublicKey') }}</span><textarea v-model="securityPublicKey" rows="2"></textarea></label><button @click="securityInput?.click()">{{ t('importSignedBulletin') }}</button><input ref="securityInput" hidden type="file" accept="application/json,.json" @change="readSecurityBulletin"><output>{{ securityStatus }}</output></section>
      <section class="card updater-card"><header><strong>{{ t('signedUpdater') }}</strong><span>{{ ecosystemShippingState.updaterStatus }}</span></header><label class="toggle"><input :checked="ecosystemShippingState.updaterOptIn" type="checkbox" @change="setUpdaterOptIn(($event.target as HTMLInputElement).checked)"><span>{{ t('optInUpdates') }}</span></label><label><span>{{ t('channel') }}</span><select v-model="ecosystemShippingState.updaterChannel"><option value="stable">stable</option><option value="preview">preview</option></select></label><button :disabled="!ecosystemShippingState.updaterOptIn" @click="updateInput?.click()">{{ t('stageSignedManifest') }}</button><input ref="updateInput" hidden type="file" accept="application/json,.json" @change="readUpdateManifest"><p>{{ t('updaterNoImplicitNetwork') }}</p><dl v-if="ecosystemShippingState.stagedUpdate"><div><dt>{{ t('version') }}</dt><dd>{{ ecosystemShippingState.stagedUpdate.from }} → {{ ecosystemShippingState.stagedUpdate.release }}</dd></div><div><dt>SHA-256</dt><dd>{{ ecosystemShippingState.stagedUpdate.artifact.sha256.slice(0, 16) }}…</dd></div></dl><output>{{ updaterMessage }}</output></section>
      <section class="card span-two"><header><strong>{{ t('matchingHostPipelines') }}</strong><span>{{ hostPipelines.length }}</span></header><div class="ci-table"><article v-for="job in hostPipelines" :key="job.id"><b>{{ job.id }}</b><span>{{ job.host }} → {{ job.target }}/{{ job.architecture }}</span><code>{{ job.command }}</code><strong :class="job.status === 'local-ready' ? 'passed' : 'pending'">{{ t(job.status) }}</strong></article></div></section>
<!-- 生命周期展示回调把每个动作映射为动作名称和待外部验证标签。 -->      <section class="card span-three"><header><strong>{{ t('shippingEvidence') }}</strong><span>{{ t('networkDisabledDefault') }}</span></header><div class="shipping-evidence"><article><b>SBOM · provenance · patch</b><p>{{ shippingEvidence.files.join(' · ') }}</p></article><article><b>{{ t('signingHooks') }}</b><p>{{ shippingEvidence.signingHooks.join(' · ') }}</p></article><article><b>{{ t('cleanMachineLifecycle') }}</b><p>{{ shippingEvidence.lifecycle.map(item => `${item.action}: ${t('pending-external')}`).join(' · ') }}</p></article></div></section>
    </main>

    <main v-else class="studio-grid audit-grid">
      <section class="card span-three"><header><div><strong>{{ t('ecosystemAudit') }}</strong><small>{{ t('ecosystemAuditHint') }}</small></div><span>{{ NOVA_ENGINE_VERSION }}</span></header><div class="audit-cards"><article v-for="audit in audits" :key="audit.id"><EditorIcon :class="audit.status" :name="audit.status === 'passed' ? 'check' : audit.status === 'blocked' ? 'warning' : 'circle'" /><div><strong>{{ t(audit.label) }}</strong><small :class="audit.status">{{ t(audit.status) }}</small><p>{{ t(audit.detail) }}</p></div></article></div></section>
    </main>
  </section>
</template>

<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import UiButton from '../ui/components/UiButton.vue'
import UiTabs from '../ui/components/UiTabs.vue'
import UiPanelHeader from '../ui/components/UiPanelHeader.vue'
import EditorIcon from './EditorIcon.vue'
import { t } from '../i18n'
import { ecosystemAuditSummary } from '../editor/ecosystemAuditSummary'
import { requestConfirmation } from '../store/dialog'
import { NOVA_ENGINE_VERSION } from '../projects/projectFormat'
import { PLUGIN_API_MATRIX, NOVA_PLUGIN_API_VERSION, pluginRuntime, pluginState, setPluginSafeMode, type PluginContribution, type PluginContributionKind } from '../runtime/plugins'
import { addOfflineRegistryManifest, diagnosePackageResolution, packageState } from '../runtime/packages'
import { NOVA_NATIVE_EXTENSION_ABI_VERSION, createLocalRegistry, createPackageWizardDraft, ecosystemAuditState, importLocalRegistry, packageManifestFromDraft, publisherSigningRequest, scanPackageCandidate, verifyPublisherSignature, type PackageCertificationReport } from '../runtime/extensionEcosystem'
import { exportTemplateState, installOfflineExportTemplate, platformQualification } from '../runtime/exportTemplates'
import { NOVA_CI_MATRIX_VERSION, deliveryPipelineState, normalizeDeploymentConnector, prepareDeployment, refreshCiCacheKeys, type DeploymentConnector } from '../runtime/deliveryPipeline'
import { exportCapabilities } from '../runtime/buildSettings'
import { createShippingEvidencePlan, ecosystemShippingState, importSignedSecurityBulletin, matchingHostPipelines, setUpdaterOptIn, stageSignedUpdate } from '../runtime/ecosystemShipping'

type StudioTab = 'extensions' | 'package' | 'templates' | 'delivery' | 'shipping' | 'audit'
const tabs: Array<{ id: StudioTab; label: string }> = [{ id: 'extensions', label: 'extensions' }, { id: 'package', label: 'packageLab' }, { id: 'templates', label: 'exportTemplates' }, { id: 'delivery', label: 'delivery' }, { id: 'shipping', label: 'shipping' }, { id: 'audit', label: 'audit' }]
const activeTab = ref<StudioTab>('extensions')
const draft = reactive(createPackageWizardDraft()), publicKey = ref(''), signature = ref(''), signatureStatus = ref<'notChecked' | 'verified' | 'invalid'>('notChecked')
const certification = ref<PackageCertificationReport | null>(null), registryInput = ref<HTMLInputElement | null>(null), templateInput = ref<HTMLInputElement | null>(null)
const registryResult = ref<{ imported: number; blocked: number } | null>(null)
const securityInput = ref<HTMLInputElement | null>(null), updateInput = ref<HTMLInputElement | null>(null), securityPublicKey = ref(''), securityStatus = ref(''), updaterMessage = ref('')
const solver = ref(diagnosePackageResolution()), hostPipelines = matchingHostPipelines(), shippingEvidence = createShippingEvidencePlan()
const connectorDraft = reactive({ id: '', name: 'Web release webhook', kind: 'https-webhook', destination: '', enabled: true, permissionGranted: false, headers: [] } as DeploymentConnector)
const permissionText = computed({ get: /* 调用 draft.permissions.join(', ') 并返回调用结果。 */ () => draft.permissions.join(', '), set: /** 按逗号解析权限文本，去空白、去重并限制最多三十二项。 */ value => { draft.permissions = [...new Set(value.split(',').map(/* 调用 item.trim() 并返回调用结果。 */ item => item.trim()).filter(Boolean))].slice(0, 32) } })
const qualifications = computed(/** 分别计算 Windows、Web、Linux、macOS 和 Android 的平台资格。 */ () => (['windows', 'web', 'linux', 'macos', 'android'] as const).map(/* 调用 platformQualification(target, exportCapabilities) 并返回调用结果。 */ target => platformQualification(target, exportCapabilities)))
const audits = computed(/** 由当前配置与计划生成诚实摘要；没有执行证据的审核保持未运行。 */ () => ecosystemAuditSummary({apiCount:PLUGIN_API_MATRIX.length,isolatedFailures:pluginState.isolatedFailures,offlineMode:packageState.offlineMode,plan:deliveryPipelineState.lastPlan}))

/** 按插件标识、贡献种类和贡献编号调用对应扩展功能。 */ function invoke(item: PluginContribution & { pluginId: string }): void { pluginRuntime.invokeContribution(item.kind as PluginContributionKind, item.id, item.pluginId) }
/** 下载 JSON 内容并立即释放临时对象地址。 */ function download(name: string, content: string): void { const url = URL.createObjectURL(new Blob([content], { type: 'application/json' })), anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url) }
/* 调用 packageManifestFromDraft(draft, signatureValue) 并返回调用结果。 */ function manifest(signatureValue = '') { return packageManifestFromDraft(draft, signatureValue) }
/** 生成发布者签名请求并下载，失败将原因加入阻断结果。 */ function downloadSigningRequest(): void { try { download(`${draft.id}-${draft.version}.signing-request.json`, publisherSigningRequest(manifest())) } catch (error) { certification.value = scanPackageCandidate({}); certification.value.blocking.push(error instanceof Error ? error.message : String(error)) } }
/** 扫描草稿清单与固定包结构描述，保存认证摘要；异常产生阻断结果。 */ function certifyDraft(): void { try { certification.value = scanPackageCandidate(manifest(signature.value), { compressedBytes: 1, expandedBytes: 1, files: ['package.json', 'README.md', 'tests/certification.json'] }) } catch (error) { certification.value = { status: 'blocked', checks: [], blocking: [error instanceof Error ? error.message : String(error)], warnings: [] } }; ecosystemAuditState.lastCertification = certification.value }
/** 验证发布者签名，成功登记离线清单并扫描候选，失败显示无效状态。 */ async function verifySignature(): Promise<void> { try { const candidate = manifest(signature.value); const verified = await verifyPublisherSignature(candidate, publicKey.value.trim(), signature.value.trim()); signatureStatus.value = verified ? 'verified' : 'invalid'; if (verified) { addOfflineRegistryManifest(candidate); certification.value = scanPackageCandidate(candidate) } } catch { signatureStatus.value = 'invalid' } }
/** 把当前目录清单导出为本地注册表 JSON。 */ function downloadRegistry(): void { download('nova-local-registry.json', `${JSON.stringify(createLocalRegistry(packageState.registryCatalog), null, 2)}\n`) }
/** 读取不超过八兆字节的已选 JSON 文件并清空输入，缺失或超限抛出错误。 */ async function readJsonFile(event: Event): Promise<unknown> { const input = event.target as HTMLInputElement, file = input.files?.[0]; input.value = ''; if (!file || file.size > 8 * 1024 * 1024) throw new Error('JSON file is missing or exceeds 8 MB.'); return JSON.parse(await file.text()) as unknown }
/** 导入本地注册表并保存结果，异常返回一项阻断结果。 */ async function readRegistry(event: Event): Promise<void> { try { registryResult.value = importLocalRegistry(await readJsonFile(event)); ecosystemAuditState.lastRegistryResult = registryResult.value } catch { registryResult.value = { imported: 0, blocked: 1 } } }
/** 读取并安装离线导出模板，失败记录模板错误。 */ async function readTemplate(event: Event): Promise<void> { try { installOfflineExportTemplate(await readJsonFile(event)) } catch (error) { exportTemplateState.lastError = error instanceof Error ? error.message : String(error) } }
/** 以当前项目和引擎版本刷新 CI 缓存键。 */ function refreshKeys(): void { refreshCiCacheKeys('current-project', NOVA_ENGINE_VERSION) }
/** 归一化并注册部署连接器，成功设为选中项；无效输入保持未注册。 */ function addConnector(): void { try { const connector = normalizeDeploymentConnector({ ...connectorDraft, id: `connector-${Date.now()}` }); deliveryPipelineState.connectors.push(connector); deliveryPipelineState.selectedConnectorId = connector.id } catch { /* Invalid connector stays unregistered and is shown by its unchanged fields. */ } }
/** 请求部署授权确认，同意后设置连接器权限标记。 */ async function grantConnector(connector: DeploymentConnector): Promise<void> { if (!await requestConfirmation({ title: t('grantDeploymentPermission'), message: t('grantDeploymentPermissionHint'), confirmLabel: t('grant'), cancelLabel: t('cancel'), destructive: false })) return; connector.permissionGranted = true }
/** 以指定产物路径和占位摘要生成部署预览，异常清除旧计划。 */ function prepare(id: string): void { try { prepareDeployment(id, 'build/game-artifact', '0'.repeat(64)) } catch { deliveryPipelineState.lastPlan = null } }
/** 刷新资源包解析诊断。 */ function refreshSolver(): void { solver.value = diagnosePackageResolution() }
/** 读取并验证签名安全公告，显示吊销、漏洞和禁用统计，再刷新依赖诊断。 */ async function readSecurityBulletin(event: Event): Promise<void> { try { const result = await importSignedSecurityBulletin(await readJsonFile(event), securityPublicKey.value.trim()); securityStatus.value = `${result.revoked} ${t('revoked')} · ${result.vulnerable} ${t('vulnerabilities')} · ${result.disabled} ${t('disabled')}`; refreshSolver() } catch (error) { securityStatus.value = error instanceof Error ? error.message : String(error) } }
/** 读取并验证更新清单，暂存升级计划并提示仍需显式下载。 */ async function readUpdateManifest(event: Event): Promise<void> { try { const plan = await stageSignedUpdate(await readJsonFile(event), securityPublicKey.value.trim()); updaterMessage.value = `${plan.from} → ${plan.release} · ${t('explicitDownloadRequired')}` } catch (error) { updaterMessage.value = error instanceof Error ? error.message : String(error) } }
</script>

<style scoped>
.ecosystem-studio { height: 100%; min-height: 0; min-width: 0; display: flex; flex-direction: column; overflow: hidden; background: var(--surface-1); container: ecosystem / inline-size; }
.studio-header output { font-size: var(--type-caption); color: var(--text-muted); white-space: nowrap; }.ecosystem-studio > .ui-tabs { border-bottom: var(--ui-border-width) solid var(--border-subtle); }
.studio-grid { min-height: 0; flex: 1; display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); align-content: start; overflow: auto; }
.card { min-width: 0; padding: var(--space-2) var(--space-3); border-bottom: var(--ui-border-width) solid var(--border-subtle); border-right: var(--ui-border-width) solid var(--border-subtle); }
.card > header { min-height: var(--ui-standard-height); display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: var(--space-2); margin-bottom: var(--space-1); }.card > header > div { min-width: 0; display: grid; gap: var(--ui-control-gap); }
.card p, .card small, .card > header > span, .card output { font-size: var(--type-caption); color: var(--text-muted); line-height: var(--line-body); overflow-wrap: anywhere; }.card p { margin-block: var(--space-2); }.card ul { padding-inline-start: var(--space-4); font-size: var(--type-caption); color: var(--text-secondary); }
.span-two { grid-column: span 2; }.span-three { grid-column: 1 / -1; }.button-row { display: flex; flex-wrap: wrap; gap: var(--space-1); margin-block: var(--space-2); }
.toggle { min-height: var(--ui-standard-height); display: flex; align-items: center; gap: var(--space-2); font-size: var(--type-dense); }
.field-grid { display: grid; grid-template-columns: repeat(2,minmax(0,1fr)); gap: var(--space-2); }.field-grid label, .signing-card label, .connector-editor label, .security-card label, .updater-card > label:not(.toggle) { display: grid; align-content: start; gap: var(--ui-control-gap); min-width: 0; color: var(--text-secondary); font-size: var(--type-dense); }.field-grid .wide { grid-column: 1 / -1; }
.api-table, .ci-table { overflow: auto; }.api-table article, .ci-table article { display: grid; grid-template-columns: minmax(16ch,1fr) minmax(19ch,1fr) minmax(9ch,.6fr) minmax(24ch,1.3fr); min-width: 72ch; min-height: var(--ui-tree-row-height); align-items: center; gap: var(--space-2); border-bottom: var(--ui-border-width) solid var(--border-subtle); font-size: var(--type-caption); }.ci-table article { grid-template-columns: minmax(16ch,1fr) minmax(21ch,1fr) minmax(21ch,1fr) 14ch; }
.card dl { margin-block: var(--space-2); }.card dl div { min-height: var(--ui-tree-row-height); display: flex; flex-wrap: wrap; align-items: baseline; justify-content: space-between; gap: var(--space-2); border-bottom: var(--ui-border-width) solid var(--border-subtle); font-size: var(--type-caption); }.card dt { color: var(--text-muted); }.card dd { margin: 0; overflow-wrap: anywhere; }
.extension-list article, .connector-list article { display: flex; flex-wrap: wrap; align-items: center; gap: var(--space-2); min-height: var(--ui-standard-height); padding-block: var(--space-1); border-bottom: var(--ui-border-width) solid var(--border-subtle); }.extension-list article > div, .connector-list article > div { flex: 1 1 24ch; min-width: 0; display: grid; }.extension-list code, .connector-list code { overflow: hidden; color: var(--text-muted); font-size: var(--type-caption); text-overflow: ellipsis; white-space: nowrap; }
.contribution-grid, .audit-cards { display: flex; flex-direction: column; }.contribution-grid article { display: grid; grid-template-columns: minmax(14ch,1fr) minmax(0,2fr) minmax(12ch,1fr) auto; align-items: center; gap: var(--space-2); min-height: var(--ui-standard-height); border-bottom: var(--ui-border-width) solid var(--border-subtle); }.contribution-grid article > span { color: var(--text-muted); font-size: var(--type-caption); }.contribution-grid article small { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.check-list article { display: grid; grid-template-columns: var(--ui-icon-size) minmax(12ch,.5fr) minmax(0,1fr); align-items: center; gap: var(--space-2); min-height: var(--ui-standard-height); border-bottom: var(--ui-border-width) solid var(--border-subtle); font-size: var(--type-caption); }
.passed,.verified,.qualified,.local-ready { color: var(--success) !important; }.blocked,.invalid { color: var(--danger) !important; }.pending,.pending-external,.external,.notChecked { color: var(--warning) !important; }
.signing-card output { display: block; margin-block: var(--space-2); }.template-toolbar { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: var(--space-2); }.template-toolbar > div { min-width: 0; flex: 1 1 24ch; }
.qualification-card > article { display: flex; flex-wrap: wrap; align-items: center; gap: var(--space-2); min-height: var(--ui-standard-height); padding-block: var(--space-1); border-bottom: var(--ui-border-width) solid var(--border-subtle); }.qualification-card > article > b { flex: 0 1 24ch; }.qualification-card > article > span { display: inline-flex; align-items: center; gap: var(--space-1); font-size: var(--type-caption); }
.cache-key { display: block; margin-block: var(--space-2); overflow-wrap: anywhere; font-size: var(--type-caption); }.connector-editor,.security-card,.updater-card { display: grid; gap: var(--space-2); align-content: start; }.connector-list + pre { max-height: calc(7 * var(--ui-control-height)); overflow: auto; padding: var(--space-2); background: var(--bg-canvas); font-size: var(--type-caption); }
.audit-cards article { display: grid; grid-template-columns: var(--ui-icon-size) minmax(0,1fr); align-items: start; gap: var(--space-2); padding-block: var(--space-2); border-bottom: var(--ui-border-width) solid var(--border-subtle); }.audit-cards small { margin-inline-start: var(--space-2); }.audit-cards .notRun { color: var(--text-muted); }
.publisher-card > code { display: block; margin-block: var(--space-2); padding: var(--space-2); overflow: auto; background: var(--bg-canvas); font-size: var(--type-caption); white-space: nowrap; }
.shipping-evidence { display: grid; grid-template-columns: repeat(3,minmax(0,1fr)); gap: var(--space-3); }.shipping-evidence article { min-width: 0; }
@container ecosystem (max-width: 920px) { .studio-grid { grid-template-columns: repeat(2,minmax(0,1fr)); }.shipping-evidence { grid-template-columns: minmax(0,1fr); }.contribution-grid article { grid-template-columns: minmax(0,1fr) minmax(0,1fr) auto; }.contribution-grid article > span { grid-column: 1 / -1; } }
@container ecosystem (max-width: 560px) { .studio-grid { grid-template-columns: minmax(0,1fr); }.span-two,.span-three { grid-column: 1; }.field-grid { grid-template-columns: minmax(0,1fr); }.studio-header output { display: none; } }
</style>
