<template>
  <Teleport to="body"><div v-if="state.visible" class="external-scrim" role="dialog" aria-modal="true" :aria-label="t('externalChanges')"><section><header><div><span>⇄</span><p><strong>{{ t('externalChanges') }}</strong><small>{{ state.fileName }} · {{ t(state.kind==='branch-switch'?'externalKind_branchSwitch':state.kind==='large-update'?'externalKind_largeUpdate':'externalKind_external') }}</small></p></div></header><p class="notice">{{ t('externalChangeChoice') }}</p><div class="summary"><span>{{ state.changes.length }} {{ t('diskChanges') }}</span><span>{{ state.conflicts.length }} {{ t('editorDifferences') }}</span><code>{{ state.incomingChecksum }}</code></div><details open><summary>{{ t('compare') }}</summary><ol><li v-for="change in compared.slice(0,100)" :key="`${change.kind}:${change.uuid}`"><b>{{ change.kind }}</b><span>{{ change.resourceType }}</span><code>{{ change.path }}</code></li></ol></details><footer><button @click="keepEditorProjectVersion">{{ t('keepEditor') }}</button><button @click="compare">{{ t('compare') }}</button><button class="disk" @click="keepDisk">{{ t('keepDisk') }}</button><button class="primary" @click="reload">{{ t('reload') }}</button></footer></section></div></Teleport>
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { t } from '../i18n'
import { compareExternalProject, externalChangeState as state, keepDiskProjectVersion, keepEditorProjectVersion, reloadExternalProject } from '../runtime/projectExternalChanges'
import type { SemanticProjectChange } from '../projects/projectData'
import { notify } from '../runtime/editorFeedback'
const compared=ref<SemanticProjectChange[]>([])
function compare(){compared.value=compareExternalProject()}
function keepDisk(){if(!keepDiskProjectVersion())notify(t('externalReloadFailed'),'error')}
function reload(){if(!reloadExternalProject())notify(t('externalReloadFailed'),'error')}
</script>
<style scoped>
.external-scrim{position:fixed;inset:0;z-index:9200;padding:18px;display:grid;place-items:center;background:var(--scrim);backdrop-filter:blur(8px)}.external-scrim>section{width:min(720px,100%);max-height:min(720px,calc(100vh - 36px));display:flex;flex-direction:column;overflow:hidden;border:1px solid var(--border-strong);border-radius:var(--radius-dialog);background:var(--surface-1);box-shadow:var(--shadow-lg)}header{padding:14px;border-bottom:1px solid var(--border-subtle)}header>div{display:flex;gap:10px;align-items:center}header>div>span{width:38px;height:38px;display:grid;place-items:center;border-radius:10px;color:var(--warning);background:color-mix(in srgb,var(--warning) 12%,transparent);font-size:20px}header p{margin:0;display:grid}header small,.notice{color:var(--text-muted)}.notice{padding:0 14px}.summary{margin:0 14px;padding:8px;display:grid;grid-template-columns:auto auto minmax(0,1fr);gap:8px;border:1px solid var(--border-subtle);border-radius:8px;background:var(--surface-2)}.summary code{overflow:hidden;text-overflow:ellipsis;text-align:right}details{min-height:0;margin:10px 14px;overflow:auto}ol{padding-left:20px}li{display:grid;grid-template-columns:70px 70px minmax(0,1fr);gap:6px}li b{color:var(--accent)}li code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}footer{padding:10px 14px;display:flex;justify-content:flex-end;gap:7px;border-top:1px solid var(--border-subtle)}footer button{min-height:34px;padding:0 11px;border:1px solid var(--border-subtle);border-radius:8px;background:var(--surface-2)}footer .primary{color:var(--accent-contrast);border-color:var(--accent);background:var(--accent)}footer .disk{color:var(--warning)}
</style>
