<template>
  <section v-if="grid" class="gameplay-card"><header><strong>{{ t('gridMover2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('inputAction') }}</span><select v-model="grid.action"><option v-for="action in vectorActions" :key="action.name">{{ action.name }}</option></select></label><label><span>{{ t('cellSize') }}</span><div><input v-model.number="grid.cellSize.x" type="number" min="0.000001"><input v-model.number="grid.cellSize.y" type="number" min="0.000001"></div></label><label><span>{{ t('repeatDelay') }}</span><input v-model.number="grid.repeatDelay" type="number" min="0" step="0.01"></label><label><span>{{ t('allowDiagonal') }}</span><input v-model="grid.allowDiagonal" type="checkbox"></label><label><span>{{ t('localSpace') }}</span><input v-model="grid.localSpace" type="checkbox"></label></section>
  <section v-if="platform" class="gameplay-card"><header><strong>{{ t('platformController2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('moveAction') }}</span><select v-model="platform.moveAction"><option v-for="action in scalarActions" :key="action.name">{{ action.name }}</option></select></label><label><span>{{ t('jumpAction') }}</span><select v-model="platform.jumpAction"><option v-for="action in buttonActions" :key="action.name">{{ action.name }}</option></select></label><label><span>{{ t('speed') }}</span><input v-model.number="platform.speed" type="number" min="0"></label><label><span>{{ t('acceleration') }}</span><input v-model.number="platform.acceleration" type="number" min="0"></label><label><span>{{ t('airControl') }}</span><input v-model.number="platform.airControl" type="number" min="0" max="1" step="0.05"></label><label><span>{{ t('jumpImpulse') }}</span><input v-model.number="platform.jumpImpulse" type="number" min="0"></label></section>
  <section v-if="topDown" class="gameplay-card"><header><strong>{{ t('topDownController2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('moveAction') }}</span><select v-model="topDown.moveAction"><option v-for="action in vectorActions" :key="action.name">{{ action.name }}</option></select></label><label><span>{{ t('speed') }}</span><input v-model.number="topDown.speed" type="number" min="0"></label><label><span>{{ t('acceleration') }}</span><input v-model.number="topDown.acceleration" type="number" min="0"></label><label><span>{{ t('rotateToMovement') }}</span><input v-model="topDown.rotateToMovement" type="checkbox"></label></section>
  <section v-if="health" class="gameplay-card"><header><strong>{{ t('health2D') }}</strong><span>{{ health.current.toFixed(1) }} / {{ health.maximum.toFixed(1) }}</span></header><label><span>{{ t('maximumHealth') }}</span><input v-model.number="health.maximum" type="number" min="0.000001"></label><label><span>{{ t('currentHealth') }}</span><input v-model.number="health.current" type="number" min="0" :max="health.maximum"></label><label><span>{{ t('invulnerability') }}</span><input v-model.number="health.invulnerabilitySeconds" type="number" min="0" step="0.01"></label><label><span>{{ t('destroyOnZero') }}</span><input v-model="health.destroyOnZero" type="checkbox"></label></section>
  <section v-if="hitbox" class="gameplay-card"><header><strong>{{ t('damageHitbox2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('damage') }}</span><input v-model.number="hitbox.damage" type="number" min="0"></label><label><span>{{ t('knockback') }}</span><input v-model.number="hitbox.knockback" type="number" min="0"></label><label><span>{{ t('targetTag') }}</span><input v-model="hitbox.targetTag"></label><label><span>{{ t('hitCooldown') }}</span><input v-model.number="hitbox.hitCooldown" type="number" min="0" step="0.01"></label><label><span>{{ t('destroyOnHit') }}</span><input v-model="hitbox.destroyOnHit" type="checkbox"></label></section>
  <section v-if="collectible" class="gameplay-card"><header><strong>{{ t('collectible2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('collectorTag') }}</span><input v-model="collectible.collectorTag"></label><label><span>{{ t('scoreReward') }}</span><input v-model.number="collectible.score" type="number"></label><label><span>{{ t('destroyOnCollect') }}</span><input v-model="collectible.destroyOnCollect" type="checkbox"></label></section>
  <section v-if="projectile" class="gameplay-card"><header><strong>{{ t('projectile2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('speed') }}</span><input v-model.number="projectile.speed" type="number" min="0"></label><label><span>{{ t('direction') }}</span><div><input v-model.number="projectile.direction.x" type="number"><input v-model.number="projectile.direction.y" type="number"></div></label><label><span>{{ t('damage') }}</span><input v-model.number="projectile.damage" type="number" min="0"></label><label><span>{{ t('lifetime') }}</span><input v-model.number="projectile.lifetime" type="number" min="0"></label><label><span>{{ t('destroyOnHit') }}</span><input v-model="projectile.destroyOnImpact" type="checkbox"></label></section>
  <section v-if="spawner" class="gameplay-card"><header><strong>{{ t('spawner2D') }}</strong><span>{{ spawner.runtimeSpawned.length }} / {{ spawner.maximumAlive }}</span></header><label><span>{{ t('prefabAsset') }}</span><select v-model="spawner.prefabAsset"><option :value="null">{{ t('none') }}</option><option v-for="asset in prefabAssets" :key="asset.uuid" :value="assetReference(asset.uuid)">{{ asset.name }}</option></select></label><label><span>{{ t('spawnInterval') }}</span><input v-model.number="spawner.interval" type="number" min="0.000001"></label><label><span>{{ t('initialDelay') }}</span><input v-model.number="spawner.initialDelay" type="number" min="0"></label><label><span>{{ t('burst') }}</span><input v-model.number="spawner.burst" type="number" min="1" max="256"></label><label><span>{{ t('maximumAlive') }}</span><input v-model.number="spawner.maximumAlive" type="number" min="1"></label><label><span>{{ t('autoStart') }}</span><input v-model="spawner.autoStart" type="checkbox"></label></section>
  <section v-if="cooldown" class="gameplay-card"><header><strong>{{ t('cooldown2D') }}</strong><span>{{ cooldown.runtimeReady ? t('ready') : cooldown.runtimeRemaining.toFixed(2) }}</span></header><label><span>{{ t('duration') }}</span><input v-model.number="cooldown.duration" type="number" min="0.000001"></label><label><span>{{ t('autoStart') }}</span><input v-model="cooldown.autoStart" type="checkbox"></label><label><span>{{ t('readySignal') }}</span><input v-model="cooldown.readySignal"></label></section>
  <section v-if="lifetime" class="gameplay-card"><header><strong>{{ t('lifetime2D') }}</strong><span>{{ Math.max(0, lifetime.runtimeRemaining).toFixed(2) }}</span></header><label><span>{{ t('duration') }}</span><input v-model.number="lifetime.seconds" type="number" min="0.000001"></label><label><span>{{ t('useDespawn') }}</span><input v-model="lifetime.useDespawn" type="checkbox"></label></section>
  <section v-if="mouseFollower" class="gameplay-card"><header><strong>{{ t('mouseFollower2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('offset') }}</span><div><input v-model.number="mouseFollower.offset.x" type="number"><input v-model.number="mouseFollower.offset.y" type="number"></div></label><label><span>{{ t('maximumSpeed') }}</span><input v-model.number="mouseFollower.maximumSpeed" type="number" min="0" step="0.1"></label><small>{{ t('zeroMeansExact') }}</small></section>
  <section v-if="follow" class="gameplay-card"><header><strong>{{ t('cameraFollow2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('targetEntity') }}</span><select v-model="follow.targetUuid"><option value="">{{ t('byTag') }}</option><option v-for="candidate in targets" :key="candidate.uuid" :value="candidate.uuid">{{ candidate.name }}</option></select></label><label><span>{{ t('targetTag') }}</span><input v-model="follow.targetTag"></label><label><span>{{ t('offset') }}</span><div><input v-model.number="follow.offset.x" type="number"><input v-model.number="follow.offset.y" type="number"></div></label><label><span>{{ t('smoothing') }}</span><input v-model.number="follow.smoothing" type="number" min="0"></label><label><span>{{ t('deadZone') }}</span><div><input v-model.number="follow.deadZone.x" type="number" min="0"><input v-model.number="follow.deadZone.y" type="number" min="0"></div></label></section>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { assetReference, assetState } from '../assets/AssetDatabase'
import { t } from '../i18n'
import { physicsState } from '../store/physics'
import type { Entity } from '../world/Entity'
import type { CameraFollow2D, Collectible2D, Cooldown2D, DamageHitbox2D, GridMover2D, Health2D, Lifetime2D, MouseFollower2D, PlatformController2D, Projectile2D, Spawner2D, TopDownController2D } from '../world/components'

const props = defineProps<{ entity: Entity }>()
const grid = computed(() => props.entity.getComponent<GridMover2D>('GridMover2D')), platform = computed(() => props.entity.getComponent<PlatformController2D>('PlatformController2D')), topDown = computed(() => props.entity.getComponent<TopDownController2D>('TopDownController2D'))
const health = computed(() => props.entity.getComponent<Health2D>('Health2D')), hitbox = computed(() => props.entity.getComponent<DamageHitbox2D>('DamageHitbox2D')), collectible = computed(() => props.entity.getComponent<Collectible2D>('Collectible2D')), projectile = computed(() => props.entity.getComponent<Projectile2D>('Projectile2D'))
const spawner = computed(() => props.entity.getComponent<Spawner2D>('Spawner2D')), cooldown = computed(() => props.entity.getComponent<Cooldown2D>('Cooldown2D')), lifetime = computed(() => props.entity.getComponent<Lifetime2D>('Lifetime2D')), mouseFollower = computed(() => props.entity.getComponent<MouseFollower2D>('MouseFollower2D')), follow = computed(() => props.entity.getComponent<CameraFollow2D>('CameraFollow2D'))
const vectorActions = computed(() => physicsState.inputMap.filter(action => action.kind === 'vector2')), scalarActions = computed(() => physicsState.inputMap.filter(action => action.kind === 'axis' || action.kind === 'button')), buttonActions = computed(() => physicsState.inputMap.filter(action => action.kind === 'button'))
const prefabAssets = computed(() => assetState.records.filter(asset => asset.assetType === 'prefab')), targets = computed(() => physicsState.world.entities.filter(entity => entity !== props.entity))
</script>

<style scoped>
.gameplay-card{margin-top:8px;padding:10px;display:grid;gap:5px;border:1px solid var(--border-subtle);border-radius:10px;background:var(--surface-1)}header{display:flex;align-items:center;justify-content:space-between;gap:8px}header span,.gameplay-card small{color:var(--text-muted);font-size:var(--type-caption);line-height:1.4}label{min-height:34px;display:flex;align-items:center;justify-content:space-between;gap:10px;border-top:1px solid var(--border-subtle);font-size:var(--type-caption)}label>input,label>select,label>div{width:56%;min-width:0}label>div{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:5px}@media(max-width:1180px){label{align-items:stretch;flex-direction:column;padding:5px 0}label>input,label>select,label>div{width:100%}}
</style>
