<template>
  <section v-if="grid" class="gameplay-card"><header><strong>{{ t('gridMover2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('inputAction') }}</span><select v-model="grid.action"><option v-for="action in vectorActions" :key="action.name">{{ action.name }}</option></select></label><label><span>{{ t('cellSize') }}</span><div><NumericExpressionInput v-model="grid.cellSize.x" :minimum="0.000001" :resource-key="entity.uuid + ':' + grid.uuid + ':grid.cellSize.x'" /><NumericExpressionInput v-model="grid.cellSize.y" :minimum="0.000001" :resource-key="entity.uuid + ':' + grid.uuid + ':grid.cellSize.y'" /></div></label><label><span>{{ t('repeatDelay') }}</span><NumericExpressionInput v-model="grid.repeatDelay" :minimum="0" :step="0.01" :resource-key="entity.uuid + ':' + grid.uuid + ':grid.repeatDelay'" /></label><label><span>{{ t('allowDiagonal') }}</span><input v-model="grid.allowDiagonal" type="checkbox"></label><label><span>{{ t('localSpace') }}</span><input v-model="grid.localSpace" type="checkbox"></label></section>
  <section v-if="platform" class="gameplay-card"><header><strong>{{ t('platformController2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('moveAction') }}</span><select v-model="platform.moveAction"><option v-for="action in scalarActions" :key="action.name">{{ action.name }}</option></select></label><label><span>{{ t('jumpAction') }}</span><select v-model="platform.jumpAction"><option v-for="action in buttonActions" :key="action.name">{{ action.name }}</option></select></label><label><span>{{ t('speed') }}</span><NumericExpressionInput v-model="platform.speed" :minimum="0" :resource-key="entity.uuid + ':' + platform.uuid + ':platform.speed'" /></label><label><span>{{ t('acceleration') }}</span><NumericExpressionInput v-model="platform.acceleration" :minimum="0" :resource-key="entity.uuid + ':' + platform.uuid + ':platform.acceleration'" /></label><label><span>{{ t('airControl') }}</span><NumericExpressionInput v-model="platform.airControl" :minimum="0" :maximum="1" :step="0.05" :resource-key="entity.uuid + ':' + platform.uuid + ':platform.airControl'" /></label><label><span>{{ t('jumpImpulse') }}</span><NumericExpressionInput v-model="platform.jumpImpulse" :minimum="0" :resource-key="entity.uuid + ':' + platform.uuid + ':platform.jumpImpulse'" /></label></section>
  <section v-if="topDown" class="gameplay-card"><header><strong>{{ t('topDownController2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('moveAction') }}</span><select v-model="topDown.moveAction"><option v-for="action in vectorActions" :key="action.name">{{ action.name }}</option></select></label><label><span>{{ t('speed') }}</span><NumericExpressionInput v-model="topDown.speed" :minimum="0" :resource-key="entity.uuid + ':' + topDown.uuid + ':topDown.speed'" /></label><label><span>{{ t('acceleration') }}</span><NumericExpressionInput v-model="topDown.acceleration" :minimum="0" :resource-key="entity.uuid + ':' + topDown.uuid + ':topDown.acceleration'" /></label><label><span>{{ t('rotateToMovement') }}</span><input v-model="topDown.rotateToMovement" type="checkbox"></label></section>
  <section v-if="health" class="gameplay-card"><header><strong>{{ t('health2D') }}</strong><span>{{ health.current.toFixed(1) }} / {{ health.maximum.toFixed(1) }}</span></header><label><span>{{ t('maximumHealth') }}</span><NumericExpressionInput v-model="health.maximum" :minimum="0.000001" :resource-key="entity.uuid + ':' + health.uuid + ':health.maximum'" /></label><label><span>{{ t('currentHealth') }}</span><NumericExpressionInput v-model="health.current" :minimum="0" :maximum="health.maximum" :resource-key="entity.uuid + ':' + health.uuid + ':health.current'" /></label><label><span>{{ t('invulnerability') }}</span><NumericExpressionInput v-model="health.invulnerabilitySeconds" :minimum="0" :step="0.01" :resource-key="entity.uuid + ':' + health.uuid + ':health.invulnerabilitySeconds'" /></label><label><span>{{ t('destroyOnZero') }}</span><input v-model="health.destroyOnZero" type="checkbox"></label></section>
  <section v-if="hitbox" class="gameplay-card"><header><strong>{{ t('damageHitbox2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('damage') }}</span><NumericExpressionInput v-model="hitbox.damage" :minimum="0" :resource-key="entity.uuid + ':' + hitbox.uuid + ':hitbox.damage'" /></label><label><span>{{ t('knockback') }}</span><NumericExpressionInput v-model="hitbox.knockback" :minimum="0" :resource-key="entity.uuid + ':' + hitbox.uuid + ':hitbox.knockback'" /></label><label><span>{{ t('targetTag') }}</span><input v-model="hitbox.targetTag"></label><label><span>{{ t('hitCooldown') }}</span><NumericExpressionInput v-model="hitbox.hitCooldown" :minimum="0" :step="0.01" :resource-key="entity.uuid + ':' + hitbox.uuid + ':hitbox.hitCooldown'" /></label><label><span>{{ t('destroyOnHit') }}</span><input v-model="hitbox.destroyOnHit" type="checkbox"></label></section>
  <section v-if="collectible" class="gameplay-card"><header><strong>{{ t('collectible2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('collectorTag') }}</span><input v-model="collectible.collectorTag"></label><label><span>{{ t('scoreReward') }}</span><NumericExpressionInput v-model="collectible.score" :resource-key="entity.uuid + ':' + collectible.uuid + ':collectible.score'" /></label><label><span>{{ t('destroyOnCollect') }}</span><input v-model="collectible.destroyOnCollect" type="checkbox"></label></section>
  <section v-if="projectile" class="gameplay-card"><header><strong>{{ t('projectile2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('speed') }}</span><NumericExpressionInput v-model="projectile.speed" :minimum="0" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.speed'" /></label><label><span>{{ t('direction') }}</span><div><NumericExpressionInput v-model="projectile.direction.x" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.direction.x'" /><NumericExpressionInput v-model="projectile.direction.y" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.direction.y'" /></div></label><label><span>{{ t('damage') }}</span><NumericExpressionInput v-model="projectile.damage" :minimum="0" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.damage'" /></label><label><span>{{ t('lifetime') }}</span><NumericExpressionInput v-model="projectile.lifetime" :minimum="0" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.lifetime'" /></label><label><span>{{ t('destroyOnHit') }}</span><input v-model="projectile.destroyOnImpact" type="checkbox"></label></section>
  <section v-if="spawner" class="gameplay-card"><header><strong>{{ t('spawner2D') }}</strong><span>{{ spawner.runtimeSpawned.length }} / {{ spawner.maximumAlive }}</span></header><label><span>{{ t('prefabAsset') }}</span><select v-model="spawner.prefabAsset"><option :value="null">{{ t('none') }}</option><option v-for="asset in prefabAssets" :key="asset.uuid" :value="assetReference(asset.uuid)">{{ asset.name }}</option></select></label><label><span>{{ t('spawnInterval') }}</span><NumericExpressionInput v-model="spawner.interval" :minimum="0.000001" :resource-key="entity.uuid + ':' + spawner.uuid + ':spawner.interval'" /></label><label><span>{{ t('initialDelay') }}</span><NumericExpressionInput v-model="spawner.initialDelay" :minimum="0" :resource-key="entity.uuid + ':' + spawner.uuid + ':spawner.initialDelay'" /></label><label><span>{{ t('burst') }}</span><NumericExpressionInput v-model="spawner.burst" :minimum="1" :maximum="256" :resource-key="entity.uuid + ':' + spawner.uuid + ':spawner.burst'" /></label><label><span>{{ t('maximumAlive') }}</span><NumericExpressionInput v-model="spawner.maximumAlive" :minimum="1" :resource-key="entity.uuid + ':' + spawner.uuid + ':spawner.maximumAlive'" /></label><label><span>{{ t('autoStart') }}</span><input v-model="spawner.autoStart" type="checkbox"></label></section>
  <section v-if="cooldown" class="gameplay-card"><header><strong>{{ t('cooldown2D') }}</strong><span>{{ cooldown.runtimeReady ? t('ready') : cooldown.runtimeRemaining.toFixed(2) }}</span></header><label><span>{{ t('duration') }}</span><NumericExpressionInput v-model="cooldown.duration" :minimum="0.000001" :resource-key="entity.uuid + ':' + cooldown.uuid + ':cooldown.duration'" /></label><label><span>{{ t('autoStart') }}</span><input v-model="cooldown.autoStart" type="checkbox"></label><label><span>{{ t('readySignal') }}</span><input v-model="cooldown.readySignal"></label></section>
  <section v-if="lifetime" class="gameplay-card"><header><strong>{{ t('lifetime2D') }}</strong><span>{{ Math.max(0, lifetime.runtimeRemaining).toFixed(2) }}</span></header><label><span>{{ t('duration') }}</span><NumericExpressionInput v-model="lifetime.seconds" :minimum="0.000001" :resource-key="entity.uuid + ':' + lifetime.uuid + ':lifetime.seconds'" /></label><label><span>{{ t('useDespawn') }}</span><input v-model="lifetime.useDespawn" type="checkbox"></label></section>
  <section v-if="mouseFollower" class="gameplay-card"><header><strong>{{ t('mouseFollower2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('offset') }}</span><div><NumericExpressionInput v-model="mouseFollower.offset.x" :resource-key="entity.uuid + ':' + mouseFollower.uuid + ':mouseFollower.offset.x'" /><NumericExpressionInput v-model="mouseFollower.offset.y" :resource-key="entity.uuid + ':' + mouseFollower.uuid + ':mouseFollower.offset.y'" /></div></label><label><span>{{ t('maximumSpeed') }}</span><NumericExpressionInput v-model="mouseFollower.maximumSpeed" :minimum="0" :step="0.1" :resource-key="entity.uuid + ':' + mouseFollower.uuid + ':mouseFollower.maximumSpeed'" /></label><small>{{ t('zeroMeansExact') }}</small></section>
  <section v-if="follow" class="gameplay-card"><header><strong>{{ t('cameraFollow2D') }}</strong><span>{{ t('runtimeComponent') }}</span></header><label><span>{{ t('targetEntity') }}</span><select v-model="follow.targetUuid"><option value="">{{ t('byTag') }}</option><option v-for="candidate in targets" :key="candidate.uuid" :value="candidate.uuid">{{ candidate.name }}</option></select></label><label><span>{{ t('targetTag') }}</span><input v-model="follow.targetTag"></label><label><span>{{ t('offset') }}</span><div><NumericExpressionInput v-model="follow.offset.x" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.offset.x'" /><NumericExpressionInput v-model="follow.offset.y" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.offset.y'" /></div></label><label><span>{{ t('smoothing') }}</span><NumericExpressionInput v-model="follow.smoothing" :minimum="0" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.smoothing'" /></label><label><span>{{ t('deadZone') }}</span><div><NumericExpressionInput v-model="follow.deadZone.x" :minimum="0" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.deadZone.x'" /><NumericExpressionInput v-model="follow.deadZone.y" :minimum="0" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.deadZone.y'" /></div></label></section>
</template>

<script setup lang="ts">
import NumericExpressionInput from './NumericExpressionInput.vue'
import { computed } from 'vue'
import { assetReference, assetState } from '../assets/AssetDatabase'
import { t } from '../i18n'
import { physicsState } from '../store/physics'
import type { Entity } from '../world/Entity'
import type { CameraFollow2D, Collectible2D, Cooldown2D, DamageHitbox2D, GridMover2D, Health2D, Lifetime2D, MouseFollower2D, PlatformController2D, Projectile2D, Spawner2D, TopDownController2D } from '../world/components'

const props = defineProps<{ entity: Entity }>()
const grid = computed(() => props.entity.getComponent<GridMover2D>('GridMover2D')), platform = computed(() => props.entity.getComponent<PlatformController2D>('PlatformController2D')), topDown = computed(() => props.entity.getComponent<TopDownController2D>('TopDownController2D'))
const health = computed(() => props.entity.getComponent<Health2D>('Health2D')), hitbox = computed(() => props.entity.getComponent<DamageHitbox2D>('DamageHitbox2D')), collectible = computed(() => props.entity.getComponent<Collectible2D>('Collectible2D')), projectile = computed(() => props.entity.getComponent<Projectile2D>('Projectile2D'))
const spawner = computed(() => props.entity.getComponent<Spawner2D>('Spawner2D')), cooldown = computed(() => props.entity.getComponent<Cooldown2D>('Cooldown2D')), lifetime = computed(() => props.entity.getComponent<Lifetime2D>('Lifetime2D')), mouseFollower = computed(() => props.entity.getComponent<MouseFollower2D>('MouseFollower2D')), follow = computed(() => props.entity.getComponent<CameraFollow2D>('CameraFollow2D'))
const vectorActions = computed(() => physicsState.inputMap.filter(action => action.kind === 'vector2')), scalarActions = computed(() => physicsState.inputMap.filter(action => action.kind === 'axis' || action.kind === 'button')), buttonActions = computed(() => physicsState.inputMap.filter(action => action.kind === 'button'))
const prefabAssets = computed(() => assetState.records.filter(asset => asset.assetType === 'prefab')), targets = computed(() => physicsState.world.entities.filter(entity => entity !== props.entity))
</script>

<style scoped>
.gameplay-card{margin-top:8px;padding:10px;display:grid;gap:5px;border:1px solid var(--border-subtle);border-radius:10px;background:var(--surface-1)}header{display:flex;align-items:center;justify-content:space-between;gap:8px}header span,.gameplay-card small{color:var(--text-muted);font-size:var(--type-caption);line-height:1.4}label{min-height:34px;display:flex;align-items:center;justify-content:space-between;gap:10px;border-top:1px solid var(--border-subtle);font-size:var(--type-caption)}label>input,label>select,label>div{width:56%;min-width:0}label>div{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:5px}@media(max-width:1180px){label{align-items:stretch;flex-direction:column;padding:5px 0}label>input,label>select,label>div{width:100%}}
label:has(> .numeric-draft){flex-wrap:wrap;align-items:stretch}label>div:has(.numeric-draft){display:flex;flex-wrap:wrap;gap:6px}.numeric-draft{max-width:100%}.inline:has(.numeric-draft){flex-wrap:wrap}
</style>
