<!-- 游戏组件检查器：编辑实体游戏逻辑组件并记录场景修改。 -->
<template>
  <UiPropertySection :title="t('gridMover2D')" v-if="grid" ><template #actions><span>{{ t('runtimeComponent') }}</span></template><UiPropertyRow :label="t('inputAction')"><select v-model="grid.action"><option v-for="action in vectorActions" :key="action.name">{{ action.name }}</option></select></UiPropertyRow><UiPropertyRow :label="t('cellSize')"><div><NumericExpressionInput v-model="grid.cellSize.x" :minimum="0.000001" :resource-key="entity.uuid + ':' + grid.uuid + ':grid.cellSize.x'" /><NumericExpressionInput v-model="grid.cellSize.y" :minimum="0.000001" :resource-key="entity.uuid + ':' + grid.uuid + ':grid.cellSize.y'" /></div></UiPropertyRow><UiPropertyRow :label="t('repeatDelay')"><NumericExpressionInput v-model="grid.repeatDelay" :minimum="0" :step="0.01" :resource-key="entity.uuid + ':' + grid.uuid + ':grid.repeatDelay'" /></UiPropertyRow><UiPropertyRow :label="t('allowDiagonal')"><input v-model="grid.allowDiagonal" type="checkbox"></UiPropertyRow><UiPropertyRow :label="t('localSpace')"><input v-model="grid.localSpace" type="checkbox"></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('platformController2D')" v-if="platform" ><template #actions><span>{{ t('runtimeComponent') }}</span></template><UiPropertyRow :label="t('moveAction')"><select v-model="platform.moveAction"><option v-for="action in scalarActions" :key="action.name">{{ action.name }}</option></select></UiPropertyRow><UiPropertyRow :label="t('jumpAction')"><select v-model="platform.jumpAction"><option v-for="action in buttonActions" :key="action.name">{{ action.name }}</option></select></UiPropertyRow><UiPropertyRow :label="t('speed')"><NumericExpressionInput v-model="platform.speed" :minimum="0" :resource-key="entity.uuid + ':' + platform.uuid + ':platform.speed'" /></UiPropertyRow><UiPropertyRow :label="t('acceleration')"><NumericExpressionInput v-model="platform.acceleration" :minimum="0" :resource-key="entity.uuid + ':' + platform.uuid + ':platform.acceleration'" /></UiPropertyRow><UiPropertyRow :label="t('airControl')"><NumericExpressionInput v-model="platform.airControl" :minimum="0" :maximum="1" :step="0.05" :resource-key="entity.uuid + ':' + platform.uuid + ':platform.airControl'" /></UiPropertyRow><UiPropertyRow :label="t('jumpImpulse')"><NumericExpressionInput v-model="platform.jumpImpulse" :minimum="0" :resource-key="entity.uuid + ':' + platform.uuid + ':platform.jumpImpulse'" /></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('topDownController2D')" v-if="topDown" ><template #actions><span>{{ t('runtimeComponent') }}</span></template><UiPropertyRow :label="t('moveAction')"><select v-model="topDown.moveAction"><option v-for="action in vectorActions" :key="action.name">{{ action.name }}</option></select></UiPropertyRow><UiPropertyRow :label="t('speed')"><NumericExpressionInput v-model="topDown.speed" :minimum="0" :resource-key="entity.uuid + ':' + topDown.uuid + ':topDown.speed'" /></UiPropertyRow><UiPropertyRow :label="t('acceleration')"><NumericExpressionInput v-model="topDown.acceleration" :minimum="0" :resource-key="entity.uuid + ':' + topDown.uuid + ':topDown.acceleration'" /></UiPropertyRow><UiPropertyRow :label="t('rotateToMovement')"><input v-model="topDown.rotateToMovement" type="checkbox"></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('health2D')" v-if="health" ><template #actions><span>{{ health.current.toFixed(1) }} / {{ health.maximum.toFixed(1) }}</span></template><UiPropertyRow :label="t('maximumHealth')"><NumericExpressionInput v-model="health.maximum" :minimum="0.000001" :resource-key="entity.uuid + ':' + health.uuid + ':health.maximum'" /></UiPropertyRow><UiPropertyRow :label="t('currentHealth')"><NumericExpressionInput v-model="health.current" :minimum="0" :maximum="health.maximum" :resource-key="entity.uuid + ':' + health.uuid + ':health.current'" /></UiPropertyRow><UiPropertyRow :label="t('invulnerability')"><NumericExpressionInput v-model="health.invulnerabilitySeconds" :minimum="0" :step="0.01" :resource-key="entity.uuid + ':' + health.uuid + ':health.invulnerabilitySeconds'" /></UiPropertyRow><UiPropertyRow :label="t('destroyOnZero')"><input v-model="health.destroyOnZero" type="checkbox"></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('damageHitbox2D')" v-if="hitbox" ><template #actions><span>{{ t('runtimeComponent') }}</span></template><UiPropertyRow :label="t('damage')"><NumericExpressionInput v-model="hitbox.damage" :minimum="0" :resource-key="entity.uuid + ':' + hitbox.uuid + ':hitbox.damage'" /></UiPropertyRow><UiPropertyRow :label="t('knockback')"><NumericExpressionInput v-model="hitbox.knockback" :minimum="0" :resource-key="entity.uuid + ':' + hitbox.uuid + ':hitbox.knockback'" /></UiPropertyRow><UiPropertyRow :label="t('targetTag')"><input v-model="hitbox.targetTag"></UiPropertyRow><UiPropertyRow :label="t('hitCooldown')"><NumericExpressionInput v-model="hitbox.hitCooldown" :minimum="0" :step="0.01" :resource-key="entity.uuid + ':' + hitbox.uuid + ':hitbox.hitCooldown'" /></UiPropertyRow><UiPropertyRow :label="t('destroyOnHit')"><input v-model="hitbox.destroyOnHit" type="checkbox"></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('collectible2D')" v-if="collectible" ><template #actions><span>{{ t('runtimeComponent') }}</span></template><UiPropertyRow :label="t('collectorTag')"><input v-model="collectible.collectorTag"></UiPropertyRow><UiPropertyRow :label="t('scoreReward')"><NumericExpressionInput v-model="collectible.score" :resource-key="entity.uuid + ':' + collectible.uuid + ':collectible.score'" /></UiPropertyRow><UiPropertyRow :label="t('destroyOnCollect')"><input v-model="collectible.destroyOnCollect" type="checkbox"></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('projectile2D')" v-if="projectile" ><template #actions><span>{{ t('runtimeComponent') }}</span></template><UiPropertyRow :label="t('speed')"><NumericExpressionInput v-model="projectile.speed" :minimum="0" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.speed'" /></UiPropertyRow><UiPropertyRow :label="t('direction')"><div><NumericExpressionInput v-model="projectile.direction.x" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.direction.x'" /><NumericExpressionInput v-model="projectile.direction.y" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.direction.y'" /></div></UiPropertyRow><UiPropertyRow :label="t('damage')"><NumericExpressionInput v-model="projectile.damage" :minimum="0" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.damage'" /></UiPropertyRow><UiPropertyRow :label="t('lifetime')"><NumericExpressionInput v-model="projectile.lifetime" :minimum="0" :resource-key="entity.uuid + ':' + projectile.uuid + ':projectile.lifetime'" /></UiPropertyRow><UiPropertyRow :label="t('destroyOnHit')"><input v-model="projectile.destroyOnImpact" type="checkbox"></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('spawner2D')" v-if="spawner" ><template #actions><span>{{ spawner.runtimeSpawned.length }} / {{ spawner.maximumAlive }}</span></template><UiPropertyRow :label="t('prefabAsset')"><select v-model="spawner.prefabAsset"><option :value="null">{{ t('none') }}</option><option v-for="asset in prefabAssets" :key="asset.uuid" :value="assetReference(asset.uuid)">{{ asset.name }}</option></select></UiPropertyRow><UiPropertyRow :label="t('spawnInterval')"><NumericExpressionInput v-model="spawner.interval" :minimum="0.000001" :resource-key="entity.uuid + ':' + spawner.uuid + ':spawner.interval'" /></UiPropertyRow><UiPropertyRow :label="t('initialDelay')"><NumericExpressionInput v-model="spawner.initialDelay" :minimum="0" :resource-key="entity.uuid + ':' + spawner.uuid + ':spawner.initialDelay'" /></UiPropertyRow><UiPropertyRow :label="t('burst')"><NumericExpressionInput v-model="spawner.burst" :minimum="1" :maximum="256" :resource-key="entity.uuid + ':' + spawner.uuid + ':spawner.burst'" /></UiPropertyRow><UiPropertyRow :label="t('maximumAlive')"><NumericExpressionInput v-model="spawner.maximumAlive" :minimum="1" :resource-key="entity.uuid + ':' + spawner.uuid + ':spawner.maximumAlive'" /></UiPropertyRow><UiPropertyRow :label="t('autoStart')"><input v-model="spawner.autoStart" type="checkbox"></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('cooldown2D')" v-if="cooldown" ><template #actions><span>{{ cooldown.runtimeReady ? t('ready') : cooldown.runtimeRemaining.toFixed(2) }}</span></template><UiPropertyRow :label="t('duration')"><NumericExpressionInput v-model="cooldown.duration" :minimum="0.000001" :resource-key="entity.uuid + ':' + cooldown.uuid + ':cooldown.duration'" /></UiPropertyRow><UiPropertyRow :label="t('autoStart')"><input v-model="cooldown.autoStart" type="checkbox"></UiPropertyRow><UiPropertyRow :label="t('readySignal')"><input v-model="cooldown.readySignal"></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('lifetime2D')" v-if="lifetime" ><template #actions><span>{{ Math.max(0, lifetime.runtimeRemaining).toFixed(2) }}</span></template><UiPropertyRow :label="t('duration')"><NumericExpressionInput v-model="lifetime.seconds" :minimum="0.000001" :resource-key="entity.uuid + ':' + lifetime.uuid + ':lifetime.seconds'" /></UiPropertyRow><UiPropertyRow :label="t('useDespawn')"><input v-model="lifetime.useDespawn" type="checkbox"></UiPropertyRow></UiPropertySection>
  <UiPropertySection :title="t('mouseFollower2D')" v-if="mouseFollower" ><template #actions><span>{{ t('runtimeComponent') }}</span></template><UiPropertyRow :label="t('offset')"><div><NumericExpressionInput v-model="mouseFollower.offset.x" :resource-key="entity.uuid + ':' + mouseFollower.uuid + ':mouseFollower.offset.x'" /><NumericExpressionInput v-model="mouseFollower.offset.y" :resource-key="entity.uuid + ':' + mouseFollower.uuid + ':mouseFollower.offset.y'" /></div></UiPropertyRow><UiPropertyRow :label="t('maximumSpeed')"><NumericExpressionInput v-model="mouseFollower.maximumSpeed" :minimum="0" :step="0.1" :resource-key="entity.uuid + ':' + mouseFollower.uuid + ':mouseFollower.maximumSpeed'" /></UiPropertyRow><small>{{ t('zeroMeansExact') }}</small></UiPropertySection>
  <UiPropertySection :title="t('cameraFollow2D')" v-if="follow" ><template #actions><span>{{ t('runtimeComponent') }}</span></template><UiPropertyRow :label="t('targetEntity')"><select v-model="follow.targetUuid"><option value="">{{ t('byTag') }}</option><option v-for="candidate in targets" :key="candidate.uuid" :value="candidate.uuid">{{ candidate.name }}</option></select></UiPropertyRow><UiPropertyRow :label="t('targetTag')"><input v-model="follow.targetTag"></UiPropertyRow><UiPropertyRow :label="t('offset')"><div><NumericExpressionInput v-model="follow.offset.x" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.offset.x'" /><NumericExpressionInput v-model="follow.offset.y" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.offset.y'" /></div></UiPropertyRow><UiPropertyRow :label="t('smoothing')"><NumericExpressionInput v-model="follow.smoothing" :minimum="0" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.smoothing'" /></UiPropertyRow><UiPropertyRow :label="t('deadZone')"><div><NumericExpressionInput v-model="follow.deadZone.x" :minimum="0" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.deadZone.x'" /><NumericExpressionInput v-model="follow.deadZone.y" :minimum="0" :resource-key="entity.uuid + ':' + follow.uuid + ':follow.deadZone.y'" /></div></UiPropertyRow></UiPropertySection>
</template>

<script setup lang="ts">
import NumericExpressionInput from './NumericExpressionInput.vue'
import { computed } from 'vue'
import { assetReference, assetState } from '../assets/AssetDatabase'
import { t } from '../i18n'
import { physicsState } from '../store/physics'
import type { Entity } from '../world/Entity'
import type { CameraFollow2D, Collectible2D, Cooldown2D, DamageHitbox2D, GridMover2D, Health2D, Lifetime2D, MouseFollower2D, PlatformController2D, Projectile2D, Spawner2D, TopDownController2D } from '../world/components'

const props = defineProps<{ entity: Entity }>()
const grid = computed(/* 调用 props.entity.getComponent<GridMover2D>('GridMover2D') 并返回调用结果。 */ () => props.entity.getComponent<GridMover2D>('GridMover2D')), platform = computed(/* 调用 props.entity.getComponent<PlatformController2D>('PlatformController2D') 并返回调用结果。 */ () => props.entity.getComponent<PlatformController2D>('PlatformController2D')), topDown = computed(/* 调用 props.entity.getComponent<TopDownController2D>('TopDownController2D') 并返回调用结果。 */ () => props.entity.getComponent<TopDownController2D>('TopDownController2D'))
const health = computed(/* 调用 props.entity.getComponent<Health2D>('Health2D') 并返回调用结果。 */ () => props.entity.getComponent<Health2D>('Health2D')), hitbox = computed(/* 调用 props.entity.getComponent<DamageHitbox2D>('DamageHitbox2D') 并返回调用结果。 */ () => props.entity.getComponent<DamageHitbox2D>('DamageHitbox2D')), collectible = computed(/* 调用 props.entity.getComponent<Collectible2D>('Collectible2D') 并返回调用结果。 */ () => props.entity.getComponent<Collectible2D>('Collectible2D')), projectile = computed(/* 调用 props.entity.getComponent<Projectile2D>('Projectile2D') 并返回调用结果。 */ () => props.entity.getComponent<Projectile2D>('Projectile2D'))
const spawner = computed(/* 调用 props.entity.getComponent<Spawner2D>('Spawner2D') 并返回调用结果。 */ () => props.entity.getComponent<Spawner2D>('Spawner2D')), cooldown = computed(/* 调用 props.entity.getComponent<Cooldown2D>('Cooldown2D') 并返回调用结果。 */ () => props.entity.getComponent<Cooldown2D>('Cooldown2D')), lifetime = computed(/* 调用 props.entity.getComponent<Lifetime2D>('Lifetime2D') 并返回调用结果。 */ () => props.entity.getComponent<Lifetime2D>('Lifetime2D')), mouseFollower = computed(/* 调用 props.entity.getComponent<MouseFollower2D>('MouseFollower2D') 并返回调用结果。 */ () => props.entity.getComponent<MouseFollower2D>('MouseFollower2D')), follow = computed(/* 调用 props.entity.getComponent<CameraFollow2D>('CameraFollow2D') 并返回调用结果。 */ () => props.entity.getComponent<CameraFollow2D>('CameraFollow2D'))
const vectorActions = computed(/** 仅返回二维向量输入动作供移动绑定选择。 */ () => physicsState.inputMap.filter(/* 比较 action.kind 与 'vector2'，返回严格相等的判断结果。 */ action => action.kind === 'vector2')), scalarActions = computed(/* 调用 physicsState.inputMap.filter(action => action.kind === 'axis' || action.kind === 'button') 并返回调用结果。 */ () => physicsState.inputMap.filter(/* 先计算 action.kind === 'axis'；仅当其为假值时求右侧 action.kind === 'button'，返回短路求值结果。 */ action => action.kind === 'axis' || action.kind === 'button')), buttonActions = computed(/** 仅返回按钮输入动作供事件绑定选择。 */ () => physicsState.inputMap.filter(/* 比较 action.kind 与 'button'，返回严格相等的判断结果。 */ action => action.kind === 'button'))
const prefabAssets = computed(/** 仅返回预制体资源供生成器选择。 */ () => assetState.records.filter(/* 比较 asset.assetType 与 'prefab'，返回严格相等的判断结果。 */ asset => asset.assetType === 'prefab')), targets = computed(/** 排除当前实体，返回其他世界实体作为目标候选。 */ () => physicsState.world.entities.filter(/* 比较 entity 与 props.entity，返回严格不等的判断结果。 */ entity => entity !== props.entity))
</script>

<style scoped>
header{display:flex;align-items:center;justify-content:space-between;gap:var(--space-2)}header span{color:var(--text-muted);line-height:1.4}
</style>
