<template><aside class="layer-bar"><div class="layer-header">{{ t('layers') }}</div><div class="layer-list"><button v-for="layer in state.layers" :key="layer" :class="{ active: state.activeLayer === layer }" :title="t('rightClickOptions')" @click="setActiveLayer(layer)" @contextmenu.prevent="openContextMenu($event, 'layer', layer)"><i class="layer-color" :style="{ background: layerColorCss(layer) }"></i><span>{{ layer }}</span></button></div><button class="add" :title="t('addLayer')" @click="addLayer">＋</button></aside></template>
<script setup lang="ts">
import { t } from '../i18n'
import { addLayer, editorState as state, openContextMenu, setActiveLayer } from '../store/editor'
import { layerColorCss } from '../world/layers'
</script>
<style scoped>
.layer-bar { position: absolute; top: 58px; left: 12px; z-index: 140; width: 58px; max-height: calc(100% - 72px); padding: 8px 6px; display: flex; flex-direction: column; gap: 6px; border: 1px solid var(--border-subtle); border-radius: 14px; background: var(--surface-1); backdrop-filter: var(--glass-blur); box-shadow: var(--shadow-sm); }.layer-header { color: var(--text-muted); font-size: 7.5px; font-weight: 700; text-align: center; letter-spacing: .08em; text-transform: uppercase; overflow: hidden; }.layer-list { display: flex; flex-direction: column; gap: 3px; overflow: auto; }button { min-height: 34px; padding: 4px; display: flex; align-items: center; justify-content: center; gap: 5px; border: 1px solid transparent; border-radius: 9px; color: var(--text-muted); background: transparent; font-size: 10px; }.layer-color { width: 11px; height: 11px; flex: 0 0 11px; border: 2px solid color-mix(in srgb, white 72%, transparent); border-radius: 50%; box-shadow: 0 0 0 1px var(--border-strong); }button img { width: 13px; height: 13px; opacity: .55; filter: var(--icon-filter); }button:hover { color: var(--text-primary); background: var(--surface-hover); }button.active { color: var(--accent); border-color: color-mix(in srgb, var(--accent) 25%, transparent); background: var(--accent-soft); }button.active img { opacity: 1; }.add { border-style: dashed; border-color: var(--border-strong); color: var(--text-secondary); font-size: 17px; }
</style>
