<!-- 粒子模块编辑器：显示诊断与成本，编辑模块值并提交规范化粒子配置。 -->
<template>
  <section class="particle-graph-editor">
    <header><div><strong>{{ t('particleGraph') }}</strong><small>{{ t('particleGraphHint') }}</small></div><label>{{ t('simulationBackend') }}<select v-model="document.simulation" @change="commit"><option>Auto</option><option>CPU</option><option>GPU</option></select></label></header>
    <div class="particle-layout">
      <aside><div v-for="item in document.modules" :key="item.id" class="module-row" :class="{ active: selectedId === item.id, disabled: !item.enabled }"><input :aria-label="t('enabled') + ' · ' + t(`particleModule${item.kind}`)" :checked="item.enabled" type="checkbox" @click.stop @change="toggle(item.id,$event)"><button :aria-pressed="selectedId === item.id" @click="selectedId = item.id"><span>{{ t(`particleModule${item.kind}`) }}</span><small>#{{ item.order + 1 }}</small></button></div></aside>
      <main v-if="selected">
        <header><strong>{{ t(`particleModule${selected.kind}`) }}</strong><span>{{ selected.id }}</span></header>
        <label v-if="selected.kind === 'Spawn'">{{ t('emissionRate') }}<NumericExpressionInput :model-value="Number(value('rate',20))" :minimum="0" :maximum="100000" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':rate'" @update:model-value="setNumber('rate',$event)" /></label>
        <label v-if="selected.kind === 'Spawn'">{{ t('burst') }}<NumericExpressionInput :model-value="Number(value('burst',0))" :minimum="0" :maximum="100000" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':burst'" @update:model-value="setNumber('burst',$event,true)" /></label>
        <label v-if="selected.kind === 'Spawn'">{{ t('lifetime') }}<NumericExpressionInput :model-value="Number(value('lifetime',1))" :minimum=".0001" :maximum="86400" :step=".1" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':lifetime'" @update:model-value="setNumber('lifetime',$event)" /></label>
        <label v-if="selected.kind === 'Spawn'">{{ t('maxParticles') }}<NumericExpressionInput :model-value="Number(value('maximum',1000))" :minimum="0" :maximum="100000" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':maximum'" @update:model-value="setNumber('maximum',$event,true)" /></label>
        <label v-if="selected.kind === 'Shape'">{{ panelControlLabel('emissionShape') }}<select :value="value('shape','Point')" @change="setText('shape',$event)"><option>Point</option><option>Box</option><option>Circle</option><option>Edge</option></select></label>
        <label v-if="selected.kind === 'Velocity'">{{ t('minimumVelocity') }}<span class="particle-vector"><NumericExpressionInput v-for="index in [0,1]" :key="index" :aria-label="t('minimumVelocity') + ' ' + (index === 0 ? 'X' : 'Y')" :model-value="vectorComponent('minimum',[-1,1],index)" :minimum="-1000000000" :maximum="1000000000" :step=".01" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':minimum:' + index" @update:model-value="setVectorComponent('minimum',[-1,1],index,$event)" /></span></label>
        <label v-if="selected.kind === 'Velocity'">{{ t('maximumVelocity') }}<span class="particle-vector"><NumericExpressionInput v-for="index in [0,1]" :key="index" :aria-label="t('maximumVelocity') + ' ' + (index === 0 ? 'X' : 'Y')" :model-value="vectorComponent('maximum',[1,3],index)" :minimum="-1000000000" :maximum="1000000000" :step=".01" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':maximum:' + index" @update:model-value="setVectorComponent('maximum',[1,3],index,$event)" /></span></label>
        <label v-if="selected.kind === 'Force'">{{ t('particleGravity') }}<span class="particle-vector"><NumericExpressionInput v-for="index in [0,1]" :key="index" :aria-label="t('particleGravity') + ' ' + (index === 0 ? 'X' : 'Y')" :model-value="vectorComponent('gravity',[0,-9.80665],index)" :minimum="-1000000000" :maximum="1000000000" :step=".01" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':gravity:' + index" @update:model-value="setVectorComponent('gravity',[0,-9.80665],index,$event)" /></span></label>
        <label v-if="selected.kind === 'Size'">{{ t('startSize') }}<NumericExpressionInput :model-value="Number(value('start',.2))" :minimum="0" :step=".05" :maximum="1000000" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':start'" @update:model-value="setNumber('start',$event)" /></label>
        <label v-if="selected.kind === 'Size'">{{ t('endSize') }}<NumericExpressionInput :model-value="Number(value('end',0))" :minimum="0" :step=".05" :maximum="1000000" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':end'" @update:model-value="setNumber('end',$event)" /></label>
        <label v-if="selected.kind === 'Collision'">{{ t('collisionMode') }}<select :value="value('mode','Bounce')" @change="setText('mode',$event)"><option>Bounce</option><option>Stop</option></select></label>
        <label v-if="selected.kind === 'Events'">{{ t('eventSignal') }}<input :value="value('signal','particle.event')" @input="setText('signal',$event)"></label>
        <label v-if="selected.kind === 'SubEmitter'">{{ t('subEmitterUuid') }}<input :value="value('emitterUuid','')" @input="setText('emitterUuid',$event)"></label>
        <label v-if="selected.kind === 'Trail'">{{ t('trailLength') }}<NumericExpressionInput :model-value="Number(value('length',12))" :minimum="2" :maximum="32" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':length'" @update:model-value="setNumber('length',$event,true)" /></label>
        <label v-if="selected.kind === 'Trail'">{{ t('trailWidth') }}<NumericExpressionInput :model-value="Number(value('width',.08))" :minimum=".001" :step=".01" :maximum="1000000" :resource-key="(props.resourceKey ?? 'particle-graph') + ':' + selected.id + ':width'" @update:model-value="setNumber('width',$event)" /></label>
        <label v-if="selected.kind === 'Renderer'">{{ t('blendMode') }}<select :value="value('blend','Additive')" @change="setText('blend',$event)"><option>Alpha</option><option>Additive</option></select></label>
        <p v-if="!editableSelected">{{ t('moduleUsesInspectorCurves') }}</p>
      </main>
      <aside class="particle-preview">
        <strong>{{ t('budgetEstimate') }}</strong><dl><div><dt>{{ t('maxParticles') }}</dt><dd>{{ cost.maximumParticles }}</dd></div><div><dt>{{ t('operationsPerFrame') }}</dt><dd>{{ cost.operationsPerFrame }}</dd></div><div><dt>CPU</dt><dd>{{ cost.estimatedCpuMs }} ms</dd></div><div><dt>{{ t('trailVertices') }}</dt><dd>{{ cost.trailVertices }}</dd></div></dl>
<!-- 诊断过滤回调检查是否存在错误，决定提示的错误或警告样式。 -->        <p>{{ backendMessage }}</p><p :class="diagnostics.some(item=>item.severity==='error') ? 'error' : diagnostics.length ? 'warning' : 'good'">{{ diagnostics.length ? t('particleFallbackNotice') : costMessage }}</p>
      </aside>
    </div>
  </section>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import NumericExpressionInput from './NumericExpressionInput.vue'
import { t } from '../i18n'
import { panelControlLabel } from '../editor/panelControlCopy'
import { normalizeParticleGraph, particleGraphCost, validateParticleGraph, type ParticleGraphDocument } from '../renderer/particleGraph'
const props = defineProps<{ modelValue: ParticleGraphDocument; backend: 'WebGL2' | 'Canvas2D'; resourceKey?: string }>()
const emit = defineEmits<{ 'update:modelValue': [value: ParticleGraphDocument] }>()
const selectedId = ref('spawn'), document = computed(/* 返回 props.modelValue 的当前值。 */ () => props.modelValue), selected = computed(/** 读取选中模块，缺失时回退首项或空值。 */ () => document.value.modules.find(/* 比较 item.id 与 selectedId.value，返回严格相等的判断结果。 */ item => item.id === selectedId.value) ?? document.value.modules[0] ?? null)
const diagnostics = computed(/** 按当前后端校验粒子图。 */ () => validateParticleGraph(document.value, props.backend)), cost = computed(/** 估算粒子图运行成本。 */ () => particleGraphCost(document.value))
const backendMessage = computed(/** 根据 Canvas 后端或 GPU 不支持的启用模块显示 CPU、混合或通用执行提示。 */ () => props.backend === 'Canvas2D' ? t('particleCpuOnly') : document.value.simulation === 'GPU' && document.value.modules.some(/** 检查启用的碰撞、事件或子发射器模块是否需要回退。 */ item => item.enabled && ['Collision','Events','SubEmitter'].includes(item.kind)) ? t('particleHybridFallback') : t('particleCpuGpu'))
const costMessage = computed(/** 按每帧操作成本阈值显示预算建议。 */ () => cost.value.operationsPerFrame > 700_000 ? t('particleBudgetReduce') : t('particleBudgetGood'))
const editableSelected = computed(/** 判断选中模块是否属于提供通用参数控件的种类。 */ () => selected.value && ['Spawn','Shape','Velocity','Force','Size','Collision','Events','SubEmitter','Trail','Renderer'].includes(selected.value.kind))
/** 规范化粒子文档并向父组件发出更新。 */ function commit(){emit('update:modelValue',normalizeParticleGraph(document.value))}
/** 更新指定模块启用状态后提交文档。 */ function toggle(id:string,event:Event){const item=document.value.modules.find(/* 比较 candidate.id 与 id，返回严格相等的判断结果。 */ candidate=>candidate.id===id);if(item)item.enabled=(event.target as HTMLInputElement).checked;commit()}
/** 读取所选模块值，缺失使用调用方默认值。 */ function value(key:string,fallback:number|string){return selected.value?.values[key]??fallback}
/** 读取向量指定分量并转换为数字，非数组时使用默认分量。 */ function vectorComponent(key:string,fallback:number[],index:number):number{const raw=selected.value?.values[key];return Array.isArray(raw)?Number(raw[index]??fallback[index]):fallback[index]!}
/** 只接受有限数值，按需取整后写入所选模块并提交。 */ function setNumber(key:string,number:number,integer=false){if(!selected.value||!Number.isFinite(number))return;selected.value.values[key]=integer?Math.round(number):number;commit()}
/** 读取输入或选择控件文本，写入所选模块并提交。 */ function setText(key:string,event:Event){if(!selected.value)return;selected.value.values[key]=(event.target as HTMLInputElement|HTMLSelectElement).value;commit()}
/** 保留另一个向量分量，更新指定有限分量并提交。 */ function setVectorComponent(key:string,fallback:number[],index:number,number:number){if(!selected.value||!Number.isFinite(number))return;const values=[vectorComponent(key,fallback,0),vectorComponent(key,fallback,1)];values[index]=number;selected.value.values[key]=values;commit()}
</script>

<style scoped>
main>label{flex-wrap:wrap}
.particle-vector{display:flex;flex-wrap:wrap;gap:6px;flex:1 1 18ch;min-width:0}

.particle-graph-editor{min-height:350px;display:flex;flex-direction:column;border:1px solid var(--border-subtle);border-radius:10px;overflow:hidden;background:var(--surface-2)}.particle-graph-editor>header{min-height:42px;padding:6px 9px;display:flex;align-items:center;justify-content:space-between;gap:10px;border-bottom:1px solid var(--border-subtle)}header>div{display:grid}header small{color:var(--text-muted);font-size:11px}.particle-layout{min-height:0;display:grid;grid-template-columns:minmax(170px,220px) minmax(290px,1fr) minmax(210px,280px);flex:1}.particle-layout>aside,.particle-layout>main{min-width:0;padding:8px;overflow:auto;border-right:1px solid var(--border-subtle)}.particle-layout>aside:first-child{display:flex;flex-direction:column;gap:4px}.particle-layout>aside:first-child button{min-height:32px;padding:4px 7px;display:grid;grid-template-columns:20px 1fr auto;align-items:center;text-align:left}.particle-layout button.disabled{opacity:.6}.particle-layout button.active{border-color:var(--accent);background:var(--accent-soft)}main header{display:flex;justify-content:space-between}main>label{min-height:34px;display:flex;align-items:center;justify-content:space-between;gap:8px;border-bottom:1px solid var(--border-subtle);color:var(--text-muted)}main input,main select{width:min(180px,55%)}.particle-preview{border-right:0!important}.particle-preview dl{display:grid;gap:5px}.particle-preview dl div{display:flex;justify-content:space-between}.particle-preview dd{margin:0;color:var(--accent)}.particle-preview p{font-size:11px;line-height:1.4}.good{color:var(--success)}.warning{color:var(--warning)}.error{color:var(--danger)}@container nova-particle (max-width:1000px){.particle-layout{grid-template-columns:180px 1fr}.particle-preview{grid-column:1/-1;max-height:150px;border-top:1px solid var(--border-subtle)}}@container nova-particle (max-width:680px){.particle-layout{grid-template-columns:1fr}.particle-layout>aside:first-child{max-height:135px}.particle-preview{grid-column:auto}}
/* 26.13: module enable and selection are separate keyboard controls. */
.particle-graph-editor{container:nova-particle/inline-size;min-width:0}.particle-graph-editor>header{flex-wrap:wrap}.particle-graph-editor>header>*{min-width:0;max-width:100%}.particle-layout{overflow:auto}.particle-layout>main{container:nova-particle-fields/inline-size}.module-row{min-width:0;display:grid;grid-template-columns:20px minmax(0,1fr);gap:5px;align-items:center}.module-row>button{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;min-width:0;white-space:normal;overflow-wrap:anywhere}.module-row.disabled{opacity:.6}.module-row.active>button{border-color:var(--accent);background:var(--accent-soft)}.particle-preview :is(p,dt,dd){overflow-wrap:anywhere}.particle-preview dl div{flex-wrap:wrap;gap:5px}
@container nova-particle (max-width:1000px){.particle-layout{grid-template-columns:180px minmax(0,1fr)}.particle-preview{grid-column:1/-1}}
@container nova-particle (max-width:680px){.particle-layout{grid-template-columns:minmax(0,1fr)}.particle-layout>aside:first-child{max-height:180px}.particle-preview{grid-column:auto;max-height:none}}
@container nova-particle-fields (max-width:380px){main>label{flex-direction:column;align-items:stretch;height:auto;gap:5px;padding-block:5px}main input,main select{width:100%;max-width:100%;min-width:0}main header{flex-wrap:wrap;overflow-wrap:anywhere}}
</style>
