<!-- 世界组件检查器：编辑导航、路径等场景世界组件。 -->
<template>
  <SimulationStatusPanel17 v-if="region || chunk" />
  <p v-if="form17.error.value" class="form-error17" role="alert">{{ form17.error.value }}</p>
  <UiPropertySection :title="(t('navigationRegion2D'))" v-if="region"  @focusin="form17.focus" @change="form17.change">
    <template #actions><span>{{ region.navigationMode }}</span></template>
    <UiPropertyRow :label="t('navigationMode')"><select v-model="region.navigationMode"><option>Grid</option><option>Polygon</option></select></UiPropertyRow>
    <UiPropertyRow :label="t('source')"><select v-model="region.source"><option>SceneGeometry</option><option>TileMap</option><option>Manual</option></select></UiPropertyRow>
    <UiPropertyRow :label="(t('source')) + ' UUID'" v-if="region.source === 'TileMap'"><input v-model="region.sourceEntityUuid"></UiPropertyRow>
    <UiPropertyRow :label="t('cellSize')"><NumericExpressionInput v-model="region.cellSize" :minimum="0.01" :step="0.05" :resource-key="entity.uuid + ':' + region.uuid + ':region.cellSize'" /></UiPropertyRow>
    <UiPropertyRow :label="t('agentRadius')"><NumericExpressionInput v-model="region.agentRadius" :minimum="0" :step="0.05" :resource-key="entity.uuid + ':' + region.uuid + ':region.agentRadius'" /></UiPropertyRow>
    <UiPropertyRow :label="t('navigationLayer')"><NumericExpressionInput v-model="region.navigationLayer" :minimum="1" :maximum="32" :resource-key="entity.uuid + ':' + region.uuid + ':region.navigationLayer'" /></UiPropertyRow>
    <UiPropertyRow :label="t('cost')"><NumericExpressionInput v-model="region.traversalCost" :minimum="0.001" :step="0.1" :resource-key="entity.uuid + ':' + region.uuid + ':region.traversalCost'" /></UiPropertyRow>
    <UiPropertyRow :label="t('dynamicRebake')"><input v-model="region.dynamic" type="checkbox"></UiPropertyRow>
    <div class="actions"><button :disabled="navigationBakeState.active" @click="bake">{{ t('bake') }}</button><button v-if="navigationBakeState.active" @click="cancelNavigationBake">{{ t('cancel') }}</button><button @click="clearBake">{{ t('clear') }}</button></div>
    <small>{{ bakeMessage || `${t('navigationProfile')}: ${profile.pathQueries} queries · ${profile.lastQueryMilliseconds.toFixed(2)} ms` }}</small>
    <details><summary>{{ t('navigationLinks') }} · {{ region.links.length }}</summary><article v-for="(link,index) in region.links" :key="link.id"><UiPropertyRow :label="t('enabled')"><input v-model="link.enabled" type="checkbox"></UiPropertyRow><UiPropertyRow :label="(label17('linkStart')) + ' X / Y'"><div><NumericExpressionInput v-model="link.start.x" aria-label="Start X" :resource-key="entity.uuid + ':navigation-link:' + link.id + ':link.start.x'" /><NumericExpressionInput v-model="link.start.y" aria-label="Start Y" :resource-key="entity.uuid + ':navigation-link:' + link.id + ':link.start.y'" /></div></UiPropertyRow><UiPropertyRow :label="(label17('linkEnd')) + ' X / Y'"><div><NumericExpressionInput v-model="link.end.x" aria-label="End X" :resource-key="entity.uuid + ':navigation-link:' + link.id + ':link.end.x'" /><NumericExpressionInput v-model="link.end.y" aria-label="End Y" :resource-key="entity.uuid + ':navigation-link:' + link.id + ':link.end.y'" /></div></UiPropertyRow><UiPropertyRow :label="label17('bidirectional')"><input v-model="link.bidirectional" type="checkbox"></UiPropertyRow><UiPropertyRow :label="t('cost')"><NumericExpressionInput v-model="link.cost" :minimum="0.000001" :step="0.1" :resource-key="entity.uuid + ':navigation-link:' + link.id + ':link.cost'" /></UiPropertyRow><button @click="removeLink(index)">{{ t('remove') }}</button></article><UiButton icon="add" @click="addLink">{{ t('navigationLinks') }}</UiButton></details>
  </UiPropertySection>

  <UiPropertySection :title="(t('navigationAgent2D'))" v-if="agent"  @focusin="form17.focus" @change="form17.change"><template #actions><span>{{ agent.pathStatus }}</span></template><UiPropertyRow :label="t('targetPosition')"><div><NumericExpressionInput v-model="agent.targetPosition.x" :aria-label="t('targetPosition') + ' X'" :resource-key="entity.uuid + ':' + agent.uuid + ':agent.targetPosition.x'" /><NumericExpressionInput v-model="agent.targetPosition.y" :aria-label="t('targetPosition') + ' Y'" :resource-key="entity.uuid + ':' + agent.uuid + ':agent.targetPosition.y'" /></div></UiPropertyRow><UiPropertyRow :label="t('speed')"><NumericExpressionInput v-model="agent.speed" :minimum="0" :resource-key="entity.uuid + ':' + agent.uuid + ':agent.speed'" /></UiPropertyRow><UiPropertyRow :label="t('acceleration')"><NumericExpressionInput v-model="agent.acceleration" :minimum="0" :resource-key="entity.uuid + ':' + agent.uuid + ':agent.acceleration'" /></UiPropertyRow><UiPropertyRow :label="t('agentRadius')"><NumericExpressionInput v-model="agent.radius" :minimum="0" :resource-key="entity.uuid + ':' + agent.uuid + ':agent.radius'" /></UiPropertyRow><UiPropertyRow :label="t('avoidance')"><input v-model="agent.avoidance" type="checkbox"></UiPropertyRow><UiPropertyRow :label="t('avoidancePriority')"><UiSlider :resource-key="entity.uuid + ':' + agent.uuid + ':avoidancePriority'" v-model.lazy.number="agent.avoidancePriority" min="0" max="1" step="0.01" /></UiPropertyRow><small>{{ agent.path.length }} {{ t('waypoints') }}</small></UiPropertySection>

  <UiPropertySection :title="(t('navigationObstacle2D'))" v-if="obstacle"  @focusin="form17.focus" @change="form17.change"><template #actions><span>{{ obstacle.dynamic ? t('dynamic') : t('static') }}</span></template><UiPropertyRow :label="t('areaShape')"><select v-model="obstacle.shape"><option>Circle</option><option>Box</option></select></UiPropertyRow><UiPropertyRow :label="t('dynamicRebake')"><input v-model="obstacle.dynamic" type="checkbox"></UiPropertyRow><UiPropertyRow :label="t('navigationLayer')"><NumericExpressionInput v-model="obstacle.navigationLayer" :minimum="1" :maximum="32" :resource-key="entity.uuid + ':' + obstacle.uuid + ':obstacle.navigationLayer'" /></UiPropertyRow></UiPropertySection>

  <UiPropertySection :title="(t('worldChunk2D'))" v-if="chunk"  @focusin="form17.focus" @change="form17.change"><template #actions><span>{{ streamCell?.status ?? 'Unloaded' }}</span></template><UiPropertyRow :label="t('chunkSize')"><div><NumericExpressionInput v-model="chunk.size.x" :minimum="1" :aria-label="t('chunkSize') + ' X'" :resource-key="entity.uuid + ':' + chunk.uuid + ':chunk.size.x'" /><NumericExpressionInput v-model="chunk.size.y" :minimum="1" :aria-label="t('chunkSize') + ' Y'" :resource-key="entity.uuid + ':' + chunk.uuid + ':chunk.size.y'" /></div></UiPropertyRow><UiPropertyRow :label="t('loadDistance')"><NumericExpressionInput v-model="chunk.loadDistance" :minimum="0" :resource-key="entity.uuid + ':' + chunk.uuid + ':chunk.loadDistance'" /></UiPropertyRow><UiPropertyRow :label="t('unloadDistance')"><NumericExpressionInput v-model="chunk.unloadDistance" :minimum="chunk.loadDistance" :resource-key="entity.uuid + ':' + chunk.uuid + ':chunk.unloadDistance'" /></UiPropertyRow><UiPropertyRow :label="t('prefetchDistance')"><NumericExpressionInput v-model="chunk.prefetchDistance" :minimum="0" :resource-key="entity.uuid + ':' + chunk.uuid + ':chunk.prefetchDistance'" /></UiPropertyRow><UiPropertyRow :label="t('memoryEstimate')"><NumericExpressionInput v-model="chunk.memoryEstimateMb" :minimum="0" :resource-key="entity.uuid + ':' + chunk.uuid + ':chunk.memoryEstimateMb'" /></UiPropertyRow><UiPropertyRow :label="t('cachePolicy')"><select v-model="chunk.cachePolicy"><option>Release</option><option>LRU</option><option>Retain</option></select></UiPropertyRow><UiPropertyRow :label="t('ownership')"><input v-model="chunk.ownership"></UiPropertyRow><UiPropertyRow :label="t('dependencies')" class="stacked"><textarea :value="chunk.dependencies.join('\n')" @change="setDependencies"></textarea></UiPropertyRow><small>{{ streamCell ? `${streamCell.memoryMb.toFixed(1)} MB · ${streamCell.owner}` : t('notLoaded') }}</small></UiPropertySection>

  <UiPropertySection :title="(t('behaviorTree2D'))" v-if="behavior"  @focusin="form17.focus" @change="form17.change"><template #actions><span>{{ aiEnabled ? t('enabled') : t('packageRequired') }}</span></template><UiButton icon="add" v-if="!aiEnabled" class="package" @click="enableAi">{{ t('aiPackage') }}</UiButton><UiPropertyRow :label="t('treeAsset')"><input v-model="behavior.treeAsset"></UiPropertyRow><UiPropertyRow :label="t('tickRate')"><NumericExpressionInput v-model="behavior.tickRate" :minimum="1" :maximum="240" :resource-key="entity.uuid + ':' + behavior.uuid + ':behavior.tickRate'" /></UiPropertyRow></UiPropertySection>

  <UiPropertySection :title="(t('objectPool2D'))" v-if="pool"  @focusin="form17.focus" @change="form17.change"><template #actions><span>{{ poolEnabled ? t('enabled') : t('packageRequired') }}</span></template><UiButton icon="add" v-if="!poolEnabled" class="package" @click="enablePool">{{ t('objectPool') }}</UiButton><UiPropertyRow :label="t('capacity')"><NumericExpressionInput v-model="pool.capacity" :minimum="1" :resource-key="entity.uuid + ':' + pool.uuid + ':pool.capacity'" /></UiPropertyRow><UiPropertyRow :label="t('prewarm')"><NumericExpressionInput v-model="pool.prewarm" :minimum="0" :maximum="pool.capacity" :resource-key="entity.uuid + ':' + pool.uuid + ':pool.prewarm'" /></UiPropertyRow><UiPropertyRow :label="t('resetContract')"><select v-model="pool.resetContract"><option>TransformAndPhysics</option><option>FullSerializedState</option><option>CustomSignal</option></select></UiPropertyRow><UiPropertyRow :label="t('maximumLifetime')"><NumericExpressionInput v-model="pool.maximumLifetime" :minimum="0" :step="0.1" :resource-key="entity.uuid + ':' + pool.uuid + ':pool.maximumLifetime'" /></UiPropertyRow><small v-if="poolStats">{{ poolStats.active }}/{{ poolStats.allocated }} {{ t('active') }} · {{ poolStats.reused }} reused · {{ poolStats.leaked }} leaked</small></UiPropertySection>

  <UiPropertySection :title="(t('particleEmitter2D'))" v-if="emitter"  @focusin="form17.focus" @change="form17.change"><template #actions><span>{{ emitter.simulationBackend }}</span></template><UiPropertyRow :label="t('particleSystemAsset')"><input v-model="emitter.particleSystemAsset" placeholder="asset://…"></UiPropertyRow><UiPropertyRow :label="t('simulationBackend')"><select v-model="emitter.simulationBackend"><option>Auto</option><option>CPU</option><option>GPU</option></select></UiPropertyRow><UiPropertyRow :label="t('emissionRate')"><NumericExpressionInput v-model="emitter.emissionRate" :minimum="0" :maximum="100000" :resource-key="entity.uuid + ':' + emitter.uuid + ':emitter.emissionRate'" /></UiPropertyRow><UiPropertyRow :label="t('burst')"><NumericExpressionInput v-model="emitter.burst" :minimum="0" :maximum="100000" :resource-key="entity.uuid + ':' + emitter.uuid + ':emitter.burst'" /></UiPropertyRow><UiPropertyRow :label="t('lifetime')"><NumericExpressionInput v-model="emitter.lifetime" :minimum=".0001" :maximum="86400" :step=".1" :resource-key="entity.uuid + ':' + emitter.uuid + ':emitter.lifetime'" /></UiPropertyRow><UiPropertyRow :label="t('maxParticles')"><NumericExpressionInput v-model="emitter.maxParticles" :minimum="0" :maximum="100000" :resource-key="entity.uuid + ':' + emitter.uuid + ':emitter.maxParticles'" /></UiPropertyRow><UiPropertyRow :label="t('collisionMode')"><select v-model="emitter.collisionMode"><option>None</option><option>Bounce</option><option>Stop</option></select></UiPropertyRow><UiPropertyRow :label="t('eventSignal')"><input v-model="emitter.eventSignal" maxlength="128"></UiPropertyRow><UiPropertyRow :label="t('trailLength')"><span class="inline"><input v-model="emitter.trailEnabled" type="checkbox"><NumericExpressionInput v-model="emitter.trailLength" :minimum="2" :maximum="32" :resource-key="entity.uuid + ':' + emitter.uuid + ':emitter.trailLength'" /></span></UiPropertyRow><UiPropertyRow :label="t('trailWidth')"><NumericExpressionInput v-model="emitter.trailWidth" :minimum=".001" :step=".01" :resource-key="entity.uuid + ':' + emitter.uuid + ':emitter.trailWidth'" /></UiPropertyRow><small>{{ t('particleGraphHint') }}</small></UiPropertySection>
</template>

<script setup lang="ts">
import NumericExpressionInput from './NumericExpressionInput.vue'
import SimulationStatusPanel17 from './SimulationStatusPanel17.vue'
import { useSimulationFormGuard17 } from '../editor/simulationForm17'
import { simulationLabel17 as label17 } from '../editor/simulationLabels17'

import { computed, ref } from 'vue'
import { t } from '../i18n'
import type { Entity } from '../world/Entity'
import type { BehaviorTree2D, NavigationAgent2D, NavigationObstacle2D, NavigationRegion2D, ObjectPool2D, ParticleEmitter2D, WorldChunk2D } from '../world/components'
import { clearNavigationData, navigationProfileSnapshot, requestNavigationBake, navigationBakeState, cancelNavigationBake } from '../runtime/navigation2d'
import { physicsState, pushHistory } from '../store/physics'
import { OFFICIAL_AI_PACKAGE_ID, OFFICIAL_OBJECT_POOL_PACKAGE_ID, enableOfficialPackage, packageEnabled } from '../runtime/packages'
import { worldStreamingState } from '../runtime/worldStreaming'
import { objectPoolDiagnostics } from '../runtime/objectPool'

const form17 = useSimulationFormGuard17(/* 调用 pushHistory('Edit world component') 并返回调用结果。 */ () => pushHistory('Edit world component'))
const props = defineProps<{ entity: Entity }>()
const region = computed(/* 调用 props.entity.getComponent<NavigationRegion2D>('NavigationRegion2D') 并返回调用结果。 */ () => props.entity.getComponent<NavigationRegion2D>('NavigationRegion2D'))
const agent = computed(/* 调用 props.entity.getComponent<NavigationAgent2D>('NavigationAgent2D') 并返回调用结果。 */ () => props.entity.getComponent<NavigationAgent2D>('NavigationAgent2D'))
const obstacle = computed(/* 调用 props.entity.getComponent<NavigationObstacle2D>('NavigationObstacle2D') 并返回调用结果。 */ () => props.entity.getComponent<NavigationObstacle2D>('NavigationObstacle2D'))
const chunk = computed(/* 调用 props.entity.getComponent<WorldChunk2D>('WorldChunk2D') 并返回调用结果。 */ () => props.entity.getComponent<WorldChunk2D>('WorldChunk2D'))
const behavior = computed(/* 调用 props.entity.getComponent<BehaviorTree2D>('BehaviorTree2D') 并返回调用结果。 */ () => props.entity.getComponent<BehaviorTree2D>('BehaviorTree2D'))
const pool = computed(/* 调用 props.entity.getComponent<ObjectPool2D>('ObjectPool2D') 并返回调用结果。 */ () => props.entity.getComponent<ObjectPool2D>('ObjectPool2D'))
const emitter = computed(/* 调用 props.entity.getComponent<ParticleEmitter2D>('ParticleEmitter2D') 并返回调用结果。 */ () => props.entity.getComponent<ParticleEmitter2D>('ParticleEmitter2D'))
const profile = computed(/* 调用 navigationProfileSnapshot() 并返回调用结果。 */ () => navigationProfileSnapshot())
const streamCell = computed(/** 查找当前实体对应的世界流送单元。 */ () => worldStreamingState.cells.find(/* 比较 cell.entityUuid 与 props.entity.uuid，返回严格相等的判断结果。 */ cell => cell.entityUuid === props.entity.uuid))
const poolStats = computed(/** 查找当前实体拥有的对象池诊断。 */ () => objectPoolDiagnostics().find(/* 比较 item.ownerUuid 与 props.entity.uuid，返回严格相等的判断结果。 */ item => item.ownerUuid === props.entity.uuid))
const aiEnabled = computed(/* 调用 packageEnabled(OFFICIAL_AI_PACKAGE_ID) 并返回调用结果。 */ () => packageEnabled(OFFICIAL_AI_PACKAGE_ID)), poolEnabled = computed(/* 调用 packageEnabled(OFFICIAL_OBJECT_POOL_PACKAGE_ID) 并返回调用结果。 */ () => packageEnabled(OFFICIAL_OBJECT_POOL_PACKAGE_ID))
const bakeMessage = ref('')
/** 请求世界导航烘焙并显示烘焙数、单元数及耗时，失败显示错误。 */ async function bake() { try { const result = await requestNavigationBake(physicsState.world.entities); bakeMessage.value = `${result.baked} / ${result.cells} · ${result.milliseconds.toFixed(2)} ms` } catch (error) { bakeMessage.value = String(error) } }
/** 清除当前区域或全部导航数据，更新提示并记录历史。 */ function clearBake() { clearNavigationData(region.value ? props.entity.uuid : undefined); bakeMessage.value = t('cleared'); pushHistory('Clear navigation bake') }
/** 移除指定导航链接并记录历史。 */ function removeLink(index: number) { region.value?.links.splice(index, 1); pushHistory('Remove navigation link') }
/** 增加默认双向导航链接并记录历史。 */ function addLink() { region.value?.links.push({ id: crypto.randomUUID(), start: { x: 0, y: 0 }, end: { x: 1, y: 0 }, bidirectional: true, cost: 1, enabled: true }); pushHistory('Add navigation link') }
/** 按行清理流送依赖，去空白及空项并限制为一百二十八项。 */ function setDependencies(event: Event) { if (chunk.value) chunk.value.dependencies = (event.target as HTMLTextAreaElement).value.split(/\r?\n/).map(/* 调用 value.trim() 并返回调用结果。 */ value => value.trim()).filter(Boolean).slice(0, 128) }
/** 启用官方 AI 工具包并记录历史。 */ function enableAi() { enableOfficialPackage(OFFICIAL_AI_PACKAGE_ID); pushHistory('Enable AI Tools package') }
/** 启用官方对象池包并记录历史。 */ function enablePool() { enableOfficialPackage(OFFICIAL_OBJECT_POOL_PACKAGE_ID); pushHistory('Enable Object Pool package') }
</script>

<style scoped>
header{display:flex;justify-content:space-between;gap:var(--space-2)}header span,small{color:var(--text-muted)}.inline{display:flex;align-items:center;gap:var(--space-1)}.stacked{padding:var(--space-1) 0;align-items:stretch;flex-direction:column}.actions{display:flex;gap:var(--space-1)}.package{min-height:30px;padding:0 var(--space-2);border:1px solid var(--border-subtle);background:var(--surface-2);color:var(--text-secondary)}.package{border-color:var(--accent);color:var(--accent)}details article{display:grid;grid-template-columns:auto repeat(2,1fr) auto repeat(2,1fr) auto;gap:var(--space-0);align-items:center}header{flex-wrap:wrap}header strong,header span,small{overflow-wrap:anywhere;min-width:0}.actions{flex-wrap:wrap}details article{display:grid;grid-template-columns:minmax(0,1fr);padding:var(--space-2) 0;gap:var(--space-2);border-top:1px solid var(--border-subtle)}.form-error17{color:var(--danger,#d95065);overflow-wrap:anywhere}
details article .inline{flex-wrap:wrap}
</style>
