/** Measure final computed geometry, including explicit dense-tool exceptions. */
import assert from 'node:assert/strict'
export function collectComfortableGeometry({rootSelector=null}={}){
 const num=v=>Number.parseFloat(v)||0,root=document.documentElement,style=getComputedStyle(root),uiScale=num(style.getPropertyValue('--ui-scale'))||1,scope=rootSelector?document.querySelector(rootSelector):document
 if(!scope)throw new Error('Geometry root is missing: '+rootSelector)
 const query=selector=>[...(scope instanceof Element&&scope.matches(selector)?[scope]:[]),...scope.querySelectorAll(selector)]
 const compact=root.dataset.density==='compact',metrics={field:compact?32:44,font:compact?13:16,line:compact?19.5:24,verticalPadding:compact?5.25:9,tree:compact?28:40,fieldGap:compact?12:20,sectionGap:compact?16:28,inset:compact?12:20}
 const gameOwned=e=>!!e.closest('.theme-preview,.virtual-controls,[data-ui-scope="game"],[data-control-scope="game"]')
 const graphZoom=e=>{const transform=e.closest('.graph-transform');if(!transform)return 1;const matrix=new DOMMatrixReadOnly(getComputedStyle(transform).transform);return Math.hypot(matrix.a,matrix.b)||1}
 const visible=e=>{if(e.closest('[hidden],[inert],[aria-hidden="true"],.cm-editor'))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);if(!r.width||!r.height||s.display==='none'||s.visibility==='hidden'||num(s.opacity)===0)return false;let area={left:Math.max(r.left,0),top:Math.max(r.top,0),right:Math.min(r.right,innerWidth),bottom:Math.min(r.bottom,innerHeight)};for(let p=e.parentElement;p;p=p.parentElement){const ps=getComputedStyle(p),pr=p.getBoundingClientRect();if(/hidden|clip|auto|scroll/.test(ps.overflowX)){area.left=Math.max(area.left,pr.left);area.right=Math.min(area.right,pr.right)}if(/hidden|clip|auto|scroll/.test(ps.overflowY)){area.top=Math.max(area.top,pr.top);area.bottom=Math.min(area.bottom,pr.bottom)}}return area.right>area.left&&area.bottom>area.top}
 const read=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect(),diagram=!!e.closest('.graph-transform'),cssScale=diagram?1:uiScale,rectScale=diagram?graphZoom(e):uiScale,raw={fontSize:num(s.fontSize),lineHeight:s.lineHeight==='normal'?null:num(s.lineHeight),padding:[s.paddingTop,s.paddingRight,s.paddingBottom,s.paddingLeft].map(num),border:[s.borderTopWidth,s.borderRightWidth,s.borderBottomWidth,s.borderLeftWidth].map(num),radius:[s.borderTopLeftRadius,s.borderTopRightRadius,s.borderBottomRightRadius,s.borderBottomLeftRadius].map(num),height:r.height,width:r.width,rowGap:num(s.rowGap),columnGap:num(s.columnGap)};return{tag:e.tagName,type:e.getAttribute('type'),classes:e.className?.baseVal??e.className,label:e.getAttribute('aria-label')??e.textContent?.trim().slice(0,120),...raw,fontSize:raw.fontSize/cssScale,lineHeight:raw.lineHeight===null?null:raw.lineHeight/cssScale,padding:raw.padding.map(v=>v/cssScale),border:raw.border.map(v=>v/cssScale),radius:raw.radius.map(v=>v/cssScale),height:raw.height/rectScale,width:raw.width/rectScale,rowGap:raw.rowGap/cssScale,columnGap:raw.columnGap/cssScale,rawPixels:raw,logicalScale:cssScale,rectScale,diagram,rect:r.toJSON(),overflow:s.overflow,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth,scrollHeight:e.scrollHeight,clientHeight:e.clientHeight,gap:s.gap,transform:s.transform}}
 const failures=[],exceptions=[],inputs=[],buttons=[],properties=[],panels=[],rows=[]
 const fail=(kind,m,message)=>failures.push({kind,label:m.label,classes:m.classes,message,measurement:m})
 const body=read(document.body);if(body.fontSize<metrics.font-.1)fail('body',body,'Readable body follows the actual selected density in logical pixels');if(body.lineHeight!==null&&body.lineHeight<metrics.line-.1)fail('body',body,'Body line box follows the selected density')
 for(const e of query('input:not([type="checkbox"],[type="radio"],[type="range"],[type="file"],[type="color"]),select'))if(visible(e)){
  const m=read(e);inputs.push(m)
  if(gameOwned(e)){exceptions.push({kind:'authored-game-preview',reason:'This is the actual authored theme/virtual-control preview, not an editor property field.',measurement:m});continue}
  if(m.diagram){exceptions.push({kind:'graph-coordinate-value',reason:'Only the graph-transform diagram uses independent graph zoom; surrounding graph properties remain ordinary controls.',measurement:m});if(m.height<27.8)fail('graph-value',m,'Diagram editable value is at least28 graph logical pixels');if(m.fontSize<metrics.font-.1)fail('graph-value',m,'Diagram editable values retain16px text');if(m.lineHeight!==null&&m.lineHeight+m.padding[0]+m.padding[2]+m.border[0]+m.border[2]>m.height+.8)fail('graph-value',m,'Actual diagram value line, padding and borders fit');continue}
  const rename=e.matches('.entity-item>input.edit-input,.scene-main>input,.asset-grid input.rename-input,.asset-grid input[data-rename]');if(rename){exceptions.push({kind:'inline-rename',reason:'Rename stays within the40px selectable tree/list row; value text remains16px.',measurement:m});if(m.height<metrics.tree-.2||m.height>metrics.tree+.8||m.fontSize<metrics.font-.1)fail('rename',m,'Inline rename fits the actual selected tree stride and readable value font');continue}
  if(m.height<metrics.field-.2)fail('input',m,'Standard field is at least44px high');if(m.fontSize<metrics.font-.1)fail('input',m,'Property/input values are at least16px');if(m.lineHeight!==null&&m.lineHeight<metrics.line-.2)fail('input',m,'Input line box is24px');if(m.padding[0]<metrics.verticalPadding-.2||m.padding[2]<metrics.verticalPadding-.2)fail('input',m,'Input vertical padding is at least9px');if(m.padding[1]<15.8||m.padding[3]<15.8)fail('input',m,'Input horizontal padding is at least16px');if(Math.min(...m.radius)<11.8)fail('input',m,'Input corners use12px radius');if(m.lineHeight!==null&&m.lineHeight+m.padding[0]+m.padding[2]+m.border[0]+m.border[2]>m.height+.8)fail('input',m,'Line box, padding and borders must fit actual field height')
  const host=e.closest('.ui-property-control,.setting-row,.config-row,.ui-slider')??e.parentElement,hr=host.getBoundingClientRect();if(m.rect.left<hr.left-2||m.rect.right>hr.right+2)fail('input-overflow',m,'Field lies within the actual control column')
 }
 for(const e of query('button,[role="button"],summary'))if(visible(e)){
  const m=read(e);buttons.push(m);const stepper=e.closest('.numeric-steppers'),tree=e.matches('.entity-item>.name,.entity-item>.disclosure,.entity-item>.state-button,.entity-item>.row-overflow,.scene-main,.scene-item>.scene-direct-action,.folder-tree>button,.folder-tree .folder-row>button'),tab=e.matches('[role="tab"],.panel-tab')||e.closest('.ui-tabs,.workspace-list,.logic-tabs,.panel-tabs,.theme-switch'),precision=e.matches('.keyframe,.keyframe-handle,.frame-marker,.timeline-playhead')&&!!e.closest('.timeline-ruler,.keyframe-track,.animation-track')
  if(gameOwned(e)){exceptions.push({kind:'authored-game-preview',reason:'Authored game theme/virtual controls use game geometry.',measurement:m});continue}
  if(e.matches('.script-studio .editor-shell > .gutter > button')){exceptions.push({kind:'code-gutter',reason:'Only actual source line-number/breakpoint buttons follow the shared15/24 code line geometry; editor toolbar remains ordinary44/16.',measurement:m});if(m.fontSize<13.9||m.lineHeight===null||m.lineHeight<m.fontSize*1.45||m.height<m.lineHeight-.2)fail('code-gutter',m,'Readable code gutter matches its scaled source line box');continue}
  if(e.matches('.console-list > .log-entry')){exceptions.push({kind:'code-log-list',reason:'Monospace code logs use15px text,40px list rows and8px selection corners; console toolbar is not exempt.',measurement:m});if(m.fontSize<13.9||m.lineHeight===null||m.lineHeight<m.fontSize*1.45||m.height<metrics.tree-.2||Math.min(...m.radius)<7.8)fail('code-log-list',m,'Code logs retain readable type,40px list geometry and rounded selection');continue}
  if(m.diagram){exceptions.push({kind:'graph-coordinate-action',reason:'Only actual graph-transform node/pin/wire actions retain coordinate-sized hit areas; graph toolbar and property actions are not exempt.',measurement:m});continue}
  if(stepper){exceptions.push({kind:'numeric-stepper',reason:'Paired half-height actions are part of the measured numeric field.',measurement:m});if(m.height<metrics.field/2-.2)fail('numeric-stepper',m,'Stepper has half the ordinary field height');continue}
  if(tree){exceptions.push({kind:'tree-list-action',reason:'Only explicit row-local names/disclosures/state/menu actions share the measured tree/list stride.',measurement:m});if(m.height<metrics.tree-.2)fail('tree-list-action',m,'Row-local action has the actual selected tree stride');if((e.textContent??'').trim()&&m.fontSize<metrics.font-.1)fail('tree-list-action',m,'Ordinary row name remains readable');continue}
  if(precision){exceptions.push({kind:'precision-tool',reason:'Timeline coordinate tools retain data-aligned geometry; ordinary property controls are not exempt.',measurement:m});continue}
  if(m.height<metrics.field-.2)fail('button',m,'Ordinary buttons/tabs have44px vertical hit areas');if(!tab&&Math.min(...m.radius)<11.8)fail('button',m,'Ordinary button corners use12px radius');if((e.textContent??'').trim()&&m.fontSize<metrics.font-.1)fail('button',m,'Ordinary action text is at least16px')
  const iconOnly=!(e.textContent??'').trim()&&e.querySelector('svg,img');if(iconOnly&&m.width<metrics.field-.2)fail('icon-button',m,'Icon-only action has a44px horizontal hit area')
  if(m.scrollWidth>m.clientWidth+2&&m.overflow==='hidden'&&!e.title&&!e.getAttribute('aria-label'))fail('clipped-label',m,'Clipped action has no accessible complete label')
 }
 for(const e of query('.ui-property-row'))if(visible(e)){
  const label=e.querySelector(':scope>.ui-property-label'),control=e.querySelector(':scope>.ui-property-control');if(!label||!control||!visible(label)||!visible(control))continue;const m=read(e),l=read(label),c=read(control),stacked=c.rect.top>=l.rect.bottom-1,actualGap=(stacked?c.rect.top-l.rect.bottom:c.rect.left-l.rect.right)/uiScale;const item={...m,labelGeometry:l,controlGeometry:c,stacked,actualGap};properties.push(item);if(l.fontSize<(compact?12.9:14.9))fail('property-label',l,'Important field labels are at least15px');if(actualGap<(stacked?11.8:15.8))fail('property-gap',m,'Actual label-to-control gap is12px stacked or16px inline')
 }
 for(const e of query('.sidebar-container,.config-wrapper,.settings-page,.ui-dialog,.ui-menu,.command-palette,.ui-section-body,.ui-section-list,.ui-panel-header'))if(visible(e)){
  const m=read(e);panels.push(m);if(e.matches('.ui-dialog')&&Math.min(...m.radius)<23.8)fail('dialog-radius',m,'Dialog has24px rounded surface');if(e.matches('.ui-section-body')&&m.rowGap<metrics.fieldGap-.2)fail('field-gap',m,'Property body has20px field-group spacing');if(e.matches('.ui-section-list')&&m.rowGap<metrics.sectionGap-.2)fail('section-gap',m,'Property sections have28px spacing');if(e.matches('.settings-page')&&Math.min(...m.padding)<metrics.inset-.2)fail('panel-inset',m,'Settings panel has20px four-way inset')
 }
 for(const e of query('.tile-definition-fields,.tile-properties,.tile-properties section,.tilemap-workspace>aside,.tilemap-workspace .asset-selects'))if(visible(e)){
  const m=read(e);panels.push(m)
  const fields=e.matches('.tile-definition-fields,.tile-properties section,.tilemap-workspace .asset-selects')
  if(fields){if(!/grid|flex/.test(getComputedStyle(e).display)||m.rowGap<metrics.fieldGap-.2)fail('tile-field-gap',m,'Real TileMap field hosts use effective20px layout gaps')}
  if(e.matches('.tile-properties')){const blocks=Array.from(e.children).filter(child=>{const r=child.getBoundingClientRect();return r.width&&r.height});for(let i=1;i<blocks.length;i++){const previous=read(blocks[i-1]),current=read(blocks[i]),actualGap=(current.rect.top-previous.rect.bottom)/uiScale;properties.push({kind:'tile-adjacent-blocks',previous,current,actualGap});if(actualGap<metrics.sectionGap-.2)fail('tile-section-gap',current,'Actual neighboring TileMap blocks use28px separation')}}
  if(e.matches('.tile-properties,.tilemap-workspace>aside')&&Math.min(...m.padding)<metrics.inset-.2)fail('tile-panel-inset',m,'TileMap content uses20px four-way inset')
  if(fields){const children=Array.from(e.children).filter(child=>child.matches('.ui-property-row,input,select')&&visible(child));for(let i=1;i<children.length;i++){
   const previous=read(children[i-1]),current=read(children[i]),sameColumn=Math.min(previous.rect.right,current.rect.right)>Math.max(previous.rect.left,current.rect.left)+1
   if(sameColumn&&current.rect.top>=previous.rect.bottom-1){const actualGap=(current.rect.top-previous.rect.bottom)/uiScale;properties.push({kind:'tile-adjacent-fields',previous,current,actualGap});if(actualGap<metrics.fieldGap-.2)fail('tile-neighbor-gap',current,'Actual neighboring TileMap fields retain20px vertical breathing room')}
  }}
 }
 for(const e of query('.entity-item'))if(visible(e)){const m=read(e);rows.push(m);if(m.height<metrics.tree-.2)fail('tree-row',m,'Tree row has40px comfortable hit area')}
 return{format:'nova-comfortable-computed-geometry',version:2,scope:rootSelector??'document',units:'logical geometry; rawPixels and rect preserve browser measurements',conditions:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio,uiScale:num(style.getPropertyValue('--ui-scale'))||1,density:root.dataset.density,uiMotion:root.dataset.uiMotion,rootZoom:style.zoom,rootTransform:style.transform},body,inputs,buttons,properties,panels,rows,exceptions,failures,limitations:['Only visible mounted controls are measured; the all-route audit separately covers other panels.','Physical DPI and native GPU effects are not measured in the software browser.']}
}
export async function auditComfortableGeometry(a,name,{strict=true,rootSelector=null,comparison=strict,settle=false}={}){
 if(settle){const rootCode=rootSelector?'document.querySelector('+JSON.stringify(rootSelector)+')':'document';await a.until('(()=>{const root='+rootCode+';return !!root && !document.getAnimations().some(animation=>{const target=animation.effect?.target;return target instanceof Element && root.contains(target) && animation.playState==="running" && animation.effect.getTiming().iterations!==Infinity && !target.closest(".graph-transform,.timeline-ruler,.keyframe-track,.animation-track,.theme-preview,.virtual-controls")})})()')}
 const data=await a.evaluate('('+collectComfortableGeometry.toString()+')('+JSON.stringify({rootSelector})+')');a.observations.push({name:'comfortable-geometry-'+name,data});if(strict){assert.equal(data.conditions.density,'comfortable','Comfortable is the real default density');if(comparison){assert.equal(data.conditions.uiScale,1,'Comparison uses logical scale1');assert.equal(data.conditions.dpr,1)}assert.deepEqual(data.failures,[],name+' actual geometry failures: '+JSON.stringify(data.failures))}return data
}
