/** 网络与导出用户审计辅助库，驱动实际页面并保留产物证据。 */
import assert from 'node:assert/strict'
import {wait} from './browserUserAudit.mjs'
/** Same-origin second window in the audit's existing browser profile; real CDP input only. */
/** 创建并附接独立浏览器对等页面，提供有超时的协议、输入、查找和清理操作。 */ export async function networkPeerPage18(parent,url){
 const {targetId}=await parent.send('Target.createTarget',{url,newWindow:true}),{sessionId}=await parent.send('Target.attachToTarget',{targetId,flatten:false}),pending=new Map(),listeners=new Map(),exceptions=[];let next=0;
 const off=parent.on('Target.receivedMessageFromTarget',/** 只处理目标会话消息，分派命令响应或事件并清理响应计时器。 */ event=>{if(event.sessionId!==sessionId)return;const m=JSON.parse(event.message);if(m.id){const p=pending.get(m.id);if(!p)return;pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else for(const fn of listeners.get(m.method)||[])fn(m.params)});
 const client={/** 将命令封装为带唯一标识和超时的目标会话请求。 */ send(method,params={}){return new Promise(/** 登记待响应请求及计时器，并通过父会话发送命令。 */ (resolve,reject)=>{const id=++next,timer=setTimeout(/** 命令超时后移除待响应项并拒绝请求。 */ ()=>{pending.delete(id);reject(Error('Peer page timeout '+method))},30000);pending.set(id,{resolve,reject,timer});parent.send('Target.sendMessageToTarget',{sessionId,message:JSON.stringify({id,method,params})}).catch(reject)})},/** 注册协议事件监听，并返回解除该监听的入口。 */ on(method,fn){const set=listeners.get(method)||new Set();set.add(fn);listeners.set(method,set);return/* 调用 set.delete(fn) 并返回调用结果。 */ ()=>set.delete(fn)}};
 const evaluate=/** 在对等页面等待表达式完成并返回值，页面异常时抛错。 */ async expression=>{const r=await client.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
 const until=/** 在截止时间前轮询页面条件，超时报告具体表达式。 */ async(expression,timeout=20000)=>{const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(expression))return;await wait(75)}throw Error('Peer page timed out '+expression)};
 const press=/** 按键名和修饰键发送按下与释放，支持持续按键及回车文本。 */ async(key,modifiers=0,duration=0)=>{const e={key,code:key.length===1?'Key'+key.toUpperCase():key,windowsVirtualKeyCode:({Tab:9,Enter:13,Escape:27,Home:36,End:35,ArrowDown:40,ArrowUp:38,ArrowLeft:37,ArrowRight:39})[key]||(key.length===1?key.toUpperCase().charCodeAt(0):undefined),modifiers};await client.send('Input.dispatchKeyEvent',{type:'keyDown',...e,...(key==='Enter'?{text:'\r',unmodifiedText:'\r'}:{})});if(duration)await wait(duration);await client.send('Input.dispatchKeyEvent',{type:'keyUp',...e});await wait(90)};
 const click=/** 定位可用元素中心并滚动可见，通过真实鼠标按下释放执行点击。 */ async(selector,index=0)=>{const point=await evaluate(`(()=>{const e=document.querySelectorAll(${JSON.stringify(selector)})[${index}];if(!e||e.disabled)throw Error('Unavailable '+${JSON.stringify(selector)});e.scrollIntoView({block:'center',inline:'nearest'});const r=e.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}})()`);for(const type of['mousePressed','mouseReleased'])await client.send('Input.dispatchMouseEvent',{type,...point,button:'left',clickCount:1});await wait(150)};
 const clickText=/** 查找可见且文本匹配的元素，再通过点击入口操作。 */ async(selector,text,exact=false)=>{const index=await evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})].findIndex(e=>e.getBoundingClientRect().width&&${exact?'e.textContent.trim()===':'e.textContent.includes('}${JSON.stringify(text)}${exact?'':')'})`);assert.ok(index>=0,'Missing '+text);await click(selector,index)};
 const select=/** 查找目标选项后使用键盘从首项移动并确认选择。 */ async(selector,value,index=0)=>{const target=await evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})[${index}].options].findIndex(o=>o.value===${JSON.stringify(value)})`);assert.ok(target>=0);await click(selector,index);await press('Escape');await press('Home');for(let n=0;n<target;n++)await press('ArrowDown');await press('Enter');await press('Tab')};
 client.on('Runtime.exceptionThrown',/* 调用 exceptions.push(event.exceptionDetails?.exception?.description||event.exceptionDetails?.text) 并返回调用结果。 */ event=>exceptions.push(event.exceptionDetails?.exception?.description||event.exceptionDetails?.text));await client.send('Runtime.enable');await client.send('Page.enable');await client.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 return{client,evaluate,until,press,click,clickText,select,exceptions,/** 解除会话监听并拒绝所有待响应请求，然后关闭目标页面。 */ async close(){off();for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('Peer closed'))}pending.clear();await parent.send('Target.closeTarget',{targetId})}};
}
