import assert from 'node:assert/strict'
import {wait} from './browserUserAudit.mjs'
/** Same-origin second window in the audit's existing browser profile; real CDP input only. */
export async function networkPeerPage18(parent,url){
 const {targetId}=await parent.send('Target.createTarget',{url,newWindow:true}),{sessionId}=await parent.send('Target.attachToTarget',{targetId,flatten:false}),pending=new Map(),listeners=new Map(),exceptions=[];let next=0;
 const off=parent.on('Target.receivedMessageFromTarget',event=>{if(event.sessionId!==sessionId)return;const m=JSON.parse(event.message);if(m.id){const p=pending.get(m.id);if(!p)return;pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}else for(const fn of listeners.get(m.method)||[])fn(m.params)});
 const client={send(method,params={}){return new Promise((resolve,reject)=>{const id=++next,timer=setTimeout(()=>{pending.delete(id);reject(Error('Peer page timeout '+method))},30000);pending.set(id,{resolve,reject,timer});parent.send('Target.sendMessageToTarget',{sessionId,message:JSON.stringify({id,method,params})}).catch(reject)})},on(method,fn){const set=listeners.get(method)||new Set();set.add(fn);listeners.set(method,set);return()=>set.delete(fn)}};
 const evaluate=async expression=>{const r=await client.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value};
 const until=async(expression,timeout=20000)=>{const end=Date.now()+timeout;while(Date.now()<end){if(await evaluate(expression))return;await wait(75)}throw Error('Peer page timed out '+expression)};
 const press=async(key,modifiers=0,duration=0)=>{const e={key,code:key.length===1?'Key'+key.toUpperCase():key,windowsVirtualKeyCode:({Tab:9,Enter:13,Escape:27,Home:36,End:35,ArrowDown:40,ArrowUp:38,ArrowLeft:37,ArrowRight:39})[key]||(key.length===1?key.toUpperCase().charCodeAt(0):undefined),modifiers};await client.send('Input.dispatchKeyEvent',{type:'keyDown',...e,...(key==='Enter'?{text:'\r',unmodifiedText:'\r'}:{})});if(duration)await wait(duration);await client.send('Input.dispatchKeyEvent',{type:'keyUp',...e});await wait(90)};
 const click=async(selector,index=0)=>{const point=await evaluate(`(()=>{const e=document.querySelectorAll(${JSON.stringify(selector)})[${index}];if(!e||e.disabled)throw Error('Unavailable '+${JSON.stringify(selector)});e.scrollIntoView({block:'center',inline:'nearest'});const r=e.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}})()`);for(const type of['mousePressed','mouseReleased'])await client.send('Input.dispatchMouseEvent',{type,...point,button:'left',clickCount:1});await wait(150)};
 const clickText=async(selector,text,exact=false)=>{const index=await evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})].findIndex(e=>e.getBoundingClientRect().width&&${exact?'e.textContent.trim()===':'e.textContent.includes('}${JSON.stringify(text)}${exact?'':')'})`);assert.ok(index>=0,'Missing '+text);await click(selector,index)};
 const select=async(selector,value,index=0)=>{const target=await evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})[${index}].options].findIndex(o=>o.value===${JSON.stringify(value)})`);assert.ok(target>=0);await click(selector,index);await press('Escape');await press('Home');for(let n=0;n<target;n++)await press('ArrowDown');await press('Enter');await press('Tab')};
 client.on('Runtime.exceptionThrown',event=>exceptions.push(event.exceptionDetails?.exception?.description||event.exceptionDetails?.text));await client.send('Runtime.enable');await client.send('Page.enable');await client.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 return{client,evaluate,until,press,click,clickText,select,exceptions,async close(){off();for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('Peer closed'))}pending.clear();await parent.send('Target.closeTarget',{targetId})}};
}
