/** 操作审计证据辅助库，保留证据来源与适用范围。 */
import {readFile,readdir} from 'node:fs/promises'
import {createHash} from 'node:crypto'
import {resolve,relative,isAbsolute} from 'node:path'
/** 核验已通过 Node 套件断言、正入口计数及源码产物散列后关联操作执行证据。 */ export async function linkNodeOperationCoverage22(operations,{root=process.cwd()}={}){
 const hashes=new Map();let links=0;/** 限制追踪路径在仓库内，并缓存文件的 SHA-256 散列。 */ async function hash(path){const full=resolve(root,path),part=relative(root,full);if(!part||part.startsWith('..')||isAbsolute(part))throw Error('Node trace outside repository');if(!hashes.has(full))hashes.set(full,createHash('sha256').update(await readFile(full)).digest('hex'));return hashes.get(full)}
 for(const directory of ['release-audits','reports'])for(const file of await readdir(resolve(root,directory))){if(!/^v26\.22-.*\.json$/.test(file))continue;const path=directory+'/'+file,report=JSON.parse(await readFile(resolve(root,path),'utf8'));if(report.status!=='passed'||!report.nodeOperationCoverageCase)continue;if(report.nodeOperationCoverageAssertion?.name!==report.nodeOperationCoverageCase||report.nodeOperationCoverageAssertion?.status!=='passed'||!report.checks.length||report.checks.some(/* 比较 check.status 与 'passed'，返回严格不等的判断结果。 */ check=>check.status!=='passed'))throw Error('Unasserted node trace');
  for(const entry of report.nodeOperationCoverage||[]){if(entry.mappingVersion!==2)continue;if(!Number.isFinite(entry.entryCount)||entry.entryCount<=0)throw Error('Nonpositive node trace');const matches=operations.filter(/* 先计算 row.id===entry.id&&row.source===entry.source&&row.line===entry.line；仅当其为真值时求右侧 row.kind===entry.kind，返回短路求值结果。 */ row=>row.id===entry.id&&row.source===entry.source&&row.line===entry.line&&row.kind===entry.kind);if(matches.length!==1||await hash(entry.source)!==entry.sourceSha256)continue;if(await hash(entry.generatedFile)!==entry.generatedSha256||await hash(entry.generatedFile+'.map')!==entry.mapSha256)throw Error('Node trace artifact changed: '+path);matches[0].cases.push({report:path,case:report.nodeOperationCoverageCase,link:'Observed V8 function entry during the complete asserted programmer suite, including fixture setup. Not isolated operation correctness or exhaustive input-domain coverage.',mappingVersion:entry.mappingVersion,sourceSha256:entry.sourceSha256,generatedSha256:entry.generatedSha256,mapSha256:entry.mapSha256,entryCount:entry.entryCount});links++}
 }return links
}
