/** 操作审计证据辅助库，保留证据来源与适用范围。 */
import {constructorFactoryReference22} from './constructorFactoryEvidence22.mjs'
import ts from 'typescript'
import {readFile} from 'node:fs/promises'
/** Conservative direct-call links only. Indirect helper effects and unresolved aliases remain unclaimed. */
/** 读取保留套件的通过报告，静态解析已执行命名用例中的直接源码调用并关联操作，不推断间接行为覆盖。 */ export async function linkRetainedOperations22(tested){
 for(const [version,name] of [['26.16','animation-audio'],['26.16','timeline-actions'],['26.16','interface'],['26.17','queries'],['26.17','navigation'],['26.17','bindings'],['26.16','animation-authoring'],['26.16','media-roundtrip'],['26.17','world-streaming'],['26.17','world-roundtrip'],['26.18','networking'],['26.22','foundations'],['26.22','asset-library-operations'],['26.14','runtime-stage'],['26.21','save-recovery'],['26.21','delivery']]){
  const suite='scripts/verify-v'+version+'-'+name+'.mjs',report=name==='runtime-stage'?'release-audits/v26.14-runtime-native.json':name==='foundations'?'release-audits/v26.22-foundations-regressions.json':name==='asset-library-operations'?'release-audits/v26.22-asset-library-operations.json':'reports/v26.22-'+name+'.json',evidence=JSON.parse(await readFile(report,'utf8'));if(evidence.status!=='passed')throw Error('Unpassed runtime evidence '+report)
  const source=ts.createSourceFile(suite,await readFile(suite,'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),moduleMap=new Map(),globals=new Map()
  /** 从套件模块加载入口收集别名与源码路径映射。 */ function findMaps(node){let map;
   if(name==='runtime-stage'&&ts.isPropertyAssignment(node)&&node.name.getText(source)==='input'&&ts.isObjectLiteralExpression(node.initializer))for(const prop of node.initializer.properties){if(!ts.isPropertyAssignment(prop))continue;let value=prop.initializer;if(ts.isIdentifier(value)&&value.text==='runtimeFile'){const declaration=source.statements.flatMap(/* 根据 ts.isVariableStatement(n) 的真假，分别返回 [...n.declarationList.declarations] 或 []。 */ n=>ts.isVariableStatement(n)?[...n.declarationList.declarations]:[]).find(/* 比较 n.name.getText(source) 与 'runtimeFile'，返回严格相等的判断结果。 */ n=>n.name.getText(source)==='runtimeFile');value=declaration?.initializer}if(value&&ts.isCallExpression(value)&&value.expression.getText(source)==='join'&&value.arguments[0]?.getText(source)==='root'&&ts.isStringLiteral(value.arguments[1])&&value.arguments[1].text.startsWith('src/'))moduleMap.set(prop.name.getText(source),{source:value.arguments[1].text,path:''})}
  if(ts.isCallExpression(node)&&node.expression.getText(source)==='openMediaAuditModules')map=node.arguments[1];if(ts.isVariableDeclaration(node)&&node.name.getText(source)==='entries')map=node.initializer;if(map&&ts.isObjectLiteralExpression(map))for(const prop of map.properties)if(ts.isPropertyAssignment(prop)&&ts.isStringLiteral(prop.initializer))moduleMap.set(prop.name.getText(source),{source:'src/'+prop.initializer.text+'.ts',path:''});ts.forEachChild(node,findMaps)}findMaps(source)
  const namespace={modules:moduleMap};globals.set('modules',namespace);globals.set('opened',{members:new Map([['modules',namespace]])})
  /** 在当前作用域中保守解析模块、成员、构造器和工厂引用。 */ function ref(node,scope){if(!node)return null;
   if(ts.isArrowFunction(node)||ts.isFunctionExpression(node)){const instance=constructorFactoryReference22(node,scope,ref);return instance?{instance}:null}
   if(ts.isCallExpression(node)&&ts.isIdentifier(node.expression)){const factory=scope.get(node.expression.text);if(factory?.instance)return factory.instance}

   if(name==='delivery'&&ts.isCallExpression(node)&&ts.isPropertyAccessExpression(node.expression)&&node.expression.expression.getText(source)==='vite'&&node.expression.name.text==='ssrLoadModule'&&ts.isStringLiteral(node.arguments[0])&&/^\/src\/.*\.ts$/.test(node.arguments[0].text))return{source:node.arguments[0].text.slice(1),path:''};
   if(name==='runtime-stage'&&ts.isCallExpression(node)){
    if(node.expression.getText(source)==='load'&&ts.isStringLiteral(node.arguments[0]))return moduleMap.get(node.arguments[0].text)||null;
    const arg=node.arguments[0];if(node.expression.getText(source)==='Promise.all'&&arg&&ts.isCallExpression(arg)&&ts.isPropertyAccessExpression(arg.expression)&&arg.expression.name.text==='map'&&ts.isArrayLiteralExpression(arg.expression.expression)&&arg.arguments[0]?.getText(source)==='load'&&arg.expression.expression.elements.every(ts.isStringLiteral))return{items:arg.expression.expression.elements.map(/* 先计算 moduleMap.get(item.text)；仅当其为假值时求右侧 null，返回短路求值结果。 */ item=>moduleMap.get(item.text)||null)};
   }
  if(name==='foundations'&&ts.isCallExpression(node)&&ts.isIdentifier(node.expression)&&node.expression.text==='moduleAt'&&ts.isStringLiteral(node.arguments[0])&&/^src\/.*\.ts$/.test(node.arguments[0].text))return{source:node.arguments[0].text,path:''};if(ts.isCallExpression(node)&&node.expression.getText(source)==='openMediaAuditModules')return{members:new Map([['modules',namespace]])};if(ts.isIdentifier(node))return scope.get(node.text)||null;if(ts.isParenthesizedExpression(node)||ts.isAwaitExpression(node))return ref(node.expression,scope);if(ts.isNewExpression(node))return ref(node.expression,scope);if(ts.isPropertyAccessExpression(node)){const base=ref(node.expression,scope);if(base?.modules)return base.modules.get(node.name.text)||null;if(base?.members)return base.members.get(node.name.text)||null;if(base?.source)return{source:base.source,path:[base.path,node.name.text].filter(Boolean).join('.')}}return null}
  /** 按标识符、数组或对象解构递归绑定引用，未知引用解除旧绑定。 */ function bind(pattern,value,scope){if(ts.isIdentifier(pattern)){if(value)scope.set(pattern.text,value);else scope.delete(pattern.text)}else if(ts.isArrayBindingPattern(pattern)){pattern.elements.forEach(/** 将数组解构中的绑定项关联到对应位置引用。 */ (part,index)=>{if(ts.isBindingElement(part))bind(part.name,value?.items?.[index]||null,scope)})}else if(ts.isObjectBindingPattern(pattern))for(const part of pattern.elements){const key=(part.propertyName||part.name).getText(source),child=value?.modules?.get(key)||value?.members?.get(key)||(value?.source?{source:value.source,path:[value.path,key].filter(Boolean).join('.')}:null);bind(part.name,child,scope)}}
  /** 仅扫描顶层赋值和声明初始化全局引用，不进入函数体。 */ function top(node){if(ts.isFunctionLike(node))return;if(ts.isBinaryExpression(node)&&node.operatorToken.kind===ts.SyntaxKind.EqualsToken&&ts.isIdentifier(node.left))bind(node.left,ref(node.right,globals),globals);if(ts.isVariableDeclaration(node)){if(node.name.getText(source)==='modules'&&moduleMap.size)globals.set('modules',namespace);else bind(node.name,ref(node.initializer,globals),globals)}ts.forEachChild(node,top)}
  // Seed only top-level declarations; the dynamic bundle's modules binding is known from entries.
  for(const statement of source.statements){top(statement);if(moduleMap.size)globals.set('modules',namespace)}
  /** 为可解析操作追加去重的命名用例证据，区分构造器入口。 */ function add(reference,caseName,constructor=false){if(!reference?.source||!reference.path)return;const id=reference.source+'#'+reference.path+(constructor?'.constructor':''),list=tested.get(id)||[];if(!list.some(/* 先计算 row.suite===suite；仅当其为真值时求右侧 row.case===caseName，返回短路求值结果。 */ row=>row.suite===suite&&row.case===caseName))list.push({suite,report,case:caseName,link:'Direct resolved source operation in executed case; indirect effects and input-domain completeness are not implied.'});tested.set(id,list)}
  /** 按词法作用域跟踪局部引用，并记录直接调用和构造入口。 */ function inspect(node,scope,caseName){if(ts.isBlock(node)){const local=new Map(scope);for(const child of node.statements)inspect(child,local,caseName);return}if(ts.isVariableDeclaration(node))bind(node.name,ref(node.initializer,scope),scope);if(ts.isCallExpression(node)){const reference=ref(node.expression,scope);if(reference?.instance)add(reference.instance,caseName,true);else add(reference,caseName);}if(ts.isNewExpression(node))add(ref(node.expression,scope),caseName,true);if(ts.isFunctionLike(node)){const local=new Map(scope);for(const p of node.parameters)bind(p.name,null,local);if(node.body)inspect(node.body,local,caseName);return}ts.forEachChild(node,/* 调用 inspect(child,scope,caseName) 并返回调用结果。 */ child=>inspect(child,scope,caseName))}
  /** 查找命名测试调用，确认报告已通过后分析其测试函数。 */ function cases(node){if(ts.isCallExpression(node)&&ts.isIdentifier(node.expression)&&node.expression.text===(name==='foundations'?'test':'check')&&ts.isStringLiteral(node.arguments[0])){const caseName=node.arguments[0].text;if(!evidence.checks.some(/* 先计算 row.name===caseName；仅当其为真值时求右侧 row.status==='passed'，返回短路求值结果。 */ row=>row.name===caseName&&row.status==='passed'))throw Error('Unexecuted named runtime case '+caseName);inspect(node.arguments[1],new Map(globals),caseName);return}ts.forEachChild(node,cases)}cases(source)
 }
}
