import assert from 'node:assert/strict'
import {mkdir,readFile,writeFile} from 'node:fs/promises'
import {join} from 'node:path'
import {wait} from './browserUserAudit.mjs'
/** Real mouse/keyboard/chooser actions; evaluation is limited to DOM observations, focus and scrolling. */
export function worldUserControls17(a){
 const {evaluate,until,click,clickText,press,client}=a;let downloadIndex=0;
 const activate=async(selector,index=0)=>{await evaluate(`(()=>{const e=document.querySelectorAll(${JSON.stringify(selector)})[${index}];if(!e||e.disabled)throw Error('Unavailable action '+${JSON.stringify(selector)});e.scrollIntoView({block:'center'});e.focus()})()`);await press('Enter');await wait(130)};
 const field=async(selector,value,index=0)=>{await evaluate(`(()=>{const e=document.querySelectorAll(${JSON.stringify(selector)})[${index}];if(!e)throw Error('Missing '+${JSON.stringify(selector)});e.scrollIntoView({block:'center'});e.focus();e.select()})()`);await client.send('Input.insertText',{text:String(value)});await press('Tab');await wait(160)};
 const labelInput=async(scope,label,offset=0)=>{const result=await evaluate(`(()=>{const root=document.querySelector(${JSON.stringify(scope)}),label=[...root.querySelectorAll('label,.property-row')].find(e=>(e.querySelector(':scope>span')?.textContent??e.textContent).trim().startsWith(${JSON.stringify(label)})&&e.querySelector('input[type=number]'));const input=label?.querySelectorAll('input[type=number]')[${offset}];return [...document.querySelectorAll('input[type=number]')].indexOf(input)})()`);assert.ok(result>=0,'Missing number label '+label+' in '+scope);return result};
 const labeled=async(scope,label,value,offset=0)=>field('input[type=number]',value,await labelInput(scope,label,offset));
 const readLabel=async(scope,label,offset=0)=>Number(await evaluate(`document.querySelectorAll('input[type=number]')[${await labelInput(scope,label,offset)}].value`));
 const open=async(file)=>{let navigated=false;const offNavigation=client.on('Page.frameNavigated',event=>{if(!event.frame.parentId)navigated=true});try{await client.send('Page.reload');const navigationDeadline=Date.now()+30000;while(!navigated&&Date.now()<navigationDeadline)await wait(50);assert.ok(navigated,'Project reload must reach a fresh main frame')}finally{offNavigation()};await until("document.readyState==='complete'&&[...document.querySelectorAll('.quick-actions button')].some(e=>e.textContent.includes('Open Project')&&e.getBoundingClientRect().width&&e.getBoundingClientRect().height)",30000);let chooser;const off=client.on('Page.fileChooserOpened',v=>chooser=v);await client.send('Page.setInterceptFileChooserDialog',{enabled:true});await clickText('.quick-actions button','Open Project');const deadline=Date.now()+10000;while(!chooser&&Date.now()<deadline)await wait(50);assert.ok(chooser);await client.send('DOM.setFileInputFiles',{files:[file],backendNodeId:chooser.backendNodeId});off();await until("!!document.querySelector('.upgrade-dialog,.editor-root')",30000);if(await evaluate("!!document.querySelector('.upgrade-dialog')"))await click('.upgrade-dialog footer button.primary');await until("!!document.querySelector('.editor-root')&&!document.querySelector('.project-manager')",30000);await wait(650);if(await evaluate("!!document.querySelector('.onboarding-scrim')")){await evaluate("document.querySelector('.onboarding-scrim').focus()");await press('Escape');await until("!document.querySelector('.onboarding-scrim')")};await wait(350)};
 const workspace=async(name)=>{const index=['Design','Script','Animation','UI','Debug','Manage'].indexOf(name);assert.ok(index>=0);await click('.workspace-list button',index);await wait(350)};
 const entity=async(name)=>{await workspace('Design');const index=await evaluate(`[...document.querySelectorAll('.entity-list .entity-item .name')].findIndex(e=>[...e.childNodes].filter(n=>n.nodeName!=='SMALL').map(n=>n.textContent).join('').trim()===${JSON.stringify(name)})`);assert.ok(index>=0,'Entity '+name);await click('.entity-list .entity-item .name',index);await wait(160)};
 const world=async(tab)=>{await clickText('.bottom-tabs button,.panel-tabs button','World Studio');await until("!!document.querySelector('.world-tools')");if(tab)await clickText('.world-tools>header nav button',tab,true);await wait(150)};
 const expandInspector=async()=>{for(let i=0;i<40;i++){const at=await evaluate("[...document.querySelectorAll('.config-panel details>summary')].findIndex(e=>!e.parentElement.open)");if(at<0)break;await activate('.config-panel details>summary',at)}};
 const save=async(slug)=>{const folder=join(a.profile,'download-'+downloadIndex++);await mkdir(folder,{recursive:true});await client.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:folder,eventsEnabled:true});await click('.menu-item>button',0);await clickText('.menu-item .dropdown button','Save Project');let bytes;for(let i=0;!bytes&&i<250;i++){try{bytes=await readFile(join(folder,'project.nova'));JSON.parse(bytes.toString())}catch{bytes=null;await wait(80)}}assert.ok(bytes,'Saved project download');const file=join(a.evidence,'v26.17-'+slug+'.nova');await writeFile(file,bytes);a.observations.push({name:'actual-project-download',file,bytes:bytes.length});return{file,document:JSON.parse(bytes.toString()),folder}};
 const position=async()=>JSON.parse(await evaluate("JSON.stringify([...document.querySelectorAll('[data-property-path=\"Transform.position\"] input')].map(e=>Number(e.value)))"));
 return{activate,field,labeled,readLabel,open,workspace,entity,world,expandInspector,save,position};
}
