import assert from 'node:assert/strict'
import {mkdir,readFile,writeFile} from 'node:fs/promises'
import {join,resolve,relative,isAbsolute,extname} from 'node:path'
import {spawnSync,fork} from 'node:child_process'
import {fileURLToPath} from 'node:url'
import {createHash} from 'node:crypto'
import {gunzipSync} from 'node:zlib'
import {wait} from './browserUserAudit.mjs'
const hash=v=>createHash('sha256').update(v).digest('hex')
/** Export with real UI input; independently inspect downloaded bytes and run only those files. */
export async function exportWorldUser17(a,u,slug,saved){
 const name='PhysicsAudit'+slug,folder=join(a.profile,'export-'+slug);await mkdir(folder,{recursive:true});await a.client.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:folder,eventsEnabled:true});await a.click('.menu-item>button',2);await a.clickText('.menu-item .dropdown button','Build');await a.until("!!document.querySelector('.build-panel')");await a.select('.field-grid select','web',1);await u.field('.field-grid input[maxlength="80"]',name);await a.until("!!document.querySelector('.build-actions>button.primary:not([disabled])')");await u.activate('.build-actions>button.primary');let bytes;for(let n=0;!bytes&&n<500;n++){try{bytes=await readFile(join(folder,name+'-web.zip'))}catch{await wait(100)}}assert.ok(bytes,'Actual Web export download; visible build state: '+await a.evaluate("document.querySelector('.build-actions')?.innerText"));const artifact=join(a.evidence,'v26.17-'+slug+'-authored-web.zip');await writeFile(artifact,bytes);await a.capture(slug+'-web-download');
 const output=join(a.profile,'player-'+slug),script=join(a.profile,'extract-'+slug+'.ps1');await writeFile(script,'param([string]$Archive,[string]$Output)\nAdd-Type -AssemblyName System.IO.Compression.FileSystem\n$zip=[IO.Compression.ZipFile]::OpenRead($Archive)\ntry{foreach($entry in $zip.Entries){if($entry.FullName -match "(^/|(^|/)\\.\\.(/|$)|:|\\\\)"){throw "Unsafe archive path"}}}finally{$zip.Dispose()}\n[IO.Compression.ZipFile]::ExtractToDirectory($Archive,$Output)\n');const result=spawnSync('powershell',['-NoProfile','-File',script,'-Archive',artifact,'-Output',output],{encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(result.status,0,result.stderr);
 const manifest=JSON.parse(await readFile(join(output,'nova-build-report.json'),'utf8'));assert.equal(manifest.engineVersion,a.expectedRelease+'.0');for(const file of manifest.files){const content=await readFile(join(output,file.path));assert.equal(content.length,file.bytes);assert.equal(hash(content),file.sha256)}
 const pak=await readFile(join(output,'game.nova-pak'));assert.equal(pak.subarray(0,8).toString(),'NOVAPAK\0');assert.equal(pak.readUInt32LE(8),1);const start=16+pak.readUInt32LE(12),index=JSON.parse(pak.subarray(16,start));let project;for(const entry of index.entries){assert.ok(entry.offset>=0&&entry.length>=0&&start+entry.offset+entry.length<=pak.length);const stored=pak.subarray(start+entry.offset,start+entry.offset+entry.length),content=entry.codec==='gzip'?gunzipSync(stored):stored;assert.equal(content.length,entry.originalLength);assert.equal(hash(content),entry.sha256);if(entry.path==='project.nova')project=JSON.parse(content)}assert.ok(project);
 const canonical=scenes=>scenes.map(s=>({uuid:s.uuid,entities:s.entities.map(e=>({...e,components:[...e.components].sort((a,b)=>a.uuid.localeCompare(b.uuid))})),connections:s.connections}));assert.deepEqual(canonical(project.scenes),canonical(saved.document.scenes),'Export retains every authored entity/component/connection value');
 console.log('EXPORT '+slug+' bytes and authored scene comparison passed');
 a.observations.push({name:'exact-export-download',slug,artifact,bytes:bytes.length,sha256:hash(bytes),files:manifest.files.length,projectComparison:'All scene entities/components/connections equal the actual saved authoring project.'});
}
export async function runWorldPlayer17(a,slug,saved){
 const artifact=join(a.evidence,'v26.17-'+slug+'-authored-web.zip'),bytes=await readFile(artifact);
 const output=join(a.profile,'player-'+slug),script=join(a.profile,'extract-'+slug+'.ps1');await writeFile(script,'param([string]$Archive,[string]$Output)\nAdd-Type -AssemblyName System.IO.Compression.FileSystem\n$zip=[IO.Compression.ZipFile]::OpenRead($Archive)\ntry{foreach($entry in $zip.Entries){if($entry.FullName -match "(^/|(^|/)\\.\\.(/|$)|:|\\\\)"){throw "Unsafe archive path"}}}finally{$zip.Dispose()}\n[IO.Compression.ZipFile]::ExtractToDirectory($Archive,$Output)\n');const result=spawnSync('powershell',['-NoProfile','-File',script,'-Archive',artifact,'-Output',output],{encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(result.status,0,result.stderr);
 const manifest=JSON.parse(await readFile(join(output,'nova-build-report.json'),'utf8'));assert.equal(manifest.engineVersion,a.expectedRelease+'.0');for(const file of manifest.files){const content=await readFile(join(output,file.path));assert.equal(content.length,file.bytes);assert.equal(hash(content),file.sha256)}
 const pak=await readFile(join(output,'game.nova-pak'));assert.equal(pak.subarray(0,8).toString(),'NOVAPAK\0');assert.equal(pak.readUInt32LE(8),1);const start=16+pak.readUInt32LE(12),index=JSON.parse(pak.subarray(16,start));let project;for(const entry of index.entries){assert.ok(entry.offset>=0&&entry.length>=0&&start+entry.offset+entry.length<=pak.length);const stored=pak.subarray(start+entry.offset,start+entry.offset+entry.length),content=entry.codec==='gzip'?gunzipSync(stored):stored;assert.equal(content.length,entry.originalLength);assert.equal(hash(content),entry.sha256);if(entry.path==='project.nova')project=JSON.parse(content)}assert.ok(project);
 const canonical=scenes=>scenes.map(s=>({uuid:s.uuid,entities:s.entities.map(e=>({...e,components:[...e.components].sort((a,b)=>a.uuid.localeCompare(b.uuid))})),connections:s.connections}));assert.deepEqual(canonical(project.scenes),canonical(saved.document.scenes),'Export retains every authored entity/component/connection value');
 console.log('EXPORT '+slug+' bytes and authored scene comparison passed');
 const label=project.scenes.flatMap(s=>s.entities).find(e=>e.name==='Physics Readout');assert.ok(label);const selector='[data-ui-uuid="'+label.uuid+'"]',read=()=>a.evaluate(`document.querySelector(${JSON.stringify(selector)})?.getAttribute('aria-label')`);
 const server=fork(fileURLToPath(new URL('./worldExportServer17.mjs',import.meta.url)),[output],{stdio:['ignore','ignore','ignore','ipc'],windowsHide:true});const port=await new Promise((done,reject)=>{const timer=setTimeout(()=>reject(Error('Export HTTP server startup timeout')),10000);server.once('message',v=>{clearTimeout(timer);done(v.port)});server.once('error',reject)});
 try{await a.client.send('Page.navigate',{url:'http://127.0.0.1:'+port+'/'});await wait(1500);await a.until("!!document.querySelector('.player-root .render-canvas')",30000);await a.until(`document.querySelector(${JSON.stringify(selector)})?.getAttribute('aria-label')?.startsWith('X ')`,15000);console.log('EXPORT '+slug+' player and readout ready');await wait(700);const before=await read();await a.click('.overlay-canvas');if(slug!=='puzzle'){const startX=Number(before.match(/-?\d+(?:\.\d+)?/)[0]),key={key:'d',code:'KeyD',windowsVirtualKeyCode:68};await a.client.send('Input.dispatchKeyEvent',{type:'keyDown',...key});try{await a.until(`(()=>{const value=document.querySelector(${JSON.stringify(selector)})?.getAttribute('aria-label');return Number(value?.match(/-?\\d+(?:\\.\\d+)?/)?.[0])>${startX+.1}})()`,8000)}finally{await a.client.send('Input.dispatchKeyEvent',{type:'keyUp',...key})}}else await wait(650);await wait(1200);const after=await read(),numbers=value=>value.match(/-?\d+(?:\.\d+)?/g)?.map(Number);console.log('EXPORT '+slug+' readout '+before+' -> '+after);assert.equal(numbers(after)?.length,2);assert.ok(numbers(after).every(Number.isFinite));if(slug!=='puzzle')assert.ok(numbers(after)[0]>numbers(before)[0]+.1,'Actual exported D input moves the character right');assert.equal(await a.evaluate("!!document.querySelector('.player-status.error,.fault-overlay')"),false);await a.capture(slug+'-downloaded-player');a.observations.push({name:'exact-exported-physics-player',slug,artifact,bytes:bytes.length,sha256:hash(bytes),engineVersion:manifest.engineVersion,files:manifest.files.length,before,after,projectComparison:'All authored scene entities, components and connections are equal; all package entries and reported player files pass independent SHA256 checks.'})}finally{server.disconnect();await new Promise(done=>server.once('exit',done))}
}
