/** 编辑器用户操作辅助：使用真实键盘、鼠标和文件选择器；页面求值用于观察、焦点及滚动。 */
import assert from 'node:assert/strict'
import {mkdir,readFile,writeFile} from 'node:fs/promises'
import {join} from 'node:path'
import {wait} from './browserUserAudit.mjs'
/** Real mouse/keyboard/chooser actions; evaluation is limited to DOM observations, focus and scrolling. */
/** 封装项目打开、面板导航、字段编辑和实际下载操作，供用户流程检查复用。 */ export function worldUserControls17(a){
 const {evaluate,until,click,clickText,press,client}=a;let downloadIndex=0;
 const activate=/** 滚动并聚焦可用控件，通过 Enter 触发操作后等待界面更新。 */ async(selector,index=0)=>{await evaluate(`(()=>{const e=document.querySelectorAll(${JSON.stringify(selector)})[${index}];if(!e||e.disabled)throw Error('Unavailable action '+${JSON.stringify(selector)});e.scrollIntoView({block:'center'});e.focus()})()`);await press('Enter');await wait(130)};
 const field=/** 聚焦并选中输入框，以实际输入事件填值，再用 Tab 提交。 */ async(selector,value,index=0)=>{await evaluate(`(()=>{const e=document.querySelectorAll(${JSON.stringify(selector)})[${index}];if(!e)throw Error('Missing '+${JSON.stringify(selector)});e.scrollIntoView({block:'center'});e.focus();e.select()})()`);await client.send('Input.insertText',{text:String(value)});await press('Tab');await wait(160)};
 const labelInput=/** 在指定容器中按可读标签定位数值输入，找不到时报告检查失败。 */ async(scope,label,offset=0)=>{const result=await evaluate(`(()=>{const root=document.querySelector(${JSON.stringify(scope)}),label=[...root.querySelectorAll('label,.property-row')].find(e=>(e.querySelector(':scope>span')?.textContent??e.textContent).trim().startsWith(${JSON.stringify(label)})&&e.querySelector('input[type=number],input[data-numeric-expression]'));const input=label?.querySelectorAll('input[type=number],input[data-numeric-expression]')[${offset}];return [...document.querySelectorAll('input[type=number],input[data-numeric-expression]')].indexOf(input)})()`);assert.ok(result>=0,'Missing number label '+label+' in '+scope);return result};
 const labeled=/* 调用 field('input[type=number],input[data-numeric-expression]',value,await labelInput(scope,label,offset)) 并返回调用结果。 */ async(scope,label,value,offset=0)=>field('input[type=number],input[data-numeric-expression]',value,await labelInput(scope,label,offset));
 const readLabel=/** 按标签找到数值输入并读取其当前数值。 */ async(scope,label,offset=0)=>Number(await evaluate(`document.querySelectorAll('input[type=number],input[data-numeric-expression]')[${await labelInput(scope,label,offset)}].value`));
 const open=/** 重新加载到新主页面，通过真实文件选择器打开项目，等待升级及引导界面处理完毕。 */ async(file)=>{let navigated=false;const offNavigation=client.on('Page.frameNavigated',/** 只在主框架完成导航时记录重新载入成功。 */ event=>{if(!event.frame.parentId)navigated=true});try{await client.send('Page.reload');const navigationDeadline=Date.now()+30000;while(!navigated&&Date.now()<navigationDeadline)await wait(50);assert.ok(navigated,'Project reload must reach a fresh main frame')}finally{offNavigation()};await until("document.readyState==='complete'&&[...document.querySelectorAll('.quick-actions button')].some(e=>e.textContent.includes('Open Project')&&e.getBoundingClientRect().width&&e.getBoundingClientRect().height)",30000);let chooser;const off=client.on('Page.fileChooserOpened',/** 保留真实文件选择器事件，以便向该输入设置文件。 */ v=>chooser=v);await client.send('Page.setInterceptFileChooserDialog',{enabled:true});await clickText('.quick-actions button','Open Project');const deadline=Date.now()+10000;while(!chooser&&Date.now()<deadline)await wait(50);assert.ok(chooser);await client.send('DOM.setFileInputFiles',{files:[file],backendNodeId:chooser.backendNodeId});off();await until("!!document.querySelector('.upgrade-dialog,.editor-root')",30000);if(await evaluate("!!document.querySelector('.upgrade-dialog')"))await click('.upgrade-dialog footer button.primary');await until("!!document.querySelector('.editor-root')&&!document.querySelector('.project-manager')",30000);await wait(650);if(await evaluate("!!document.querySelector('.onboarding-scrim')")){await evaluate("document.querySelector('.onboarding-scrim').focus()");await press('Escape');await until("!document.querySelector('.onboarding-scrim')")};await wait(350)};
 const workspace=/** 按工作区顺序点击导航，并等待目标工作区所需控件出现。 */ async(name)=>{const index=['Design','Script','Animation','UI','Debug','Manage'].indexOf(name);assert.ok(index>=0);await click('.workspace-list button',index);await until(`document.querySelectorAll('.workspace-list button')[${index}]?.getAttribute('aria-pressed')==='true'`);if(name==='Manage')await until("!!document.querySelector('.manage-body>nav button')");else if(name==='Script')await until("!!document.querySelector('.script-workspace .logic-tabs')");else if(name==='UI')await until("!!document.querySelector('.ui-workspace')");await wait(350)};
 const entity=/** 进入设计工作区，按不含附属标签的完整实体名选择对象。 */ async(name)=>{await workspace('Design');const index=await evaluate(`[...document.querySelectorAll('.entity-list .entity-item .name')].findIndex(e=>[...e.childNodes].filter(n=>n.nodeName!=='SMALL').map(n=>n.textContent).join('').trim()===${JSON.stringify(name)})`);assert.ok(index>=0,'Entity '+name);await click('.entity-list .entity-item .name',index);await wait(160)};
 /** 通过当前可见标签或紧凑选择器打开底栏；先记录并关闭提示，必要时显式展开已选中的折叠页。 */
 const bottom=async(id,label)=>{
  while(await evaluate("!!document.querySelector('.toast-stack article button:last-child')")){
   a.observations.push({name:'dismissed-notification',text:await evaluate("document.querySelector('.toast-stack article')?.textContent")})
   await click('.toast-stack article button:last-child')
  }
  if(await evaluate("!!document.querySelector('.compact-tab-select')?.getBoundingClientRect().width"))await a.select('.compact-tab-select',id)
  else await clickText('.bottom-panel .panel-tab',label,true)
  if(!await evaluate("!!document.querySelector('.bottom-panel .panel-content')"))await click('.bottom-panel .panel-controls > button:last-child')
  await until("!!document.querySelector('.bottom-panel .panel-content')")
 };
 const world=/** 用当前可见的底栏入口打开世界工具，再选择指定子页。 */ async(tab)=>{if(await evaluate("!!document.querySelector('.compact-tab-select')?.getBoundingClientRect().width"))await a.select('.compact-tab-select','worldProduction');else await clickText('.bottom-tabs button,.panel-tabs button','World Studio');await until("!!document.querySelector('.world-tools')");if(tab)await clickText('.world-tools>header nav button',tab,true);await wait(150)};
 const expandInspector=/** 通过键盘逐个展开检查器折叠组，最多处理四十项。 */ async()=>{for(let i=0;i<40;i++){const at=await evaluate("[...document.querySelectorAll('.config-panel details.inspector-section>summary')].findIndex(e=>!e.parentElement.open)");if(at<0)break;await activate('.config-panel details.inspector-section>summary',at)}};
 const save=/** 选择保存项目并等待真实下载的有效 JSON，复制到证据目录并记录原始文件大小。 */ async(slug)=>{const folder=join(a.profile,'download-'+downloadIndex++);await mkdir(folder,{recursive:true});await client.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:folder,eventsEnabled:true});await click('.menu-item>button',0);await clickText('.menu-item .dropdown button','Save Project');let bytes;for(let i=0;!bytes&&i<250;i++){try{bytes=await readFile(join(folder,'project.nova'));JSON.parse(bytes.toString())}catch{bytes=null;await wait(80)}}assert.ok(bytes,'Saved project download');const file=join(a.evidence,'v26.17-'+slug+'.nova');await writeFile(file,bytes);a.observations.push({name:'actual-project-download',file,bytes:bytes.length});return{file,document:JSON.parse(bytes.toString()),folder}};
 const position=/** 等待两个位置字段出现，再读取当前二维坐标。 */ async()=>{await until("document.querySelectorAll('[data-property-path=\"Transform.position\"] input').length===2");return JSON.parse(await evaluate("JSON.stringify([...document.querySelectorAll('[data-property-path=\"Transform.position\"] input')].map(e=>Number(e.value)))"))};
 return{activate,field,labeled,readLabel,open,workspace,entity,bottom,world,expandInspector,save,position};
}
