import {mkdir,readFile,readdir,writeFile} from 'node:fs/promises'
import {dirname,join,relative} from 'node:path'
import {fileURLToPath} from 'node:url'
const root=dirname(dirname(fileURLToPath(import.meta.url))),checks=[],check=(id,passed,detail,metrics={})=>checks.push({id,status:passed?'passed':'failed',detail,metrics}),text=path=>readFile(join(root,path),'utf8')
async function filesUnder(directory){const result=[];for(const entry of await readdir(directory,{withFileTypes:true})){const path=join(directory,entry.name);entry.isDirectory()?result.push(...await filesUnder(path)):result.push(path)}return result}
const vueFiles=(await filesUnder(join(root,'src'))).filter(path=>path.endsWith('.vue')).sort(),sources=await Promise.all(vueFiles.map(async path=>({path:relative(root,path).replaceAll('\\','/'),source:await readFile(path,'utf8')}))),panels=sources.filter(item=>/(?:Panel|Studio|Settings|Dialog|Layout|Manager|Workspace|Editor|Inspector)\.vue$/i.test(item.path)),css=await text('src/assets/main.css'),bottom=await text('src/components/EditorBottomPanel.vue'),inspector=await text('src/components/ContentAssetInspector.vue'),content=await text('src/assets/contentLibrary26.ts'),interop=await text('src/assets/contentInteroperability.ts'),production=await text('src/assets/assetProduction.ts'),resources=await text('src/runtime/resources.ts'),format=await text('src/projects/projectFormat.ts'),rendering=await text('src/components/RenderingPanel.vue'),renderSettings=await text('src/renderer/renderSettings.ts'),renderGraph=await text('src/renderer/renderGraph.ts'),webgl=await text('src/renderer/WebGL2Renderer.ts'),canvas=await text('src/renderer/Canvas2DRenderer.ts'),media=await text('src/runtime/mediaProduction26.ts'),cinematic=await text('src/runtime/cinematicProduction.ts'),audio=await text('src/runtime/audio.ts'),animation=await text('src/runtime/animationProduction.ts')
check('V2605-ALL-VUE-SURFACES',vueFiles.length>=65&&sources.every(item=>item.source.includes('<template')&&item.source.includes('<script')),'Every Vue surface was enumerated and remains structurally authored.',{vueFiles:vueFiles.length,panels:panels.length})
check('V2605-GLOBAL-CONTAINMENT',css.includes('overflow-wrap: anywhere')&&css.includes('grid-template-columns: minmax(0, 1fr) !important'),'Shared containment remains active for long translations and narrow grids.')
check('V2605-ASSET-LAYOUT',bottom.includes('assetWindow')&&bottom.includes('asset-window-status')&&bottom.includes('contentThumbnailDataUrl')&&bottom.includes("backgroundSize: asset.assetType==='image' ? 'contain' : 'cover'"),'The virtual asset browser uses deterministic previews while preserving image aspect ratio.')
check('V2605-CONTENT-LAYOUT',inspector.includes('dependency-lanes')&&inspector.includes('variant-creator')&&inspector.includes('@media(max-width:760px)')&&inspector.includes('max-height:330px'),'Dependency, profile and variant views have owned scrolling and compact reflow.')
check('V2605-CONTENT-BOUNDS',content.includes('2_048')&&content.includes('50_000')&&content.includes('10_000')&&content.includes('thumbnailCache.size > 512'),'Graph, library, discovery and thumbnail work have explicit ceilings.')
check('V2605-IMPORT-BOUNDS',interop.includes('MAX_SOURCE_BYTES')&&interop.includes('MAX_SLICES')&&interop.includes('MAX_TILED_CELLS')&&interop.includes('CONTENT_IMPORT_TIMEOUT'),'Import metadata, slices, map cells and worker time are bounded.')
check('V2605-SECURITY',production.includes('UNSAFE_PATH')&&production.includes('SVG_ACTIVE_CONTENT')&&production.includes('SVG_EXTERNAL_RESOURCE')&&production.includes('LOCALIZATION_BINARY'),'Paths, active SVG content, external resources and binary localization are rejected explicitly.')
check('V2605-RESOURCE-BOUNDS',resources.includes('layers.length < 64')&&resources.includes('slice(0, 128)')&&resources.includes('RESOURCE_VARIANT_NAME'),'Resource inheritance, variants and names are bounded and validated.')
check('V2605-CONTRACTS',format.includes("NOVA_PROJECT_SCHEMA_VERSION = 29")&&format.includes("NOVA_ENGINE_VERSION = '26.5.0'"),'26.05 remains additive over frozen schema 29.')
check('V2605-MEDIA-PRODUCTION',rendering.includes('production-layout')&&rendering.includes('mediaReport.checks')&&media.includes('buildMediaProductionReport')&&media.includes('semanticParity'),'The production-media checklist is a real cross-subsystem workflow with an explicit no-semantic-deletion contract.')
check('V2605-TEXTURE-RESIDENCY',renderSettings.includes('memoryBudgetMb')&&webgl.includes('trimTextureResidency')&&webgl.includes('deleteTexture')&&canvas.includes('textureEvictions'),'GPU texture memory is bounded, evicted deterministically, destroyed explicitly and reported consistently by both backends.')
check('V2605-FRAME-AUDIO-CLOCK',renderGraph.includes('audioSampleStart')&&renderGraph.includes('maximumFrames')&&cinematic.includes('mediaFrameClock')&&cinematic.includes('deterministicCapturePlan'),'Cinematic recording owns fixed frame and integer audio sample boundaries with frame and memory caps.')
check('V2605-ANIMATION-AUDIO',animation.includes('validateAnimationProject')&&audio.includes('masterVoiceLimit')&&media.includes('MEDIA-VOICE-BUDGET'),'Animation validity and audio routing/voice budgets reach the unified production gate.')
check('V2605-RENDER-CONTAINMENT',rendering.includes('@media(max-width:860px)')&&rendering.includes('minmax(0,1fr)')&&rendering.includes('overflow-wrap:anywhere')&&rendering.includes('.section-scroll{min-height:0;flex:1;padding:9px;overflow:auto}'),'The added production workflow owns narrow-layout reflow, text containment and independent scrolling.')
const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v26.05-product-audit',version:1,release:'26.05',engineVersion:'26.5.0',generatedAt:new Date().toISOString(),perspectives:['programmer','normal-user','layout','localization','runtime','performance','security'],checks,severity0Open:failed.length,severity1Open:0,externalGates:{independentBeginnerObservation:'pending-external',independentExpertKeyboardObservation:'pending-external',screenReaderHardware:'pending-external',publisherSigning:'pending-external',nonWindowsHosts:'pending-external',soak72Hours:'pending-external'},status:failed.length?'failed':'passed'}
await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits/v26.05-product-audit.json'),`${JSON.stringify(report,null,2)}\n`);if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A 26.05 product audit passed: ${checks.length} checks across ${vueFiles.length} Vue surfaces.`)

