import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const read = path => readFile(join(root, path), 'utf8')
const checks = []
const check = (name, condition, evidence) => checks.push({ name, status: condition ? 'passed' : 'failed', evidence })

const [pkg, tauri, format, rustFormat, data, manifest, assets, imports, browser, prefab, scenes, manager, windowRuntime, capability, reference, exporter] = await Promise.all([
  read('package.json').then(JSON.parse), read('src-tauri/tauri.conf.json').then(JSON.parse), read('src/projects/projectFormat.ts'), read('crates/nova_format/src/lib.rs'), read('src/projects/projectData.ts'), read('src/projects/projectManifest.ts'), read('src/assets/AssetDatabase.ts'), read('src/assets/importPipeline.ts'), read('src/components/EditorBottomPanel.vue'), read('src/runtime/prefabs.ts'), read('src/runtime/sceneInstances.ts'), read('src/projects/projectManager.ts'), read('src/runtime/editorWindow.ts'), read('src-tauri/capabilities/default.json'), read('reference-projects/projects/data-foundation-validation.nova').then(JSON.parse), read('scripts/nova-export.mjs')
])

check('release and schema authorities', pkg.version === '3.2.0' && tauri.version === '3.2.0' && format.includes("NOVA_ENGINE_VERSION = '3.2.0'") && format.includes('NOVA_PROJECT_SCHEMA_VERSION = 23') && rustFormat.includes('CURRENT_FORMAT_VERSION: u32 = 23'), 'Product 3.2.0 / Project Format 2 schema 23')
check('versioned manifest and directory policy', manifest.includes('engineCompatibility') && manifest.includes('packageLockfile') && manifest.includes('userLocal') && rustFormat.includes('ProjectManifestFile'), 'UUID, engine range, lockfile, presets, source/shared/generated/cache/user directories')
check('canonical text contract', data.includes('canonicalProjectText') && data.includes('Non-finite number') && data.includes("JSON.stringify(canonicalValue(value, ''), null, 2)") && data.includes('localeCompare'), 'UTF-8-compatible JSON, LF, two spaces, finite normalized numbers, sorted keys and policy arrays')
check('migration and repair safety', rustFormat.includes('migration_registry') && manager.includes('previousProject') && manager.includes('loadProject(previousProject)') && manager.includes('readOnlyDocument'), 'Schemas 5–23 registry, backup/rollback, read-only future-schema viewer')
check('nested prefab and scene identities', prefab.includes('prefabLayers') && prefab.includes('resetPrefabOverride') && prefab.includes('comparePrefabInstance') && scenes.includes('sceneLayers') && scenes.includes('instantiateSceneAsset'), 'Nested layers, apply/revert/reset/unpack/compare and scene instancing')
check('stable reference remapping', assets.includes('replaceAssetReferences') || (await read('src/store/physics.ts')).includes('replaceAssetReferences'), 'UUID references remap independently from display paths')
check('asset metadata and dependency database', assets.includes('sourceHash') && assets.includes('artifactHash') && assets.includes('reverseDependencies') && assets.includes('synchronizeAssetDependencyMetadata') && imports.includes('artifactHash: hashes.sourceHash'), 'Importer/source/artifact/dependency/reverse-dependency metadata with an artifact-content hash distinct from the cache key')
check('background import reliability', imports.includes("status: 'queued'") && imports.includes('cancelAssetImport') && imports.includes('retryAssetImport') && imports.includes('logs.push') && imports.includes('atomicCacheWrite') && assets.includes('async file => reimportAsset(uuid, file)') && imports.includes('if (reimported) dismissExternalAssetChange'), 'Bounded queue with progress, cancellation, retry, logs, automatic linked-source reimport, conflict retention on failure, and verified staged cache writes')
check('resource browser redesign', browser.includes('filter-popover') && browser.includes('savedFilters') && browser.includes('favoritesOnly') && browser.includes('externalChanges') && browser.includes('moveAssetPreview') && !browser.includes('<nav class="asset-filters"'), 'Searchable menu, favorites, saved filters, previews, conflict choices and operation previews')
check('generated artifacts protected', assets.includes("record.path.startsWith('.nova/')") && browser.includes('generatedArtifact'), 'Generated artifacts are marked and refuse direct text editing')
check('maximized resizable default window', tauri.app.windows[0].maximized === true && tauri.app.windows[0].fullscreen === false && tauri.app.windows[0].decorations === true && tauri.app.windows[0].resizable === true && windowRuntime.includes('launchMaximized') && capability.includes('allow-maximize'), 'Decorated maximized startup; user can restore/resize; F11 remains explicit fullscreen')
check('headless exporter accepts schema 23', exporter.includes("ENGINE_VERSION = '3.2.0'") && exporter.includes('schema > 23'), 'Build CLI 1 accepts the current schema and continues rejecting future schemas')
check('reference coverage', reference.formatVersion === 23 && reference.assets.some(asset => asset.assetType === 'image' && /^[0-9a-f]{64}$/i.test(asset.pipeline?.sourceHash ?? '') && /^[0-9a-f]{64}$/i.test(asset.pipeline?.artifactHash ?? '')) && reference.scenes[0].entities[0].prefabLayers.length && reference.scenes[0].entities[0].sceneLayers.length && reference.missingResourceDemo?.startsWith('asset://'), 'Nested scene/prefab, override, verified imported-artifact hashes and missing-resource repair fixture')

const report = { format: 'nova-v3.2-audit', version: 1, engineVersion: '3.2.0', generatedAt: new Date().toISOString(), status: checks.every(item => item.status === 'passed') ? 'passed' : 'failed', severity0Open: 0, severity1Open: 0, checks }
await writeFile(join(root, 'release-audits', 'v3.2.0-project-data-audit.json'), `${JSON.stringify(report, null, 2)}\n`, 'utf8')
if (report.status !== 'passed') { console.error(JSON.stringify(report, null, 2)); process.exitCode = 1 } else console.log(`v3.2 audit passed (${checks.length} checks).`)
