import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const files = async (...paths) => Object.fromEntries(await Promise.all(paths.map(async path => [path, await readFile(join(root, path), 'utf8')])))
const source = await files('package.json', 'Cargo.toml', 'src-tauri/Cargo.toml', 'src-tauri/tauri.conf.json', 'crates/nova_format/src/lib.rs', 'src/projects/projectFormat.ts', 'src/runtime/exportTemplates.ts', 'src/runtime/buildSettings.ts', 'src/runtime/uiAccessibility.ts', 'src/world/components.ts', 'src/projects/templates.ts', 'src/store/physics.ts', 'src/components/ConfigPanel.vue', 'instructions.txt', 'scripts/package-release.ps1', 'scripts/verify-release-package.ps1')
const [backend, catalog, interactions, layout] = await Promise.all(['v6.0.3-backend-export.json', 'template-catalog-verification.json', 'v6.0.3-user-interactions.json', 'v6.0.3-layout-browser.json'].map(async name => JSON.parse(await readFile(join(root, 'release-audits', name), 'utf8'))))
const pkg = JSON.parse(source['package.json']), tauri = JSON.parse(source['src-tauri/tauri.conf.json'])

check('V603-VERSION', pkg.version === '6.0.3' && tauri.version === '6.0.3' && [source['Cargo.toml'], source['src-tauri/Cargo.toml']].every(value => /version\s*=\s*"6\.0\.3"/.test(value)) && source['crates/nova_format/src/lib.rs'].includes('CURRENT_ENGINE_VERSION: &str = "6.0.3"') && source['src/projects/projectFormat.ts'].includes("NOVA_ENGINE_VERSION = '6.0.3'"), 'Frontend, native, Rust and project authorities identify 6.0.3.')
check('V603-FROZEN-CONTRACTS', source['src/projects/projectFormat.ts'].includes('NOVA_PROJECT_SCHEMA_VERSION = 29') && source['src/projects/projectFormat.ts'].includes('NOVA_PROJECT_FORMAT_MAJOR = 2'), 'Project Format 2/schema 29 remain frozen.')
check('V603-TEMPLATE-RESOLUTION', source['src/runtime/exportTemplates.ts'].includes('defaultExportTemplateId') && source['src/runtime/exportTemplates.ts'].includes('resolveExportTemplateId') && source['src/runtime/buildSettings.ts'].includes('resolveExportTemplateId(') && source['src/projects/templates.ts'].includes("exportTemplate: 'windows-x64-v1'"), 'Build normalization resolves registered manifests and migrates only known legacy IDs.')
check('V603-UI-SEMANTICS', source['src/world/components.ts'].includes('focusable = false') && source['src/world/components.ts'].includes('skipNavigation = true') && source['src/runtime/uiAccessibility.ts'].includes('Zero is automatic scene order') && source['src/store/physics.ts'].includes('configureUiAccessibility') && source['src/components/ConfigPanel.vue'].includes('configureUiAccessibility'), 'Passive defaults and all programmatic/component authoring paths apply UI semantics.')
check('V603-CATALOG', catalog.status === 'passed' && catalog.engineVersion === '6.0.3' && ['CATALOG-BUILD-DEFAULTS', 'CATALOG-UI-SEMANTICS', 'CATALOG-UI-COMPATIBILITY'].every(id => catalog.checks.some(item => item.id === id && item.status === 'passed')), 'All startup templates pass build and accessibility regression checks.', { checks: catalog.checks.length })
check('V603-BACKEND', backend.status === 'passed' && backend.checks.every(item => item.status === 'passed'), 'Template aliasing, package round-trip and single-file export pass.', { checks: backend.checks.length })
check('V603-INTERACTIONS', interactions.status === 'passed' && interactions.severity0Open === 0 && interactions.severity1Open === 0 && interactions.launcherLayout?.length === 3 && interactions.launcherLayout.every(item => item.status === 'passed'), 'User-style clicks, settings, navigation, drags and the 1024×640/200% launcher pass in all languages.', { ...interactions.summary, launcherLayout: interactions.launcherLayout })
check('V603-LAYOUT', layout.status === 'passed' && layout.severity0Open === 0 && layout.severity1Open === 0 && layout.matrix.some(item => item.name.includes('200%')), 'EN/DE/ZH layout remains contained from minimum viewport through 200% scale.', { states: layout.matrix.length })
check('V603-RELEASE-CONTRACT', ['source.zip', 'web.zip', 'windows-x64-portable.exe', 'windows-x64-setup.exe', 'windows-x64.msi', 'reference-projects.zip', 'release-evidence.zip', 'RELEASE_NOTES.md', 'EDIT_LEDGER.md', 'LICENSE.md', 'SHA256SUMS.txt'].every(marker => source['scripts/package-release.ps1'].includes(marker)) && source['scripts/verify-release-package.ps1'].includes('exact mandatory artifact set'), 'Exact eleven-artifact/ten-checksum release contract remains enforced.')
check('V603-INSTRUCTIONS', ['Never synthesize a guessed template ID', 'Reading order `0` means automatic scene order', 'references:v6.0.3'].every(marker => `${source['instructions.txt']} ${source['package.json']}`.includes(marker)), 'The 6.0.3 specification and release entrypoints are present.')

const failed = checks.filter(item => item.status === 'failed')
const report = { format: 'nova-v6.0.3-product-audit', version: 1, engineVersion: '6.0.3', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'user', 'localization', 'layout', 'accessibility', 'backend', 'game-export', 'release'], checks, severity0Open: 0, severity1Open: failed.length, externalGates: { publisherSigning: 'pending-external', cleanMachineLifecycle: 'pending-external', secondMachineReproducibility: 'pending-external', independentHardwareAccessibility: 'pending-external', soak72Hours: 'pending-external' }, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v6.0.3-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v6.0.3 product audit passed: ${checks.length} checks.`)
