import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const read = path => readFile(join(root, path), 'utf8')
const json = async path => JSON.parse(await read(path))
const [pkg, tauri, cargo, nativeCargo, format, content, assetDatabase, assetInspector, assetPanel, controlRegistry, resources, rigging, animation, animationPanel, production, novaPak, exporter, instructions, roadmap, guide, manualEn, manualDe, manualZh, verification, catalog, interactions, layoutReport, performanceBefore, performanceAfter] = await Promise.all([
  json('package.json'), json('src-tauri/tauri.conf.json'), read('Cargo.toml'), read('src-tauri/Cargo.toml'), read('src/projects/projectFormat.ts'), read('src/assets/contentInteroperability.ts'), read('src/assets/AssetDatabase.ts'), read('src/components/ContentAssetInspector.vue'), read('src/components/EditorBottomPanel.vue'), read('src/runtime/controlRegistry.ts'), read('src/runtime/resources.ts'), read('src/runtime/rigging.ts'), read('src/runtime/animation.ts'), read('src/components/AnimationPanel.vue'), read('src/runtime/productionValidation.ts'), read('src/runtime/novaPak.ts'), read('scripts/nova-export.mjs'), read('instructions.txt'), read('docs/ROADMAP_6_2_TO_7_0.md'), read('docs/CONTENT_ANIMATION_6_4.md'), read('manual/MANUAL.en.md'), read('manual/MANUAL.de.md'), read('manual/MANUAL.zh-CN.md'), json('release-audits/v6.4.0-verification.json'), json('release-audits/template-catalog-verification.json'), json('release-audits/v6.4.0-user-interactions.json'), json('release-audits/v6.4.0-layout-browser.json'), json('release-audits/v6.4.0-performance-before.json'), json('release-audits/v6.4.0-performance-after.json')
])
check('V640-VERSION', pkg.version === '6.4.0' && tauri.version === '6.4.0' && /version\s*=\s*"6\.4\.0"/.test(cargo) && /version\s*=\s*"6\.4\.0"/.test(nativeCargo) && format.includes("NOVA_ENGINE_VERSION = '6.4.0'"), 'Frontend, native, Rust and project authorities identify 6.4.0.')
check('V640-FROZEN-CONTRACTS', format.includes('NOVA_PROJECT_FORMAT_MAJOR = 2') && format.includes('NOVA_PROJECT_SCHEMA_VERSION = 29') && instructions.includes('Graph Format 1'), 'Project Format 2/schema 29 and all public 6.x contracts remain frozen.')
check('V640-INTERCHANGE', ['aseprite-json', 'texturepacker-json', 'tiled-json', 'tiled-xml', 'atlas-json'].every(value => content.includes(value)) && content.includes('MAX_SOURCE_BYTES') && content.includes('MAX_SLICES') && content.includes('MAX_TILED_CELLS') && assetDatabase.includes('importContentInterchangeAsync'), 'Aseprite, TexturePacker/common atlas and Tiled import/reimport are deterministic and bounded.')
check('V640-IDENTITY-RECOVERY', content.includes('previousIds') && assetDatabase.includes('lastValidSource') && assetDatabase.includes('CONTENT_TYPE_MISMATCH'), 'Reimport preserves stable slice identity and the last valid artifact on failure.')
check('V640-PERFORMANCE-SCHEDULING', content.includes("new Worker(new URL('./contentInteroperability.worker.ts'") && content.includes('resultCache.size > 32'), 'Large metadata uses bounded worker parsing and repeated canonical sources use a bounded cache.')
check('V640-RESOURCE-MODEL', resources.includes("'PhysicsMaterial'") && resources.includes("'AnimationLibrary'") && resources.includes('normalizeOverrideData') && resources.includes('RESOURCE_CYCLE') && resources.includes('deepMerge'), 'Six Resource kinds support shared parents, local-only overrides, deterministic resolution and cycle rejection.')
check('V640-CONTEXTUAL-ASSETS', assetInspector.includes("const tabs=computed<ContextTab[]>") && assetInspector.includes('createResourceOverride') && assetPanel.includes('ContentAssetInspector'), 'Contextual Overview, Slices, Resource and Animation tabs are connected to the Assets panel.')
check('V640-ASSET-UI-SAFETY', assetPanel.includes('asset-overflow-menu') && assetPanel.includes('clonePipelineMetadata') && controlRegistry.includes('element.textContent'), 'Compact Asset actions remain contained and accessible, while importer history snapshots reject reactive proxies.')
check('V640-ANIMATION-PRODUCTION', rigging.includes('autoWeightSkin') && rigging.includes('skinWeightHeat') && rigging.includes('retargetPreviewSummary') && animation.includes('previewRootMotion') && animationPanel.includes('onionSamples') && animationPanel.includes('autoWeights'), 'Rig weights, constraints, onion skin, curves, retarget and root-motion preview are connected.')
check('V640-BUILD-EXPORT', production.includes('validateResourceProject') && novaPak.includes("'resource'") && exporter.includes("'resource'"), 'Resources and imported content are validated and included by native/Web packaging.')
check('V640-MANUALS', [manualEn, manualDe, manualZh].every(source => source.includes('Engine: **6.4.0**') && source.includes('Aseprite metadata import and reimport') && source.includes('Bounded automatic skin weights')), 'English, German and Chinese teaching manuals cover the v6.4 workflows.', { bytes: manualEn.length + manualDe.length + manualZh.length })
check('V640-ROADMAP', instructions.includes('## 6.4.0 implementation checkpoint') && roadmap.includes('## 6.4.0 — 2D content interoperability') && guide.includes('Reusable Resource assets'), 'Implementation follows the authoritative 6.4 checkpoint and task guide.')
check('V640-VERIFICATION', verification.status === 'passed' && verification.engineVersion === '6.4.0' && verification.severity0Open === 0, 'Golden/malformed content, Resource, animation and performance verifier passes.', { checks: verification.checks.length })
check('V640-TEMPLATES', catalog.status === 'passed' && catalog.engineVersion === '6.4.0', 'All startup templates retain valid gameplay, build and accessibility behavior.', { checks: catalog.checks.length })
check('V640-INTERACTIONS', interactions.status === 'passed' && interactions.severity0Open === 0 && interactions.severity1Open === 0, 'User-style interaction traversal reports no critical failure.', interactions.summary)
check('V640-LAYOUT', layoutReport.status === 'passed' && layoutReport.severity0Open === 0 && layoutReport.severity1Open === 0, 'EN/DE/ZH layout remains contained through 200% scale.', { states: layoutReport.results.length })
check('V640-PERFORMANCE-EVIDENCE', ['passed', 'failed'].includes(performanceBefore.status) && performanceBefore.measurements?.physics?.finite === true && performanceAfter.status === 'passed' && performanceAfter.measurements?.physics?.finite === true && performanceAfter.measurements?.export?.elapsedMs > 0, 'The measured pre-fix baseline is retained honestly and the final physics/import/script/export benchmark passes without removing features.', { beforeStatus: performanceBefore.status, afterStatus: performanceAfter.status, beforeBodyStepsPerSecond: performanceBefore.measurements.physics.bodyStepsPerSecond, afterBodyStepsPerSecond: performanceAfter.measurements.physics.bodyStepsPerSecond, finalExportMs: performanceAfter.measurements.export.elapsedMs })

const failed = checks.filter(item => item.status === 'failed')
const report = { format: 'nova-v6.4.0-product-audit', version: 1, engineVersion: '6.4.0', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'user', 'compatibility', 'content', 'resources', 'animation', 'performance', 'runtime', 'build', 'localization', 'layout', 'release'], checks, severity0Open: 0, severity1Open: failed.length, externalGates: { publisherSigning: 'pending-external', cleanMachineLifecycle: 'pending-external', secondMachineReproducibility: 'pending-external', matchingHostTargets: 'pending-external', independentHardwareAccessibility: 'pending-external', soak72Hours: 'pending-external' }, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true })
await writeFile(join(root, 'release-audits/v6.4.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v6.4.0 product audit passed: ${checks.length} checks.`)
