import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root=dirname(dirname(fileURLToPath(import.meta.url))),read=path=>readFile(join(root,path),'utf8'),checks=[],check=(id,passed,detail)=>checks.push({id,status:passed?'passed':'failed',detail})
const [pkgText,tauriText,format,production,physicsApi,world,monitor,monitorUi,debug,canvas,settings,config,connection,builder,store,health,rustWorld,rustRuntime,wasm,i18n,manual,novaPak,physicsDoc]=await Promise.all([
  'package.json','src-tauri/tauri.conf.json','src/projects/projectFormat.ts','src/runtime/physicsProduction.ts','src/runtime/physics2d.ts','src/world/World.ts','src/runtime/physicsMonitor.ts','src/components/PhysicsRuntimePanel.vue','src/runtime/physicsDebug.ts','src/components/WorldCanvas.vue','src/components/PhysicsSettingsPanel.vue','src/components/ConfigPanel.vue','src/world/Connection.ts','src/components/ConnectionBuilder.vue','src/store/physics.ts','src/components/ProjectHealthPanel.vue','crates/nova_physics/src/world/persistent.rs','crates/nova_runtime/src/lib.rs','crates/nova_wasm/src/lib.rs','src/i18n.ts','manual/index.html','src/runtime/novaPak.ts','docs/PHYSICS_2D_4_5.md'
].map(read)),pkg=JSON.parse(pkgText),tauri=JSON.parse(tauriText)
check('V450-VERSION',pkg.version==='4.5.0'&&tauri.version==='4.5.0'&&format.includes("'4.5.0'"),'Web, desktop, and project authorities report 4.5.0.')
check('V450-BODY-ROLES',['Static','DynamicRigid','Animatable','Character','Area','physicsBodyRole'].every(value=>production.includes(value)),'Five documented body roles and ownership classifier exist.')
check('V450-SHAPES',['Box','Circle','Capsule','Segment','Chain','WorldBoundary','ConvexPolygon','ConcavePolygon'].every(value=>production.includes(value))&&config.includes("'WorldBoundary'")&&config.includes("kind === 'WorldBoundary'"),'Stable shape catalog and World Boundary authoring are exposed.')
check('V450-PROFILES',['Accurate','Balanced','Fast','Custom','droppedTimePolicy','minimumSubsteps','velocityIterations','positionIterations','timeToSleep'].every(value=>production.includes(value))&&['set_physics_quality','dropped_time_policy'].every(value=>wasm.includes(value)),'Profiles, drop policy, sleep, substeps, and solver iterations reach WASM/runtime.')
check('V450-PROJECT-SCOPE',store.includes('serializePhysicsProjectSettings')&&store.includes('loadPhysicsProjectSettings')&&novaPak.includes('physicsProfile'),'Physics profile, named layers, and matrix are project/build package data.')
check('V450-QUERIES',['rayQuery','pointQuery','overlapQuery','sweep','nearest','contactQuery'].every(value=>physicsApi.includes(value))&&['layerMask','includeSensors','excludeEntityUuids','maximumResults'].every(value=>physicsApi.includes(value)),'Structured filtered query surface is connected.')
check('V450-EVENTS',['BodySleeping','BodyWoke','ConstraintBroken'].every(value=>rustWorld.includes(value))&&['BodySleeping','BodyWoke','JointBroken'].every(value=>rustRuntime.includes(value))&&['entityUuid','connectionUuid'].every(value=>world.includes(value)),'Sleep/wake and joint/Rope break events resolve stable identities.')
check('V450-CHARACTER',['moveAndSlide','characterState'].every(value=>physicsApi.includes(value))&&['character-slope','character-step','moving-platform','character-ceiling'].every(value=>production.includes(value)),'Character motion/classification workflow and catalog coverage remain stable.')
check('V450-JOINT-ROPE',['DistanceJoint2D','RevoluteJoint2D','PrismaticJoint2D','WeldJoint2D','SpringJoint2D','MotorJoint2D','Rope2D'].every(value=>world.includes(value))&&connection.includes('segmentCount')&&builder.includes('ropeSegments')&&builder.includes('collideConnected'),'Joint/Rope anchors, collision policy, segmentation, and telemetry are authorable.')
check('V450-MONITOR',['sortKey','pinnedUuids','speedHistory','constraints','captures','comparePhysicsSnapshots','physicsCaptureJson'].every(value=>monitor.includes(value))&&['virtual-list','sparkline','compareLatest','exportCapture'].every(value=>monitorUi.includes(value)),'Virtual monitor supports sort, pin, sparkline, deltas, constraints, capture/export/compare.')
check('V450-OVERLAYS',['showCentersOfMass','showVelocities','showForces'].every(value=>debug.includes(value))&&['showCentersOfMass','showVelocities','showForces'].every(value=>canvas.includes(value)),'COM, velocity, and force overlays are connected alongside existing diagnostics.')
check('V450-HEALTH',health.includes('physicsMonitorState.warnings')&&monitor.includes('physicsInstabilityWarnings'),'Physics budget/instability warnings feed Project Health.')
check('V450-ADVANCED-MATRIX',settings.includes('advancedCollisionMatrix')&&settings.includes('matrix'),'The numeric collision matrix remains available only through the advanced authoring surface.')
check('V450-SCRIPT-EXPORTS',production.includes('PHYSICS_SCRIPT_EXPORT_BINDINGS')&&['move_speed','jump_speed','segments','break_force'].every(value=>production.includes(value)),'Stable designer-tunable physics script metadata is declared with units and bounds.')
check('V450-DETERMINISM',physicsDoc.includes('Cross-platform bitwise floating-point identity is not promised')&&i18n.includes('physicsDeterminismBoundary'),'Determinism boundary is explicit and honest.')
check('V450-I18N',['physicsQualityProfile','ropeSegments','physicsWarnings','showCentersOfMass',"releaseLabel:'Nova_A v4.5.0'"].every(value=>i18n.includes(value)),'Physics workflow labels are available in English, German, and Chinese.')
check('V450-MANUAL',manual.includes('Engine 4.5.0')&&['en-v45','de-v45','zh-CN-v45'].every(value=>manual.includes(value)),'Bookmarkable multilingual v4.5 manual sections are present.')
for(const name of ['PHYSICS_2D_4_5.md','CHARACTER_CONTROLLERS_4_5.md','PHYSICS_DIAGNOSTICS_4_5.md','KNOWN_ISSUES_4_5.md']){try{await access(join(root,'docs',name));check(`V450-DOC-${name}`,true,'Present.')}catch{check(`V450-DOC-${name}`,false,'Missing.')}}
for(const slug of ['physics-v45-platformer','physics-v45-top-down','physics-v45-queries-triggers','physics-v45-joints','physics-v45-rope2d','physics-v45-diagnostics'])for(const name of ['project.nova','README.md','expected-output.json','test-controls.json']){try{await access(join(root,'reference-projects','projects',slug,name));check(`V450-REF-${slug}-${name}`,true,'Present.')}catch{check(`V450-REF-${slug}-${name}`,false,'Missing.')}}
const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v4.5-production-physics-audit',version:1,engineVersion:'4.5.0',generatedAt:new Date().toISOString(),catalog:['PHY'],checks,severity0Open:0,severity1Open:failed.length,status:failed.length?'failed':'passed'}
await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits','v4.5.0-physics-audit.json'),`${JSON.stringify(report,null,2)}\n`)
if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A v4.5 physics audit passed: ${checks.length} checks.`)
