import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const read = path => readFile(join(root, path), 'utf8')
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const paths = ['package.json', 'Cargo.toml', 'src-tauri/tauri.conf.json', 'instructions.txt', 'src/runtime/animation.ts', 'src/runtime/animationProduction.ts', 'src/runtime/timeline.ts', 'src/runtime/cinematicProduction.ts', 'src/runtime/audio.ts', 'src/runtime/GameplayRuntime.ts', 'src/components/AnimationPanel.vue', 'src/components/PresentationPanel.vue', 'src/components/WorldCanvas.vue', 'src/i18n.ts', 'README.md', 'README.zh-CN.md', 'manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md', 'manual/index.html', 'scripts/package-release.ps1', 'release-audits/v5.6.0-production-verification.json', 'release-audits/v5.6.0-layout-browser.json']
const sources = await Promise.all(paths.map(read)), source = Object.fromEntries(paths.map((path, index) => [path, sources[index]])), pkg = JSON.parse(source['package.json']), tauri = JSON.parse(source['src-tauri/tauri.conf.json']), verification = JSON.parse(source['release-audits/v5.6.0-production-verification.json']), layout = JSON.parse(source['release-audits/v5.6.0-layout-browser.json'])

check('V560-VERSION', pkg.version === '5.6.0' && tauri.version === '5.6.0' && /version\s*=\s*"5\.6\.0"/.test(source['Cargo.toml']), 'Frontend, native and Rust authorities identify 5.6.0.')
check('V560-COMPATIBILITY', source['README.md'].includes('Project Format 2/schema 29') && source['instructions.txt'].includes('Project Format 2/schema 29') && source['instructions.txt'].includes('Rhai API v2'), 'Frozen Project Format/schema and public API boundaries remain documented.')
check('V560-ROADMAP', source['instructions.txt'].includes('Implementation status (5.6.0 candidate): complete') && source['instructions.txt'].includes('10,000-clip long-timeline fixture'), 'Roadmap records the complete implementation and evidence contract.')
check('V560-ANIMATOR', ['BlendTreeType', 'parameterY', 'synchronizedTiming', 'syncMode', 'rootMotion', 'animationDispatchesBetween'].every(marker => source['src/runtime/animation.ts'].includes(marker)) && ['blendTreeType', 'transitionSync', 'runtimeRecording'].every(marker => source['src/components/AnimationPanel.vue'].includes(marker)), '2D blends, layers/masks, synchronized transitions, motion options, events and recording are runtime/editor bound.')
check('V560-CINEMATICS', ['NestedTimeline', 'Subtitle', 'Branch', 'skip(', 'resume(', 'audioRuntime.scrub'].every(marker => source['src/runtime/timeline.ts'].includes(marker)) && ['estimateTimelinePerformance', 'NOVA-CIN-SUBTITLE-READING'].every(marker => source['src/runtime/cinematicProduction.ts'].includes(marker)) && ['timeline-marker', 'subtitleSafeArea', 'skippable'].every(marker => source['src/components/AnimationPanel.vue'].includes(marker)), 'Nested timelines, markers, scrubbing, blends, subtitles, branching and skip/resume are connected and validated.')
check('V560-AUDIO', ['snapshotTransitionSeconds', 'AudioMixerSend', 'AudioDuckingRule', 'integratedLufs', 'devicechange', 'scrub('].every(marker => source['src/runtime/audio.ts'].includes(marker)) && ['waveformEditor', 'loopRegions', 'snapshotCrossfade', 'duck-rule', 'truePeak'].every(marker => source['src/components/PresentationPanel.vue'].includes(marker)), 'Waveforms, named loops, sends, ducking, crossfaded snapshots, loudness and device recovery are editor/runtime bound.')
check('V560-INTEROP', ['NestedAnimation', 'Timeline', 'VisualGraph'].every(marker => source['src/runtime/animation.ts'].includes(marker) && source['src/runtime/GameplayRuntime.ts'].includes(marker)) && ['beginRuntimeRecording', 'finishRuntimeRecording'].every(marker => source['src/runtime/animation.ts'].includes(marker)), 'Animation, Audio, Timeline and Visual Graph interoperability plus recording are connected.')
check('V560-SUBTITLE-RENDERING', ['timeline-subtitle', 'aria-live', 'TitleSafe', 'ActionSafe', 'FullFrame'].every(marker => source['src/components/WorldCanvas.vue'].includes(marker)), 'Localized subtitles render above gameplay in all supported safe areas.')
check('V560-I18N', ['synchronizedLayer', 'runtimeRecording', 'subtitleSafeArea', 'waveformEditor', 'integratedLufs'].every(key => (source['src/i18n.ts'].match(new RegExp(`${key}:`, 'g')) ?? []).length >= 3), 'Every new visible v5.6 control is localized in EN/DE/ZH.')
check('V560-DOCS', source['README.md'].includes('Version **5.6.0**') && source['README.zh-CN.md'].includes('版本 **5.6.0**') && ['manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md'].every(path => source[path].includes('Nova_A 5.6')) && ['en-v56', 'de-v56', 'zh-CN-v56'].every(marker => source['manual/index.html'].includes(marker)), 'README and all multilingual manuals teach v5.6 workflows.')
check('V560-VERIFY', verification.status === 'passed' && verification.severity0Open === 0 && verification.severity1Open === 0, 'Production behavior verification passes.', { checks: verification.checks.length })
check('V560-LAYOUT', layout.status === 'passed' && layout.matrix?.length === 12 && layout.matrix.every(item => item.status === 'passed') && layout.severity0Open === 0 && layout.severity1Open === 0, 'EN/DE/ZH browser matrix passes four viewports.', { matrix: layout.matrix?.length ?? 0 })
check('V560-RELEASE', ['source.zip', 'web.zip', 'windows-x64-portable.exe', 'windows-x64-setup.exe', 'windows-x64.msi', 'reference-projects.zip', 'release-evidence.zip', 'RELEASE_NOTES.md', 'EDIT_LEDGER.md', 'LICENSE.md', 'SHA256SUMS.txt'].every(marker => source['scripts/package-release.ps1'].includes(marker)), 'Generic packager enforces the exact eleven artifacts.')

const failed = checks.filter(item => item.status === 'failed'), report = { format: 'nova-v5.6.0-product-audit', version: 1, engineVersion: '5.6.0', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'runtime', 'user', 'layout'], checks, severity0Open: 0, severity1Open: failed.length, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v5.6.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v5.6.0 product audit passed: ${checks.length} checks.`)
