import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const version = '6.8.0', root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const read = path => readFile(join(root, path), 'utf8'), json = async path => JSON.parse(await read(path))
const [pkg, tauri, cargo, nativeCargo, format, performanceSource, jobs, worker, hierarchy, streaming, navigation, animation, particles, canvas, profiler, production, panel, guide, instructions, roadmap, manualEn, manualDe, manualZh, verification, catalog, interactions, layout, performance, windows, stability, dependency, reference, fixture100k] = await Promise.all([
  json('package.json'), json('src-tauri/tauri.conf.json'), read('Cargo.toml'), read('src-tauri/Cargo.toml'), read('src/projects/projectFormat.ts'), read('src/runtime/largeWorldPerformance.ts'), read('src/runtime/jobScheduler.ts'), read('src/runtime/jobScheduler.worker.ts'), read('src/world/hierarchy.ts'), read('src/runtime/worldStreaming.ts'), read('src/runtime/navigation2d.ts'), read('src/runtime/animation.ts'), read('src/runtime/particles.ts'), read('src/components/WorldCanvas.vue'), read('src/runtime/profiler.ts'), read('src/runtime/production.ts'), read('src/components/ProfilerPanel.vue'), read('docs/LARGE_WORLD_PERFORMANCE_6_8.md'), read('instructions.txt'), read('docs/ROADMAP_6_2_TO_7_0.md'), read('manual/MANUAL.en.md'), read('manual/MANUAL.de.md'), read('manual/MANUAL.zh-CN.md'), json('release-audits/v6.8.0-verification.json'), json('release-audits/template-catalog-verification.json'), json('release-audits/v6.8.0-user-interactions.json'), json('release-audits/v6.8.0-layout-browser.json'), json('release-audits/v6.8.0-performance-after.json'), json('release-audits/v6.8.0-windows-smoke.json'), json('release-audits/v6.8.0-stability-local.json'), json('release-audits/v6.8.0-dependency-audit.json'), json('reference-projects/projects/creator-v680-large-world/project.nova'), json('release-fixtures/v6.8.0/100000.json')
])

check('V680-VERSION', pkg.version === version && tauri.version === version && /version\s*=\s*"6\.8\.0"/.test(cargo) && /version\s*=\s*"6\.8\.0"/.test(nativeCargo) && format.includes("NOVA_ENGINE_VERSION = '6.8.0'"), 'Frontend, Rust, Tauri and project authorities identify 6.8.0.')
check('V680-FROZEN-CONTRACTS', format.includes('NOVA_PROJECT_FORMAT_MAJOR = 2') && format.includes('NOVA_PROJECT_SCHEMA_VERSION = 29') && instructions.includes('Graph Format 1'), 'Project Format 2/schema 29 and every frozen 6.x contract remain unchanged.')
check('V680-DATA-ORIENTED', performanceSource.includes('StableComponentScheduler') && animation.includes("indices('Animator')") && particles.includes("indices('ParticleEmitter2D')") && hierarchy.includes('byUuid: new Map'), 'Stable component columns and hierarchy identity lookup drive existing runtime components without a public-component migration.')
check('V680-SPATIAL-DIRTY', performanceSource.includes('SpatialHash2D') && navigation.includes('spatial.query') && performanceSource.includes('dirtyTransforms') && performanceSource.includes('recordCachePerformance'), 'Deterministic spatial queries and dirty/cache/allocation accounting reach live navigation and frame metrics.')
check('V680-WORKERS', jobs.includes('latestGenerations') && jobs.includes('runJobLocally') && worker.includes('sampleAnimation') && worker.includes('advanceParticles') && worker.includes('buildSpatialGrid') && jobs.includes('Stale'), 'Worker animation/particle/spatial tasks have exact local fallback, cancellation and stale-generation rejection.')
check('V680-BOUNDED-WORK', streaming.includes('transitionLimit') && streaming.includes('deferredThisFrame') && navigation.includes('frameWorkBudgetMs') && performanceSource.includes('BatchedCommandQueue') && performanceSource.includes('FrameBudgetQueue'), 'Commands, background work, navigation and streaming are bounded and deferred rather than dropped.')
check('V680-METRICS', ['mainThreadMs','workerMs','queueWaitMs','cacheHitRate','allocations','worstFrameMs','onePercentLowFps','inputToPixelMs','coldStartupMs','warmStartupMs'].every(field => performanceSource.includes(field) && (profiler.includes(field) || panel.includes(field))) && panel.includes("t('warmStartup')"), 'The live Profiler exposes explicit main/worker/queue/cache/allocation/worst/1%-low/input/cold/warm startup evidence.')
check('V680-ADAPTIVE', canvas.includes('adaptivePixelRatioScale') && particles.includes('adaptiveParticleScale') && production.includes('adaptiveQuality') && guide.includes('never changes physics tick rate'), 'Adaptive quality is persisted and presentation-only; fixed-step, scripts, animations, authored values and controls are retained.')
check('V680-FIXTURES', fixture100k.count === 100_000 && verification.measurements.fixtures?.length === 3 && verification.measurements.fixtures.every(item => item.fingerprint && item.generatedMs < verification.thresholds.generationMs100k), '10k/50k/100k deterministic fixtures complete within declared local thresholds.', { fixtures: verification.measurements.fixtures })
check('V680-REFERENCE', reference.engineVersion === version && reference.projectSettings.production.performance.maximumCommandsPerFrame === 2048 && reference.projectSettings.production.performance.adaptiveQuality === true, 'Playable no-code reference freezes all v6.8 runtime budgets.')
check('V680-MANUALS', [manualEn, manualDe, manualZh].every(text => text.includes('Engine: **6.8.0**')) && manualEn.includes('Large-world and low-end performance') && manualDe.includes('Großwelt- und Low-End-Leistungsablauf') && manualZh.includes('大型世界与低端设备性能流程'), 'English, German and Chinese manuals teach measurement, recovery and external boundaries.', { bytes: manualEn.length + manualDe.length + manualZh.length })
check('V680-ROADMAP', roadmap.includes('## 6.8.0 — large-world') && instructions.includes('## 6.8.0 implementation checkpoint') && guide.includes('## Qualification matrix'), 'Roadmap, checkpoint and technical guide are synchronized.')
check('V680-VERIFICATION', verification.status === 'passed' && verification.engineVersion === version && verification.checks.length >= 16, 'Focused equivalence, race, fallback and 100k verification passes.', { checks: verification.checks.length })
check('V680-TEMPLATES', catalog.status === 'passed' && catalog.engineVersion === version, 'Every startup template retains valid gameplay, build and accessibility behavior.', { checks: catalog.checks.length })
check('V680-INTERACTIONS', interactions.status === 'passed' && interactions.severity0Open === 0 && interactions.severity1Open === 0, 'Normal-user clicks, drags, inputs and settings report no critical failure.', interactions.summary)
check('V680-LAYOUT', layout.status === 'passed' && layout.severity0Open === 0 && layout.severity1Open === 0, 'EN/DE/ZH layout stays contained across required viewports and 100–200% scales.', { states: layout.results?.length ?? 0 })
check('V680-PERFORMANCE', performance.status === 'passed' && performance.measurements?.physics?.finite === true, 'Retained benchmark remains finite without removing effects, controls or animation.', { bodyStepsPerSecond: performance.measurements?.physics?.bodyStepsPerSecond })
check('V680-DEPENDENCIES', dependency.status === 'passed' && dependency.engineVersion === version && dependency.registryAdvisories?.status === 'pending-external', 'Pinned dependency coverage and integrity pass locally; live registry advisories remain explicitly pending external authorization.')
check('V680-WINDOWS', windows.status === 'passed' && windows.artifacts?.length === 4 && windows.artifacts.every(item => item.bytes > 0 && item.sha256?.length === 64), 'Windows editor and exported large-world reference launch smoke passes.', { artifacts: windows.artifacts?.length ?? 0 })
check('V680-STABILITY', stability.status === 'passed' && stability.cycles === 1000, 'A 1,000-cycle deterministic local stability gate completes without non-finite runtime state.', { cycles: stability.cycles })

const failed = checks.filter(item => item.status === 'failed')
const report = { format: 'nova-v6.8.0-product-audit', version: 1, engineVersion: version, generatedAt: new Date().toISOString(), perspectives: ['programmer', 'normal-user', 'determinism', 'race-cancel-fallback', 'large-world', 'low-end', 'localization', 'layout', 'build', 'release'], checks, severity0Open: 0, severity1Open: failed.length, externalGates: { realLowEndHardware: 'pending-external', publisherSigning: 'pending-external', cleanMachineLifecycle: 'pending-external', secondMachineReproducibility: 'pending-external', matchingHostTargets: 'pending-external', independentAccessibilityReview: 'pending-external', soak72Hours: 'pending-external' }, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v6.8.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v6.8.0 product audit passed: ${checks.length} checks.`)
