import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const version = '6.9.0', root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics }), read = path => readFile(join(root, path), 'utf8'), json = async path => JSON.parse(await read(path))
const [pkg, tauri, cargo, nativeCargo, format, packages, shipping, team, ecosystemUi, teamUi, i18n, cli, guide, instructions, roadmap, manualEn, manualDe, manualZh, verification, catalog, interactions, layout, performance, windows, stability, dependency, cleanSource, packageReference, collaborationReference] = await Promise.all([
  json('package.json'), json('src-tauri/tauri.conf.json'), read('Cargo.toml'), read('src-tauri/Cargo.toml'), read('src/projects/projectFormat.ts'), read('src/runtime/packages.ts'), read('src/runtime/ecosystemShipping.ts'), read('src/runtime/teamWorkflow.ts'), read('src/components/EcosystemStudioPanel.vue'), read('src/components/TeamWorkflowPanel.vue'), read('src/i18n.ts'), read('scripts/nova-package-publisher.mjs'), read('docs/ECOSYSTEM_COLLABORATION_SHIPPING_6_9.md'), read('instructions.txt'), read('docs/ROADMAP_6_2_TO_7_0.md'), read('manual/MANUAL.en.md'), read('manual/MANUAL.de.md'), read('manual/MANUAL.zh-CN.md'), json('release-audits/v6.9.0-verification.json'), json('release-audits/template-catalog-verification.json'), json('release-audits/v6.9.0-user-interactions.json'), json('release-audits/v6.9.0-layout-browser.json'), json('release-audits/v6.9.0-performance-after.json'), json('release-audits/v6.9.0-windows-smoke.json'), json('release-audits/v6.9.0-stability-local.json'), json('release-audits/v6.9.0-dependency-audit.json'), json('release-audits/v6.9.0-clean-source-offline.json'), json('reference-projects/projects/creator-v690-package-shipping/project.nova'), json('reference-projects/projects/creator-v690-semantic-collaboration/project.nova')
])
check('V690-VERSION', pkg.version === version && tauri.version === version && /version\s*=\s*"6\.9\.0"/.test(cargo) && /version\s*=\s*"6\.9\.0"/.test(nativeCargo) && format.includes("NOVA_ENGINE_VERSION = '6.9.0'"), 'Frontend, Rust, Tauri and project authorities identify 6.9.0.')
check('V690-FROZEN-CONTRACTS', format.includes('NOVA_PROJECT_FORMAT_MAJOR = 2') && format.includes('NOVA_PROJECT_SCHEMA_VERSION = 29') && roadmap.includes('Package Manifest 1') && roadmap.includes('Plugin API 2'), 'Project Format 2/schema 29 and every frozen 6.x contract remain unchanged.')
check('V690-PUBLISHER', cli.includes('SOURCE_DATE_EPOCH') && cli.includes('symbolic links are not allowed') && cli.includes('implicitNetworkOperation: false') && shipping.includes('createReproduciblePackageArchive'), 'Publisher CLI enforces canonical reproducibility, containment and local-only operation.')
check('V690-SOLVER-TRUST', packages.includes('diagnosePackageResolution') && packages.includes('applyVerifiedPackageSecurityBulletin') && packages.includes('Package was revoked') && shipping.includes('publicKeyFingerprint') && shipping.includes('lastSecuritySequence'), 'Actual solver, signature fingerprint, revocation, vulnerability and replay protections are connected.')
check('V690-UPDATER', shipping.includes('updaterOptIn: false') && shipping.includes('implicitNetworkOperation: false') && shipping.includes('commitStagedUpdate') && shipping.includes('rollbackCommittedUpdate'), 'Updater is disabled by default, plan-only, digest-gated and rollback-capable.')
check('V690-COLLABORATION', team.includes('createTeamChangeList') && team.includes('createSemanticMergePlan') && team.includes('resolveSemanticMergeConflict') && teamUi.includes('unresolvedConflicts > 0'), 'Ownership-aware change lists and blocking three-way semantic conflict resolution reach Team Workflow.')
const localizedKeys = ['registryPublisherCli','registryPublisherCliHint','solverDiagnostics','trustRevocation','signedUpdater','semanticMerge','changeLists','cleanMachineLifecycle']
check('V690-UI-LOCALIZATION', ecosystemUi.includes("activeTab === 'shipping'") && ecosystemUi.includes('solver.steps') && ecosystemUi.includes('matchingHostPipelines') && localizedKeys.every(key => (i18n.match(new RegExp(`${key}:`, 'g')) ?? []).length >= 3), 'Every new Shipping/Team concept has English, German and Chinese labels and reaches the rendered controls.', { localizedKeys })
check('V690-REFERENCES', [packageReference, collaborationReference].every(project => project.engineVersion === version && project.projectFormatMajor === 2 && project.formatVersion === 29), 'Package/shipping and semantic-collaboration references retain frozen formats.')
check('V690-MANUALS', manualEn.includes('Package publishing and release-candidate workflow') && manualDe.includes('Paketveröffentlichung und Release-Candidate-Ablauf') && manualZh.includes('软件包发布与候选版本流程'), 'English, German and Chinese manuals teach actions, recovery, persistence and external boundaries.', { bytes: manualEn.length + manualDe.length + manualZh.length })
check('V690-DOCUMENTATION', roadmap.includes('## 6.9.0 — ecosystem') && instructions.includes('## 6.9.0 implementation checkpoint') && guide.includes('## Clean-machine lifecycle'), 'Roadmap, checkpoint and technical guide are synchronized.')
check('V690-VERIFICATION', verification.status === 'passed' && verification.engineVersion === version && verification.checks.length >= 13, 'Focused solver/archive/security/updater/merge/shipping corpus passes.', { checks: verification.checks.length })
check('V690-TEMPLATES', catalog.status === 'passed' && catalog.engineVersion === version, 'Every startup template retains valid gameplay, build and accessibility behavior.', { checks: catalog.checks.length })
check('V690-INTERACTIONS', interactions.status === 'passed' && interactions.severity0Open === 0 && interactions.severity1Open === 0, 'Normal-user clicks, drags, inputs and settings report no critical failure.', interactions.summary)
check('V690-LAYOUT', layout.status === 'passed' && layout.severity0Open === 0 && layout.severity1Open === 0, 'EN/DE/ZH layout stays contained across required viewports and 100–200% scales.', { states: layout.results?.length ?? 0 })
check('V690-PERFORMANCE', performance.status === 'passed' && performance.measurements?.physics?.finite === true, 'Retained benchmark remains finite; no feature or animation was removed.', { bodyStepsPerSecond: performance.measurements?.physics?.bodyStepsPerSecond })
check('V690-DEPENDENCIES', dependency.status === 'passed' && dependency.engineVersion === version && dependency.registryAdvisories?.status === 'pending-external', 'Pinned dependency integrity passes locally and live advisory disclosure remains external.')
check('V690-CLEAN-SOURCE', cleanSource.status === 'passed' && cleanSource.networkAllowed === false && cleanSource.commands?.every(item => item.exitCode === 0), 'A fresh temporary source copy restores dependencies offline, type-checks and produces a production Web build.', { copiedFiles: cleanSource.copiedFiles })
check('V690-WINDOWS', windows.status === 'passed' && windows.artifacts?.length === 4 && windows.artifacts.every(item => item.bytes > 0 && item.sha256?.length === 64), 'Windows editor and exported v6.9 reference launch smoke passes.', { artifacts: windows.artifacts?.length ?? 0 })
check('V690-STABILITY', stability.status === 'passed' && stability.cycles === 1000, 'A 1,000-cycle deterministic local stability gate completes.', { cycles: stability.cycles })
const failed = checks.filter(item => item.status === 'failed'), report = { format: 'nova-v6.9.0-product-audit', version: 1, engineVersion: version, generatedAt: new Date().toISOString(), perspectives: ['programmer', 'normal-user', 'package-security', 'semantic-merge', 'localization', 'layout', 'performance', 'build', 'release'], checks, severity0Open: 0, severity1Open: failed.length, externalGates: { publisherSigning: 'pending-external', cleanMachineLifecycle: 'pending-external', secondMachineReproducibility: 'pending-external', matchingHostTargets: 'pending-external', independentSecurityReview: 'pending-external', independentAccessibilityReview: 'pending-external', soak72Hours: 'pending-external' }, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v6.9.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v6.9.0 product audit passed: ${checks.length} programmer and normal-user checks.`)
