import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const read = path => readFile(join(root, path), 'utf8'), json = async path => JSON.parse(await read(path))
const [pkg, tauri, cargo, nativeCargo, format, production, protocol, networkProduction, networking, runtime, panel, player, native, exporter, buildSettings, guide, instructions, roadmap, manualEn, manualDe, manualZh, verification, catalog, interactions, layout, before, after, windows, headlessSmoke, stability, dependency, coop, headless] = await Promise.all([
  json('package.json'), json('src-tauri/tauri.conf.json'), read('Cargo.toml'), read('src-tauri/Cargo.toml'), read('src/projects/projectFormat.ts'), read('src/runtime/production.ts'), read('src/runtime/networkProtocol.ts'), read('src/runtime/networkProduction.ts'), read('src/runtime/networking.ts'), read('src/runtime/productionRuntime.ts'), read('src/components/NetworkStudioPanel.vue'), read('src/PlayerApp.vue'), read('src-tauri/src/lib.rs'), read('src/runtime/gameExporter.ts'), read('src/runtime/buildSettings.ts'), read('docs/MULTIPLAYER_PRODUCTION_6_6.md'), read('instructions.txt'), read('docs/ROADMAP_6_2_TO_7_0.md'), read('manual/MANUAL.en.md'), read('manual/MANUAL.de.md'), read('manual/MANUAL.zh-CN.md'), json('release-audits/v6.6.0-verification.json'), json('release-audits/template-catalog-verification.json'), json('release-audits/v6.6.0-user-interactions.json'), json('release-audits/v6.6.0-layout-browser.json'), json('release-audits/v6.5.0-performance-after.json'), json('release-audits/v6.6.0-performance-after.json'), json('release-audits/v6.6.0-windows-smoke.json'), json('release-audits/v6.6.0-headless-smoke.json'), json('release-audits/v6.6.0-stability-local.json'), json('release-audits/v6.6.0-dependency-audit.json'), json('reference-projects/projects/creator-v660-coop-arena/project.nova'), json('reference-projects/projects/creator-v660-headless-authority/project.nova')
])
check('V660-VERSION', pkg.version === '6.6.0' && tauri.version === '6.6.0' && /version\s*=\s*"6\.6\.0"/.test(cargo) && /version\s*=\s*"6\.6\.0"/.test(nativeCargo) && format.includes("NOVA_ENGINE_VERSION = '6.6.0'"), 'Frontend, Rust, Tauri and project authorities identify 6.6.0.')
check('V660-FROZEN-CONTRACTS', format.includes('NOVA_PROJECT_FORMAT_MAJOR = 2') && format.includes('NOVA_PROJECT_SCHEMA_VERSION = 29') && protocol.includes('NOVA_NETWORK_PROTOCOL = 2') && instructions.includes('Graph Format 1'), 'Project Format 2/schema 29, Protocol 2 and all frozen 6.x contracts remain unchanged.')
check('V660-OPTIONAL-PERMISSION', production.includes('enabled: false') && production.includes('permissionGranted: false') && production.includes('autoStart: false') && exporter.includes('packageEnabled(OFFICIAL_NETWORKING_PACKAGE_ID)'), 'Networking stays optional, disabled and permission-gated, with package-absent export exclusion.')
check('V660-ADAPTER-AUTH', networkProduction.includes('transportReviewIssues') && networkProduction.includes('registerReviewedNetworkTransport') && networkProduction.includes('registerNetworkAuthenticationProvider') && buildSettings.includes('network-authentication'), 'Reviewed adapter/authentication registries and pre-build validation are connected.')
check('V660-SECURITY', protocol.includes('NetworkSecurityEnvelope') && networkProduction.includes('NetworkReplayProtectionWindow') && networking.includes('authenticationChecksum') && networking.includes('networkEncryptionGuidance'), 'Bounded envelopes, replay protection, proof verification and encryption guidance run before dispatch.')
check('V660-MULTI-PEER-RELIABILITY', networking.includes('nextSequence(channelId: string, peer') && networking.includes('handshakenPeers') && networking.includes('reliableWindow.track(item.destination'), 'Reliable sequencing is peer/channel-specific and unknown authenticated peers self-recover their lifecycle handshake.')
check('V660-AUTHORITY-INTEREST-SCENE', ['NetworkAuthorityTable', 'entityRelevantToPeer', 'transferNetworkAuthority', 'handoffNetworkScene', 'removePeer'].every(token => networking.includes(token) || networkProduction.includes(token)) && runtime.includes('registerNetworkSceneHandoff'), 'Authority transfer/cleanup, interest filtering and deferred scene handoff reach gameplay runtime.')
check('V660-EDITOR', ['localLobbyDirectoryState', 'ownership', 'replicationDiffs', 'rollbackTimeline', 'buildLaunchPeers'].every(token => panel.includes(token)), 'Network Studio exposes local lobby, ownership, diff/rollback and multi-instance workflows.')
check('V660-NATIVE-SAFETY', native.includes('launch_network_instances') && native.includes('executable.starts_with(&working_directory)') && player.includes('if (!overrides.instanceId) return') && !player.includes('permissionGranted = true'), 'Native launcher canonicalizes bounded build paths and runtime overrides cannot grant permission.')
check('V660-VERIFICATION', verification.status === 'passed' && verification.engineVersion === '6.6.0' && [2, 4, 8].every(count => verification.checks.some(item => item.id === `V660-${count}-PEER-SOAK` && item.status === 'passed')), 'Security/protocol plus actual 2/4/8-process UDP qualification passes.', { checks: verification.checks.length })
check('V660-REFERENCES', coop.engineVersion === '6.6.0' && coop.projectSettings.production.networking.replicatedEntities.length === 2 && headless.projectSettings.build.runtimeMode === 'headless-server' && headless.projectSettings.production.networking.role === 'server', 'Playable co-op and headless authority references retain explicit permissions and correct roles.')
check('V660-MANUALS', [manualEn, manualDe, manualZh].every(text => text.includes('Engine: **6.6.0**')) && manualEn.includes('Production multiplayer workflow') && manualDe.includes('Produktiver Mehrspieler-Ablauf') && manualZh.includes('生产级多人游戏流程'), 'English, German and Chinese manuals teach the production workflow.', { bytes: manualEn.length + manualDe.length + manualZh.length })
check('V660-GUIDANCE', guide.includes('no mandatory account') && guide.includes('Native UDP is unencrypted') && instructions.includes('## 6.6.0 implementation checkpoint') && roadmap.includes('## 6.6.0 — multiplayer production workflow'), 'Roadmap, checkpoint and guide disclose capability and limitations honestly.')
check('V660-TEMPLATES', catalog.status === 'passed' && catalog.engineVersion === '6.6.0', 'All startup templates retain valid gameplay/build/accessibility behavior.', { checks: catalog.checks.length })
check('V660-INTERACTIONS', interactions.status === 'passed' && interactions.severity0Open === 0 && interactions.severity1Open === 0, 'User-style control traversal reports no critical failure.', interactions.summary)
check('V660-LAYOUT', layout.status === 'passed' && layout.severity0Open === 0 && layout.severity1Open === 0, 'EN/DE/ZH layout remains contained through supported sizes/scales.', { states: layout.results.length })
check('V660-PERFORMANCE', before.measurements?.physics?.finite === true && after.status === 'passed' && after.measurements?.physics?.finite === true && after.measurements?.export?.elapsedMs > 0, 'Retained v6.5 baseline and v6.6 low-end benchmark remain finite and complete.', { before: before.measurements?.physics?.bodyStepsPerSecond, after: after.measurements?.physics?.bodyStepsPerSecond })
check('V660-DEPENDENCIES', dependency.status === 'passed' && dependency.engineVersion === '6.6.0', 'Pinned dependency advisory audit has no High/Critical block.')
check('V660-WINDOWS', windows.status === 'passed' && windows.artifacts?.length === 4 && windows.artifacts.every(item => item.bytes > 0 && item.sha256?.length === 64), 'Windows editor, co-op game export and independent launch smoke pass.', { artifacts: windows.artifacts?.length ?? 0 })
check('V660-HEADLESS-EXPORT', headlessSmoke.status === 'passed' && headlessSmoke.export?.runtimeMode === 'headless-server' && headlessSmoke.export?.singleFile === true && headlessSmoke.artifact?.sha256?.length === 64, 'A separate authoritative headless-server executable exports, verifies and remains alive under native smoke.', { bytes: headlessSmoke.artifact?.bytes ?? 0 })
check('V660-STABILITY', stability.status === 'passed' && stability.cycles === 1000, 'A 1,000-cycle deterministic local stability gate completes without non-finite runtime state.', { cycles: stability.cycles })
const failed = checks.filter(item => item.status === 'failed'), report = { format: 'nova-v6.6.0-product-audit', version: 1, engineVersion: '6.6.0', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'user', 'security', 'networking', 'runtime', 'build', 'localization', 'layout', 'performance', 'release'], checks, severity0Open: 0, severity1Open: failed.length, externalGates: { publisherSigning: 'pending-external', cleanMachineLifecycle: 'pending-external', secondMachineReproducibility: 'pending-external', matchingHostTargets: 'pending-external', independentHostileNetworkHardwareAccessibility: 'pending-external', publicRelayNat: 'pending-external', soak72Hours: 'pending-external' }, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v6.6.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v6.6.0 product audit passed: ${checks.length} checks.`)
