import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const read = path => readFile(join(root, path), 'utf8')
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const paths = [
  'package.json', 'Cargo.toml', 'src-tauri/tauri.conf.json', 'instructions.txt',
  'src/runtime/production.ts', 'src/runtime/networkProtocol.ts', 'src/runtime/networking.ts', 'src/runtime/networkReplay.ts', 'src/runtime/productionRuntime.ts', 'src/runtime/GameplayRuntime.ts', 'src/runtime/productionValidation.ts', 'src/runtime/buildSettings.ts',
  'src/editor/scriptApi.ts', 'crates/nova_script/src/lib.rs', 'crates/nova_format/src/lib.rs', 'src/components/NetworkStudioPanel.vue', 'src/components/EditorBottomPanel.vue', 'src/editor/workspaces.ts', 'src/i18n.ts',
  'README.md', 'README.zh-CN.md', 'docs/NETWORKING_REPLAY_5_8.md', 'manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md', 'manual/index.html',
  'scripts/package-release.ps1', 'release-audits/v5.8.0-network-verification.json', 'release-audits/v5.8.0-layout-browser.json'
]
const values = await Promise.all(paths.map(read)), source = Object.fromEntries(paths.map((path, index) => [path, values[index]]))
const pkg = JSON.parse(source['package.json']), tauri = JSON.parse(source['src-tauri/tauri.conf.json']), verification = JSON.parse(source['release-audits/v5.8.0-network-verification.json']), layout = JSON.parse(source['release-audits/v5.8.0-layout-browser.json'])

check('V580-VERSION', pkg.version === '5.8.0' && tauri.version === '5.8.0' && /version\s*=\s*"5\.8\.0"/.test(source['Cargo.toml']), 'Frontend, native and Rust release authorities identify 5.8.0.')
check('V580-COMPATIBILITY', ['Project Format 2/schema 29', 'Rhai API v2', 'Plugin API 2', 'Package Manifest 1', 'Build CLI 1', 'workspace document 3'].every(marker => source['instructions.txt'].includes(marker)) && source['crates/nova_format/src/lib.rs'].includes('CURRENT_ENGINE_VERSION: &str = "5.8.0"'), 'Frozen document, API and package boundaries remain compatible.')
check('V580-ROADMAP', source['instructions.txt'].includes('Implementation status (5.8.0 candidate): complete') && ['two-process localhost', 'packet fuzzing', 'reconnect/late join', 'divergence detection', 'no implicit network'].every(marker => source['instructions.txt'].toLowerCase().includes(marker)), 'Roadmap records completion and every required v5.8 audit target.')
check('V580-PROTOCOL', ['NOVA_NETWORK_PROTOCOL = 2', 'NetworkRateLimiter', 'ReliablePacketWindow', 'DeterministicNetworkSimulator', 'validatePayloadSchema', 'SENSITIVE_KEYS', 'maximumPacketBytes'].every(marker => source['src/runtime/networkProtocol.ts'].includes(marker)), 'Protocol 2 supplies reliable/unreliable bounds, schemas, rates, deterministic simulation and secret exclusion.')
check('V580-RUNTIME', ['LocalLobbyTransport', 'WebSocketTransport', 'NativeUdpTransport', 'acceptsRpc', 'reconcile(', 'rollbackSnapshot', 'lateJoins', 'reliableBuffers', 'bandwidthOutKbps'].every(marker => source['src/runtime/networking.ts'].includes(marker)) && ['replayFixedInput', 'callProductionRpc', 'network.${name}'].every(marker => source['src/runtime/GameplayRuntime.ts'].includes(marker)), 'Local/direct transports, RPC authority, replication, interpolation, prediction, reconciliation and fixed-input rollback are runtime-bound.')
check('V580-REPLAY-SAVE', ['nova-multiplayer-replay', 'compareMultiplayerReplays', 'nova-multiplayer-save', 'checksum mismatch', 'networkDiagnosticCapture'].every(marker => source['src/runtime/networkReplay.ts'].includes(marker)), 'Versioned replay/save documents compare divergence, validate checksums and sanitize diagnostics.')
check('V580-OPTIONAL', ['packageEnabled(OFFICIAL_NETWORKING_PACKAGE_ID)', 'permissionGranted', 'autoStart'].every(marker => source['src/runtime/productionRuntime.ts'].includes(marker)) && source['src/runtime/production.ts'].includes('enabled: false, permissionGranted: false, autoStart: false'), 'Networking remains optional, lazy-loaded, permission-gated and disabled by default.')
check('V580-SCRIPTING', ['network_enabled', 'network_connected', 'network_is_authority', 'network_peer_count', 'network_local_peer', 'network_role', 'network_tick', 'network_rpc'].every(marker => source['src/editor/scriptApi.ts'].includes(marker) && source['crates/nova_script/src/lib.rs'].includes(marker)) && source['src/editor/scriptApi.ts'].includes("['network-rpc']"), 'Rhai API 2 exposes reviewed status/query/RPC bindings and Visual Graph receives matching manifest nodes without raw sockets.')
check('V580-HEADLESS', ['headless-network', 'headless-authority', 'headless-transport', 'native UDP'].every(marker => source['src/runtime/buildSettings.ts'].includes(marker)) && ['NET-PACKAGE-MISSING', 'NET-PERMISSION-DENIED', 'NET-RELIABLE-MISSING', 'NET-RPC-CHANNEL'].every(marker => source['src/runtime/productionValidation.ts'].includes(marker)), 'Headless/server builds and project health fail closed on package, permission, authority, channel and transport errors.')
check('V580-EDITOR', source['src/editor/workspaces.ts'].includes("'networkStudio'") && source['src/components/EditorBottomPanel.vue'].includes('NetworkStudioPanel') && ['session', 'protocol', 'replication', 'simulation', 'diagnostics'].every(marker => source['src/components/NetworkStudioPanel.vue'].includes(`id: '${marker}'`)) && ['requestConfirmation', 'maximumPeers', 'maximumPayloadBytes', 'reconnectMaxAttempts', 'compareMultiplayerReplays', 'captureNetworkDiagnostics'].every(marker => source['src/components/NetworkStudioPanel.vue'].includes(marker)), 'Permanent Network Studio connects every authoring stage, explicit permission prompt, bounds, replay and diagnostics.')
check('V580-I18N', ['networkStudio', 'networkPermission', 'localLobby', 'directConnect', 'reliableOrdered', 'replicationHint', 'lagSimulation', 'replayDivergedAt', 'multiplayerSaveHint', 'packetTimeline'].every(key => (source['src/i18n.ts'].match(new RegExp(`${key}:`, 'g')) ?? []).length >= 3), 'Every new visible workflow is localized in English, German and Chinese.')
check('V580-DOCS', source['README.md'].includes('Version **5.8.0**') && source['README.zh-CN.md'].includes('版本 **5.8.0**') && source['docs/NETWORKING_REPLAY_5_8.md'].includes('No implicit network') && ['manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md'].every(path => source[path].includes('5.8')) && ['en-v58', 'de-v58', 'zh-CN-v58'].every(marker => source['manual/index.html'].includes(marker)), 'README, focused networking guide and all multilingual manuals teach v5.8 workflows and safety.')
check('V580-VERIFY', verification.status === 'passed' && verification.severity0Open === 0 && verification.severity1Open === 0 && verification.checks.some(item => item.id === 'V580-TWO-PROCESS-LOCALHOST' && item.status === 'passed') && verification.checks.some(item => item.id === 'V580-RECONNECT-LATE-JOIN' && item.status === 'passed'), 'Protocol, two-process, fuzz, late-join and divergence qualification passes.', { checks: verification.checks.length })
check('V580-LAYOUT', layout.status === 'passed' && layout.matrix?.length === 12 && layout.matrix.every(item => item.status === 'passed') && layout.severity0Open === 0 && layout.severity1Open === 0, 'EN/DE/ZH browser matrix passes four release viewports.', { matrix: layout.matrix?.length ?? 0 })
check('V580-RELEASE', ['source.zip', 'web.zip', 'windows-x64-portable.exe', 'windows-x64-setup.exe', 'windows-x64.msi', 'reference-projects.zip', 'release-evidence.zip', 'RELEASE_NOTES.md', 'EDIT_LEDGER.md', 'LICENSE.md', 'SHA256SUMS.txt'].every(marker => source['scripts/package-release.ps1'].includes(marker)), 'Generic packager enforces the exact eleven artifacts.')

const failed = checks.filter(item => item.status === 'failed')
const report = { format: 'nova-v5.8.0-product-audit', version: 1, engineVersion: '5.8.0', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'runtime', 'user', 'layout'], checks, severity0Open: 0, severity1Open: failed.length, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v5.8.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v5.8.0 product audit passed: ${checks.length} checks.`)
