import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const read = path => readFile(join(root, path), 'utf8')
const json = async path => JSON.parse(await read(path))
const [pkg, tauri, cargo, nativeCargo, format, geometry, world, physicsTests, body, solver, rope, persistent, canvas, renderingPanel, webgl, renderSettings, renderOptimization, guide, instructions, roadmap, manualEn, manualDe, manualZh, verification, catalog, interactions, layoutReport, performanceBefore, performanceAfter, windows] = await Promise.all([
  json('package.json'), json('src-tauri/tauri.conf.json'), read('Cargo.toml'), read('src-tauri/Cargo.toml'), read('src/projects/projectFormat.ts'), read('src/runtime/physicsGeometry.ts'), read('src/world/World.ts'), read('crates/nova_physics/src/tests.rs'), read('crates/nova_physics/src/body.rs'), read('crates/nova_physics/src/world/legacy.rs'), read('crates/nova_physics/src/rope/mod.rs'), read('crates/nova_physics/src/world/persistent.rs'), read('src/components/WorldCanvas.vue'), read('src/components/RenderingPanel.vue'), read('src/renderer/WebGL2Renderer.ts'), read('src/renderer/renderSettings.ts'), read('src/renderer/renderOptimization.ts'), read('docs/PHYSICS_RENDERER_6_5.md'), read('instructions.txt'), read('docs/ROADMAP_6_2_TO_7_0.md'), read('manual/MANUAL.en.md'), read('manual/MANUAL.de.md'), read('manual/MANUAL.zh-CN.md'), json('release-audits/v6.5.0-verification.json'), json('release-audits/template-catalog-verification.json'), json('release-audits/v6.5.0-user-interactions.json'), json('release-audits/v6.5.0-layout-browser.json'), json('release-audits/v6.4.0-performance-after.json'), json('release-audits/v6.5.0-performance-after.json'), json('release-audits/v6.5.0-windows-smoke.json')
])
check('V650-VERSION', pkg.version === '6.5.0' && tauri.version === '6.5.0' && /version\s*=\s*"6\.5\.0"/.test(cargo) && /version\s*=\s*"6\.5\.0"/.test(nativeCargo) && format.includes("NOVA_ENGINE_VERSION = '6.5.0'"), 'Frontend, native, Rust and project authorities identify 6.5.0.')
check('V650-FROZEN-CONTRACTS', format.includes('NOVA_PROJECT_FORMAT_MAJOR = 2') && format.includes('NOVA_PROJECT_SCHEMA_VERSION = 29') && instructions.includes('Graph Format 1'), 'Project Format 2/schema 29 and all frozen public 6.x contracts remain unchanged.')
check('V650-EXACT-GEOMETRY', geometry.includes('decomposeSimplePolygon') && geometry.includes('MAX_SOLVER_CHILD_SHAPES = 128') && geometry.includes('Dynamic ConcavePolygon is unsupported') && !world.includes('convexEnvelope'), 'Exact compound, bounded static decomposition and fail-closed dynamic concavity replace envelope approximation.')
check('V650-CHILD-IDENTITY', persistent.includes('first_collider') && persistent.includes('second_collider') && world.includes('upsert_collider_shapes') && geometry.includes('collisionMatrix[shape.physicsLayer]'), 'Per-child contact identity and child-specific layer/matrix policy cross the TS/WASM/Rust runtime boundary.')
check('V650-MASS-CCD-CONTACTS', body.includes('parallel_axis') || body.includes('child.offset.length_squared()') && body.includes('maximum_collider_radius') && solver.includes('warm_start_contact') && solver.includes('synchronize_sleep_islands'), 'Compound mass/inertia, rotational CCD, warm starts and deterministic sleep islands are connected.')
check('V650-JOINT-ROPE', rope.includes('joint_axis') && rope.includes('break_torque') && rope.includes('collider_proxy') && physicsTests.includes('prismatic_motor_drives_linear_axis_and_revolute_limits_rotation'), 'Joint motors/limits/break torque and Rope2D third-body compound collision reach solver tests.')
check('V650-PHYSICS-CORPUS', ['force_acceleration_and_torque_follow_newtons_laws', 'perfectly_elastic_head_on_collision_reverses_velocities', 'minimum_scale_shapes_collide_and_keep_analytic_inertia', 'retained_compound_children_have_exact_contact_identity_and_inertia', 'touching_dynamic_bodies_sleep_as_one_island', 'damped_collision_rope_remains_bounded_over_many_steps', 'malformed_numbers_are_sanitized'].every(name => physicsTests.includes(name)), 'Analytical force/impulse/energy, scale, compound, island, rope and non-finite regressions are retained.')
check('V650-AUTHORITATIVE-OVERLAY', canvas.includes('prepareColliderSet') && canvas.includes('colliderOutlines') && canvas.includes('outline.physicsLayer') && canvas.includes('outline.id'), 'Physics debug draws authoritative prepared children, per-child policy/identity and compound bounds.')
check('V650-RENDERER', ['textureUploads', 'shaderCompiles', 'shaderFallbacks', 'contextLosses'].every(name => webgl.includes(name)) && renderingPanel.includes('renderSubsystems') && renderOptimization.includes("'gpu-time'") && renderOptimization.includes("'device-recovery'"), 'Shader, pass, light, particle, texture and context-recovery diagnostics are visible and actionable.')
check('V650-QUALITY-VOLUMES', renderSettings.includes('RenderQualityVolume2D') && renderSettings.includes('priority') && renderSettings.includes('updateActiveRenderQuality') && renderingPanel.includes('qualityVolumes'), 'Bounded, deterministic camera quality volumes are authorable and applied by runtime consumers.')
check('V650-MANUALS', [manualEn, manualDe, manualZh].every(text => text.includes('Engine: **6.5.0**')) && manualEn.includes('Exact compound physics') && manualDe.includes('Exakte Compound-Physik') && manualZh.includes('精确组合体物理'), 'English, German and Chinese teaching manuals cover v6.5 workflows.', { bytes: manualEn.length + manualDe.length + manualZh.length })
check('V650-ROADMAP', instructions.includes('## 6.5.0 implementation checkpoint') && roadmap.includes('## 6.5.0 — production physics') && guide.includes('Exact compound bodies'), 'Implementation follows the authoritative checkpoint and task guide.')
check('V650-VERIFICATION', verification.status === 'passed' && verification.engineVersion === '6.5.0' && verification.severity0Open === 0, 'Exact-geometry, policy, renderer and low-end verification passes.', { checks: verification.checks.length })
check('V650-TEMPLATES', catalog.status === 'passed' && catalog.engineVersion === '6.5.0', 'All startup templates retain valid gameplay, build and accessibility behavior.', { checks: catalog.checks.length })
check('V650-INTERACTIONS', interactions.status === 'passed' && interactions.severity0Open === 0 && interactions.severity1Open === 0, 'User-style interaction traversal reports no critical failure.', interactions.summary)
check('V650-LAYOUT', layoutReport.status === 'passed' && layoutReport.severity0Open === 0 && layoutReport.severity1Open === 0, 'EN/DE/ZH layout remains contained from 1024×640 class windows through 4K and 200% scale.', { states: layoutReport.results.length })
check('V650-PERFORMANCE', performanceBefore.measurements?.physics?.finite === true && performanceAfter.status === 'passed' && performanceAfter.measurements?.physics?.finite === true && performanceAfter.measurements?.export?.elapsedMs > 0, 'The retained v6.4 baseline and final v6.5 low-end benchmark remain finite and complete.', { beforeBodyStepsPerSecond: performanceBefore.measurements?.physics?.bodyStepsPerSecond ?? null, afterBodyStepsPerSecond: performanceAfter.measurements?.physics?.bodyStepsPerSecond ?? null })
check(
  'V650-WINDOWS',
  windows.status === 'passed'
    && windows.artifacts?.length === 4
    && windows.artifacts.every(item => item.bytes > 0 && item.sha256?.length === 64),
  'Windows editor/player build and independent portable-player smoke pass locally.',
  { artifacts: windows.artifacts?.length ?? 0 },
)

const failed = checks.filter(item => item.status === 'failed')
const report = { format: 'nova-v6.5.0-product-audit', version: 1, engineVersion: '6.5.0', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'user', 'compatibility', 'physics', 'renderer', 'performance', 'runtime', 'build', 'localization', 'layout', 'release'], checks, severity0Open: 0, severity1Open: failed.length, externalGates: { publisherSigning: 'pending-external', cleanMachineLifecycle: 'pending-external', secondMachineReproducibility: 'pending-external', matchingHostTargets: 'pending-external', independentHardwareAccessibility: 'pending-external', soak72Hours: 'pending-external' }, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true })
await writeFile(join(root, 'release-audits/v6.5.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v6.5.0 product audit passed: ${checks.length} checks.`)
