import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const read = path => readFile(join(root, path), 'utf8')
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const paths = [
  'package.json', 'Cargo.toml', 'src-tauri/tauri.conf.json', 'instructions.txt', 'crates/nova_format/src/lib.rs',
  'src/runtime/plugins.ts', 'src/runtime/packages.ts', 'src/runtime/extensionEcosystem.ts', 'src/runtime/exportTemplates.ts', 'src/runtime/deliveryPipeline.ts', 'src/runtime/buildSettings.ts', 'src-tauri/src/lib.rs', 'src/visual/graphCatalog.ts',
  'src/components/EcosystemStudioPanel.vue', 'src/components/EditorBottomPanel.vue', 'src/components/BuildSettingsPanel.vue', 'src/editor/workspaces.ts', 'src/i18n.ts',
  'README.md', 'README.zh-CN.md', 'docs/EXTENSIONS_PLATFORM_DELIVERY_5_9.md', 'manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md', 'manual/index.html',
  'scripts/package-release.ps1', 'scripts/verify-release-package.ps1', 'release-audits/v5.9.0-ecosystem-verification.json', 'release-audits/v5.9.0-layout-browser.json'
]
const values = await Promise.all(paths.map(read)), source = Object.fromEntries(paths.map((path, index) => [path, values[index]])), pkg = JSON.parse(source['package.json']), tauri = JSON.parse(source['src-tauri/tauri.conf.json']), verification = JSON.parse(source['release-audits/v5.9.0-ecosystem-verification.json']), layout = JSON.parse(source['release-audits/v5.9.0-layout-browser.json'])

check('V590-VERSION', pkg.version === '5.9.0' && tauri.version === '5.9.0' && /version\s*=\s*"5\.9\.0"/.test(source['Cargo.toml']) && source['crates/nova_format/src/lib.rs'].includes('CURRENT_ENGINE_VERSION: &str = "5.9.0"'), 'Frontend, native, workspace and format authorities identify 5.9.0.')
check('V590-COMPATIBILITY', ['Project Format 2/schema 29', 'Rhai API v2', 'Plugin API 2', 'Package Manifest 1', 'Build CLI 1', 'workspace document 3'].every(marker => source['instructions.txt'].includes(marker)), 'All frozen 5.x contracts remain compatible and additive.')
check('V590-ROADMAP', source['instructions.txt'].includes('Implementation status (5.9.0 candidate): complete') && ['malicious package corpus', 'API matrix', 'unload/reload', 'clean offline install', 'host builds', 'network transparency'].every(marker => source['instructions.txt'].toLowerCase().includes(marker.toLowerCase())), 'The implementation record includes every requested v5.9 audit.')
check('V590-PLUGIN-API', ['docks', 'inspectors', 'importers', 'components', 'graphNodes', 'renderPasses', 'buildSteps', 'templates', 'commands', 'settings'].every(kind => source['src/runtime/plugins.ts'].includes(`kind: '${kind}'`)) && ['invokeContribution', 'reload(pluginId?', 'unload(pluginId', 'isolatedFailures'].every(marker => source['src/runtime/plugins.ts'].includes(marker)), 'Plugin API 2 covers all contribution hosts plus bounded lifecycle isolation.')
check('V590-GRAPH-HOST', source['src/visual/graphCatalog.ts'].includes("contribution.kind === 'graphNodes'") && source['src/visual/graphCatalog.ts'].includes('contribution.entry || contribution.id'), 'Declarative plugin graph nodes enter the production catalog only through API-v2 callables.')
check('V590-NATIVE-ABI', ['NOVA_NATIVE_EXTENSION_ABI_VERSION = 1', "isolation: 'sidecar-process'", 'implicitExecution: false', 'restartLimit', 'heartbeatMs'].every(marker => source['src/runtime/extensionEcosystem.ts'].includes(marker)), 'Native extension ABI 1 is platform-pinned, permission-gated and sidecar-isolated.')
check('V590-PACKAGES', ['PackageWizardDraft', 'publisherSigningRequest', 'verifyPublisherSignature', 'scanPackageCandidate', 'createLocalRegistry', 'importLocalRegistry'].every(marker => source['src/runtime/extensionEcosystem.ts'].includes(marker)) && ['markPublisherPackageVerified', 'verifiedPublisherPackages'].every(marker => source['src/runtime/packages.ts'].includes(marker)), 'Package wizard, canonical Ed25519 verification, certification and local registry are integrated with the trust store.')
check('V590-DELIVERY', ['NOVA_EXPORT_TEMPLATE_FORMAT = 1', 'platformQualification', 'androidGates', 'clean-machine'].every(marker => source['src/runtime/exportTemplates.ts'].includes(marker)) && ['NOVA_CI_MATRIX_VERSION = 1', 'contentCacheKey', 'createDeltaBuild', 'prepareDeployment', 'implicitNetworkOperation: false', 'executableAction: false'].every(marker => source['src/runtime/deliveryPipeline.ts'].includes(marker)), 'Template manager, honest platform gates, CI cache, delta and non-executing connectors are present.')
check('V590-BUILD-BINDING', ['exportTemplateIssues', 'contentCache', 'deltaBuilds', 'deploymentPermissionGranted'].every(marker => source['src/runtime/buildSettings.ts'].includes(marker)) && ['content_cache', 'delta_builds', 'ci_matrix_version', 'implicitNetworkOperation'].every(marker => source['src-tauri/src/lib.rs'].includes(marker)), 'Delivery settings validate in Vue and persist into the native deployment manifest.')
check('V590-EDITOR', source['src/components/EditorBottomPanel.vue'].includes('EcosystemStudioPanel') && source['src/editor/workspaces.ts'].includes("'ecosystem'") && ['extensions', 'package', 'templates', 'delivery', 'audit'].every(tab => source['src/components/EcosystemStudioPanel.vue'].includes(`'${tab}'`)), 'A responsive permanent Ecosystem Studio uses progressive tabs instead of adding Inspector clutter.')
check('V590-I18N', ['ecosystemStudio', 'pluginApiMatrix', 'packageWizard', 'publisherSigning', 'exportTemplateManager', 'deploymentConnectors', 'ecosystemAudit'].every(key => (source['src/i18n.ts'].match(new RegExp(`${key}:`, 'g')) ?? []).length >= 3), 'Every new visible workflow is localized in English, German and Chinese.')
check('V590-DOCS', source['README.md'].includes('Version **5.9.0**') && source['README.zh-CN.md'].includes('版本 **5.9.0**') && source['docs/EXTENSIONS_PLATFORM_DELIVERY_5_9.md'].includes('No implicit execution') && ['manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md'].every(path => source[path].includes('5.9')) && ['en-v59', 'de-v59', 'zh-CN-v59'].every(id => source['manual/index.html'].includes(id)), 'README, focused guide and all multilingual manuals teach the v5.9 workflows and safety boundaries.')
check('V590-VERIFY', verification.status === 'passed' && verification.severity0Open === 0 && verification.severity1Open === 0 && verification.checks.length >= 10, 'Malicious corpus, API, lifecycle, offline, platform, cache/delta and network-transparency verification passes.', { checks: verification.checks.length })
check('V590-LAYOUT', layout.status === 'passed' && layout.matrix?.length === 12 && layout.matrix.every(item => item.status === 'passed') && layout.severity0Open === 0 && layout.severity1Open === 0, 'EN/DE/ZH browser matrix passes four release viewports.', { matrix: layout.matrix?.length ?? 0 })
check('V590-RELEASE', ['source.zip', 'web.zip', 'windows-x64-portable.exe', 'windows-x64-setup.exe', 'windows-x64.msi', 'reference-projects.zip', 'release-evidence.zip', 'RELEASE_NOTES.md', 'EDIT_LEDGER.md', 'LICENSE.md', 'SHA256SUMS.txt'].every(marker => source['scripts/package-release.ps1'].includes(marker)) && source['scripts/verify-release-package.ps1'].includes("$Version -eq '5.9.0'"), 'The generic packager and verifier enforce the exact eleven v5.9 artifacts.')

const failed = checks.filter(item => item.status === 'failed'), report = { format: 'nova-v5.9.0-product-audit', version: 1, engineVersion: '5.9.0', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'runtime', 'user', 'layout'], checks, severity0Open: 0, severity1Open: failed.length, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v5.9.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v5.9.0 product audit passed: ${checks.length} checks.`)
