import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root=dirname(dirname(fileURLToPath(import.meta.url))),checks=[]
const check=(id,passed,detail,metrics={})=>checks.push({id,status:passed?'passed':'failed',detail,metrics})
const files=async(...paths)=>Object.fromEntries(await Promise.all(paths.map(async path=>[path,await readFile(join(root,path),'utf8')])))
const source=await files('package.json','Cargo.toml','src-tauri/Cargo.toml','src-tauri/tauri.conf.json','crates/nova_format/src/lib.rs','src/projects/projectFormat.ts','src-tauri/src/lib.rs','src/visual/graphCodeSync.ts','src/visual/graphCompiler.ts','src/visual/graphCatalog.ts','src/components/VisualGraphEditor.vue','src/components/ScriptStudio.vue','src/components/GraphProductionPanel.vue','src/components/WorldCanvas.vue','src/App.vue','src/assets/AssetDatabase.ts','src/assets/types.ts','instructions.txt','scripts/package-release.ps1','scripts/verify-release-package.ps1')
const [verification,catalog,interactions,layout]=await Promise.all(['v6.0.4-verification.json','template-catalog-verification.json','v6.0.4-user-interactions.json','v6.0.4-layout-browser.json'].map(async name=>JSON.parse(await readFile(join(root,'release-audits',name),'utf8'))))
const pkg=JSON.parse(source['package.json']),tauri=JSON.parse(source['src-tauri/tauri.conf.json'])

check('V604-VERSION',pkg.version==='6.0.4'&&tauri.version==='6.0.4'&&[source['Cargo.toml'],source['src-tauri/Cargo.toml']].every(value=>/version\s*=\s*"6\.0\.4"/.test(value))&&source['crates/nova_format/src/lib.rs'].includes('CURRENT_ENGINE_VERSION: &str = "6.0.4"')&&source['src/projects/projectFormat.ts'].includes("NOVA_ENGINE_VERSION = '6.0.4'"),'Frontend, native, Rust and project authorities identify 6.0.4.')
check('V604-FROZEN-CONTRACTS',source['src/projects/projectFormat.ts'].includes('NOVA_PROJECT_SCHEMA_VERSION = 29')&&source['src/projects/projectFormat.ts'].includes('NOVA_PROJECT_FORMAT_MAJOR = 2'),'Project Format 2/schema 29 remain frozen.')
check('V604-LOCK-SAFE',source['src-tauri/src/lib.rs'].includes('publish_embedded_player')&&source['src-tauri/src/lib.rs'].includes('locked_windows_player_uses_a_versioned_fallback_instead_of_failing')&&source['src-tauri/src/lib.rs'].includes('PermissionDenied'),'Windows publishing is staged, lock-aware and regression-tested without terminating the older player.')
check('V604-BIDIRECTIONAL',source['src/visual/graphCodeSync.ts'].includes('createLinkedRhaiSource')&&source['src/visual/graphCodeSync.ts'].includes('applyLinkedRhaiSource')&&source['src/components/ScriptStudio.vue'].includes('synchronizeLinkedGraphForScript')&&source['src/components/VisualGraphEditor.vue'].includes('synchronizeLinkedScriptsForGraph')&&source['src/components/GraphProductionPanel.vue'].includes('linkScriptToGraph'),'Visual and text editors save through the linked projection in both directions.')
check('V604-SOURCE-PRESERVATION',source['src/visual/graphCatalog.ts'].includes("type: 'code.module'")&&source['src/visual/graphCatalog.ts'].includes("type: 'code.statement'")&&source['src/visual/graphCompiler.ts'].includes('rhaiSourceOverride'),'Custom Rhai has visible, bounded Code-node preservation instead of silent loss.')
check('V604-ASSET-LOAD',source['src/assets/AssetDatabase.ts'].includes("'particleSystem', 'visualScript', 'other'")&&source['src/assets/types.ts'].includes('linkedGraphUuid'),'Visual-graph type and link metadata persist through project loading.')
check('V604-PERFORMANCE',source['src/App.vue'].includes('defineAsyncComponent')&&source['src/components/VisualGraphEditor.vue'].includes('scheduleCompile')&&source['src/components/VisualGraphEditor.vue'].includes('activeNodeIndex')&&source['src/components/WorldCanvas.vue'].includes('sampleInterval')&&source['src/components/WorldCanvas.vue'].includes("performanceProfile==='low-end'"),'Startup, graph, rendering and diagnostics avoid redundant work while retaining runtime behavior.')
check('V604-VERIFICATION',verification.status==='passed'&&verification.engineVersion==='6.0.4'&&verification.checks.every(item=>item.status==='passed'),'Graph round-trip, arbitrary code, performance, lock path and portable export verification passes.',{checks:verification.checks.length})
check('V604-CATALOG',catalog.status==='passed'&&catalog.engineVersion==='6.0.4','All startup templates retain valid gameplay/build/accessibility behavior.',{checks:catalog.checks.length})
check('V604-INTERACTIONS',interactions.status==='passed'&&interactions.severity0Open===0&&interactions.severity1Open===0,'User-style clicks, settings, navigation and localized launcher checks pass.',interactions.summary)
check('V604-LAYOUT',layout.status==='passed'&&layout.severity0Open===0&&layout.severity1Open===0&&layout.matrix.some(item=>item.name.includes('200%')),'EN/DE/ZH layout remains contained from minimum viewport through 200% scale.',{states:layout.matrix.length})
check('V604-RELEASE-CONTRACT',['source.zip','web.zip','windows-x64-portable.exe','windows-x64-setup.exe','windows-x64.msi','reference-projects.zip','release-evidence.zip','RELEASE_NOTES.md','EDIT_LEDGER.md','LICENSE.md','SHA256SUMS.txt'].every(marker=>source['scripts/package-release.ps1'].includes(marker))&&source['scripts/verify-release-package.ps1'].includes('exact mandatory artifact set'),'Exact eleven-artifact/ten-checksum release contract remains enforced.')
check('V604-INSTRUCTIONS',['same-directory staging path','Saving a linked script updates graph','Low-end profile','references:v6.0.4'].every(marker=>`${source['instructions.txt']} ${source['package.json']}`.includes(marker)),'The 6.0.4 specification and release entrypoints are present.')

const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v6.0.4-product-audit',version:1,engineVersion:'6.0.4',generatedAt:new Date().toISOString(),perspectives:['programmer','user','localization','layout','backend','visual-scripting','performance','game-export','release'],checks,severity0Open:0,severity1Open:failed.length,externalGates:{publisherSigning:'pending-external',cleanMachineLifecycle:'pending-external',secondMachineReproducibility:'pending-external',independentHardwareAccessibility:'pending-external',soak72Hours:'pending-external'},status:failed.length?'failed':'passed'}
await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits/v6.0.4-product-audit.json'),`${JSON.stringify(report,null,2)}\n`)
if(failed.length){console.error(failed);process.exit(1)}
console.log(`Nova_A v6.0.4 product audit passed: ${checks.length} checks.`)
