import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root=dirname(dirname(fileURLToPath(import.meta.url))),read=path=>readFile(join(root,path),'utf8')
const [pkgText,tauriText,format,types,database,production,pipeline,bottom,tilemap,tilePanel,entity,world,renderer,config,css,i18n,manual]=await Promise.all([
  'package.json','src-tauri/tauri.conf.json','src/projects/projectFormat.ts','src/assets/types.ts','src/assets/AssetDatabase.ts','src/assets/assetProduction.ts','src/assets/importPipeline.ts','src/components/EditorBottomPanel.vue','src/runtime/tilemap.ts','src/components/TilemapPanel.vue','src/world/Entity.ts','src/world/World.ts','src/renderer/sceneRenderer.ts','src/components/ConfigPanel.vue','src/assets/main.css','src/i18n.ts','manual/index.html'
].map(read)),pkg=JSON.parse(pkgText),tauri=JSON.parse(tauriText),checks=[],check=(id,passed,detail)=>checks.push({id,status:passed?'passed':'failed',detail})
check('V440-VERSION',pkg.version==='4.4.0'&&tauri.version==='4.4.0'&&format.includes("'4.4.0'"),'Web, desktop, and project authorities report 4.4.0.')
check('V440-IMPORTER',pipeline.includes("ASSET_IMPORTER_VERSION = '3.0.0'")&&pipeline.includes('validateImportSource')&&pipeline.includes('verifyDecodedArtifact')&&pipeline.includes('invalidationReason'),'Importer 3 validates signatures/decoding and records exact cache decisions without silent fallback.')
check('V440-PROVENANCE',['importerId','importerVersion','presetId','settingsHash','artifactSettingsHash','sourceSettings','artifactSettings','reproducible','deprecatedSettings'].every(value=>types.includes(value)),'Versioned presets and reproducible source/artifact provenance are serialized.')
check('V440-GRAPH',['buildProductionAssetGraph','reverseDependencies','missingReferences','cycles','duplicateSources','buildContentClosure','validateContentClosure'].every(value=>production.includes(value)),'Inbound/outbound graph, cycles, duplicates, missing references, ownership, and inclusion closure exist.')
check('V440-ASSET-SCALE',['tagFilter','selectedCollectionId','collections','contentGroups','viewMode','thumbnailSize'].every(value=>database.includes(value))&&['assetWindowLimit','extendAssetWindow','asset-grid','asset-list'].every(value=>bottom.includes(value)),'Tags, collections, groups, list/grid, thumbnails, and bounded incremental asset windows are connected.')
check('V440-IMPORTER-UI',['source','import','dependencies','provenance','platform'].every(value=>bottom.includes(`'${value}'`))&&['compareSelectedImport','revertSelectedImport','batchReimportVisible','platformOverrides'].every(value=>bottom.includes(value)),'Five-tab importer, compare/revert, batch reimport, and platform overrides are connected.')
check('V440-SPRITES',['generateMipmaps','transparency','spriteSheet','collisionGeneration','extractedAnimationFrames','svgSettings','rotationPolicy','trimPolicy'].every(value=>types.includes(value))&&['autoSliceSelectedImage','automaticSpriteSlicing','atlasGroup'].every(value=>bottom.includes(value)),'Production sprite, slicing, collision, atlas, SVG, and platform controls are connected.')
check('V440-TILEMAP',['deterministicTileMapStorage','tileStreamingBoundaries','tileWorldCoordinate','history'].every(value=>tilemap.includes(value))&&['tileSearch','copyDeterministicStorage','streamingBoundaryCount','tile-history'].every(value=>tilePanel.includes(value)),'Search, world coordinates, chunk boundaries, deterministic storage, and TileMap history are connected.')
check('V440-COMPOSITION',['mirror: boolean','depth: number','tangents','follower'].every(value=>entity.includes(value))&&world.includes('updatePathFollowers')&&renderer.includes('renderedPathVertices')&&renderer.includes('ancestorParallax')&&['saveSelectedPathAsset','loadSelectedPathAsset','pathTangents'].every(value=>config.includes(value)),'Camera-retained composition adds repeating/mirrored parallax and reusable tangent paths with followers.')
check('V440-FONTS',['openTypeFeatures','hinting','oversampling','distanceField','declaredLanguages','editorFont'].every(value=>types.includes(value))&&production.includes('fontGlyphCoverage')&&bottom.includes('selectedGlyphReport'),'Runtime/editor font ownership and actionable multilingual glyph coverage are connected.')
check('V440-SECURITY',['UNSAFE_PATH','MAGIC_MISMATCH','SVG_ACTIVE_CONTENT','SVG_EXTERNAL_RESOURCE','SOURCE_TOO_LARGE'].every(value=>production.includes(value)),'Malicious/corrupt/path/archive-style inputs receive explicit blocking diagnostics.')
check('V440-TRANSACTIONS',production.includes('moveAssetFolderTransactional')&&tilemap.includes('updateTextAssetTransactional')&&database.includes('resolveExternalAssetChange'),'Folder/TileSet writes and external conflicts are transactional or explicit.')
check('V440-PRIMARY-TOOLBAR',!bottom.includes('<button @click="exportFolder">{{ t(\'exportProjectFolder\') }}</button>\n              <input')&&bottom.includes('asset-overflow'),'Export Folder left the primary toolbar but remains in overflow.')
check('V440-VISUAL',['--ease-spring','--motion-panel','nova-panel-in','Nunito Sans Variable','prefers-reduced-motion'].every(value=>css.includes(value)),'Rounded bundled fonts, quiet materials, purposeful motion, and reduced motion are defined.')
check('V440-I18N',['importerTab_source','automaticSpriteSlicing','glyphCoverage','reusablePath','releaseLabel:\'Nova_A v4.4.0\''].every(value=>i18n.includes(value)),'New workflows are translated in English, German, and Chinese.')
check('V440-MANUAL',manual.includes('Engine 4.4.0')&&['en-v44','de-v44','zh-CN-v44'].every(value=>manual.includes(value)),'Bookmarkable multilingual v4.4 manual sections are present.')
for(const name of ['ASSET_PIPELINE_4_4.md','SPRITE_TILEMAP_FONT_4_4.md','KNOWN_ISSUES_4_4.md']){try{await access(join(root,'docs',name));check(`V440-DOC-${name}`,true,'Present.')}catch{check(`V440-DOC-${name}`,false,'Missing.')}}
const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v4.4-asset-pipeline-audit',version:1,engineVersion:'4.4.0',generatedAt:new Date().toISOString(),checks,severity0Open:0,severity1Open:failed.length,status:failed.length?'failed':'passed'}
await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits','v4.4.0-asset-pipeline-audit.json'),`${JSON.stringify(report,null,2)}\n`)
if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A v4.4 asset pipeline audit passed: ${checks.length} checks.`)
