import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const text = path => readFile(join(root,path),'utf8')
const [pkgSource,tauriSource,cargo,instructions,components,componentRegistry,physics,dynamic,runtime,gameplay,gameFlow,input,scriptApi,ai,palette,inspector,settings,i18n,readme,readmeZh,manualEn,manualDe,manualZh,manualHtml,releaseScript,verificationSource] = await Promise.all([
  'package.json','src-tauri/tauri.conf.json','Cargo.toml','instructions.txt','src/world/components.ts','src/world/componentRegistry.ts','src/store/physics.ts','src/runtime/dynamicObjects.ts','src/runtime/GameplayRuntime.ts','src/runtime/gameplayComponents.ts','src/runtime/gameFlow.ts','src/runtime/input.ts','src/editor/scriptApi.ts','src/runtime/aiTools.ts','src/editor/componentPalette.ts','src/components/GameplayComponentsInspector.vue','src/panels/SettingsPanel.vue','src/i18n.ts','README.md','README.zh-CN.md','manual/MANUAL.en.md','manual/MANUAL.de.md','manual/MANUAL.zh-CN.md','manual/index.html','scripts/package-release.ps1','release-audits/v5.4.0-gameplay-verification.json'
].map(text))
const pkg=JSON.parse(pkgSource),tauri=JSON.parse(tauriSource),verification=JSON.parse(verificationSource)
let layout = null; try { layout=JSON.parse(await text('release-audits/v5.4.0-layout-browser.json')) } catch {}

check('V540-VERSION',pkg.version==='5.4.0'&&tauri.version==='5.4.0'&&/version\s*=\s*"5\.4\.0"/.test(cargo),'Frontend, native and Rust version authorities identify 5.4.0.')
check('V540-ROADMAP',instructions.includes('Implementation status (5.4.0 candidate)')&&instructions.includes('Snake growth, platformer, twin-stick, menu and pooling')&&instructions.includes('stale handles fail explicitly'),'The authoritative roadmap records the complete implementation and audit contract.')
const kinds=['GridMover2D','PlatformController2D','TopDownController2D','Health2D','DamageHitbox2D','Collectible2D','Projectile2D','Spawner2D','Cooldown2D','Lifetime2D','CameraFollow2D']
check('V540-COMPONENTS',kinds.every(kind=>components.includes(`class ${kind}`)&&componentRegistry.includes(`kind: '${kind}'`)&&physics.includes(`'${kind}'`)),'All eleven gameplay components have data classes, stable registry descriptors, persistence factories and normalization.',{kinds})
check('V540-DYNAMIC', ['spawnRuntimePrefab','runtimeHandleGeneration','resolveRuntimeHandle','Stale entity handle rejected','applyTargetMutation','runtimeSceneEntitySnapshots'].every(marker=>dynamic.includes(marker))&&['pendingHandleResolutions','flushDynamicCommands','targetSetComponentEnabled','targetSetUiText','targetAddGroup'].every(marker=>runtime.includes(marker)),'Pending/instance handles, generations, targeted operations and explicit stale failures are wired through the host command boundary.')
check('V540-QUERIES', ['query_tag','query_group','query_component','query_radius','entity_position_x_on','slice(0, 100_000)'].every(marker=>scriptApi.includes(marker)||dynamic.includes(marker))&&scriptApi.includes('at most 256'),'Typed scene queries and snapshot reads declare deterministic hard bounds.')
check('V540-RUNTIME', ['updateGameplayComponents','processGameplayContacts','initializeGameplayEntities'].every(marker=>gameplay.includes(marker))&&['beginGameplayComponents','processGameplayContacts','updateGameplayComponents'].every(marker=>runtime.includes(marker)),'Gameplay initialization, fixed-step update and collision dispatch are connected to live runtime phases.')
check('V540-GAME-FLOW',['gameFlowState','setGamePaused','setRuntimeCheckpoint','restoreRuntimeCheckpoint','setRuntimeScore','setSessionValue'].every(marker=>gameFlow.includes(marker))&&['scene_reload','scene_load','scene_quit','game_pause','checkpoint_set','score_add','session_set'].every(marker=>scriptApi.includes(marker)),'Pause, restart, transition, checkpoint, score/session and quit share API-v2 commands.')
check('V540-INPUT',['InputInteraction','performed','cancelled','contexts','maps','enableMap','disableMap','pushContext','consume','priority','callback'].every(marker=>input.includes(marker))&&['actionBehavior','inputContext','actionMap','controlSchemes','inputMultiTap','callbackFunction'].every(marker=>settings.includes(marker)),'Contexts, maps, schemes, interactions, consumption, priority and callbacks persist and have authoring controls.')
check('V540-AI',['recordGraphTrace','recordGraphError','recordScriptFunction','BehaviorTree.tick','StateMachine.tick'].every(marker=>ai.includes(marker)),'Behavior trees and state machines share graph trace/error/coverage/timing and profiler infrastructure.')
check('V540-AUTHORING',palette.includes("gameplay.has(kind) ? 'Gameplay'")&&kinds.every(kind=>inspector.includes(kind))&&settings.includes('action-advanced-grid'),'Gameplay components and advanced input are reachable from responsive editor authoring surfaces.')
check('V540-I18N',['gridMover2D','platformController2D','health2D','actionBehavior','inputContext','inputMultiTap','callbackFunction'].every(key=>(i18n.match(new RegExp(`${key}:`,'g'))??[]).length>=3),'All new visible controls have English, German and Chinese strings.')
check('V540-DOCS',readme.includes('Version **5.4.0**')&&readmeZh.includes('版本 **5.4.0**')&&[manualEn,manualDe,manualZh].every(source=>source.includes('Nova_A 5.4'))&&['en-v54','de-v54','zh-CN-v54','Nova_A 5.4 Manual'].every(marker=>manualHtml.includes(marker))&&['GAMEPLAY_FRAMEWORK_5_4.md','DYNAMIC_OBJECT_API_5_4.md','INPUT_GAME_FLOW_5_4.md'].every(marker=>readme.includes(marker)),'English/Chinese README and offline EN/DE/ZH manuals teach the v5.4 workflows and link focused guides.')
check('V540-REFERENCES',['gameplay-v54-snake-growth','gameplay-v54-platformer','gameplay-v54-twin-stick','gameplay-v54-menu','gameplay-v54-pooling'].every(id=>verificationSource.includes(id))&&verification.status==='passed','Five gameplay references pass deterministic component/API/static-script verification.',{checks:verification.checks.length})
check('V540-LAYOUT',layout?.status==='passed'&&layout.matrix?.length===12&&layout.matrix.every(item=>item.status==='passed')&&layout.severity0Open===0&&layout.severity1Open===0,'Browser layout qualification passed EN/DE/ZH at four required viewports.',{matrix:layout?.matrix?.length??0})
check('V540-RELEASE',['source.zip','web.zip','windows-x64-portable.exe','windows-x64-setup.exe','windows-x64.msi','reference-projects.zip','release-evidence.zip','RELEASE_NOTES.md','EDIT_LEDGER.md','LICENSE.md','SHA256SUMS.txt'].every(marker=>releaseScript.includes(marker)),'Generic packager enforces the exact eleven-file release contract.')

const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v5.4.0-product-audit',version:1,engineVersion:'5.4.0',generatedAt:new Date().toISOString(),perspectives:['programmer','runtime','user','layout'],checks,severity0Open:0,severity1Open:failed.length,status:failed.length?'failed':'passed'}
await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits/v5.4.0-product-audit.json'),`${JSON.stringify(report,null,2)}\n`)
if(failed.length){console.error(failed);process.exit(1)}
console.log(`Nova_A v5.4.0 product audit passed: ${checks.length} checks.`)
