import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const read = path => readFile(join(root, path), 'utf8')
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const paths = ['package.json', 'Cargo.toml', 'src-tauri/Cargo.toml', 'src-tauri/tauri.conf.json', 'crates/nova_format/src/lib.rs', 'instructions.txt', 'src/runtime/stableContracts.ts', 'src/runtime/creatorLearning.ts', 'src/runtime/creatorQualification.ts', 'src/components/CreatorLearningCenter.vue', 'src/components/CreatorOnboarding.vue', 'src/components/ManageWorkspace.vue', 'src/components/CommandPalette.vue', 'src/components/SceneSideBar.vue', 'src/layout/EditorLayout.vue', 'src/panels/SettingsPanel.vue', 'src/i18n.ts', 'manual/index.html', 'manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md', 'docs/CREATOR_EXPERIENCE_6_0.md', 'docs/STABLE_CONTRACTS_6_0.md', 'docs/PERFORMANCE_ACCESSIBILITY_6_0.md', 'scripts/package-release.ps1', 'scripts/verify-release-package.ps1', 'release-audits/v6.0.0-creator-verification.json', 'release-audits/v6.0.0-layout-browser.json']
const values = await Promise.all(paths.map(read)), source = Object.fromEntries(paths.map((path, index) => [path, values[index]])), pkg = JSON.parse(source['package.json']), tauri = JSON.parse(source['src-tauri/tauri.conf.json']), verification = JSON.parse(source['release-audits/v6.0.0-creator-verification.json']), layout = JSON.parse(source['release-audits/v6.0.0-layout-browser.json'])

check('V600-VERSION', pkg.version === '6.0.0' && tauri.version === '6.0.0' && [source['Cargo.toml'], source['src-tauri/Cargo.toml']].every(value => /version\s*=\s*"6\.0\.0"/.test(value)) && source['crates/nova_format/src/lib.rs'].includes('CURRENT_ENGINE_VERSION: &str = "6.0.0"'), 'Frontend, native and Rust authorities identify v6.0.0.')
check('V600-FREEZE', ['project', 'script', 'graph', 'plugin', 'package', 'build', 'workspace'].every(id => source['src/runtime/stableContracts.ts'].includes(`id: '${id}'`)) && source['src/runtime/stableContracts.ts'].includes('contractMigrationCheck'), 'All seven contracts have a frozen compatibility and fail-closed migration path.')
check('V600-ONBOARDING', source['src/layout/EditorLayout.vue'].includes('CreatorOnboarding') && source['src/components/ManageWorkspace.vue'].includes('CreatorLearningCenter') && source['src/components/CommandPalette.vue'].includes("id: 'creator-learning'"), 'First-run onboarding, task learning and command discovery are integrated.')
check('V600-TEACHING', ['classification', 'purpose', 'prerequisites', 'steps', 'expectedResult', 'persistence', 'undoRecovery', 'mistakes', 'accessibility', 'minimalExample', 'productionExample', 'relatedRhai', 'relatedGraph'].every(value => source['src/runtime/creatorLearning.ts'].includes(value)) && (source['src/runtime/creatorLearning.ts'].match(/task-[a-z]+/g) ?? []).length >= 12, 'The source catalog covers every required lesson field and all twelve complete tasks.')
check('V600-PERFORMANCE', ['hierarchy-10000', 'assets-50000', 'graphs-1000', 'low-end'].every(value => source['src/runtime/creatorQualification.ts'].includes(value)) && source['src/components/SceneSideBar.vue'].includes('const byUuid = new Map'), 'Large-project qualifications and map-backed Hierarchy ancestor lookup are present.')
check('V600-A11Y-I18N', ['en:', 'de:', 'zh:'].every(locale => source['src/runtime/creatorLearning.ts'].includes(locale)) && ['aria-modal', 'aria-labelledby', 'prefers-reduced-motion'].every(marker => source['src/components/CreatorOnboarding.vue'].includes(marker)) && ['creatorLearning', 'performanceProfiles'].every(key => (source['src/i18n.ts'].match(new RegExp(`${key}:`, 'g')) ?? []).length >= 3), 'New UI is trilingual, semantic, keyboard reachable and reduced-motion aware.')
check('V600-MANUAL', source['manual/index.html'].includes('6.0.0 Offline Teaching Manual') && ['NOVA_V6_TEACHING_START', 'en-v60', 'de-v60', 'zh-CN-v60'].every(marker => source['manual/index.html'].includes(marker)) && ['manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md'].every(path => source[path].includes('NOVA_V6_TEACHING_START')), 'HTML and three Markdown manuals contain the generated task-oriented manual and bookmarks.')
check('V600-VERIFICATION', verification.status === 'passed' && verification.severity0Open === 0 && verification.severity1Open === 0 && Object.values(verification.externalGates).every(value => value === 'pending-external'), 'Creator/lifecycle verification passes while every external gate remains honestly pending.', { checks: verification.checks.length })
check('V600-LAYOUT', layout.status === 'passed' && layout.matrix?.length === 12 && layout.matrix.every(item => item.status === 'passed') && layout.severity0Open === 0 && layout.severity1Open === 0, 'EN/DE/ZH browser layout matrix passes four release viewports.', { matrix: layout.matrix?.length ?? 0 })
check('V600-RELEASE', ['source.zip', 'web.zip', 'windows-x64-portable.exe', 'windows-x64-setup.exe', 'windows-x64.msi', 'reference-projects.zip', 'release-evidence.zip', 'RELEASE_NOTES.md', 'EDIT_LEDGER.md', 'LICENSE.md', 'SHA256SUMS.txt'].every(marker => source['scripts/package-release.ps1'].includes(marker)) && source['scripts/verify-release-package.ps1'].includes("$Version -eq '6.0.0'"), 'Generic packaging and independent verification enforce the exact eleven v6 artifacts.')

const failed = checks.filter(item => item.status === 'failed'), report = { format: 'nova-v6.0.0-product-audit', version: 1, engineVersion: '6.0.0', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'creator', 'runtime', 'accessibility', 'localization', 'layout', 'release'], checks, severity0Open: 0, severity1Open: failed.length, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v6.0.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v6.0 product audit passed: ${checks.length} checks.`)
