import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), read = path => readFile(join(root, path), 'utf8')
const checks = [], check = (id, passed, detail) => checks.push({ id, status: passed ? 'passed' : 'failed', detail })
const paths = ['package.json','src-tauri/tauri.conf.json','src/editor/scriptApi.ts','src/editor/scriptLanguage.ts','src/editor/scriptLanguage.worker.ts','src/editor/scriptIndexPersistence.ts','src/runtime/scriptDebug.ts','src/runtime/scriptHotReload.ts','src/runtime/scriptCoverage.ts','src/runtime/testRunner.ts','src/runtime/production.ts','src/runtime/scriptSettings.ts','src/runtime/GameplayRuntime.ts','src/components/ScriptStudio.vue','src/panels/SettingsPanel.vue','src/components/ProjectHealthPanel.vue','crates/nova_script/src/lib.rs','crates/nova_script/examples/nova_script_test.rs','scripts/nova-rhai-language-server.mjs','scripts/nova-cli.mjs','src/i18n.ts','manual/index.html']
const text = Object.fromEntries(await Promise.all(paths.map(async path => [path, await read(path)])))
const pkg = JSON.parse(text['package.json']), tauri = JSON.parse(text['src-tauri/tauri.conf.json'])
check('SCR460-VERSION', pkg.version === '4.6.0' && tauri.version === '4.6.0', 'Web and Tauri authorities report 4.6.0.')
check('SCR460-API-MANIFEST', ['SCRIPT_API_VERSION = 2','ScriptApiV2Manifest','resultConvention','lifetime','threadRule','determinism','permissions','deprecated'].every(value => text['src/editor/scriptApi.ts'].includes(value)), 'API v2 manifest has typed module, result, lifetime, thread, determinism, permission and deprecation metadata.')
check('SCR460-API-DOMAINS', ['scene','object','component','resources','input','physics','animation','ui','audio','save','navigation','logging','timing','tasks','signals','testing'].every(value => text['src/editor/scriptApi.ts'].includes(`'${value}'`)), 'Every required stable API domain is catalogued.')
check('SCR460-SANDBOX', ['register_fn','max_operations','api_version'].every(value => text['crates/nova_script/src/lib.rs'].includes(value)) && !text['crates/nova_script/src/lib.rs'].includes('std::process::Command'), 'Host registration and execution bounds are explicit; no process execution binding is present.')
check('SCR460-LANGUAGE', ['completionDetails','parameterHint','hoverInfo','diagnostics','workspaceSymbols','definition','references','rename','scriptCodeActions','formatScript','moduleAssistance','snapshot','restore'].every(value => text['src/editor/scriptLanguage.ts'].includes(value)), 'Semantic editing and workspace index operations are implemented.')
check('SCR460-LANGUAGE-SAFETY', ['AbortSignal','revision','pending','terminate'].every(value => text['src/editor/scriptLanguage.ts'].includes(value)) && ['TEMP_KEY','checksum','restart-required'].every(value => text['src/editor/scriptIndexPersistence.ts'].includes(value)), 'Cancellation, stale-result prevention, atomic persistence, checksum and restart behavior are implemented.')
check('SCR460-DEBUGGER', ['hitCondition','logMessage','group','selectedFrame','evaluateDebugExpression','normalizeDebugSourceMap','exceptionPolicy','tasks','handleDebugProtocol'].every(value => `${text['src/runtime/scriptDebug.ts']}\n${text['src/components/ScriptStudio.vue']}`.includes(value)), 'Persistent breakpoints, stack/frame, source maps, locals/watches/eval, exceptions, tasks and protocol are connected.')
check('SCR460-REMOTE-SECURITY', ['127.0.0.1','::1','allowExportedPlayers','secureTokenMatch','NOVA-DEBUG-AUTH'].every(value => text['src/runtime/scriptDebug.ts'].includes(value)), 'Remote debug is explicit, authenticated and loopback-only.')
check('SCR460-HOT-RELOAD', ['restart-required','recreate-instances','rollbackSources','prepareHotReload','commitHotReload','rejectHotReload','rollbackHotReload'].every(value => text['src/runtime/scriptHotReload.ts'].includes(value)) && text['src/runtime/GameplayRuntime.ts'].includes('validateModuleSource'), 'Hot reload validates, classifies, commits transactionally and retains rollback.')
check('SCR460-TESTS', ['unit','integration','scene','ui','physics','animation','regression'].every(value => `${text['src/runtime/testRunner.ts']}\n${text['src/runtime/production.ts']}`.includes(value)) && ['tags','changed','shardIndex','AbortSignal','flakyInfrastructure','seed'].every(value => text['src/runtime/testRunner.ts'].includes(value)), 'All categories, selection, sharding, cancellation, deterministic seeds and infrastructure-only retries are represented.')
check('SCR460-CLI', ['junit','json','--coverage-output','--shard-index','--changed','ExitCode::from'].every(value => text['crates/nova_script/examples/nova_script_test.rs'].includes(value)) && text['scripts/nova-cli.mjs'].includes('script-test'), 'Headless CLI exposes reports, coverage, changed selection, sharding and stable process status.')
check('SCR460-COVERAGE', ['lineRate','functionRate','bindingRate','scriptCoverageLcov','missingBindings'].every(value => text['src/runtime/scriptCoverage.ts'].includes(value)), 'Function, line and API binding coverage is connected.')
check('SCR460-STUDIO-LAYOUT', ['project-scripts','code-workspace','studio-inspector','detail-bottom','failedTests','copyHeadlessCommand'].every(value => text['src/components/ScriptStudio.vue'].includes(value)), 'Script Studio has Explorer, Editor, dockable detail and all run scopes.')
check('SCR460-PROJECT-INTEGRATION', ['formatting','lint','indexing','remoteDebug'].every(value => text['src/runtime/scriptSettings.ts'].includes(value)) && ['scriptApiVersion','scriptDebugger','testParallelism','remoteDebugging'].every(value => text['src/panels/SettingsPanel.vue'].includes(value)) && text['src/components/ProjectHealthPanel.vue'].includes('deprecatedUses'), 'Project settings and Project Health expose API/lint/index/debug/test state.')
check('SCR460-EXTERNAL', ['semanticCompletion','signatureHelp','definition','references','rename','formatting','$/cancelRequest','workspace/saveIndex'].every(value => text['scripts/nova-rhai-language-server.mjs'].includes(value)), 'External editor protocol covers language navigation, editing, cancellation and persistence.')
check('SCR460-I18N', ['releaseLabel:\'Nova_A v4.6.0\'','scriptStudio','remoteDebugging','testScope','rollbackHotReload'].every(value => text['src/i18n.ts'].includes(value)), 'The v4.6 workflow labels exist in all locale tables.')
check('SCR460-MANUAL', text['manual/index.html'].includes('Engine 4.6.0') && ['en-v46','de-v46','zh-CN-v46'].every(value => text['manual/index.html'].includes(value)), 'The searchable multilingual manual has bookmarkable v4.6 sections.')
for (const name of ['RHAI_API_V2.md','RHAI_API_V2_MANIFEST.json','RHAI_V1_TO_V2.json','NOVA_RHAI_API_V2_STUBS.rhai','RHAI_DEBUG_PROTOCOL_V2.md','RHAI_HOT_RELOAD_4_6.md','RHAI_TESTING_COVERAGE_4_6.md','RHAI_EXTERNAL_TOOLS_4_6.md','KNOWN_ISSUES_4_6.md']) {
  try { await access(join(root, 'docs', name)); check(`SCR460-DOC-${name}`, true, 'Present.') } catch { check(`SCR460-DOC-${name}`, false, 'Missing.') }
}
for (const slug of ['script-v46-api-contract','script-v46-language-services','script-v46-debugger','script-v46-hot-reload','script-v46-tests-coverage','script-v46-external-tools']) for (const name of ['project.nova','README.md','expected-output.json','test-controls.json']) {
  try { await access(join(root, 'reference-projects', 'projects', slug, name)); check(`SCR460-REF-${slug}-${name}`, true, 'Present.') } catch { check(`SCR460-REF-${slug}-${name}`, false, 'Missing.') }
}
const failed = checks.filter(item => item.status === 'failed'), report = { format: 'nova-v4.6-programming-workflow-audit', version: 1, engineVersion: '4.6.0', generatedAt: new Date().toISOString(), catalog: ['SCR','API','DBG','TST'], checks, severity0Open: 0, severity1Open: failed.length, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits', 'v4.6.0-programming-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v4.6 programming audit passed: ${checks.length} checks.`)
