import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const paths = ['package.json', 'Cargo.toml', 'src-tauri/Cargo.toml', 'src-tauri/tauri.conf.json', 'crates/nova_format/src/lib.rs', 'src/projects/projectFormat.ts', 'src/store/preferences.ts', 'src/assets/main.css', 'src/components/ConfigPanel.vue', 'src/components/EditorBottomPanel.vue', 'src/components/SceneSideBar.vue', 'src/components/WorldCanvas.vue', 'src/components/AnimationPanel.vue', 'src/components/ConnectionBuilder.vue', 'src/components/PresentationPanel.vue', 'src-tauri/src/lib.rs', 'src/runtime/buildSettings.ts', 'scripts/nova-export.mjs', 'scripts/verify-v6.0.2-interactions.mjs', 'scripts/qualify-layout-v6.0.2.mjs', 'instructions.txt', 'scripts/package-release.ps1', 'scripts/verify-release-package.ps1']
const source = Object.fromEntries(await Promise.all(paths.map(async path => [path, await readFile(join(root, path), 'utf8')])))
const [backend, interactions, layout] = await Promise.all(['v6.0.2-backend-export.json', 'v6.0.2-user-interactions.json', 'v6.0.2-layout-browser.json'].map(async name => JSON.parse(await readFile(join(root, 'release-audits', name), 'utf8'))))
const pkg = JSON.parse(source['package.json']), tauri = JSON.parse(source['src-tauri/tauri.conf.json'])

check('V602-VERSION', pkg.version === '6.0.2' && tauri.version === '6.0.2' && [source['Cargo.toml'], source['src-tauri/Cargo.toml']].every(value => /version\s*=\s*"6\.0\.2"/.test(value)) && source['crates/nova_format/src/lib.rs'].includes('CURRENT_ENGINE_VERSION: &str = "6.0.2"') && source['src/projects/projectFormat.ts'].includes("NOVA_ENGINE_VERSION = '6.0.2'"), 'Frontend, native, Rust and project authorities identify v6.0.2.')
check('V602-FROZEN-FORMAT', source['src/projects/projectFormat.ts'].includes('NOVA_PROJECT_SCHEMA_VERSION = 29') && source['src/projects/projectFormat.ts'].includes('NOVA_PROJECT_FORMAT_MAJOR = 2'), 'Project Format 2/schema 29 remain frozen.')
check('V602-LAYOUT-IMPLEMENTATION', source['src/store/preferences.ts'].includes("'xlarge'") && ["data-ui-scale='large'", "data-ui-scale='xlarge'", 'overflow-wrap:', 'anywhere', 'max-width: calc(100vw'].every(marker => source['src/assets/main.css'].includes(marker)), 'Scale tiers, wrapping and viewport-bounded surfaces implement the containment correction.')
check('V602-INTERACTIONS', interactions.status === 'passed' && interactions.summary.registeredControls > 0 && interactions.summary.settingsMutatedAndRestored > 0 && interactions.drags.every(item => item.status !== 'failed'), 'The user-style browser audit inventories controls, executes safe settings and gives every drag family an explicit result or automation/context boundary.', interactions.summary)
check('V602-DRAG-BINDINGS', source['src/components/ConfigPanel.vue'].includes('@mousedown="startResize"') && source['src/components/EditorBottomPanel.vue'].includes('@dragstart="draggedTab = tab.id"') && source['src/components/EditorBottomPanel.vue'].includes('@drop="dropTab(tab.id)"') && source['src/components/SceneSideBar.vue'].includes('@dragstart="startEntityDrag($event, row.entity)"') && source['src/components/WorldCanvas.vue'].includes('@mousedown="onMouseDown"') && source['src/components/AnimationPanel.vue'].includes('beginKeyDrag') && source['src/components/ConnectionBuilder.vue'].includes('@pointerdown') && source['src/components/PresentationPanel.vue'].includes('@pointerdown="beginWaveformEdit"'), 'Pane resizing, tab/entity dragging, canvas manipulation, animation keys, connection drawing and waveform editing retain live event bindings.')
check('V602-LAYOUT', layout.status === 'passed' && layout.severity0Open === 0 && layout.severity1Open === 0 && Array.isArray(layout.matrix) && layout.matrix.some(item => item.name.includes('200%')), 'EN/DE/ZH layout qualification covers the minimum window through 200% UI scale.', { states: Array.isArray(layout.matrix) ? layout.matrix.length : 0 })
check('V602-BACKEND', backend.status === 'passed' && backend.checks.every(item => item.status === 'passed'), 'Backend, template, package and portable export verification passes.', { checks: backend.checks.length })
check('V602-EXPORT-SECURITY', ['MAX_WEB_EXPORT_FILES', 'decode_base64_limited', 'nova-backup-', 'the game output cannot overwrite the running Nova_A editor'].every(marker => source['src-tauri/src/lib.rs'].includes(marker)) && ['MAX_PACKAGE_BYTES', 'NOVAPK2!', 'Unsafe output path', 'dynamicImports'].every(marker => source['scripts/nova-export.mjs'].includes(marker)), 'Native and CLI exporters bound payloads, block unsafe targets, preserve rollback and emit verified embedded packages.')
check('V602-ANDROID', source['src-tauri/src/lib.rs'].includes('"windows" | "linux" | "macos" | "web" | "android"') && source['src/runtime/buildSettings.ts'].includes("settings.target !== 'android'"), 'Android capability, target validation and cross-architecture validation agree.')
check('V602-RELEASE-CONTRACT', ['source.zip', 'web.zip', 'windows-x64-portable.exe', 'windows-x64-setup.exe', 'windows-x64.msi', 'reference-projects.zip', 'release-evidence.zip', 'RELEASE_NOTES.md', 'EDIT_LEDGER.md', 'LICENSE.md', 'SHA256SUMS.txt'].every(marker => source['scripts/package-release.ps1'].includes(marker)) && source['scripts/verify-release-package.ps1'].includes('exact mandatory artifact set'), 'The exact eleven-artifact and ten-checksum contract is retained.')
check('V602-INSTRUCTIONS', ['every registered button', '100% to 200%', 'temporary/backup/rollback', 'one actual Mouse Knockout game executable'].every(marker => source['instructions.txt'].includes(marker)), 'The v6.0.2 specification records interaction, containment, backend, game-output and audit requirements.')

const failed = checks.filter(item => item.status === 'failed')
const report = { format: 'nova-v6.0.2-product-audit', version: 1, engineVersion: '6.0.2', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'user', 'localization', 'layout', 'backend', 'game-export', 'release'], checks, severity0Open: 0, severity1Open: failed.length, externalGates: { publisherSigning: 'pending-external', cleanMachineLifecycle: 'pending-external', secondMachineReproducibility: 'pending-external', independentHardwareAccessibility: 'pending-external', soak72Hours: 'pending-external' }, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true })
await writeFile(join(root, 'release-audits/v6.0.2-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v6.0.2 product audit passed: ${checks.length} checks.`)
