/* 审计 4.7 的动画轨道、曲线、控制器、绑定以及 UI、本地化和可访问性集成。 */
import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root=dirname(dirname(fileURLToPath(import.meta.url))),read=/* 调用 readFile(join(root,path),'utf8') 并返回调用结果。 */ path=>readFile(join(root,path),'utf8'),checks=[],check=/* 调用 checks.push({id,status:passed?'passed':'failed',detail}) 并返回调用结果。 */ (id,passed,detail)=>checks.push({id,status:passed?'passed':'failed',detail})
const paths=['package.json','src-tauri/tauri.conf.json','src/runtime/animation.ts','src/runtime/animationProduction.ts','src/runtime/rigging.ts','src/runtime/gameUi.ts','src/runtime/uiTheme.ts','src/runtime/uiProduction.ts','src/runtime/localization.ts','src/runtime/uiAccessibility.ts','src/runtime/inputModality.ts','src/runtime/presentation.ts','src/components/AnimationPanel.vue','src/components/PresentationPanel.vue','src/components/RuntimeComponentsInspector.vue','src/components/ProjectHealthPanel.vue','src/components/ProfilerPanel.vue','src/components/BuildSettingsPanel.vue','src/i18n.ts']
const text=Object.fromEntries(await Promise.all(paths.map(/* 返回按声明顺序构造的数组 [path,await read(path)]。 */ async path=>[path,await read(path)]))),all=Object.values(text).join('\n'),pkg=JSON.parse(text['package.json']),tauri=JSON.parse(text['src-tauri/tauri.conf.json'])
check('ANM470-VERSION',pkg.version==='4.7.0'&&tauri.version==='4.7.0','Web and Tauri authorities report 4.7.0.')
check('ANM470-TRACKS',['Property','Method','Audio','NestedAnimation','Custom','spriteFrames','events','markers'].every(/* 调用 all.includes(value) 并返回调用结果。 */ value=>all.includes(value)),'Property, event, method, audio, nested, marker, sprite and custom tracks are represented.')
check('ANM470-CURVES',['AnimationInterpolation','reduceAnimationKeys','retimeAnimationClip','sliceAnimationClip','ripple','inTangent','outTangent'].every(/* 调用 all.includes(value) 并返回调用结果。 */ value=>all.includes(value)),'Interpolation, tangent, retime, ripple, key reduction and slicing are connected.')
check('ANM470-CONTROLLER',['layers','parameters','transitions','conditions','blendTree','interruption','runtimeInspection'].every(/* 调用 all.includes(value) 并返回调用结果。 */ value=>all.includes(value)),'Layered state graph, parameters, conditions, blends, interruption and runtime inspection are connected.')
check('ANM470-RIG',['attachments','retargetAliases','retargetPose','ikChains','constraints','deformSkin'].every(/* 调用 all.includes(value) 并返回调用结果。 */ value=>all.includes(value)),'Bones, skins, masks, constraints, IK, attachments and retargeting are connected.')
check('ANM470-IMPORT',['trackMappings','compressionTolerance','preserveEvents','sourceFrameRate','reimportAnimationClip'].every(/* 调用 all.includes(value) 并返回调用结果。 */ value=>all.includes(value)),'Animation import mapping, compression and dependency-safe asset identity are implemented.')
check('UI470-LAYOUT',['layoutMode','anchorMin','breakpoints','safeAreaInsets','clipChildren','scrollVertical','zOrder','componentSource','componentVariant'].every(/* 调用 all.includes(value) 并返回调用结果。 */ value=>all.includes(value)),'Responsive layouts, safe areas, clipping, scrolling, z order and reusable components are exposed.')
check('UI470-PREVIEW',['UI_DEVICE_PRESETS','validateUiForPreset','responsiveValidationPassed','focusTraversal'].every(/* 调用 all.includes(value) 并返回调用结果。 */ value=>all.includes(value)),'Device preview, warnings and focus traversal are connected.')
check('UI470-THEMES',['colors','typography','spacing','radii','states','icons','sounds','animation','compareUiThemes','themeUnusedTokens'].every(/* 调用 text['src/runtime/uiTheme.ts'].includes(value) 并返回调用结果。 */ value=>text['src/runtime/uiTheme.ts'].includes(value)),'Theme token groups, inheritance comparison and unused-token reporting are implemented.')
check('LOC470-WORKFLOW',['exportLocalizationCsv','importLocalizationCsv','exportLocalizationPo','importLocalizationPo','pseudolocalize','Intl.NumberFormat','Intl.DateTimeFormat','NOVA-LOC-BIDI'].every(/* 调用 text['src/runtime/localization.ts'].includes(value) 并返回调用结果。 */ value=>text['src/runtime/localization.ts'].includes(value)),'Localization extraction/table workflows, formatting, pseudolocalization and bidi diagnostics are implemented.')
check('A11Y470-RUNTIME',['accessibilityRole','accessibilityDescription','accessibilityState','readingOrder','screenReaderMetadata','reducedMotion','subtitles','captions'].every(/* 调用 all.includes(value) 并返回调用结果。 */ value=>all.includes(value)),'Semantic metadata, focus, reduced motion and caption hooks are represented.')
check('INPUT470-PROMPTS',['keyboard','mouse','gamepad','touch','gamepadLayout','inputPromptForAction'].every(/* 调用 text['src/runtime/inputModality.ts'].includes(value) 并返回调用结果。 */ value=>text['src/runtime/inputModality.ts'].includes(value)),'Automatic keyboard, mouse, gamepad and touch prompts are implemented.')
check('UI470-INTEGRATION',['animationBudgetMs','uiBudgetMs'].every(/* 调用 text['src/components/ProfilerPanel.vue'].includes(value) 并返回调用结果。 */ value=>text['src/components/ProfilerPanel.vue'].includes(value))&&['localizationAudit','accessibilityAudit'].every(/* 调用 text['src/components/BuildSettingsPanel.vue'].includes(value) 并返回调用结果。 */ value=>text['src/components/BuildSettingsPanel.vue'].includes(value))&&['navigateSelectedHealth','animationIssues','uiIssues'].every(/* 调用 text['src/components/ProjectHealthPanel.vue'].includes(value) 并返回调用结果。 */ value=>text['src/components/ProjectHealthPanel.vue'].includes(value)),'Profiler, Health and Build integration is connected with direct navigation.')
check('UI470-DEPRECATIONS',!text['src/components/PresentationPanel.vue'].includes("<strong>{{ t('presentationStudio') }}</strong><p>")&&!text['src/components/PresentationPanel.vue'].includes('uiAudioSlots'),'Redundant heading and unrelated global UI audio card are removed.')
for(const name of ['ANIMATION_UI_4_7.md','ANIMATION_IMPORT_4_7.md','UI_LOCALIZATION_ACCESSIBILITY_4_7.md']){try{await access(join(root,'docs',name));check(`DOC470-${name}`,true,'Present.')}catch{check(`DOC470-${name}`,false,'Missing.')}}
for(const slug of ['animation-v47-state-machine','animation-v47-rig-sprite','ui-v47-responsive-hud','ui-v47-multilingual-rtl','ui-v47-accessibility'])for(const name of ['project.nova','README.md','expected-output.json','test-controls.json']){try{await access(join(root,'reference-projects','projects',slug,name));check(`REF470-${slug}-${name}`,true,'Present.')}catch{check(`REF470-${slug}-${name}`,false,'Missing.')}}
const failed=checks.filter(/* 比较 item.status 与 'failed'，返回严格相等的判断结果。 */ item=>item.status==='failed'),report={format:'nova-v4.7-animation-ui-audit',version:1,engineVersion:'4.7.0',generatedAt:new Date().toISOString(),catalog:['ANM','UI','LOC','A11Y'],checks,severity0Open:0,severity1Open:failed.length,status:failed.length?'failed':'passed'}
await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits','v4.7.0-animation-ui-audit.json'),`${JSON.stringify(report,null,2)}\n`)
if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A v4.7 animation/UI audit passed: ${checks.length} checks.`)
