import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
const root=dirname(dirname(fileURLToPath(import.meta.url))),checks=[],read=path=>readFile(join(root,path),'utf8'),check=(id,passed,detail,metrics={})=>checks.push({id,status:passed?'passed':'failed',detail,metrics})
const paths=['package.json','Cargo.toml','src-tauri/tauri.conf.json','instructions.txt','src/renderer/materialGraph.ts','src/renderer/materials.ts','src/components/MaterialGraphEditor.vue','src/components/RenderingPanel.vue','src/renderer/renderSettings.ts','src/renderer/WebGL2Renderer.ts','src/renderer/lighting2d.ts','src/renderer/particleGraph.ts','src/runtime/particles.ts','src/renderer/renderOptimization.ts','src/i18n.ts','README.md','README.zh-CN.md','manual/MANUAL.en.md','manual/MANUAL.de.md','manual/MANUAL.zh-CN.md','manual/index.html','scripts/package-release.ps1','release-audits/v5.5.0-rendering-verification.json','release-audits/v5.5.0-layout-browser.json'],sources=await Promise.all(paths.map(read)),source=Object.fromEntries(paths.map((path,index)=>[path,sources[index]])),pkg=JSON.parse(source['package.json']),tauri=JSON.parse(source['src-tauri/tauri.conf.json']),verification=JSON.parse(source['release-audits/v5.5.0-rendering-verification.json']),layout=JSON.parse(source['release-audits/v5.5.0-layout-browser.json'])
check('V550-VERSION',pkg.version==='5.5.0'&&tauri.version==='5.5.0'&&/version\s*=\s*"5\.5\.0"/.test(source['Cargo.toml']),'Frontend, native and Rust authorities identify 5.5.0.')
check('V550-ROADMAP',source['instructions.txt'].includes('Implementation status (5.5.0 candidate): complete')&&source['instructions.txt'].includes('Canvas2D/WebGL2 parity'),'Roadmap records implementation and audit boundaries.')
check('V550-MATERIALS',['MaterialGraphTarget','compileMaterialGraph','normalizeMaterialLayers','materialCapabilityPreview'].every(marker=>source['src/renderer/materialGraph.ts'].includes(marker))&&['selectedInputPins','setInput','nodeColor'].every(marker=>source['src/components/MaterialGraphEditor.vue'].includes(marker)),'Graph authoring, deterministic compilation, layers and capability preview are connected.')
check('V550-RUNTIME-MATERIAL',['resolvedMaterialFragment','canvasMaterialColor','reportMaterialFallback'].every(marker=>source['src/renderer/materials.ts'].includes(marker))&&['u_nova_time','effectsTargetActive','drawPostMaterial'].every(marker=>source['src/renderer/WebGL2Renderer.ts'].includes(marker)),'WebGL2 and Canvas2D material/post paths include isolated fallback.')
check('V550-PARTICLES',['particleGraphValues','effectiveParticleBackend','particleGraphCost'].every(marker=>source['src/renderer/particleGraph.ts'].includes(marker))&&['trailEnabled','noteEvent','gpuRendered'].every(marker=>source['src/runtime/particles.ts'].includes(marker)),'Particle graph, curves-compatible emitter values, events, trails and honest fallback are runtime-bound.')
check('V550-DIAGNOSTICS',['toDataURL','renderRecommendations','importPreviews'].every(marker=>source['src/renderer/renderOptimization.ts'].includes(marker))&&['atlasImportPreview','renderRecommendations','particleEvents'].every(marker=>source['src/components/RenderingPanel.vue'].includes(marker)),'Atlas/import previews, events and render recommendations are reachable.')
check('V550-I18N',['visualMaterialGraph','particleGraph','postProcessPresets','atlasImportPreview'].every(key=>(source['src/i18n.ts'].match(new RegExp(`${key}:`,'g'))??[]).length>=3),'Visible v5.5 controls are localized in EN/DE/ZH.')
check('V550-DOCS',source['README.md'].includes('Version **5.5.0**')&&source['README.zh-CN.md'].includes('版本 **5.5.0**')&&['manual/MANUAL.en.md','manual/MANUAL.de.md','manual/MANUAL.zh-CN.md'].every(path=>source[path].includes('Nova_A 5.5'))&&source['manual/index.html'].includes('en-v55')&&source['manual/index.html'].includes('de-v55')&&source['manual/index.html'].includes('zh-CN-v55'),'README and multilingual manuals teach v5.5 workflows.')
check('V550-VERIFY',verification.status==='passed'&&verification.severity0Open===0&&verification.severity1Open===0,'Runtime/static rendering verification passes.',{checks:verification.checks.length})
check('V550-LAYOUT',layout.status==='passed'&&layout.matrix?.length===12&&layout.matrix.every(item=>item.status==='passed')&&layout.severity0Open===0&&layout.severity1Open===0,'EN/DE/ZH browser matrix passes four viewports.',{matrix:layout.matrix?.length??0})
check('V550-RELEASE',['source.zip','web.zip','windows-x64-portable.exe','windows-x64-setup.exe','windows-x64.msi','reference-projects.zip','release-evidence.zip','RELEASE_NOTES.md','EDIT_LEDGER.md','LICENSE.md','SHA256SUMS.txt'].every(marker=>source['scripts/package-release.ps1'].includes(marker)),'Generic packager enforces exact eleven artifacts.')
const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v5.5.0-product-audit',version:1,engineVersion:'5.5.0',generatedAt:new Date().toISOString(),perspectives:['programmer','runtime','user','layout'],checks,severity0Open:0,severity1Open:failed.length,status:failed.length?'failed':'passed'};await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits/v5.5.0-product-audit.json'),`${JSON.stringify(report,null,2)}\n`);if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A v5.5.0 product audit passed: ${checks.length} checks.`)

