import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const read = path => readFile(join(root, path), 'utf8')
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const paths = ['package.json', 'Cargo.toml', 'src-tauri/Cargo.toml', 'src-tauri/tauri.conf.json', 'crates/nova_format/src/lib.rs', 'src/projects/projectFormat.ts', 'src/projects/templates.ts', 'src/components/ProjectManager.vue', 'src/store/physics.ts', 'src/runtime/input.ts', 'src/runtime/GameplayRuntime.ts', 'src/runtime/gameplayComponents.ts', 'src/runtime/dynamicObjects.ts', 'src/runtime/prefabs.ts', 'src/runtime/sceneInstances.ts', 'src/runtime/replay.ts', 'src/runtime/networkReplay.ts', 'src/renderer/sceneRenderer.ts', 'src/editor/scriptApi.ts', 'crates/nova_script/src/lib.rs', 'crates/nova_wasm/src/lib.rs', 'src/i18n.ts', 'manual/index.html', 'manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md', 'instructions.txt', 'scripts/package-release.ps1', 'scripts/verify-release-package.ps1', 'release-audits/v6.0.1-game-verification.json', 'release-audits/v6.0.1-layout-browser.json']
const values = await Promise.all(paths.map(read)), source = Object.fromEntries(paths.map((path, index) => [path, values[index]]))
const pkg = JSON.parse(source['package.json']), tauri = JSON.parse(source['src-tauri/tauri.conf.json']), verification = JSON.parse(source['release-audits/v6.0.1-game-verification.json']), layout = JSON.parse(source['release-audits/v6.0.1-layout-browser.json'])
check('V601-VERSION', pkg.version === '6.0.1' && tauri.version === '6.0.1' && [source['Cargo.toml'], source['src-tauri/Cargo.toml']].every(value => /version\s*=\s*"6\.0\.1"/.test(value)) && source['crates/nova_format/src/lib.rs'].includes('CURRENT_ENGINE_VERSION: &str = "6.0.1"') && source['src/projects/projectFormat.ts'].includes("NOVA_ENGINE_VERSION = '6.0.1'"), 'Frontend, native, Rust and project authorities identify v6.0.1.')
check('V601-INPUT', ['mouseWorldPosition', 'viewBounds', 'viewportSize'].every(value => source['src/runtime/input.ts'].includes(value) && source['src/runtime/GameplayRuntime.ts'].includes(value)) && ['mouse_world_x', 'mouse_world_y', 'view_min_x', 'view_max_x', 'view_min_y', 'view_max_y'].every(value => source['src/editor/scriptApi.ts'].includes(value) && source['crates/nova_script/src/lib.rs'].includes(value)), 'World pointer and camera bounds are serialized and exposed through matching Rhai documentation/runtime bindings.')
check('V601-REPLAY', ['mouseWorldPosition', 'viewBounds', 'viewportSize'].every(value => source['src/runtime/replay.ts'].includes(value) && source['src/runtime/networkReplay.ts'].includes(value)), 'Replay and network-replay input preserve the new deterministic pointer data with legacy fallbacks.')
check('V601-TEMPLATE', source['src/projects/templates.ts'].includes("id: 'mouse-knockout'") && ['MouseFollower2D', 'KnockoutGameManager', 'Knockout Target.nova-prefab', 'query_group("knockout-target"', 'timer_start("bounds"'].every(value => source['src/projects/templates.ts'].includes(value)) && source['src/runtime/gameplayComponents.ts'].includes("getComponent<MouseFollower2D>('MouseFollower2D')") && source['src/components/ProjectManager.vue'].includes("'mouse-knockout': '✣'"), 'The localized launcher template owns a native fixed-step pointer player, grouped target prefab, timer-bounded manager and UI content.')
check('V601-POINTER-SAFETY', source['src/projects/templates.ts'].includes('maximumSpeed: 40') && source['src/runtime/gameplayComponents.ts'].includes('pointerInsideViewport') && source['src/runtime/dynamicObjects.ts'].includes('if (physicsChanged) physicsState.world.invalidateRuntime()'), 'The starter bounds pointer impulses, stops outside the Game viewport, and avoids rebuilding physics for UI-only mutations.')
check('V601-RUNTIME-SPAWN-BATCHING', source['src/store/physics.ts'].includes('if (select) selectEntities') && source['src/store/physics.ts'].includes('if (invalidateRuntime) physicsState.world.invalidateRuntime()') && source['src/runtime/prefabs.ts'].includes("'', select, invalidateRuntime") && source['src/runtime/sceneInstances.ts'].includes("'', select, invalidateRuntime") && source['src/runtime/GameplayRuntime.ts'].includes('if (spawned) physicsState.world.invalidateRuntime()'), 'Runtime prefabs and scene instances preserve editor selection and batch physics invalidation, preventing first-tick stalls.')
check('V601-WASM-RUNTIME', source['crates/nova_script/src/lib.rs'].includes('use rhai::{Array, Dynamic, Engine, Instant') && source['crates/nova_wasm/src/lib.rs'].includes('install_panic_reporter'), 'Script tracing uses a WebAssembly-safe clock and the bridge surfaces precise panic locations.')
check('V601-SCRIPT-API-COMPATIBILITY', source['crates/nova_format/src/lib.rs'].includes('Some(1 | 2)') && source['crates/nova_format/src/lib.rs'].includes('validates_current_script_api_v2_assets'), 'Project Format 2 accepts current Rhai API v2 assets and legacy API v1 assets, protected by a native regression test.')
check('V601-MANUAL', ['manual/index.html', 'manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md'].every(path => source[path].includes('NOVA_V601_MOUSE_KNOCKOUT_START')) && !source['manual/index.html'].includes("const articles=[...document.querySelectorAll('article[data-lang]')]") && ['en-v601-build', 'de-v601-build', 'zh-CN-v601-build'].every(value => source['manual/index.html'].includes(value)), 'HTML and three Markdown manuals contain a clear trilingual game tutorial and a live article controller.')
check('V601-LOCALIZATION', (source['src/i18n.ts'].match(/template_mouse-knockout_name/g) ?? []).length === 3 && (source['src/i18n.ts'].match(/releaseLabel:'Nova_A v6\.0\.1'/g) ?? []).length === 3, 'Template identity and release labels are complete in English, German and Chinese.')
check('V601-VERIFICATION', verification.status === 'passed' && verification.severity0Open === 0 && verification.severity1Open === 0 && Object.values(verification.externalGates).every(value => value === 'pending-external'), 'Game and manual verification passes while external claims remain pending.', { checks: verification.checks.length })
check('V601-LAYOUT', layout.status === 'passed' && layout.severity0Open === 0 && layout.severity1Open === 0, 'Responsive EN/DE/ZH layout qualification passes.', { matrix: layout.matrix?.length ?? 0 })
check('V601-RELEASE', ['source.zip', 'web.zip', 'windows-x64-portable.exe', 'windows-x64-setup.exe', 'windows-x64.msi', 'reference-projects.zip', 'release-evidence.zip', 'RELEASE_NOTES.md', 'EDIT_LEDGER.md', 'LICENSE.md', 'SHA256SUMS.txt'].every(marker => source['scripts/package-release.ps1'].includes(marker)) && source['scripts/verify-release-package.ps1'].includes('exact mandatory artifact set'), 'Generic packaging and verification retain the exact eleven-artifact contract.')
const failed = checks.filter(item => item.status === 'failed'), report = { format: 'nova-v6.0.1-product-audit', version: 1, engineVersion: '6.0.1', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'player', 'localization', 'physics', 'layout', 'release'], checks, severity0Open: 0, severity1Open: failed.length, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v6.0.1-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v6.0.1 product audit passed: ${checks.length} checks.`)
