import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url))), checks = []
const read = path => readFile(join(root, path), 'utf8')
const check = (id, passed, detail, metrics = {}) => checks.push({ id, status: passed ? 'passed' : 'failed', detail, metrics })
const paths = [
  'package.json', 'Cargo.toml', 'src-tauri/tauri.conf.json', 'instructions.txt',
  'src/world/components.ts', 'src/runtime/navigation2d.ts', 'src/runtime/aiTools.ts', 'src/runtime/worldStreaming.ts', 'src/runtime/tilemap.ts', 'src/runtime/tileSceneRuntime.ts', 'src/runtime/worldGameplay.ts',
  'src/components/WorldToolsPanel.vue', 'src/components/TilemapPanel.vue', 'src/components/EditorBottomPanel.vue', 'src/editor/workspaces.ts', 'src/i18n.ts',
  'README.md', 'README.zh-CN.md', 'docs/WORLDS_NAVIGATION_AI_5_7.md', 'manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md', 'manual/index.html',
  'scripts/package-release.ps1', 'release-audits/v5.7.0-world-verification.json', 'release-audits/v5.7.0-layout-browser.json'
]
const sources = await Promise.all(paths.map(read)), source = Object.fromEntries(paths.map((path, index) => [path, sources[index]])), pkg = JSON.parse(source['package.json']), tauri = JSON.parse(source['src-tauri/tauri.conf.json']), verification = JSON.parse(source['release-audits/v5.7.0-world-verification.json']), layout = JSON.parse(source['release-audits/v5.7.0-layout-browser.json'])

check('V570-VERSION', pkg.version === '5.7.0' && tauri.version === '5.7.0' && /version\s*=\s*"5\.7\.0"/.test(source['Cargo.toml']), 'Frontend, native and Rust authorities identify 5.7.0.')
check('V570-COMPATIBILITY', source['README.md'].includes('Project Format 2/schema 29') && source['instructions.txt'].includes('Project Format 2/schema 29') && ['Rhai API v2', 'Plugin API 2', 'Package Manifest 1', 'Build CLI 1', 'workspace document 3'].every(marker => source['instructions.txt'].includes(marker)), 'Frozen project and public API boundaries remain documented.')
check('V570-ROADMAP', source['instructions.txt'].includes('Implementation status (5.7.0 candidate): complete') && ['10,000-agent', 'streamed save/reload', 'impossible path', 'bake cancellation', 'deterministic tile storage'].every(marker => source['instructions.txt'].toLowerCase().replaceAll('-', ' ').includes(marker.replaceAll('-', ' '))), 'Roadmap records completion and every required audit fixture.')
check('V570-NAVIGATION', ['HierarchicalAStar', 'clusterSize', 'links:', 'costAreas:', 'maximumAvoidanceNeighbors'].every(marker => source['src/world/components.ts'].includes(marker)) && ['MAX_NAVIGATION_AGENTS = 10_000', 'MAX_NAVIGATION_REPATHS_PER_TICK', 'spatialCellSize', 'hierarchicalAStar', 'navigationCostMultiplier', 'requestNavigationBake', 'cancelNavigationBake'].every(marker => source['src/runtime/navigation2d.ts'].includes(marker)), 'Hierarchical/grid paths, dynamic rebaking, links, costs, spatial avoidance and bounded cancellable baking are runtime bound.')
check('V570-AI', ['UtilitySelector', 'BlackboardCondition', 'SetBlackboard', 'Perception', 'BehaviorPerceptionSensor', 'MAX_AI_AGENTS = 10_000', 'MAX_AI_TICKS_PER_FRAME', 'aiDebugState', 'blackboardSnapshot'].every(marker => source['src/runtime/aiTools.ts'].includes(marker)) && ['visualDebug', 'utilityScores', 'blackboardOverrides'].every(marker => source['src/components/WorldToolsPanel.vue'].includes(marker) || source['src/world/components.ts'].includes(marker)), 'Behavior trees, blackboards, perception, utility scoring, deterministic scheduling and visual diagnostics are connected.')
check('V570-STREAMING', ['dependencies', 'prefetchDistance', 'cachePolicy', 'saveStateKey'].every(marker => source['src/world/components.ts'].includes(marker)) && ['dependencyClosure', 'captureStreamCellState', 'restoreStreamCellState', 'exportWorldStreamingHandoffs', 'importWorldStreamingHandoffs', 'peakMemoryMb'].every(marker => source['src/runtime/worldStreaming.ts'].includes(marker)) && ['originShiftThreshold', 'originShiftCount', 'lastOriginShift'].every(marker => source['src/runtime/worldGameplay.ts'].includes(marker)), 'World composition connects dependencies, preloading, cache policy, memory budgets, origin shifts and streamed save handoff.')
check('V570-TILEMAP', ['sceneAsset', 'prefabAsset', 'terrainRulesAsset', 'brushPresetAsset', 'deterministicTileMapStorage', 'requestTileMapBake', 'cancelTileMapBake'].every(marker => source['src/runtime/tilemap.ts'].includes(marker)) && ['MAX_ACTIVE_TILE_PLACEMENTS', 'instantiateSceneAsset', 'instantiatePrefab', 'streamingRadius'].every(marker => source['src/runtime/tileSceneRuntime.ts'].includes(marker)) && ['tileBakeState', 'cancelTileMapBake'].every(marker => source['src/components/TilemapPanel.vue'].includes(marker)), 'Tile rules, procedural brushes, scene/prefab tiles, streaming previews and cancellable deterministic background baking are connected.')
check('V570-REACHABILITY', source['src/editor/workspaces.ts'].includes("'worldProduction'") && source['src/components/EditorBottomPanel.vue'].includes("estate.bottomPanelTab === 'worldProduction'") && source['src/components/EditorBottomPanel.vue'].includes('WorldToolsPanel'), 'World Studio is a permanent, workspace-restorable bottom-panel destination.')
check('V570-I18N', ['worldStudio', 'bakeNavigation', 'activeAgents', 'avoidanceNeighbors', 'visualDebug', 'utilityScores', 'prefetchDistance', 'cachePolicy', 'saveStateKey', 'dependencies'].every(key => (source['src/i18n.ts'].match(new RegExp(`${key}:`, 'g')) ?? []).length >= 3), 'Every new visible production control is localized in EN/DE/ZH.')
check('V570-DOCS', source['README.md'].includes('Version **5.7.0**') && source['README.zh-CN.md'].includes('版本 **5.7.0**') && source['docs/WORLDS_NAVIGATION_AI_5_7.md'].includes('10,000') && ['manual/MANUAL.en.md', 'manual/MANUAL.de.md', 'manual/MANUAL.zh-CN.md'].every(path => source[path].includes('5.7')) && ['en-v57', 'de-v57', 'zh-CN-v57'].every(marker => source['manual/index.html'].includes(marker)), 'README, focused guide and all multilingual manuals teach v5.7 workflows.')
check('V570-VERIFY', verification.status === 'passed' && verification.severity0Open === 0 && verification.severity1Open === 0, 'World behavior verification passes.', { checks: verification.checks.length })
check('V570-LAYOUT', layout.status === 'passed' && layout.matrix?.length === 12 && layout.matrix.every(item => item.status === 'passed') && layout.severity0Open === 0 && layout.severity1Open === 0, 'EN/DE/ZH browser matrix passes four release viewports.', { matrix: layout.matrix?.length ?? 0 })
check('V570-RELEASE', ['source.zip', 'web.zip', 'windows-x64-portable.exe', 'windows-x64-setup.exe', 'windows-x64.msi', 'reference-projects.zip', 'release-evidence.zip', 'RELEASE_NOTES.md', 'EDIT_LEDGER.md', 'LICENSE.md', 'SHA256SUMS.txt'].every(marker => source['scripts/package-release.ps1'].includes(marker)), 'Generic packager enforces the exact eleven artifacts.')

const failed = checks.filter(item => item.status === 'failed'), report = { format: 'nova-v5.7.0-product-audit', version: 1, engineVersion: '5.7.0', generatedAt: new Date().toISOString(), perspectives: ['programmer', 'runtime', 'user', 'layout'], checks, severity0Open: 0, severity1Open: failed.length, status: failed.length ? 'failed' : 'passed' }
await mkdir(join(root, 'release-audits'), { recursive: true }); await writeFile(join(root, 'release-audits/v5.7.0-product-audit.json'), `${JSON.stringify(report, null, 2)}\n`)
if (failed.length) { console.error(failed); process.exit(1) }
console.log(`Nova_A v5.7.0 product audit passed: ${checks.length} checks.`)
