/** 按源码位置归类版本功能清单；静态清单不代表各功能已完成运行验证。 */
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFile, writeFile, mkdtemp, rm } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath, pathToFileURL } from 'node:url'
import ts from 'typescript'
import { build } from 'vite'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const escape = /* 调用 String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ') 并返回调用结果。 */ value => String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ')
const category = /** 按路径所属层次区分原生宿主、引擎、运行时、编辑器、样本和构建工具。 */ path => path.startsWith('src-tauri/') ? 'Native desktop host'
  : path.startsWith('crates/') ? 'Rust engine core'
    : path.startsWith('src/runtime/') ? 'Shared gameplay/runtime services'
      : path.startsWith('src/world/') ? 'World model and Rust bridge'
        : path.startsWith('src/visual/') ? 'Visual scripting compiler and model'
          : path.startsWith('src/projects/') ? 'Project format, sessions and templates'
            : path.startsWith('src/') ? 'Editor/player frontend and state'
              : path.startsWith('reference-projects/') || path.startsWith('tests/') || path.startsWith('templates/') ? 'Reference/fixture/template input'
                : path.startsWith('scripts/') || path.startsWith('.github/') ? 'Build and audit tooling' : 'Build configuration/entry assets'
const tracked = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], { cwd: root, encoding: 'utf8' }).split('\0')
const paths = [...new Set(tracked.filter(/** 选择代码、配置和入口文件，排除文档目录。 */ path => (/\.(?:ts|vue|rs|[cm]?js|json|ps1|rhai|css|html|toml|ya?ml)$/.test(path) || ['.node-version','.npmrc','.gitignore','.gitattributes'].includes(path)) && !/^(?:docs|reports|release-audits|releases|godot-master|dist|node_modules|target|\.cache)\//.test(path)))].sort()
const inventory = []
for (const path of paths) {
  const source = await readFile(join(root, path), 'utf8')
  const script = path.endsWith('.vue') ? [...source.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)].map(/* 返回 match[1] 的当前值。 */ match => match[1]).join('\n') : source
  const exports = [], imports = []
  if (/\.(?:ts|vue|[cm]?js)$/.test(path)) {
    const ast = ts.createSourceFile(path, script, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
    for (const node of ast.statements) {
      if ((ts.isImportDeclaration(node) || ts.isExportDeclaration(node)) && node.moduleSpecifier && ts.isStringLiteral(node.moduleSpecifier)) imports.push(node.moduleSpecifier.text)
      if (node.modifiers?.some(/* 比较 modifier.kind 与 ts.SyntaxKind.ExportKeyword，返回严格相等的判断结果。 */ modifier => modifier.kind === ts.SyntaxKind.ExportKeyword)) {
        if (ts.isVariableStatement(node)) for (const item of node.declarationList.declarations) exports.push(item.name.getText(ast))
        else if (node.name) exports.push(node.name.getText(ast))
      }
    }
  } else if (path.endsWith('.rs')) {
    for (const match of source.matchAll(/^\s*pub(?:\([^)]*\))?\s+(?:async\s+)?(?:fn|struct|enum|trait|type|const|mod)\s+(\w+)/gm)) exports.push(match[1])
  } else if (path.endsWith('.rhai')) {
    for (const match of source.matchAll(/^\s*fn\s+(\w+)/gm)) exports.push(match[1])
  }
  inventory.push({ path, category: category(path), lines: source.split('\n').length, sha256: createHash('sha256').update(source).digest('hex'), declaredSymbols: exports, imports, reviewLevel: 'source-inventoried; see audit reports for semantic/runtime evidence' })
}
await writeFile(join(root, 'docs/SOURCE_INVENTORY_26_30.json'), JSON.stringify({ format: 'nova-source-inventory', version: 1, limitation: 'All listed files were read and indexed by this script. That is not a line-by-line semantic review or a passing test.', files: inventory }, null, 2) + '\n')
const sourceLines = ['# Nova_A 26.30 source map', '', 'Generated by `node scripts/inventory-v26.30.mjs`. This is a source index, not a claim that every line or possible behavior has been audited. Full symbol/import/hash details are in [the JSON index](SOURCE_INVENTORY_26_30.json).', '',
  '## Working code and supporting files', '',
  '`src/main.ts` → `App.vue` → ProjectManager/EditorLayout is the editor. `src/player.ts` and `PlayerApp.vue` are the player entries. `src/store/physics.ts` owns authoring snapshots/history and scene state; `src/runtime/GameplayRuntime.ts` orchestrates lifecycle, input, scripts, animation, physics and commands. `src/world/World.ts` sends retained-world data through `nova_wasm`. Rust core lives under `crates/`; Tauri commands, filesystem and desktop hosting live under `src-tauri/`.', '',
  'There is no conventional HTTP application backend. Much of gameplay and rendering runs in TypeScript in both editor preview and player; Rust is not the sole game runtime. The crate graph is `nova_wasm` → `nova_runtime`/`nova_script`/`nova_format`, with runtime → physics → math.', '',
  '`node_modules/`, `target/`, `src-tauri/target/`, `dist/`, `nova_core/pkg/` and `release-audits/` are generated dependencies/build/evidence. They are not the files to edit to fix the engine. `reference-projects/` and `tests/` contain authored examples and fixtures; `scripts/` contains build, verification and historical release wrappers. Historical Markdown reports are documentation, not active engine implementations. No files are removed merely because they look like base files.', '',
  '| Family | Files | Lines |', '|---|---:|---:|']
for (const family of [...new Set(inventory.map(/* 返回 item.category 的当前值。 */ item => item.category))]) {
  const files = inventory.filter(/* 比较 item.category 与 family，返回严格相等的判断结果。 */ item => item.category === family)
  sourceLines.push(`| ${family} | ${files.length} | ${files.reduce(/* 计算表达式 sum + file.lines 并返回结果，沿用操作数的原有类型规则。 */ (sum, file) => sum + file.lines, 0)} |`)
}
sourceLines.push('', '## File-by-file index', '', '| Source | Role | Lines | Public declarations |', '|---|---|---:|---:|')
for (const item of inventory) sourceLines.push(`| [${item.path}](../${item.path}) | ${item.category} | ${item.lines} | ${item.declaredSymbols.length} |`)
await writeFile(join(root, 'docs/SOURCE_MAP_26_30.md'), sourceLines.join('\n') + '\n')

const compiled = await mkdtemp(join(tmpdir(), 'nova-2630-catalog-'))
globalThis.localStorage ??= { /* 返回固定值 null。 */ getItem() { return null }, /** 无持久化的存储替身：清单发现过程中不写入用户设置。 */ setItem() {}, /** 无持久化的存储替身：清单发现过程中不删除用户设置。 */ removeItem() {} }
try {
  await build({ configFile: false, root, logLevel: 'error', ssr: { noExternal: true }, build: { ssr: true, outDir: compiled, emptyOutDir: false, rollupOptions: {
    input: { platform: join(root, 'src/runtime/stableCreatorPlatform.ts'), components: join(root, 'src/world/componentRegistry.ts'), graph: join(root, 'src/visual/graphCatalog.ts') },
    output: { entryFileNames: '[name].mjs', chunkFileNames: 'chunks/[name]-[hash].mjs' }
  } } })
  const load = /* 调用 import(pathToFileURL(join(compiled, `${name}.mjs`)).href) 并返回调用结果。 */ name => import(pathToFileURL(join(compiled, `${name}.mjs`)).href)
  const [platform, components, graph] = await Promise.all(['platform', 'components', 'graph'].map(load))
  await writeFile(join(root, 'docs/EDIT_ROUTE_INVENTORY_26_30.json'), JSON.stringify({format:'nova-declared-edit-routes',release:'26.30',scope:'Current readiness declarations only; statuses are catalog assertions, never executed evidence.',operations:platform.CREATOR_PLATFORM_READINESS},null,2)+'\n')
  const api = JSON.parse(await readFile(join(root, 'docs/RHAI_API_V2_MANIFEST.json'), 'utf8'))
  const lines = ['# Nova_A 26.30 feature inventory', '',
    `Current source catalogs declare **${platform.CREATOR_PLATFORM_READINESS.length} public operations**, **${components.STABLE_COMPONENTS.length} component kinds**, **${api.entries.length} Rhai API entries**, and **${graph.GRAPH_NODE_CATALOG.length} core/API graph node definitions**. Dynamic routine/package nodes are additional. This inventory does not assert that all declarations work in all usages.`, '',
    'The operation routes below are implementation claims from the readiness catalog. Their presence is useful for tracing ownership, but is not new runtime evidence. See [the current audit](ISSUE_CLOSURE_26_30.md) and per-subsystem reports for reproduced failures, corrections and checks actually run. In particular, a graph-node definition does not prove that arbitrary source syntax converts into it.', '',
    '## Every registered public operation', '', '| ID | Workspace / panel | Feature | Binding | Validation | Undo | Persistence | Runtime/export | Test route |', '|---|---|---|---|---|---|---|---|---|']
  for (const item of platform.CREATOR_PLATFORM_READINESS) {
    const cell = /* 调用 escape(`${item.dimensions[key].status}: ${item.dimensions[key].source} (${item.dimensions[key].route})`) 并返回调用结果。 */ key => escape(`${item.dimensions[key].status}: ${item.dimensions[key].source} (${item.dimensions[key].route})`)
    lines.push(`| ${item.id} | ${escape(item.workspace)} / ${escape(item.panel)} | ${escape(item.feature)} | ${cell('binding')} | ${cell('validation')} | ${cell('undo')} | ${cell('persistence')} | ${cell('runtimeExport')} | ${cell('tests')} |`)
  }
  lines.push('', '## Every registered component', '', '| Kind | Description |', '|---|---|')
  for (const item of components.STABLE_COMPONENTS) lines.push(`| ${escape(item.kind)} | ${escape(item.description ?? item.summary ?? JSON.stringify(item))} |`)
  lines.push('', '## Every registered Rhai API entry', '', '| Identity | Signature | Behavior |', '|---|---|---|')
  for (const item of api.entries) lines.push(`| ${escape(item.id)} | ${escape(item.signature)} | ${escape(item.detail)} |`)
  lines.push('', '## Every core/API graph node', '', '| Type | Category | Behavior |', '|---|---|---|')
  for (const item of graph.GRAPH_NODE_CATALOG) lines.push(`| ${escape(item.type)} | ${escape(item.category)} | ${escape(item.description)} |`)
  lines.push('', '## Templates and non-catalog behavior', '', 'See [the retained 26.20 template catalog](TEMPLATE_LIBRARY_26_20.md) for additional starters and actual verification limits. The source map inventories declarations outside the public operation catalog; those declarations include internal helpers and must not all be counted as user features. The retained 26.20 renderer/palette additions and retained behavioral boundaries are documented in COMPETITIVE_REVIEW_26_30.md. These catalogs are inventories, not claims of passing every possible usage.', '')
  await writeFile(join(root, 'docs/FEATURE_INVENTORY_26_30.md'), lines.join('\n'))
  console.log(`Indexed ${inventory.length} source/config/fixture files and ${platform.CREATOR_PLATFORM_READINESS.length} public operations.`)
} finally {
  await rm(compiled, { recursive: true, force: true })
}
