/** 网络多进程测试辅助端：使用本机 UDP 适配器和父进程消息驱动实际网络运行时。 */
import {createSocket} from 'node:dgram'
import {createHmac,createHash} from 'node:crypto'
import {readFile} from 'node:fs/promises'
import {openMediaAuditModules} from './lib/mediaAudit16.mjs'
const [peerId,portText,hostText,sessionName]=process.argv.slice(2),port=+portText,hostPort=+hostText,role=peerId==='host'?'host':'client';
Object.defineProperty(globalThis,'navigator',{configurable:true,value:{platform:'Win32',hardwareConcurrency:4,userAgent:'Nova 26.18 process audit'}});globalThis.window={setTimeout,clearTimeout,setInterval,clearInterval,/** 无窗口事件的环境替身，本辅助进程不注册浏览器事件。 */ addEventListener(){},/** 对应无窗口环境的空移除操作。 */ removeEventListener(){}};globalThis.localStorage={/* 返回固定值 null。 */ getItem(){return null},/** 无持久化的存储替身，不写入用户设置。 */ setItem(){},/** 无持久化的存储替身，不删除用户设置。 */ removeItem(){}};
const networkingWindow=globalThis.window;process.send?.({type:'startup',phase:'bundle production modules'});
const opened=await openMediaAuditModules({repository:process.cwd(),bases:[process.cwd()]},{p:'runtime/production',n:'runtime/networking',a:'runtime/networkProduction',b:'world/BoxEntity',i:'runtime/networkInput'});globalThis.window=networkingWindow;const {p,n,a,b,i}=opened.modules;process.send?.({type:'startup',phase:'initialize real UDP peer'});
const uuid='18181818-0000-4000-8000-000000000001',body=new b.BoxEntity(1,{x:role==='host'?12:-999,y:0},{x:1,y:1},uuid),definition={entityUuid:uuid,authority:'owner',properties:['transform','velocity'],ownerPeerId:'host',interpolate:false,predict:false,alwaysRelevant:true,interestRadius:100,sceneUuid:''};
p.resetProductionSettings();p.loadProductionSettings({networking:{enabled:true,permissionGranted:true,sessionMode:'direct',role,sessionName,playerName:peerId,transportAdapterId:'audit.local-udp18',maxPeers:8,snapshotRate:30,rollbackFrames:30,reconnect:false,lateJoin:true,bandwidthKbps:1000000,maximumMessagesPerSecond:10000,maximumPendingReliable:512,reliableRetryMs:50,reliableMaximumAttempts:24,allowAuthorityTransfer:true,authentication:{mode:'hook',providerId:'audit.local-auth18',requireVerifiedPeers:true},replicatedEntities:[definition],simulation:{enabled:true,latencyMs:7,jitterMs:3,lossPercent:2,duplicatePercent:5,reorderPercent:5,seed:port}}});
const proof=/* 调用 createHmac('sha256','disposable-local-fixture-'+sessionName).update(JSON.stringify(context)).digest('hex') 并返回调用结果。 */ context=>createHmac('sha256','disposable-local-fixture-'+sessionName).update(JSON.stringify(context)).digest('hex');const unregisterAuth=a.registerNetworkAuthenticationProvider({id:'audit.local-auth18',label:'Local test proof (not a shipped provider)',createProof:proof,verifyProof:/* 比较 value 与 proof(context)，返回严格相等的判断结果。 */ (context,value)=>value===proof(context)});n.networkingState.localPeerId=peerId;
let activeSocket=null,sendCount=0,receiveCount=0,closed=0,lastHello=null;
const unregister=a.registerReviewedNetworkTransport({review:{id:'audit.local-udp18',label:'Disposable localhost audit adapter',version:'1.0.0',publisher:'Local audit fixture',sha256:createHash('sha256').update(await readFile(new URL(import.meta.url))).digest('hex'),reviewedBy:'Whitelist',permissions:['network.client','network.listen'],encrypted:false,documentationUrl:'https://example.invalid/audit-only',securityUrl:'https://example.invalid/audit-only'},/** 为每次连接创建独立 UDP 套接字和路由表，返回可连接、发送及关闭的适配器。 */ create(){const socket=createSocket('udp4'),routes=new Map();let opened=false;return{kind:'adapter',/** 监听数据与错误，在回环地址绑定端口后通知连接就绪。 */ async connect(message,state){socket.on('message',/** 读取收到的数据及源地址，尝试更新发送方路由，然后交给运行时处理。 */ (bytes,r)=>{receiveCount++;const source=bytes.toString(),endpoint=r.address+':'+r.port;try{const v=JSON.parse(source);if(typeof v.sender==='string')routes.set(v.sender,endpoint)}catch{}message(source,endpoint)});socket.on('error',/* 调用 state(e.message) 并返回调用结果。 */ e=>state(e.message));await new Promise(/** 等待回环端口绑定成功，绑定错误则拒绝等待。 */ (resolve,reject)=>{socket.once('error',reject);socket.bind(port,'127.0.0.1',/** 记录已打开及活动套接字，移除绑定错误监听并完成等待。 */ ()=>{opened=true;activeSocket=socket;socket.off('error',reject);resolve()})});state('connected')},/** 仅在套接字打开且目标有效时发送；保存握手样本，按路由选择回环端口并等待结果。 */ async send(source,target=''){if(!opened||role==='host'&&!target)return;sendCount++;const packet=JSON.parse(source);if(packet.kind==='hello')lastHello=source;const route=routes.get(target)||target,match=/^127\.0\.0\.1:(\d+)$/.exec(route),destination=match?+match[1]:hostPort;await new Promise(/* 调用 socket.send(Buffer.from(source),destination,'127.0.0.1',e=>e?reject(e):resolve()) 并返回调用结果。 */ (resolve,reject)=>socket.send(Buffer.from(source),destination,'127.0.0.1',/* 根据 e 的真假，分别返回 reject(e) 或 resolve()。 */ e=>e?reject(e):resolve()))},/** 只关闭已打开套接字，累计关闭次数并清理当前活动套接字引用。 */ async close(){if(!opened)return;opened=false;closed++;await new Promise(/* 调用 socket.close(resolve) 并返回调用结果。 */ resolve=>socket.close(resolve));if(activeSocket===socket)activeSocket=null}}}});
await n.startNetworking();n.updateNetworking([body],0,i.emptyNetworkInput());const loop=setInterval(/* 调用 n.updateNetworking([body],1/60,i.emptyNetworkInput()) 并返回调用结果。 */ ()=>n.updateNetworking([body],1/60,i.emptyNetworkInput()),16);
const state=/** 收集实体位置、收发与关闭计数以及深拷贝网络状态和运行时快照。 */ ()=>({peerId,position:body.transform.position.x,sendCount,receiveCount,closed,network:JSON.parse(JSON.stringify(n.networkingState)),runtime:n.networkRuntimeSnapshot()});
let commands=Promise.resolve();process.on('message',/** 将父进程指令串入同一异步队列，回传结果或堆栈错误，防止操作交错。 */ message=>{commands=commands.then(/** 执行查询、移动、权限移交、断连重连、旧握手重放或停止；停止时释放循环、注册项和运行时。 */ async()=>{let value;if(message.type==='state')value=state();if(message.type==='move'){body.transform.position.x=message.x;value=state()}if(message.type==='transfer')value=n.transferNetworkAuthority(uuid,message.peer);if(message.type==='disconnect'){await n.stopNetworking();value=state()}if(message.type==='reconnect'){await n.startNetworking();value=state()}if(message.type==='oldHello'){if(lastHello&&activeSocket)await new Promise(/* 调用 activeSocket.send(Buffer.from(message.source||lastHello),hostPort,'127.0.0.1',resolve) 并返回调用结果。 */ resolve=>activeSocket.send(Buffer.from(message.source||lastHello),hostPort,'127.0.0.1',resolve));value=lastHello}if(message.type==='stop'){clearInterval(loop);await n.stopNetworking();unregister();unregisterAuth();value=state();process.send?.({id:message.id,value});await opened.close();process.exit(0)}process.send?.({id:message.id,value})}).catch(/* 调用 process.send?.({id:message.id,error:error.stack}) 并返回调用结果。 */ error=>process.send?.({id:message.id,error:error.stack}))});process.send?.({type:'ready',value:state()});
