import {createSocket} from 'node:dgram'
import {createHmac,createHash} from 'node:crypto'
import {readFile} from 'node:fs/promises'
import {openMediaAuditModules} from './lib/mediaAudit16.mjs'
const [peerId,portText,hostText,sessionName]=process.argv.slice(2),port=+portText,hostPort=+hostText,role=peerId==='host'?'host':'client';
Object.defineProperty(globalThis,'navigator',{configurable:true,value:{platform:'Win32',hardwareConcurrency:4,userAgent:'Nova 26.18 process audit'}});globalThis.window={setTimeout,clearTimeout,setInterval,clearInterval,addEventListener(){},removeEventListener(){}};globalThis.localStorage={getItem(){return null},setItem(){},removeItem(){}};
const networkingWindow=globalThis.window;process.send?.({type:'startup',phase:'bundle production modules'});
const opened=await openMediaAuditModules({repository:process.cwd(),bases:[process.cwd()]},{p:'runtime/production',n:'runtime/networking',a:'runtime/networkProduction',b:'world/BoxEntity',i:'runtime/networkInput'});globalThis.window=networkingWindow;const {p,n,a,b,i}=opened.modules;process.send?.({type:'startup',phase:'initialize real UDP peer'});
const uuid='18181818-0000-4000-8000-000000000001',body=new b.BoxEntity(1,{x:role==='host'?12:-999,y:0},{x:1,y:1},uuid),definition={entityUuid:uuid,authority:'owner',properties:['transform','velocity'],ownerPeerId:'host',interpolate:false,predict:false,alwaysRelevant:true,interestRadius:100,sceneUuid:''};
p.resetProductionSettings();p.loadProductionSettings({networking:{enabled:true,permissionGranted:true,sessionMode:'direct',role,sessionName,playerName:peerId,transportAdapterId:'audit.local-udp18',maxPeers:8,snapshotRate:30,rollbackFrames:30,reconnect:false,lateJoin:true,bandwidthKbps:1000000,maximumMessagesPerSecond:10000,maximumPendingReliable:512,reliableRetryMs:50,reliableMaximumAttempts:24,allowAuthorityTransfer:true,authentication:{mode:'hook',providerId:'audit.local-auth18',requireVerifiedPeers:true},replicatedEntities:[definition],simulation:{enabled:true,latencyMs:7,jitterMs:3,lossPercent:2,duplicatePercent:5,reorderPercent:5,seed:port}}});
const proof=context=>createHmac('sha256','disposable-local-fixture-'+sessionName).update(JSON.stringify(context)).digest('hex');const unregisterAuth=a.registerNetworkAuthenticationProvider({id:'audit.local-auth18',label:'Local test proof (not a shipped provider)',createProof:proof,verifyProof:(context,value)=>value===proof(context)});n.networkingState.localPeerId=peerId;
let activeSocket=null,sendCount=0,receiveCount=0,closed=0,lastHello=null;
const unregister=a.registerReviewedNetworkTransport({review:{id:'audit.local-udp18',label:'Disposable localhost audit adapter',version:'1.0.0',publisher:'Local audit fixture',sha256:createHash('sha256').update(await readFile(new URL(import.meta.url))).digest('hex'),reviewedBy:'Whitelist',permissions:['network.client','network.listen'],encrypted:false,documentationUrl:'https://example.invalid/audit-only',securityUrl:'https://example.invalid/audit-only'},create(){const socket=createSocket('udp4'),routes=new Map();let opened=false;return{kind:'adapter',async connect(message,state){socket.on('message',(bytes,r)=>{receiveCount++;const source=bytes.toString(),endpoint=r.address+':'+r.port;try{const v=JSON.parse(source);if(typeof v.sender==='string')routes.set(v.sender,endpoint)}catch{}message(source,endpoint)});socket.on('error',e=>state(e.message));await new Promise((resolve,reject)=>{socket.once('error',reject);socket.bind(port,'127.0.0.1',()=>{opened=true;activeSocket=socket;socket.off('error',reject);resolve()})});state('connected')},async send(source,target=''){if(!opened||role==='host'&&!target)return;sendCount++;const packet=JSON.parse(source);if(packet.kind==='hello')lastHello=source;const route=routes.get(target)||target,match=/^127\.0\.0\.1:(\d+)$/.exec(route),destination=match?+match[1]:hostPort;await new Promise((resolve,reject)=>socket.send(Buffer.from(source),destination,'127.0.0.1',e=>e?reject(e):resolve()))},async close(){if(!opened)return;opened=false;closed++;await new Promise(resolve=>socket.close(resolve));if(activeSocket===socket)activeSocket=null}}}});
await n.startNetworking();n.updateNetworking([body],0,i.emptyNetworkInput());const loop=setInterval(()=>n.updateNetworking([body],1/60,i.emptyNetworkInput()),16);
const state=()=>({peerId,position:body.transform.position.x,sendCount,receiveCount,closed,network:JSON.parse(JSON.stringify(n.networkingState)),runtime:n.networkRuntimeSnapshot()});
let commands=Promise.resolve();process.on('message',message=>{commands=commands.then(async()=>{let value;if(message.type==='state')value=state();if(message.type==='move'){body.transform.position.x=message.x;value=state()}if(message.type==='transfer')value=n.transferNetworkAuthority(uuid,message.peer);if(message.type==='disconnect'){await n.stopNetworking();value=state()}if(message.type==='reconnect'){await n.startNetworking();value=state()}if(message.type==='oldHello'){if(lastHello&&activeSocket)await new Promise(resolve=>activeSocket.send(Buffer.from(message.source||lastHello),hostPort,'127.0.0.1',resolve));value=lastHello}if(message.type==='stop'){clearInterval(loop);await n.stopNetworking();unregister();unregisterAuth();value=state();process.send?.({id:message.id,value});await opened.close();process.exit(0)}process.send?.({id:message.id,value})}).catch(error=>process.send?.({id:message.id,error:error.stack}))});process.send?.({type:'ready',value:state()});
