/** 按配色依次运行对应版本的完整面板布局矩阵，并汇总图形状态和检查结果。 */
import assert from 'node:assert/strict'
import {spawn} from 'node:child_process'
import {readFile,writeFile} from 'node:fs/promises'
const palettes=['cloud-blue','meadow-cream','blush-berry','midnight-blue','night-garden'],children=[]
assert.equal(JSON.parse(await readFile('package.json','utf8')).version,'26.20.0')
for(const palette of palettes){const startedAt=Date.now();await new Promise(/** 使用指定配色、版本、视口和缩放设置启动面板检查；启动失败或非零退出使本项失败。 */ (done,reject)=>{const child=spawn(process.execPath,['scripts/qualify-panels-v26.20.mjs'],{cwd:process.cwd(),stdio:'inherit',windowsHide:true,env:{...process.env,NOVA_LAYOUT_PREFLIGHT:'0',NOVA_LAYOUT_SMOKE:'0',NOVA_LAYOUT_PALETTE:palette,NOVA_LAYOUT_ENGINE_VERSION:'26.20.0',NOVA_LAYOUT_REQUIRED_VIEWPORTS:'1024x640,1366x768,1920x1080',NOVA_LAYOUT_REQUIRED_SCALES:'1,1.5,2'}});child.on('error',reject);child.on('exit',/* 根据 code===0 的真假，分别返回 done() 或 reject(Error(palette+' panel matrix failed: '+code))。 */ code=>code===0?done():reject(Error(palette+' panel matrix failed: '+code))) });const report=JSON.parse(await readFile('release-audits/v26.20-panels-'+palette+'.json','utf8'));assert.equal(report.status,'passed');assert.equal(report.preflight,false);assert.equal(report.palette,palette);assert.ok(Date.parse(report.generatedAt)>=startedAt-1000);assert.ok(report.results.length>=1000);assert.equal(report.matrix.length,27);assert.ok([...report.results,...report.matrix].every(/* 比较 x.status 与 'passed'，返回严格相等的判断结果。 */ x=>x.status==='passed'));children.push({palette,report})}
const reports=children.map(/* 返回 x.report 的当前值。 */ x=>x.report),report={format:'nova-v26.20-layout-qualification',version:1,release:'26.20',engineVersion:'26.20.0',generatedAt:new Date().toISOString(),status:'passed',languages:['en','de','zh'],palettes,browser:reports[0].browser,graphics:children.map(/** 把配色标识与该轮实际图形环境信息合并。 */ ({palette,report})=>({palette,...report.graphics})),matrix:children.flatMap(/* 调用 report.matrix.map(x=>({...x,palette})) 并返回调用结果。 */ ({palette,report})=>report.matrix.map(/** 给测量结果附加所属配色，避免跨轮结果混淆。 */ x=>({...x,palette}))),results:reports.flatMap(/* 返回 r.results 的当前值。 */ r=>r.results),screenshots:children.flatMap(/* 调用 report.screenshots.map(x=>({...x,name:palette+'/'+x.name})) 并返回调用结果。 */ ({palette,report})=>report.screenshots.map(/** 为检查名称加配色前缀，保留原始检查数据。 */ x=>({...x,name:palette+'/'+x.name}))),stableControls:reports[0].stableControls,requiredTextResults:reports.flatMap(/* 返回 r.requiredTextResults 的当前值。 */ r=>r.requiredTextResults),consoleErrors:reports.flatMap(/* 返回 r.consoleErrors 的当前值。 */ r=>r.consoleErrors),severity0Open:0,severity1Open:0,children,scope:'Programmer-driven visible DOM panel layout across five palettes, three languages, three viewport sizes and three UI scales; original animations enabled. Browser-default GPU capability is recorded for each palette; this layout audit does not measure FPS. Separate user-input audits test real palette selection. External assistive technology and unvisited conditional dialogs remain unqualified.'}
await writeFile('release-audits/v26.20-layout-browser.json',JSON.stringify(report,null,2)+'\n')
