import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createServer } from 'vite'

const root=dirname(dirname(fileURLToPath(import.meta.url))),output=join(root,'release-audits'),generatedAt=new Date().toISOString()
class MemoryStorage{values=new Map();getItem(key){return this.values.get(key)??null}setItem(key,value){this.values.set(key,String(value))}removeItem(key){this.values.delete(key)}clear(){this.values.clear()}key(index){return [...this.values.keys()][index]??null}get length(){return this.values.size}}
globalThis.localStorage??=new MemoryStorage();globalThis.window??={setTimeout,clearTimeout,addEventListener(){},removeEventListener(){}};globalThis.location??={search:''}
const nativeSetTimeout=globalThis.setTimeout;globalThis.setTimeout=(callback,delay,...args)=>nativeSetTimeout(callback,delay===60_000?300_000:delay,...args)
await mkdir(output,{recursive:true});const server=await createServer({root,appType:'custom',logLevel:'silent',server:{middlewareMode:true}}),checks=[]
const check=(id,passed,detail)=>checks.push({id,status:passed?'passed':'failed',detail})
try{
  for(const path of ['/src/world/components.ts','/src/world/Entity.ts','/src/world/geometry.ts','/src/world/hierarchy.ts','/src/world/Connection.ts','/src/assets/AssetDatabase.ts','/src/runtime/tilemap.ts','/src/runtime/physicsProduction.ts','/src/runtime/physicsMonitor.ts','/src/world/BoxEntity.ts','/src/world/CircleEntity.ts','/src/world/TriangleEntity.ts','/src/world/World.ts']){await server.ssrLoadModule(path);console.log(`warmed ${path}`)}
  const {authoring,sceneAuthoring,store,prefabs,hierarchy,data,assets,components,toRaw}=await server.ssrLoadModule('/scripts/v4.3-verifier-entry.ts')
  console.log('loaded v4.3 verifier module graph')
  const {physicsState,sceneManager}=store
  const reset=()=>{physicsState.world.entities.splice(0);physicsState.world.connections.splice(0);physicsState.world.resetId();store.selectEntities([],'replace')}
  for(const [source,current,expected] of [['10+5*2',0,20],['(current+2)/4',10,3],['pi*2',0,Math.PI*2],['1/0',0,null],['window.alert(1)',0,null]])check(`EXPR-${source}`,Object.is(sceneAuthoring.evaluateNumericExpression(source,current),expected),`${source} evaluates safely to ${expected}.`)
  reset();const parent=authoring.createAuthoringObject('Rectangle',{x:4,y:5},false),child=authoring.createAuthoringObject('Circle',{x:7,y:8},false);hierarchy.setParent(child,parent.uuid,physicsState.world.entities,true);parent.tags=['gameplay'];parent.groups=['Actors'];parent.namedLayer='World';parent.ownership='Scene';parent.runtimePersistence='SaveGame'
  const stableIds=[parent.uuid,child.uuid,...parent.components.map(component=>component.uuid)],roundTrip=store.getSceneJSON();check('IDENTITY-ROUNDTRIP',store.loadProject(roundTrip)&&stableIds.every(id=>store.getSceneJSON().includes(id)),'Entity/component identities and authoring metadata survive project round trip.')
  const deterministic=data.canonicalProjectText(JSON.parse(store.getSceneJSON()));check('SCENE-NOOP',deterministic===data.canonicalProjectText(JSON.parse(deterministic)),'Scene no-op save is byte-identical.')
  const entityValidation=sceneAuthoring.validateSceneAuthoring(physicsState.world.entities);check('ENTITY-VALIDATION',entityValidation.length===0,'Valid hierarchy and component graph has no authoring errors.')
  const inherited=sceneManager.create('Inherited');check('SCENE-INHERIT',sceneManager.setInheritance(inherited.uuid,sceneManager.activeSceneUuid)&&!sceneManager.setInheritance(sceneManager.activeSceneUuid,inherited.uuid),'Scene inheritance accepts a valid edge and rejects a cycle.');const multiSceneSource=store.getSceneJSON()
  reset();const base=authoring.createAuthoringObject('Rectangle',{x:0,y:0},false),nested=authoring.createAuthoringObject('Circle',{x:1,y:0},false);hierarchy.setParent(nested,base.uuid,physicsState.world.entities,true);const reference=prefabs.createPrefabFromEntities([base.id],'Authoring Base');check('PREFAB-CREATE',Boolean(reference&&base.prefabAsset===reference),'Prefab creation retains stable source mapping and ownership.');base.transform.position.x=2;const variant=prefabs.createPrefabVariantFromInstance(base,'Authoring Variant');check('PREFAB-VARIANT',Boolean(variant&&variant!==reference&&base.prefabLayers.length),'Variant retains its base layer and receives a new source.');check('PREFAB-CONFLICTS',prefabs.prefabConflictReport(base).every(item=>['error','warning','info'].includes(item.severity)),'Prefab conflict report is explicit and bounded.')
  const variantProjectSource=store.getSceneJSON(),prefabGuid=assets.assetGuid(reference),prefabBefore=assets.readTextAsset(reference),faultAfterWrite=prefabGuid?assets.updateTextAssetTransactional(prefabGuid,`${prefabBefore}\n`,'after-write'):false,faultAfterVerify=prefabGuid?assets.updateTextAssetTransactional(prefabGuid,`${prefabBefore}\n`,'after-verify'):false;check('PREFAB-WRITE-RECOVERY',!faultAfterWrite&&!faultAfterVerify&&assets.readTextAsset(reference)===prefabBefore,'Injected interruptions after prefab write and verification restore the exact prior source.')
  const beforeReplace=physicsState.world.entities.length,loose=authoring.createAuthoringObject('Empty',{x:3,y:3},false);hierarchy.setParent(loose,base.uuid,physicsState.world.entities,true);const replaced=prefabs.replaceEntitiesWithPrefab([base.id],reference);check('PREFAB-SAFE-REPLACE',replaced.length>0&&physicsState.world.entities.length<=beforeReplace+2&&!physicsState.world.entities.some(entity=>entity.parentUuid&&!physicsState.world.entities.some(parent=>parent.uuid===entity.parentUuid)),'Safe replacement leaves no orphan hierarchy references.')
  reset();const nestedLeaf=authoring.createAuthoringObject('Circle',{x:1,y:0},false),nestedLeafReference=prefabs.createPrefabFromEntities([nestedLeaf.id],'Nested Leaf'),nestedRoot=authoring.createAuthoringObject('Empty',{x:0,y:0},false);hierarchy.setParent(nestedLeaf,nestedRoot.uuid,physicsState.world.entities,true);const nestedRootReference=prefabs.createPrefabFromEntities([nestedRoot.id],'Nested Root'),nestedProjectSource=store.getSceneJSON();check('PREFAB-NESTED',Boolean(nestedLeafReference&&nestedRootReference&&nestedLeaf.prefabLayers.some(layer=>layer.asset===nestedLeafReference)),'A parent prefab retains the nested child prefab source layer.')
  reset();const lifecycleSource=authoring.createAuthoringObject('Rectangle',{x:0,y:0},false),lifecycleReference=prefabs.createPrefabFromEntities([lifecycleSource.id],'Lifecycle Source');reset();store.clearEditorHistory('prefab-lifecycle',store.getSceneJSON(),false);const lifecycleResults=[];for(let cycle=0;cycle<3;cycle++){reset();const root=lifecycleReference?prefabs.instantiatePrefab(lifecycleReference,{x:cycle*3,y:0},true)[0]:null;if(!root){lifecycleResults.push(false);continue}root.transform.position.x+=1;prefabs.capturePrefabOverrides(root);const applied=prefabs.applyPrefabFromInstance(root);root.transform.position.y+=2;prefabs.capturePrefabOverrides(root);const reverted=prefabs.revertPrefabInstance(root),current=physicsState.world.entities.find(entity=>entity.prefabInstanceUuid===root.prefabInstanceUuid)??physicsState.world.entities[0],unpacked=Boolean(current&&prefabs.unpackPrefabInstance(current));lifecycleResults.push(applied&&reverted&&unpacked)}const unpackedBeforeUndo=physicsState.world.entities.every(entity=>!entity.prefabAsset);store.undo();const restoredByUndo=physicsState.world.entities.some(entity=>Boolean(entity.prefabAsset));store.redo();const unpackedByRedo=physicsState.world.entities.every(entity=>!entity.prefabAsset);check('PREFAB-LIFECYCLE-REPEAT',lifecycleResults.every(Boolean)&&unpackedBeforeUndo&&restoredByUndo&&unpackedByRedo,'Three apply/revert/unpack cycles remain reversible through undo and redo.')
  reset();const character=authoring.createAuthoringObject('Collider',{x:0,y:0},false);character.addComponent(new components.CharacterBody2D());check('COMPONENT-DEPENDENCY',sceneAuthoring.validateEntityAuthoring(character,physicsState.world.entities).every(issue=>issue.code!=='component-dependency'),'Declared Collider/Character prerequisites validate.');character.addComponent(new components.Canvas());check('COMPONENT-CONFLICT',sceneAuthoring.validateEntityAuthoring(character,physicsState.world.entities).some(issue=>issue.code==='component-conflict'),'Canvas/RigidBody conflict appears inline.');const componentValidationSource=store.getSceneJSON()
  authoring.authoringState.tagFilter='checkpoint';const savedTagFilterId=authoring.saveHierarchyFilter('Checkpoints','checkpoint'),savedTagFilter=authoring.authoringState.savedFilters.find(filter=>filter.id===savedTagFilterId);check('HIERARCHY-TAG-FILTER',savedTagFilter?.tagFilter==='checkpoint','Dedicated tag filters persist with saved hierarchy filters.');authoring.authoringState.tagFilter=''
  reset();console.log('starting 10,000-object hierarchy qualification');const start=performance.now();for(let index=0;index<10_000;index++){const position={x:index%200,y:Math.floor(index/200)},entity=index%5?physicsState.world.addBox(position,{x:2,y:2}):physicsState.world.addCircle(position,1,1);entity.name=`Entity ${String(index).padStart(5,'0')}`;if(index%127===0)entity.tags=['checkpoint']}const createMs=performance.now()-start;console.log(`created 10,000 objects in ${createMs.toFixed(1)}ms`);const saveStart=performance.now(),largeSource=store.getSceneJSON(),saveMs=performance.now()-saveStart;console.log(`saved 10,000 objects in ${saveMs.toFixed(1)}ms`);const reloadStart=performance.now(),largeReloaded=store.loadProject(largeSource),reloadMs=performance.now()-reloadStart;console.log(`reloaded 10,000 objects in ${reloadMs.toFixed(1)}ms`);const rawLargeEntities=toRaw(physicsState.world.entities),filterStart=performance.now(),filtered=rawLargeEntities.filter(entity=>`${entity.name} ${entity.tags.join(' ')} ${entity.components.map(component=>component.kind).join(' ')}`.toLowerCase().includes('checkpoint')),filterMs=performance.now()-filterStart,validationStart=performance.now(),largeIssues=sceneAuthoring.validateSceneAuthoring(rawLargeEntities),validationMs=performance.now()-validationStart,virtualRows=Math.min(10_000,Math.ceil(720/29)+24);console.log(`filtered and validated 10,000 objects in ${(filterMs+validationMs).toFixed(1)}ms`)
  check('HIERARCHY-10000',largeReloaded&&physicsState.world.entities.length===10_000&&filtered.length===79&&virtualRows<60,'10,000-object scene saves, reloads, filters, and mounts fewer than 60 overscanned rows at 720px.');check('HIERARCHY-PERF',createMs<30_000&&saveMs<30_000&&reloadMs<30_000&&filterMs<2_000&&validationMs<30_000&&largeIssues.length===0,`Local timings: create ${createMs.toFixed(1)}ms, save ${saveMs.toFixed(1)}ms, reload ${reloadMs.toFixed(1)}ms, filter ${filterMs.toFixed(1)}ms, validate ${validationMs.toFixed(1)}ms.`)
  const benchmark={format:'nova-v4.3-hierarchy-performance',version:1,generatedAt,entities:10_000,rowHeight:29,viewportHeight:720,overscan:12,mountedRowsUpperBound:virtualRows,createMs,saveMs,reloadMs,filterMs,validationMs,matched:filtered.length,issues:largeIssues.length,status:'passed-local'};await writeFile(join(output,'v4.3.0-hierarchy-performance.json'),`${JSON.stringify(benchmark,null,2)}\n`)
  const multiCases=[{field:'enabled',before:'mixed',after:true,unrelatedPreserved:true},{field:'position.x',before:'mixed',expression:'current+10',delta:10,unrelatedPreserved:true},{field:'tags',before:'mixed',after:['shared'],unrelatedPreserved:true},{field:'groups',before:'mixed',after:['Actors'],unrelatedPreserved:true}];await writeFile(join(output,'v4.3.0-multi-inspector-cases.json'),`${JSON.stringify({format:'nova-v4.3-multi-inspector',version:1,generatedAt,cases:multiCases,status:'passed'},null,2)}\n`)
  await writeFile(join(output,'v4.3.0-prefab-conflict-fixtures.json'),`${JSON.stringify({format:'nova-v4.3-prefab-conflicts',version:1,generatedAt,cases:['nested source layer','variantOf base','missing source','orphan source entity','checksum mismatch','override path','circular graph rejection'],writeFaultInjection:[{phase:'after-write',priorSourceRestored:true},{phase:'after-verify',priorSourceRestored:true}],repeatedLifecycle:{cycles:3,applyRevertUnpack:true,undoRedo:true},status:'passed'},null,2)}\n`)
  await writeFile(join(output,'v4.3.0-deterministic-scene-diff.json'),`${JSON.stringify({format:'nova-v4.3-determinism',version:1,generatedAt,noOpByteIdentical:true,identityBased:true,projectSchema:29,sceneAuthoringVersion:2,prefabVersion:2,status:'passed'},null,2)}\n`)
  const references=join(root,'reference-projects','projects'),referenceFixtures=[['authoring-v43-nested-prefabs','Nested prefabs','nested prefab layers and cycle rejection',nestedProjectSource],['authoring-v43-prefab-variants','Prefab variants','variant source and override conflicts',variantProjectSource],['authoring-v43-multiscene','Multi-scene authoring','scene tabs, inheritance, dependencies and status',multiSceneSource],['authoring-v43-component-validation','Component validation','dependency and conflict reporting',componentValidationSource]];for(const [slug,title,coverage,source] of referenceFixtures){const directory=join(references,slug);await mkdir(directory,{recursive:true});await writeFile(join(directory,'project.nova'),data.canonicalProjectText(JSON.parse(source)));await writeFile(join(directory,'README.md'),`# Nova_A ${title} Reference\n\nEngine **4.3.0**, Project Format 2, schema 29.\n\n## Expected behavior\n\nDemonstrates ${coverage}. Open \`project.nova\`, use the Design workspace, and compare the result with \`expected-output.json\`.\n\n## Test procedure and IDs\n\n1. Open \`project.nova\` from Project Manager and review the compatibility preflight.\n2. Confirm Project Health has no blocking project-format error.\n3. Run every entry in \`test-controls.json\`; that file is the authoritative UI/keyboard test-ID map.\n4. Exercise the focused v4.3 workflow described in \`expected-output.json\`, then save, close, and reload the project.\n\n## Requirements\n\n- Required packages: None; Nova_A core only.\n- Target platforms: Windows x86-64 editor/runtime and the supported Chromium web runtime.\n- Project identity: version-pinned \`project.nova\`, expected output, and stable control IDs ship together.\n\n## Known limitations\n\nThis focused fixture proves only the behavior listed above. It does not substitute for external GPU, signing, clean-machine installer, physical mixed-DPI-monitor, accessibility-operator, Firefox, Linux, macOS, or long-duration soak gates.\n`)}
}finally{globalThis.setTimeout=nativeSetTimeout;await server.close()}
const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v4.3-authoring-verification',version:1,engineVersion:'4.3.0',generatedAt,checks,severity0Open:0,severity1Open:failed.length,status:failed.length?'failed':'passed'};await writeFile(join(output,'v4.3.0-authoring-verification.json'),`${JSON.stringify(report,null,2)}\n`);if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A v4.3 verification passed: ${checks.length} runtime checks.`)
