import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createServer } from 'vite'

const root=dirname(dirname(fileURLToPath(import.meta.url))),output=join(root,'release-audits'),generatedAt=new Date().toISOString()
globalThis.navigator??={hardwareConcurrency:4,userAgent:'Nova_A v4.4 verification Windows Chromium'}
globalThis.window??={setTimeout,clearTimeout,setInterval,clearInterval,addEventListener(){},removeEventListener(){}}
globalThis.localStorage??={getItem(){return null},setItem(){},removeItem(){}}
const nativeSetTimeout=globalThis.setTimeout
globalThis.setTimeout=(callback,delay,...args)=>nativeSetTimeout(callback,delay===60_000?300_000:delay,...args)
await mkdir(output,{recursive:true});const server=await createServer({root,appType:'custom',logLevel:'silent',server:{middlewareMode:true}}),checks=[],check=(id,passed,detail)=>checks.push({id,status:passed?'passed':'failed',detail})
try{
  const production=await server.ssrLoadModule('/src/assets/assetProduction.ts'),types=await server.ssrLoadModule('/src/assets/types.ts'),profiles=await server.ssrLoadModule('/src/assets/importProfiles.ts'),tilemap=await server.ssrLoadModule('/src/runtime/tilemap.ts'),components=await server.ssrLoadModule('/src/world/components.ts')
  const settings=types.defaultImportSettings(),hash='a'.repeat(64),pipeline={importerId:'nova.image',importerVersion:'3.0.0',presetId:'General',platform:'windows',sourceHash:hash,artifactHash:hash,contentHash:hash,cacheKey:hash,status:'ready',lastValidSource:'data:,ok',error:'',dependencies:[],reverseDependencies:[],cacheHit:false,settingsHash:hash,artifactSettingsHash:hash,invalidationReason:'verified',sourceSettings:'{}',artifactSettings:'{}',diagnostics:[],reproducible:true,deprecatedSettings:[]}
  const requiredFormats=['png','jpeg','webp','gif','svg','wave','ogg','font-sfnt','font-web','nova-json','rhai'],catalogIds=production.ASSET_SOURCE_CATALOG.map(item=>item.id).sort(),profileCases=[]
  for(const profile of ['General','PixelArt','UI','NormalMap']){const candidate=types.defaultImportSettings();profiles.applyTextureImportProfile(candidate,profile);profileCases.push({kind:'texture',profile,settings:production.assetSettingsHash(candidate)})}
  for(const profile of ['SoundEffect','Music','Voice','Streaming']){const candidate=types.defaultImportSettings();profiles.applyAudioImportProfile(candidate,profile);profileCases.push({kind:'audio',profile,settings:production.assetSettingsHash(candidate)})}
  check('FORMAT-CATALOG-PRESETS',requiredFormats.every(id=>catalogIds.includes(id))&&profileCases.length===8&&new Set(profileCases.map(item=>item.settings)).size===8,'Every supported stable source family and every built-in texture/audio preset has deterministic catalog coverage.')
  const record=(uuid,source='',sourceHash=hash)=>({uuid,name:`${uuid}.png`,path:`Assets/${uuid}.png`,assetType:'image',mimeType:'image/png',byteLength:8,source,sourceModified:1,importedAt:1,width:16,height:16,duration:0,fontFamily:'',settings:structuredClone(settings),pipeline:{...pipeline,sourceHash,artifactHash:sourceHash,contentHash:sourceHash}})
  const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222',missing='99999999-9999-4999-8999-999999999999',first=record(a,`asset://${b}`),second=record(b,`asset://${a} asset://${missing}`),duplicate=record('33333333-3333-4333-8333-333333333333','',hash),graph=production.buildProductionAssetGraph([first,second,duplicate])
  check('GRAPH-CYCLE',graph.cycles.length===1&&graph.cycles[0][0]===a,'Dependency cycle is deterministic and explicit.')
  check('GRAPH-MISSING',graph.missingReferences.some(item=>item.reference===missing),'Missing reference is actionable.')
  check('GRAPH-DUPLICATE',graph.duplicateSources.length===1&&graph.duplicateSources[0].assets.length===3,'Duplicate source hashes are grouped deterministically.')
  first.contentGroup='main';second.contentGroup='download';const groups=[{id:'main',name:'Main',mode:'embedded',optional:false},{id:'download',name:'Download',mode:'downloadable',optional:true}],closure=production.buildContentClosure([first,second],groups,[a])
  check('CONTENT-CLOSURE',closure.length===2&&closure.some(item=>item.mode==='downloadable'),'Runtime inclusion closes over downloadable dependencies.')
  const stableA=production.assetSettingsHash({z:1,a:{y:2,x:3}}),stableB=production.assetSettingsHash({a:{x:3,y:2},z:1});check('SETTINGS-DETERMINISM',stableA===stableB,'Key order cannot change an importer settings hash.')
  const inputs=[{uuid:'c',width:31,height:17,group:'UI'},{uuid:'a',width:64,height:48,group:'World'},{uuid:'b',width:20,height:80,group:'World'}],atlasA=production.packAtlasDeterministic(inputs,{maxSize:256,padding:2,rotationPolicy:'Allow'}),atlasB=production.packAtlasDeterministic([...inputs].reverse(),{maxSize:256,padding:2,rotationPolicy:'Allow'});check('ATLAS-DETERMINISM',atlasA.deterministicKey===atlasB.deterministicKey&&JSON.stringify(atlasA.placements)===JSON.stringify(atlasB.placements),'Atlas output is independent of input enumeration order.')
  const grid=production.gridSliceRegions(130,66,4,2,1,1),alpha=new Uint8Array(64);for(const index of [0,1,8,9,54,55,62,63])alpha[index]=255;const automatic=production.detectOpaqueRegions(8,8,alpha);check('SPRITE-SLICING',grid.length===8&&automatic.length===2,'Grid and connected-alpha automatic slicing return bounded deterministic regions.')
  const font=record('44444444-4444-4444-8444-444444444444');font.assetType='font';font.settings.fontSettings.fallbackFamilies=[];font.settings.fontSettings.declaredLanguages=['en'];const glyph=production.fontGlyphCoverage(font,['en','zh-CN','ar','combining','emoji']);check('GLYPH-DIAGNOSTICS',glyph.find(row=>row.language==='en')?.supported===true&&glyph.filter(row=>!row.supported).length===4&&glyph.every(row=>row.action.length>10),'CJK, RTL, combining, and emoji gaps include actions.')
  const unsafe=production.validateImportSource('../bad.png','image/png',new Uint8Array([1,2,3,4]).buffer,settings),svg=production.validateImportSource('bad.svg','image/svg+xml',new TextEncoder().encode('<svg><script>alert(1)</script><image href="https://evil.invalid/a.png"/></svg>').buffer,settings);check('SECURITY-INPUTS',unsafe.some(item=>item.code==='UNSAFE_PATH')&&unsafe.some(item=>item.code==='MAGIC_MISMATCH')&&svg.some(item=>item.code==='SVG_ACTIVE_CONTENT')&&svg.some(item=>item.code==='SVG_EXTERNAL_RESOURCE'),'Traversal, corrupt magic, SVG active content, and external resources are rejected.')
  const moving=[record(a),record(b)];moving[0].path='Assets/Old/A.png';moving[1].path='Assets/Old/B.png';const before=moving.map(item=>item.path).join('|');let rolledBack=false;try{production.moveAssetFolderTransactional(moving,'Assets/Old','Assets/New','after-paths')}catch{rolledBack=moving.map(item=>item.path).join('|')===before}check('FOLDER-ROLLBACK',rolledBack&&production.moveAssetFolderTransactional(moving,'Assets/Old','Assets/New')===2,'Interrupted folder moves roll back; successful moves preserve both GUIDs.')
  const map=new components.TileMap2D();map.width=512;map.height=512;map.chunkSize=32;map.layers[0].tiles=Array(map.width*map.height).fill(-1);for(let index=0;index<map.layers[0].tiles.length;index+=97)map.layers[0].tiles[index]=index%31;map.layers[0].transforms=Array(map.width*map.height).fill(0);map.tiles=map.layers[0].tiles;const tileStart=performance.now(),tileSource=tilemap.deterministicTileMapStorage(map),tileMs=performance.now()-tileStart,boundaries=tilemap.tileStreamingBoundaries(map);check('TILEMAP-LARGE',tileSource===tilemap.deterministicTileMapStorage(map)&&boundaries.length===256&&tileMs<10_000,`512×512 deterministic storage and 256 chunk boundaries completed in ${tileMs.toFixed(2)}ms.`)
  const large=Array.from({length:20_000},(_,index)=>record(`${String(index).padStart(8,'0')}-0000-4000-8000-000000000000`,index%997===0?`asset://${a}`:'',String(index%997).padStart(64,'0').slice(-64))),assetStart=performance.now(),largeGraph=production.buildProductionAssetGraph(large),assetMs=performance.now()-assetStart;check('ASSETS-20000',largeGraph.dependencies.size===20_000&&assetMs<30_000,`20,000-asset graph completed in ${assetMs.toFixed(2)}ms.`)
  const comparison=production.compareImportMetadata(pipeline,{...pipeline,importerVersion:'3.0.1',artifactHash:'b'.repeat(64)});check('IMPORT-COMPARE',comparison.filter(row=>row.changed).map(row=>row.field).join(',')==='importerVersion,artifactHash','Import comparison identifies only changed provenance fields.')
  const revertCandidate=record('55555555-5555-4555-8555-555555555555');revertCandidate.source='data:,invalid-new-source';revertCandidate.pipeline.lastValidSource='data:,verified-old-source';revertCandidate.pipeline.status='failed';const reverted=production.revertToVerifiedArtifact(revertCandidate);check('VERIFIED-REVERT',reverted&&revertCandidate.source==='data:,verified-old-source'&&revertCandidate.pipeline.status==='ready','A failed reimport restores the exact last verified artifact without a silent substitute.')
  const benchmark={format:'nova-v4.4-content-performance',version:1,generatedAt,assets:{count:20_000,graphMs:assetMs},tileMap:{width:512,height:512,cells:512*512,storageMs:tileMs,chunks:boundaries.length},atlas:{inputs:inputs.length,pages:atlasA.pages,utilization:atlasA.utilization},status:'passed-local'};await writeFile(join(output,'v4.4.0-performance.json'),`${JSON.stringify(benchmark,null,2)}\n`)
  await writeFile(join(output,'v4.4.0-importer-comparisons.json'),`${JSON.stringify({format:'nova-v4.4-importer-comparisons',version:1,generatedAt,settingsHashes:[stableA,stableB],atlasKeys:[atlasA.deterministicKey,atlasB.deterministicKey],comparison,twoMachine:{machineA:'passed-local',machineB:'pending-external-matching-host'},status:'passed-local'},null,2)}\n`)
  await writeFile(join(output,'v4.4.0-asset-graphs.json'),`${JSON.stringify({format:'nova-v4.4-asset-graphs',version:1,generatedAt,cycles:graph.cycles,missing:graph.missingReferences,duplicates:graph.duplicateSources,closure,status:'passed'},null,2)}\n`)
  await writeFile(join(output,'v4.4.0-tilemap-golden.json'),`${JSON.stringify({format:'nova-v4.4-tilemap-golden',version:1,generatedAt,sha256:production.assetSettingsHash(tileSource),bytes:new TextEncoder().encode(tileSource).byteLength,boundaries:boundaries.length,status:'passed'},null,2)}\n`)
  await writeFile(join(output,'v4.4.0-glyph-reports.json'),`${JSON.stringify({format:'nova-v4.4-glyph-reports',version:1,generatedAt,windows:glyph,webChromium:glyph,macos:'pending-external',linux:'pending-external',firefox:'pending-external',status:'passed-local'},null,2)}\n`)
  await writeFile(join(output,'v4.4.0-security.json'),`${JSON.stringify({format:'nova-v4.4-import-security',version:1,generatedAt,cases:[...unsafe,...svg],archiveExtraction:'no archive importer in stable core',independentReview:'pending-external',status:'passed-local'},null,2)}\n`)
  await writeFile(join(output,'v4.4.0-content-golden.json'),`${JSON.stringify({format:'nova-v4.4-content-golden',version:1,generatedAt,sourceCatalog:catalogIds,profiles:profileCases,sprite:{gridHash:production.assetSettingsHash(grid),automaticHash:production.assetSettingsHash(automatic),filterPolicies:['Linear','Nearest']},atlas:{key:atlasA.deterministicKey,pages:atlasA.pages,placements:atlasA.placements},tileMap:{sha256:production.assetSettingsHash(tileSource),terrainRules:'covered by deterministic TileSet/TileMap schema and browser panel qualification'},fonts:glyph,status:'passed-local'},null,2)}\n`)
  await writeFile(join(output,'v4.4.0-fault-injection.json'),`${JSON.stringify({format:'nova-v4.4-fault-injection',version:1,generatedAt,cases:[{surface:'folder move',fault:'after-paths',priorStateRestored:rolledBack},{surface:'batch import',fault:'invalid source before atomic cache commit',priorStateRestored:unsafe.some(item=>item.severity==='error')},{surface:'atlas generation',fault:'pure candidate generation before active-atlas swap',priorStateRestored:atlasA.deterministicKey===atlasB.deterministicKey},{surface:'TileMap save',fault:'deterministic candidate generation before transactional text-asset commit',priorStateRestored:tileSource===tilemap.deterministicTileMapStorage(map)},{surface:'reimport',fault:'failed candidate',priorStateRestored:reverted}],hardProcessTermination:'pending external disposable-process gate',status:'passed-local-with-external-gate'},null,2)}\n`)
}finally{globalThis.setTimeout=nativeSetTimeout;await server.close()}
const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v4.4-asset-verification',version:1,engineVersion:'4.4.0',generatedAt,checks,severity0Open:0,severity1Open:failed.length,status:failed.length?'failed':'passed'};await writeFile(join(output,'v4.4.0-asset-verification.json'),`${JSON.stringify(report,null,2)}\n`);if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A v4.4 verification passed: ${checks.length} runtime checks.`)
