/** 验证脚本（v26.02）：组织对应功能与边界场景检查，断言行为并汇总验证结果。 */
import { build } from 'vite'
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root=dirname(dirname(fileURLToPath(import.meta.url))),compiled=await mkdtemp(join(tmpdir(),'nova-v2602-verify-')),checks=[]
const check=/* 调用 checks.push({id,status:passed?'passed':'failed',detail,metrics}) 并返回调用结果。 */ (id,passed,detail,metrics={})=>checks.push({id,status:passed?'passed':'failed',detail,metrics}),read=/* 调用 readFile(join(root,path),'utf8') 并返回调用结果。 */ path=>readFile(join(root,path),'utf8')
globalThis.crypto??=(await import('node:crypto')).webcrypto
globalThis.localStorage??={/* 返回固定值 null。 */ getItem(){return null},/** 隔离存储桩忽略写入，不持久化生成过程数据。 */ setItem(){},/** 隔离存储桩忽略删除请求。 */ removeItem(){}}
try{
  await build({configFile:false,root,logLevel:'warn',ssr:{noExternal:true},build:{ssr:true,outDir:compiled,emptyOutDir:false,rollupOptions:{input:{format:join(root,'src/projects/projectFormat.ts'),events:join(root,'src/runtime/eventSheets.ts'),graph:join(root,'src/visual/graphInteraction.ts'),platform:join(root,'src/runtime/stableCreatorPlatform.ts')},output:{entryFileNames:'[name].mjs',chunkFileNames:'chunks/[name]-[hash].mjs'}}}})
  const load=/* 调用 import(`${pathToFileURL(join(compiled,`${name}.mjs`)).href}?v=${Date.now()}`) 并返回调用结果。 */ name=>import(`${pathToFileURL(join(compiled,`${name}.mjs`)).href}?v=${Date.now()}`),[format,events,graph,platform]=await Promise.all(['format','events','graph','platform'].map(load))
  const pkg=JSON.parse(await read('package.json')),tauri=JSON.parse(await read('src-tauri/tauri.conf.json')),cargo=await read('Cargo.toml'),nativeCargo=await read('src-tauri/Cargo.toml'),rust=await read('crates/nova_format/src/lib.rs')
  check('V2602-AUTHORITY',format.NOVA_ENGINE_VERSION==='26.2.0'&&format.NOVA_RELEASE_NAME==='26.02'&&pkg.version==='26.2.0'&&tauri.version==='26.2.0'&&/version\s*=\s*"26\.2\.0"/.test(cargo)&&/version\s*=\s*"26\.2\.0"/.test(nativeCargo)&&rust.includes('CURRENT_ENGINE_VERSION: &str = "26.2.0"'),'Public 26.02 and machine 26.2.0 authorities agree.')
  check('V2602-FROZEN-FORMAT',format.NOVA_PROJECT_FORMAT_MAJOR===2&&format.NOVA_PROJECT_SCHEMA_VERSION===29,'Project Format 2/schema 29 remains frozen.')
  const logic=events.createEventSheetAsset('Verifier','asset://00000000-0000-4000-8000-000000000001'),base=events.defaultEventSheet('Base','asset://00000000-0000-4000-8000-000000000001')
  base.handlers=[{...events.defaultEventHandler('input-pressed'),selector:'Jump',callback:'base_jump',priority:1},{...events.defaultEventHandler('update'),callback:'tick'}]
  events.saveEventSheetAsset(logic.uuid,base)
  const derivedAsset=events.createEventSheetAsset('Derived','asset://00000000-0000-4000-8000-000000000001'),derived=events.readEventSheet(derivedAsset.uuid)
  derived.baseSheetAsset=`asset://${logic.uuid}`;derived.handlers=[{...events.defaultEventHandler('input-pressed'),selector:'Jump',callback:'derived_jump',priority:9,overrideInherited:true}];events.saveEventSheetAsset(derivedAsset.uuid,derived)
  const resolved=events.resolveEventHandlers(derivedAsset.uuid),jump=resolved.filter(/* 先计算 item.kind==='input-pressed'；仅当其为真值时求右侧 item.selector==='Jump'，返回短路求值结果。 */ item=>item.kind==='input-pressed'&&item.selector==='Jump')
  check('V2602-INHERITANCE',jump.length===1&&jump[0].callback==='derived_jump'&&resolved.some(/* 比较 item.callback 与 'tick'，返回严格相等的判断结果。 */ item=>item.callback==='tick'),'Inherited handlers merge deterministically and explicit overrides replace one matching event key.',{resolved:resolved.map(/* 返回 item.callback 的当前值。 */ item=>item.callback)})
  const fake=Array.from({length:10050},/** 创建关联派生事件表的测试实体，使用补零标识并仅禁用首项。 */ (_,index)=>({uuid:index.toString().padStart(12,'0'),enabled:index!==0,script2D:{enabled:true,eventSheetAsset:`asset://${derivedAsset.uuid}`}})),schedule=events.scheduleObjectEvents(fake,'update')
  check('V2602-SCHEDULER',schedule.length===10000&&schedule.every(/* 先计算 !index；仅当其为假值时求右侧 schedule[index-1].entityUuid<=item.entityUuid，返回短路求值结果。 */ (item,index)=>!index||schedule[index-1].entityUuid<=item.entityUuid),'The scheduler excludes disabled entities, preserves deterministic order, and stops at 10,000 callbacks.',{scheduled:schedule.length})
  const first=events.createEventRandomStream(42),second=events.createEventRandomStream(42),a=Array.from({length:64},first),b=Array.from({length:64},second)
  check('V2602-RANDOM',JSON.stringify(a)===JSON.stringify(b)&&new Set(a).size>60,'Named Event Sheet seeds reproduce non-constant random streams.')
  const node=/** 创建带执行输入输出引脚的测试图节点，首项为启动事件，其余为顺序节点。 */ (index)=>({uuid:`n${index}`,type:index?'flow.sequence':'event.start',title:'Node',category:index?'Flow':'Events',position:{x:0,y:0},size:{width:220,height:80},collapsed:false,pins:[{uuid:`in${index}`,key:'in',name:'In',direction:'input',kind:'execution',valueType:null,required:false,defaultValue:null},{uuid:`out${index}`,key:'next',name:'Next',direction:'output',kind:'execution',valueType:null,required:false,defaultValue:null}],config:{}}),nodes=Array.from({length:10000},/* 调用 node(index) 并返回调用结果。 */ (_,index)=>node(index)),edges=nodes.slice(0,-1).map(/** 构造从当前节点输出连接到下一节点输入的执行边。 */ (_,index)=>({uuid:`e${index}`,from:{nodeUuid:`n${index}`,pinUuid:`out${index}`},to:{nodeUuid:`n${index+1}`,pinUuid:`in${index+1}`}})),scope={nodes,edges,comments:[],viewport:{x:0,y:0,zoom:1}},started=performance.now(),layout=graph.arrangeExecutionBlocks(scope),elapsed=performance.now()-started
  check('V2602-GRAPH-LAYOUT',layout.visited===10000&&layout.edgesIndexed===9999&&elapsed<2000,'Indexed non-recursive layout processes a 10,000-node chain without stack overflow or quadratic edge scans.',{elapsedMs:Number(elapsed.toFixed(2)),...layout})
  const zoom=graph.focalGraphZoom({x:10,y:20,zoom:1},2,110,120)
  check('V2602-ZOOM',zoom.zoom===2&&zoom.x===-90&&zoom.y===-80&&graph.focalGraphZoom(zoom,99,110,120).zoom===4,'Focal zoom preserves the pointer world position and clamps safely.')
  const [runtime,editor,workspace,bottom,assets,blueprints,i18n,roadmap,readme,zhReadme]=await Promise.all(['src/runtime/GameplayRuntime.ts','src/components/VisualGraphEditor.vue','src/components/ScriptWorkspace.vue','src/components/EditorBottomPanel.vue','src/assets/AssetDatabase.ts','src/runtime/objectBlueprints.ts','src/i18n.ts','docs/ROADMAP_26_01_TO_26_10.md','README.md','README.zh-CN.md'].map(read))
  check('V2602-RUNTIME-BINDING',['awake','start','update','fixed-update','input-pressed','input-released','timer','signal','collision-enter','trigger-enter','ui','animation','network'].every(/* 调用 runtime.includes(`'${token}'`) 并返回调用结果。 */ token=>runtime.includes(`'${token}'`))&&runtime.includes('runEventSheetHandlers'),'Every Event Sheet family reaches an existing deterministic runtime boundary without replacing Script2D.')
  check('V2602-EDITOR-BINDING',workspace.includes('EventSheetEditor')&&bottom.includes("asset.assetType === 'eventSheet'")&&assets.includes("'eventSheet'")&&blueprints.includes('createQuickObjectWorkflow'),'Event Sheets, Object Blueprints, assets, Inspector/workspace handoff, and guided creation are reachable.')
  check('V2602-GRAPH-UX',editor.includes('@wheel.capture.prevent.stop')&&editor.includes('requestAnimationFrame')&&editor.includes('startWire')&&editor.includes('tidyBlocks')&&!editor.includes("if(studio.authoringMode==='blocks')arrangeScratchBlocks(false)"),'Graph navigation is capture-safe, frame-batched, direct-connectable, and never destroys saved layout on open.')
  check('V2602-LOCALIZATION',['eventSheet','objectBlueprint','graphPanHint','event_network'].every(/* 比较 (i18n.match(new RegExp(`(?:'${key}'|${key}):`,'g'))??[]).length 与 3，返回大于或等于的判断结果。 */ key=>(i18n.match(new RegExp(`(?:'${key}'|${key}):`,'g'))??[]).length>=3),'All new public graph/event/object controls have EN/DE/ZH strings.')
  check('V2602-READINESS',platform.CREATOR_CONTRACT_REVIEW.release==='26.02'&&platform.CREATOR_PLATFORM_SUMMARY.uncovered===0&&platform.CREATOR_PLATFORM_READINESS.some(/* 调用 item.id.startsWith('event-sheet-') 并返回调用结果。 */ item=>item.id.startsWith('event-sheet-')),'The seven-dimension inventory includes every 26.02 operation.',platform.CREATOR_PLATFORM_SUMMARY)
  check('V2602-DOCUMENTATION',roadmap.includes('## 26.02')&&readme.includes('26.02')&&zhReadme.includes('26.02'),'Roadmap and both READMEs identify the current release.')
}finally{await rm(compiled,{recursive:true,force:true})}
const failed=checks.filter(/* 比较 item.status 与 'failed'，返回严格相等的判断结果。 */ item=>item.status==='failed'),report={format:'nova-v26.02-verification',version:1,release:'26.02',engineVersion:'26.2.0',generatedAt:new Date().toISOString(),perspectives:['versioning','object-events','runtime','visual-graph','performance','localization','user'],checks,severity0Open:failed.length,severity1Open:0,status:failed.length?'failed':'passed'}
await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits/v26.02-verification.json'),`${JSON.stringify(report,null,2)}\n`)
if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A 26.02 verification passed: ${checks.length} checks.`)
