import { build } from 'vite'
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root=dirname(dirname(fileURLToPath(import.meta.url))),compiled=await mkdtemp(join(tmpdir(),'nova-v2605-verify-')),checks=[]
const check=(id,passed,detail,metrics={})=>checks.push({id,status:passed?'passed':'failed',detail,metrics}),read=path=>readFile(join(root,path),'utf8')
globalThis.crypto??=(await import('node:crypto')).webcrypto
globalThis.localStorage??={getItem(){return null},setItem(){},removeItem(){}}
globalThis.atob??=value=>Buffer.from(value,'base64').toString('binary')
globalThis.btoa??=value=>Buffer.from(value,'binary').toString('base64')
try{
  await build({configFile:false,root,logLevel:'warn',ssr:{noExternal:true},build:{ssr:true,outDir:compiled,emptyOutDir:false,rollupOptions:{input:{format:join(root,'src/projects/projectFormat.ts'),types:join(root,'src/assets/types.ts'),interop:join(root,'src/assets/contentInteroperability.ts'),production:join(root,'src/assets/assetProduction.ts'),content:join(root,'src/assets/contentLibrary26.ts'),graph:join(root,'src/assets/assetGraph.ts'),resources:join(root,'src/runtime/resources.ts'),renderSettings:join(root,'src/renderer/renderSettings.ts'),renderGraph:join(root,'src/renderer/renderGraph.ts'),materialGraph:join(root,'src/renderer/materialGraph.ts'),materials:join(root,'src/renderer/materials.ts'),cinematic:join(root,'src/runtime/cinematicProduction.ts'),media:join(root,'src/runtime/mediaProduction26.ts')},output:{entryFileNames:'[name].mjs',chunkFileNames:'chunks/[name]-[hash].mjs'}}}})
  const load=name=>import(`${pathToFileURL(join(compiled,`${name}.mjs`)).href}?v=${Date.now()}`),[format,types,interop,production,content,graph,resources,renderSettings,renderGraph,materialGraph,materials,cinematic,media]=await Promise.all(['format','types','interop','production','content','graph','resources','renderSettings','renderGraph','materialGraph','materials','cinematic','media'].map(load))
  const pkg=JSON.parse(await read('package.json')),tauri=JSON.parse(await read('src-tauri/tauri.conf.json')),cargo=await read('Cargo.toml'),nativeCargo=await read('src-tauri/Cargo.toml'),rust=await read('crates/nova_format/src/lib.rs')
  check('V2605-AUTHORITY',format.NOVA_ENGINE_VERSION==='26.5.0'&&format.NOVA_RELEASE_NAME==='26.05'&&pkg.version==='26.5.0'&&tauri.version==='26.5.0'&&/version\s*=\s*"26\.5\.0"/.test(cargo)&&/version\s*=\s*"26\.5\.0"/.test(nativeCargo)&&rust.includes('CURRENT_ENGINE_VERSION: &str = "26.5.0"'),'Public 26.05 and machine 26.5.0 authorities agree.')
  check('V2605-FROZEN-FORMAT',format.NOVA_PROJECT_FORMAT_MAJOR===2&&format.NOVA_PROJECT_SCHEMA_VERSION===29,'Project Format 2/schema 29 and all additive compatibility contracts remain frozen.')

  const aseprite=JSON.stringify({frames:{'idle 0':{frame:{x:0,y:0,w:16,h:16},duration:100,pivot:{x:.5,y:.5}},'idle 1':{frame:{x:16,y:0,w:16,h:16},duration:120,pivot:{x:.5,y:.5}}},meta:{app:'https://www.aseprite.org/',image:'hero.png',size:{w:32,h:16},frameTags:[{name:'idle',from:0,to:1,direction:'forward'}]}})
  const first=interop.importContentInterchange('hero.aseprite.json',aseprite),reordered=JSON.stringify({frames:{'idle 1':{frame:{x:16,y:0,w:16,h:16},duration:120,pivot:{x:.5,y:.5}},'idle 0':{frame:{x:0,y:0,w:16,h:16},duration:100,pivot:{x:.5,y:.5}}},meta:{app:'https://www.aseprite.org/',image:'hero.png',size:{w:32,h:16},frameTags:[{name:'idle',from:0,to:1,direction:'forward'}]}}),second=interop.importContentInterchange('hero.aseprite.json',reordered,first?.metadata)
  const firstIds=new Map(first?.metadata.slices.map(item=>[item.sourceKey,item.id])??[])
  check('V2605-ASEPRITE-REIMPORT',first?.metadata.format==='aseprite-json'&&first.metadata.slices.length===2&&second?.metadata.slices.every(item=>firstIds.get(item.sourceKey)===item.id),'Aseprite frames retain duration, tags, pivots and stable slice identity when source order changes.',{slices:first?.metadata.slices.length??0})
  const texturePacker=interop.importContentInterchange('atlas.json',JSON.stringify({frames:{button:{frame:{x:1,y:2,w:30,h:12},pivot:{x:.25,y:.75}}},meta:{app:'TexturePacker',image:'ui.png',size:{w:64,h:64}}})),tiled=interop.importContentInterchange('world.tmj',JSON.stringify({type:'map',width:2,height:2,tilewidth:32,tileheight:32,layers:[{id:1,name:'Ground',data:[1,0,0,1]}],tilesets:[{firstgid:1,source:'terrain.tsx'}]})),tmx=interop.importContentInterchange('world.tmx','<map width="2" height="1" tilewidth="32" tileheight="32"><layer id="1"><data encoding="csv">1,0</data></layer></map>')
  check('V2605-INTERCHANGE-CORPUS',texturePacker?.metadata.slices.length===1&&tiled?.assetType==='tileset'&&tmx?.metadata.format==='tiled-xml'&&interop.detectInterchangeFormat('broken.json','{')===null,'TexturePacker, Tiled JSON/XML and malformed metadata follow bounded deterministic import paths.')
  let oversized=false;try{interop.importContentInterchange('huge.json',' '.repeat(16*1024*1024+1))}catch{oversized=true}
  check('V2605-IMPORT-BOUNDS',oversized,'Metadata larger than 16 MiB is rejected before parsing.')
  const localizationSettings=types.defaultImportSettings(),badArb=production.validateImportSource('de.arb','application/json',new TextEncoder().encode('[]').buffer,localizationSettings),badPo=production.validateImportSource('de.po','text/plain',new TextEncoder().encode('not a po catalog').buffer,localizationSettings),mp3=production.validateImportSource('music.mp3','audio/mpeg',Uint8Array.from([0x49,0x44,0x33,0]).buffer,localizationSettings),flac=production.validateImportSource('music.flac','audio/flac',new TextEncoder().encode('fLaC').buffer,localizationSettings)
  check('V2605-RICH-SOURCE-VALIDATION',badArb.some(item=>item.code==='ARB_JSON')&&badPo.some(item=>item.code==='PO_MESSAGES')&&!mp3.some(item=>item.severity==='error')&&!flac.some(item=>item.severity==='error'),'Localization, MP3 and FLAC validation is connected to the production source catalog without executing content.')

  const ids={a:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',b:'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',c:'cccccccc-cccc-cccc-cccc-cccccccccccc',missing:'dddddddd-dddd-dddd-dddd-dddddddddddd'}
  const asset=(uuid,name,source='',overrides={})=>({uuid,name,path:`Assets/${name}`,assetType:'other',mimeType:'text/plain',byteLength:source.length,source,sourceModified:1,importedAt:1,width:0,height:0,duration:0,fontFamily:'',settings:types.defaultImportSettings(),...overrides})
  const assets=[asset(ids.a,'A.txt',`asset://${ids.b} asset://${ids.missing}`),asset(ids.b,'B.txt',`asset://${ids.a}`),asset(ids.c,'编辑器.txt','', {editorOnly:true})]
  const dependency=content.buildAssetDependencyView(ids.a,assets)
  check('V2605-DEPENDENCY-GRAPH',dependency.directDependencies===2&&dependency.directDependents===1&&dependency.missing===1&&dependency.cycles.length>=1&&dependency.nodes.some(node=>node.direction==='missing'),'Two-way dependency projection reports direct/transitive relationships, cycles and missing references.',{nodes:dependency.nodes.length,edges:dependency.edges.length,cycles:dependency.cycles.length})
  const repaired=[asset(ids.a,'Owner.txt','Assets/旧/source.png'),asset(ids.b,'Replacement.txt')],pathRepairs=graph.repairAssetPathReferences(repaired,'Assets/旧','Assets/新'),referenceOwner=asset(ids.c,'Reference.txt',`asset://${ids.missing}`),referenceRepairs=graph.repairMissingAssetReference([referenceOwner],ids.missing,ids.b)
  check('V2605-REPAIR',pathRepairs===1&&repaired[0].source==='Assets/新/source.png'&&referenceRepairs===1&&referenceOwner.source.includes(ids.b),'Moved Unicode source paths and deleted UUID references are repaired transactionally through canonical utilities.')
  const closure=production.buildContentClosure(assets,[{id:'main',name:'Main',mode:'embedded',optional:false},{id:'excluded',name:'Excluded',mode:'excluded',optional:false}],[ids.a]),excludedAssets=[asset(ids.a,'Root.txt',`asset://${ids.b}`),asset(ids.b,'Required.txt','',{contentGroup:'excluded'}),asset(ids.c,'EditorOnly.txt','',{editorOnly:true})],excludedClosure=production.buildContentClosure(excludedAssets,[{id:'main',name:'Main',mode:'embedded',optional:false},{id:'excluded',name:'Excluded',mode:'excluded',optional:false}],[ids.a])
  check('V2605-EXPORT-CLOSURE',closure.some(item=>item.uuid===ids.b)&&!closure.some(item=>item.uuid===ids.c)&&production.validateContentClosure(excludedClosure).length===1,'Export closure follows transitive dependencies, strips editor-only content and blocks required excluded content.')

  const thumbnailAsset=asset(ids.a,'Player script.rhai','fn update() {}',{assetType:'script',mimeType:'text/rhai'}),thumbnailA=content.contentThumbnailDataUrl(thumbnailAsset),thumbnailB=content.contentThumbnailDataUrl(structuredClone(thumbnailAsset)),profile=content.assetContentProfile(asset(ids.b,'Theme.resource','{}',{assetType:'resource',mimeType:'application/x-nova-resource'}))
  check('V2605-THUMBNAIL-PROFILE',thumbnailA===thumbnailB&&thumbnailA.startsWith('data:image/svg+xml')&&profile.some(item=>item.id==='resource')&&profile.some(item=>item.id==='content-group'),'Non-image thumbnails and production profiles are deterministic and truthfully describe Resources/export groups.')
  let document=resources.defaultResource('Theme','Shared Theme');document=resources.setResourceVariantData(document,'High Contrast',{tokens:{foreground:'#fff'}});const normalized=resources.normalizeResource(JSON.parse(resources.serializeResource(document)))
  check('V2605-RESOURCE-VARIANTS',resources.resourceVariantNames(normalized).join(',')==='Default,High_Contrast'&&normalized.activeVariant==='High_Contrast'&&normalized.variants.High_Contrast.tokens.foreground==='#fff','Named Resource variants normalize, serialize and round-trip without changing Resource format version 1.')
  const discovered=content.discoverOfflineContent([{id:'remote',name:'Remote',kind:'package',provenance:'registry',trusted:true,offline:false,tags:[]},{id:'community',name:'Community Pack',kind:'package',provenance:'cache',trusted:false,offline:true,tags:['audio']},{id:'builtin',name:'Built-in Platformer',kind:'template',provenance:'bundled',trusted:true,offline:true,tags:['game']}],'')
  check('V2605-OFFLINE-DISCOVERY',discovered.length===2&&discovered[0].id==='builtin'&&!discovered.some(item=>item.id==='remote'),'Offline discovery hides unavailable entries, exposes provenance and sorts trusted content first.')
  const many=Array.from({length:50_000},(_,index)=>asset(index.toString(16).padStart(8,'0')+'-0000-0000-0000-000000000000',`资源-${index}.txt`)),started=performance.now(),auditA=content.auditContentLibrary(many),auditB=content.auditContentLibrary([...many].reverse()),elapsedMs=performance.now()-started
  check('V2605-50000-ASSETS',auditA.scanned===50_000&&auditA.unicodePaths===50_000&&auditA.deterministicHash===auditB.deterministicHash&&elapsedMs<30_000,'The 50,000-record audit remains bounded, Unicode-safe and order-deterministic.',{elapsedMs:Number(elapsedMs.toFixed(2)),hash:auditA.deterministicHash})

  const normalizedRendering=renderSettings.normalizeRenderingSettings({textureStreaming:{enabled:true,memoryBudgetMb:1,idleFrames:999999,uploadBudgetPerFrame:0,preloadMargin:99},deterministicCapture:{frameRate:0,sampleRate:999999,maximumFrames:999999,memoryBudgetMb:1,includeUi:false}})
  check('V2605-RENDER-BOUNDS',normalizedRendering.textureStreaming.memoryBudgetMb===16&&normalizedRendering.textureStreaming.idleFrames===36_000&&normalizedRendering.textureStreaming.uploadBudgetPerFrame===1&&normalizedRendering.textureStreaming.preloadMargin===8&&normalizedRendering.deterministicCapture.frameRate===1&&normalizedRendering.deterministicCapture.sampleRate===192_000&&normalizedRendering.deterministicCapture.maximumFrames===18_000&&normalizedRendering.deterministicCapture.memoryBudgetMb===16,'Texture residency and deterministic capture inputs normalize to explicit production limits.')
  renderSettings.applyQualityPreset('Performance');const lowEndSystems=media.MEDIA_PROFILE_CONTRACTS.LowEnd.semanticSystems.join('|'),balancedSystems=media.MEDIA_PROFILE_CONTRACTS.Balanced.semanticSystems.join('|')
  check('V2605-LOW-END-SEMANTICS',renderSettings.renderingSettings.textureStreaming.memoryBudgetMb===96&&renderSettings.renderingSettings.particleBudget===2_500&&lowEndSystems===balancedSystems,'Low-end changes budgets and presentation quality without deleting rendering, animation, audio, timeline or UI semantics.')
  const graphDocument=materialGraph.defaultMaterialGraph('Sprite'),compiledGraph=materialGraph.compileMaterialGraph(graphDocument),canvasPreview=materialGraph.materialCapabilityPreview(graphDocument,[materialGraph.defaultMaterialLayer('Outline')],'Canvas2D'),webglPreview=materialGraph.materialCapabilityPreview(graphDocument,[materialGraph.defaultMaterialLayer('Outline')],'WebGL2'),material=materials.normalizeMaterial({...materials.defaultMaterial('Production material'),graph:graphDocument,layers:[materialGraph.defaultMaterialLayer('Outline')]})
  check('V2605-MATERIAL-PARITY',compiledGraph.diagnostics.length===0&&compiledGraph.source.includes('nova_material')&&webglPreview.fallbackNodes.length===0&&canvasPreview.fallbackNodes.length>0&&materials.validateMaterialForPlatform(material,'web','WebGL2').every(item=>item.severity!=='error'),'Visual materials compile for WebGL2 and retain an explicit named Canvas2D fallback path.')
  const clocks=[24,30,60,120,144].map(displayRate=>media.mediaTimingAudit(10,60,48_000,[displayRate])),plan=cinematic.deterministicCapturePlan(2,60,48_000),edgeClock=cinematic.mediaFrameClock(59,60,44_100)
  check('V2605-MEDIA-CLOCK',clocks.every(result=>result.passed&&result.expectedSamples===480_000)&&plan.frames===120&&plan.clocks.at(-1)?.audioSampleEnd===96_000&&edgeClock.audioSampleEnd===44_100,'Frame capture and audio sample boundaries are integer-stable across variable display rates.',{displayRates:[24,30,60,120,144],captureFrames:plan.frames})
  renderGraph.startDeterministicCapture({name:'Verification',frameRate:60,sampleRate:48_000,maximumFrames:2,memoryBudgetMb:16,includeUi:false});const fakeCanvas={width:320,height:180,toDataURL:()=>`data:image/png;base64,${'A'.repeat(64)}`};renderGraph.captureRenderSurface(fakeCanvas,null);renderGraph.captureRenderSurface(fakeCanvas,null)
  check('V2605-DETERMINISTIC-CAPTURE',renderGraph.renderGraphState.sequence.frames.length===2&&!renderGraph.renderGraphState.sequence.active&&renderGraph.renderGraphState.sequence.frames[1].timeSeconds===1/60&&renderGraph.renderGraphState.sequence.frames[1].audioSampleStart===800&&renderGraph.renderGraphState.sequence.stoppedReason==='Maximum frame count reached','Numbered capture stops at its bound and records deterministic time/audio sample ownership.')
  const emptyReport=media.buildMediaProductionReport([],[],{backend:'WebGL2',drawCalls:4,batches:3,culled:0,triangles:12,textureUploads:0,textureMemoryBytes:0,shaderSwitches:0,lights:1,shadowCasters:0,particlesCpu:0,particlesGpu:0,passes:5,contextLosses:0,fallbackEvents:0,textureEvictions:0,textureBudgetBytes:96*1048576,textureBudgetExceeded:false,streamingMisses:0},{mixer:{buses:[{id:'Master',name:'Master',parent:null,sends:[]}],masterVoiceLimit:32}})
  check('V2605-PRODUCTION-REPORT',emptyReport.checks.length===6&&emptyReport.checks.every(item=>item.status==='ready')&&emptyReport.semanticParity===true&&emptyReport.exportParity===true,'One report joins renderer, material, texture, animation, audio and cinematic build readiness.')

  const [inspector,bottom,i18n,packages,roadmap,readme,zhReadme,contract,layout,renderingPanel,mediaContract]=await Promise.all(['src/components/ContentAssetInspector.vue','src/components/EditorBottomPanel.vue','src/i18n.ts','src/runtime/packages.ts','docs/ROADMAP_26_01_TO_26_10.md','README.md','README.zh-CN.md','docs/ASSET_CONTENT_LIBRARY_26_04.md','docs/UI_LAYOUT_AUDIT_26_04.md','src/components/RenderingPanel.vue','docs/PRODUCTION_MEDIA_26_05.md'].map(read))
  check('V2605-UI-BINDING',inspector.includes('buildAssetDependencyView')&&inspector.includes('setResourceVariantData')&&inspector.includes('productionProfile')&&bottom.includes('contentThumbnailDataUrl'),'Dependencies, variants, profiles and thumbnails reach the actual Assets workspace.')
  check('V2605-PACKAGE-TRUST',packages.includes('permissions')&&packages.includes('signature')&&packages.includes('quarantine'),'Package permission, signature and quarantine controls remain in the content ecosystem.')
  check('V2605-UI-BINDING-MEDIA',renderingPanel.includes("activeSection === 'production'")&&renderingPanel.includes('buildMediaProductionReport')&&renderingPanel.includes('startDeterministicCapture')&&renderingPanel.includes('textureStreaming'),'Production controls reach the canonical media report, texture settings and deterministic capture state.')
  check('V2605-LOCALIZATION',['productionMedia','textureStreaming','deterministicCapture','lowEndProfile'].every(key=>(i18n.match(new RegExp(`${key}:`,'g'))??[]).length>=3),'Every new production-media control has EN/DE/ZH strings.')
  check('V2605-DOCUMENTATION',roadmap.includes('completed in the 26.05 release candidate')&&readme.includes('26.05')&&zhReadme.includes('26.05')&&contract.includes('50,000')&&layout.includes('Asset dependency graph')&&mediaContract.includes('deterministic'),'Roadmap, READMEs, retained content contracts and the production-media contract identify the 26.05 candidate.')
}finally{await rm(compiled,{recursive:true,force:true})}
const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v26.05-verification',version:1,release:'26.05',engineVersion:'26.5.0',generatedAt:new Date().toISOString(),perspectives:['versioning','importers','reimport','dependencies','resources','content-library','export','performance','localization','user'],checks,severity0Open:failed.length,severity1Open:0,status:failed.length?'failed':'passed'}
await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits/v26.05-verification.json'),`${JSON.stringify(report,null,2)}\n`)
if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A 26.05 verification passed: ${checks.length} checks.`)

