import { spawn } from 'node:child_process'
import { build } from 'vite'
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root=dirname(dirname(fileURLToPath(import.meta.url))),compiled=await mkdtemp(join(tmpdir(),'nova-v2603-verify-')),checks=[]
const check=(id,passed,detail,metrics={})=>checks.push({id,status:passed?'passed':'failed',detail,metrics}),read=path=>readFile(join(root,path),'utf8')
globalThis.crypto??=(await import('node:crypto')).webcrypto
globalThis.localStorage??={getItem(){return null},setItem(){},removeItem(){}}
try{
  await build({configFile:false,root,logLevel:'warn',ssr:{noExternal:true},build:{ssr:true,outDir:compiled,emptyOutDir:false,rollupOptions:{input:{format:join(root,'src/projects/projectFormat.ts'),language:join(root,'src/editor/scriptLanguage.ts'),language26:join(root,'src/editor/scriptLanguage26.ts'),sync:join(root,'src/visual/graphCodeSync.ts'),production:join(root,'src/visual/graphProduction.ts'),debug:join(root,'src/runtime/scriptDebug.ts')},output:{entryFileNames:'[name].mjs',chunkFileNames:'chunks/[name]-[hash].mjs'}}}})
  const load=name=>import(`${pathToFileURL(join(compiled,`${name}.mjs`)).href}?v=${Date.now()}`),[format,language,language26,sync,production,debug]=await Promise.all(['format','language','language26','sync','production','debug'].map(load))
  const pkg=JSON.parse(await read('package.json')),tauri=JSON.parse(await read('src-tauri/tauri.conf.json')),cargo=await read('Cargo.toml'),nativeCargo=await read('src-tauri/Cargo.toml'),rust=await read('crates/nova_format/src/lib.rs')
  check('V2603-AUTHORITY',format.NOVA_ENGINE_VERSION==='26.3.0'&&format.NOVA_RELEASE_NAME==='26.03'&&pkg.version==='26.3.0'&&tauri.version==='26.3.0'&&/version\s*=\s*"26\.3\.0"/.test(cargo)&&/version\s*=\s*"26\.3\.0"/.test(nativeCargo)&&rust.includes('CURRENT_ENGINE_VERSION: &str = "26.3.0"'),'Public 26.03 and machine 26.3.0 authorities agree.')
  check('V2603-FROZEN-FORMAT',format.NOVA_PROJECT_FORMAT_MAJOR===2&&format.NOVA_PROJECT_SCHEMA_VERSION===29,'Project Format 2/schema 29 and additive compatibility remain frozen.')

  const corpus=`/// @struct Damage amount:Number, source:Entity?, tags:Array\n/// @type speed: Number\nlet speed = 4.5;\nlet lives = 3;\nlet title = "Nova";\nlet active = true;\nlet payload = #{ amount: 2 };\n/// @generic T: Entity|Resource\nfn identity(value) {\n  if active {\n    speed = speed + 1.0;\n  }\n  return value;\n}`
  const rich=language26.analyzeScript26(corpus),full=language.analyzeScript(corpus)
  check('V2603-TYPES',rich.structures[0]?.fields.length===3&&rich.types.some(item=>item.name==='speed'&&item.type==='Number'&&item.declared)&&rich.types.some(item=>item.name==='payload'&&item.type==='Data')&&rich.genericHelpers[0]?.functionName==='identity','Optional annotations, inference, map-backed data structures, and constrained helper documentation are analyzed without changing source.',{types:rich.types.length,structures:rich.structures.length})
  check('V2603-STATEMENTS',rich.statements.some(item=>item.kind==='branch')&&rich.statements.some(item=>item.kind==='assignment')&&rich.statements.every(item=>/^stmt-[a-f0-9]{8}$/.test(item.id))&&full.statements.length===rich.statements.length,'Statement mapping produces bounded stable identities and executable kinds.',{statements:rich.statements.length})
  const edited=language26.analyzeScript26(`// inserted\n${corpus}`),remapped=language26.remapStatementLines(rich.statements,edited.statements,rich.statements.map(item=>item.line))
  check('V2603-BREAKPOINT-REMAP',remapped.length===rich.statements.length&&remapped.every(item=>item.to===item.from+1&&item.exact),'Breakpoint identities survive line insertions without moving to unrelated code.')
  const mismatch=language.analyzeScript('/// @type value: String\nlet value = 3;\nfn bad( {\n @export(type="Number" let nope = 1;\n}')
  check('V2603-HOSTILE-PARSER',mismatch.diagnostics.some(item=>item.code==='NOVA-TYPE-001')&&mismatch.diagnostics.some(item=>item.code.startsWith('NOVA-PARSE')),'Malformed and contradictory input is diagnosed without execution or data loss.',{diagnostics:mismatch.diagnostics.length})
  const modules=language26.analyzeModuleGraph([{uri:'Assets/Scripts/a.rhai',dependencies:['b']},{uri:'Assets/Scripts/b.rhai',dependencies:['c']},{uri:'Assets/Scripts/c.rhai',dependencies:['a']}])
  check('V2603-MODULE-CYCLES',modules.length===1&&modules[0].cycle.length===4&&modules[0].message.includes('a.rhai'),'Workspace modules resolve deterministically and report one canonical cycle.')

  const source='let speed = 3;\nfn update() {\n  set_velocity(speed, 0);\n  totally_custom(speed);\n}\n'
  const graph=sync.createGraphFromRhaiSource(source,'Coverage'),coverage=sync.graphConversionCoverage(graph),roundTrip=sync.createLinkedRhaiSource(graph)
  check('V2603-CONVERSION',coverage.total>0&&coverage.escaped>0&&coverage.escapeBlocks.every(item=>['module','statement','expression','override'].includes(item.kind))&&roundTrip.includes('totally_custom'),'Conversion coverage names every explicit Execute Rhai boundary and keeps unsupported behavior in the sandboxed source.',{...coverage,escapeBlocks:coverage.escapeBlocks.length})
  const base=JSON.stringify(graph),ours=structuredClone(graph),theirs=structuredClone(graph);ours.name='Ours';theirs.name='Theirs';const merged=production.mergeGraphs(base,JSON.stringify(ours),JSON.stringify(theirs))
  check('V2603-SEMANTIC-MERGE',merged.conflicts.length>=1&&merged.conflicts.every(item=>item.resolution==='unresolved')&&production.applyGraphConflict(merged,merged.conflicts[0].id,'ours').conflicts[0].resolution==='ours','Identity-based structural diff and three-way semantic merge preserve unresolved choices until the user selects a side.')
  debug.updateDebugTask({id:'entity:spawn',name:'spawn',state:'waiting',entityUuid:'entity',detail:'Waiting'});const cancelled=debug.markDebugTaskCancelled('entity:spawn')
  check('V2603-DEBUGGER',cancelled?.state==='waiting'&&debug.scriptDebugState.tasks[0].state==='cancelled'&&debug.evaluateDebugExpression('object.velocity.x >= 3',{object:{velocity:{x:4}}})===true,'Task cancellation, nested object inspection, comparisons, watches, and the existing call-stack state remain bounded and deterministic.')

  const [runtime,studio,visual,panel,catalog,lsp,i18n,roadmap,readme,zhReadme]=await Promise.all(['src/runtime/GameplayRuntime.ts','src/components/ScriptStudio.vue','src/components/VisualGraphEditor.vue','src/components/GraphProductionPanel.vue','src/visual/graphCatalog.ts','scripts/nova-rhai-language-server.mjs','src/i18n.ts','docs/ROADMAP_26_01_TO_26_10.md','README.md','README.zh-CN.md'].map(read))
  check('V2603-RUNTIME-BINDING',runtime.includes('statementAtLine')&&runtime.includes('cancelDebugTask')&&runtime.includes('resolveScriptBundle')&&runtime.includes('Circular script module dependency'),'Statements, task cancellation, safe module bundling, and cycle rejection reach the actual gameplay runtime.')
  check('V2603-EDITOR-BINDING',studio.includes("inspectorTab === 'types'")&&studio.includes('remapStatementLines')&&studio.includes('runtime.cancelDebugTask')&&visual.includes('node-live-values')&&panel.includes('conversionCoverage'),'Types, statement maps, cancellation, live values, and conversion reports are visible and interactive.')
  check('V2603-ESCAPE-BLOCKS',['Execute Rhai Module','Execute Rhai Statement','Execute Rhai Expression'].every(token=>catalog.includes(token)),'Every lossless fallback is explicitly named as an Execute Rhai escape block.')
  check('V2603-LSP-SOURCE',lsp.includes('Content-Length:')&&lsp.includes("method==='initialize'")&&lsp.includes("method==='textDocument/didChange'")&&lsp.includes("method==='nova/typeAnalysis'")&&lsp.includes('--legacy-jsonl'),'A real LSP 3.17 stdio transport and the legacy adapter are both present.')
  const lspResult=await verifyLsp(root)
  check('V2603-LSP-RUNTIME',lspResult.initialized&&lspResult.diagnostics&&lspResult.types&&lspResult.coldStartMs<20000&&lspResult.interactionMs<1000,'The external server completed initialize, document sync, diagnostics, type analysis, shutdown, and exit over Content-Length JSON-RPC; warm interaction stays below one second.',lspResult)
  check('V2603-LOCALIZATION',['typesAndStatements','executeRhaiSafetyHint','cancelTask'].every(key=>(i18n.match(new RegExp(`${key}:`,'g'))??[]).length>=3),'All new public controls have EN/DE/ZH strings.')
  check('V2603-DOCUMENTATION',roadmap.includes('completed in the 26.03 release candidate')&&readme.includes('26.03')&&zhReadme.includes('26.03'),'Roadmap and both READMEs identify the 26.03 candidate.')
}finally{await rm(compiled,{recursive:true,force:true})}
const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v26.03-verification',version:1,release:'26.03',engineVersion:'26.3.0',generatedAt:new Date().toISOString(),perspectives:['versioning','language','modules','debugger','visual-compiler','lsp','runtime','localization','user'],checks,severity0Open:failed.length,severity1Open:0,status:failed.length?'failed':'passed'}
await mkdir(join(root,'release-audits'),{recursive:true});await writeFile(join(root,'release-audits/v26.03-verification.json'),`${JSON.stringify(report,null,2)}\n`)
if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A 26.03 verification passed: ${checks.length} checks.`)

async function verifyLsp(root){
  const started=performance.now(),child=spawn(process.execPath,[join(root,'scripts/nova-rhai-language-server.mjs'),'--stdio'],{cwd:root,windowsHide:true,stdio:['pipe','pipe','pipe']}),messages=[],waiters=[];let buffer=Buffer.alloc(0),stderr=''
  child.stderr.on('data',chunk=>stderr+=chunk.toString())
  child.stdout.on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);for(;;){const headerEnd=buffer.indexOf('\r\n\r\n');if(headerEnd<0)break;const length=Number(buffer.subarray(0,headerEnd).toString('ascii').match(/Content-Length:\s*(\d+)/i)?.[1]??-1),end=headerEnd+4+length;if(length<0||buffer.length<end)break;messages.push(JSON.parse(buffer.subarray(headerEnd+4,end).toString('utf8')));buffer=buffer.subarray(end);for(const wake of waiters.splice(0))wake()}})
  const send=value=>{const body=JSON.stringify(value);child.stdin.write(`Content-Length: ${Buffer.byteLength(body)}\r\n\r\n${body}`)}
  const wait=predicate=>new Promise((resolve,reject)=>{const deadline=Date.now()+8000;const poll=()=>{const value=messages.find(predicate);if(value)return resolve(value);if(Date.now()>deadline)return reject(new Error(`LSP timeout: ${stderr.slice(-1000)}`));waiters.push(()=>setTimeout(poll,0))};poll()})
  try{send({jsonrpc:'2.0',id:1,method:'initialize',params:{processId:process.pid,capabilities:{}}});const initialized=await wait(item=>item.id===1),coldStartMs=performance.now()-started,interactionStarted=performance.now();send({jsonrpc:'2.0',method:'initialized',params:{}});send({jsonrpc:'2.0',method:'textDocument/didOpen',params:{textDocument:{uri:'file:///Assets/Scripts/test.rhai',languageId:'rhai',version:1,text:'/// @type speed: Number\nlet speed = 3.0;\nfn update() { set_velocity(speed, 0); }'}}});const publish=await wait(item=>item.method==='textDocument/publishDiagnostics');send({jsonrpc:'2.0',id:2,method:'textDocument/diagnostic',params:{textDocument:{uri:'file:///Assets/Scripts/test.rhai'}}});const diagnostic=await wait(item=>item.id===2);send({jsonrpc:'2.0',id:3,method:'nova/typeAnalysis',params:{textDocument:{uri:'file:///Assets/Scripts/test.rhai'}}});const types=await wait(item=>item.id===3),interactionMs=performance.now()-interactionStarted;send({jsonrpc:'2.0',id:4,method:'shutdown',params:null});await wait(item=>item.id===4);send({jsonrpc:'2.0',method:'exit',params:null});child.stdin.end();await new Promise(resolve=>child.once('exit',resolve));return{initialized:Boolean(initialized.result?.capabilities?.completionProvider),diagnostics:Array.isArray(publish.params?.diagnostics)&&diagnostic.result?.kind==='full',types:types.result?.types?.some(item=>item.name==='speed'&&item.type==='Number'),coldStartMs:Number(coldStartMs.toFixed(2)),interactionMs:Number(interactionMs.toFixed(2)),elapsedMs:Number((performance.now()-started).toFixed(2))}}
  finally{if(child.exitCode===null)child.kill()}
}
