import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createServer } from 'vite'

const root=dirname(dirname(fileURLToPath(import.meta.url))),output=join(root,'release-audits'),checks=[],check=(id,passed,detail,metrics={})=>checks.push({id,status:passed?'passed':'failed',detail,metrics}),generatedAt=new Date().toISOString()
globalThis.navigator??={hardwareConcurrency:4,userAgent:'Nova_A v4.7 verification'};globalThis.window??={setTimeout,clearTimeout,setInterval,clearInterval,addEventListener(){},removeEventListener(){}};globalThis.localStorage??={getItem(){return null},setItem(){},removeItem(){}}
await mkdir(output,{recursive:true});const server=await createServer({root,appType:'custom',logLevel:'silent',server:{middlewareMode:true}})
try{
  const animation=await server.ssrLoadModule('/src/runtime/animation.ts'),production=await server.ssrLoadModule('/src/runtime/animationProduction.ts'),ui=await server.ssrLoadModule('/src/runtime/uiProduction.ts'),components=await server.ssrLoadModule('/src/world/components.ts'),boxModule=await server.ssrLoadModule('/src/world/BoxEntity.ts'),localization=await server.ssrLoadModule('/src/runtime/localization.ts'),theme=await server.ssrLoadModule('/src/runtime/uiTheme.ts'),prompts=await server.ssrLoadModule('/src/runtime/inputModality.ts')
  const clip=animation.normalizeAnimationClip({name:'Golden',loop:true,frameRate:60,tracks:[{property:'Transform.position.x',targetEntityUuid:null,keyframes:[{time:0,value:0,tangentMode:'Linear',interpolation:'Linear'},{time:1,value:10,tangentMode:'Linear',interpolation:'Linear'}]}],events:[{time:.25,signal:'quarter',payload:''},{time:.75,signal:'three-quarter',payload:''}],markers:[],commandTracks:[],spriteFrames:[]})
  const golden=[0,.25,.5,.75,1].map(time=>animation.sampleAnimationTrack(clip.tracks[0].keyframes,time)),sampling=production.validateAnimationSampling('golden',clip,120)
  check('ANM-GOLDEN-LINEAR',JSON.stringify(golden)==='[0,2.5,5,7.5,10]','Linear animation samples match analytical values.',{golden,sampling})
  const retimed=animation.retimeAnimationClip(clip,.25,.75,2,true),sliced=animation.sliceAnimationClip(retimed,.5,1.5),reduced=animation.reduceAnimationKeys([{time:0,value:0,tangentMode:'Linear',inTangent:0,outTangent:0,interpolation:'Linear'},{time:.5,value:5,tangentMode:'Linear',inTangent:0,outTangent:0,interpolation:'Linear'},{time:1,value:10,tangentMode:'Linear',inTangent:0,outTangent:0,interpolation:'Linear'}],1e-6)
  check('ANM-EDITING',retimed.events[1].time===1.25&&sliced.events.every(event=>event.time>=0)&&reduced.length===2,'Retime/ripple, slice and deterministic key reduction passed.',{retimedEvents:retimed.events,slicedEvents:sliced.events,reduced:reduced.length})
  const forward=animation.animationEventsBetween(clip,.1,2.1).map(event=>event.signal),reverse=animation.animationEventsBetween(clip,2.1,.1).map(event=>event.signal)
  check('ANM-LOOP-REVERSE',forward.join(',')==='quarter,three-quarter,quarter,three-quarter'&&reverse.join(',')==='three-quarter,quarter,three-quarter,quarter','Forward/reverse multi-loop event ordering is exact.',{forward,reverse})
  const stressStart=performance.now();let checksum=0;for(let iteration=0;iteration<100_000;iteration++)checksum+=animation.sampleAnimationTrack(clip.tracks[0].keyframes,(iteration%1000)/1000)??0;const stressMs=performance.now()-stressStart
  check('ANM-STRESS',Number.isFinite(checksum)&&stressMs<30_000,`100,000 runtime samples completed in ${stressMs.toFixed(2)} ms.`,{samples:100000,stressMs,checksum})
  const canvasEntity=new boxModule.BoxEntity(1,{x:0,y:0},{x:1,y:1}),canvasRect=canvasEntity.addComponent(new components.RectTransform()),canvas=canvasEntity.addComponent(new components.Canvas());canvasEntity.name='HUD';canvasRect.anchorMin={x:0,y:0};canvasRect.anchorMax={x:1,y:1};canvas.safeArea=true
  const label=new boxModule.BoxEntity(2,{x:0,y:0},{x:1,y:1}),rect=label.addComponent(new components.RectTransform()),text=label.addComponent(new components.Text());label.name='Score';label.parentUuid=canvasEntity.uuid;rect.size={x:180,y:30};rect.position={x:20,y:10};rect.accessibilityRole='text';rect.accessibilityLabel='Score';text.text='Score 👩🏽‍🚀 é 中文'
  const entities=[canvasEntity,label],matrix=[...ui.validateResponsiveUi(entities,ui.UI_DEVICE_PRESETS,'ltr',44),...ui.validateResponsiveUi(entities,ui.UI_DEVICE_PRESETS,'rtl',44)],finite=matrix.every(result=>result.rects.every(item=>[item.x,item.y,item.width,item.height].every(Number.isFinite)))
  check('UI-RESPONSIVE-MATRIX',matrix.length===12&&finite,'Six device classes render finite LTR and RTL matrices.',{matrices:matrix.length,issues:matrix.reduce((sum,item)=>sum+item.issues.length,0)})
  const source=localization.defaultLocalizationTable('ar');source.direction='rtl';source.entries={'coins':{one:'عملة واحدة',other:'{count} عملات'},'stress':'👩🏽‍🚀 é 中文'};const csv=localization.exportLocalizationCsv(source),po=localization.exportLocalizationPo(source),csvRound=localization.importLocalizationCsv(csv,'ar'),poRound=localization.importLocalizationPo(po,'ar')
  check('LOC-ROUNDTRIP',typeof csvRound.entries.coins==='object'&&poRound.entries.stress==='👩🏽‍🚀 é 中文','CSV preserves plurals and PO preserves Unicode/combining content.',{csvBytes:csv.length,poBytes:po.length})
  const base=theme.defaultUiTheme(),variant=structuredClone(base);variant.tokens.colors.accent='#ffffff';const differences=theme.compareUiThemes(base,variant)
  check('UI-THEME',differences.some(item=>item.path==='colors.accent')&&theme.themeUnusedTokens(base).length>=0,'Theme comparison and unused-token inspection execute deterministically.',{differences:differences.length})
  const actions=[{name:'Jump',kind:'button',bindings:[{device:'keyboard',code:'Space',scale:1,x:1,y:0,gamepad:0,deviceId:'',deadzone:.18,threshold:.0001,invert:false,responseCurve:'linear',modifiers:[],chord:[]},{device:'gamepad-button',code:'0',scale:1,x:1,y:0,gamepad:0,deviceId:'',deadzone:.18,threshold:.0001,invert:false,responseCurve:'linear',modifiers:[],chord:[]}]}],keyboard=prompts.formatInputPrompt(prompts.inputPromptForAction('Jump',actions,'keyboard')),gamepad=prompts.formatInputPrompt(prompts.inputPromptForAction('Jump',actions,'gamepad'))
  check('INPUT-PROMPTS',keyboard.includes('Space')&&gamepad.includes('A'),'Keyboard and gamepad prompts select the matching binding.',{keyboard,gamepad})
}finally{await server.close()}
const failed=checks.filter(item=>item.status==='failed'),report={format:'nova-v4.7-animation-ui-verification',version:1,engineVersion:'4.7.0',generatedAt,checks,severity0Open:0,severity1Open:failed.length,status:failed.length?'failed':'passed'};await writeFile(join(output,'v4.7.0-verification.json'),`${JSON.stringify(report,null,2)}\n`);if(failed.length){console.error(failed);process.exit(1)}console.log(`Nova_A v4.7 verification passed: ${checks.length} checks.`)
