[package]
name = "nova_physics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Platform-independent Nova_A 2D physics engine"

[lib]
crate-type = ["rlib"]

[dependencies]
nova_math = { path = "../nova_math" }
serde.workspace = true
