/** 内置模板目录数据：声明模板分类、检索字段和发现界面使用的元信息。 */
/** Additive 26.11 starters. Each ID has its own authored scene recipe. */
export const TEMPLATE_ADDITIONS_26_11 = [
  { id: 'coin-trail', category: 'game', name: 'Coin Trail', description: 'Collect six checkpoints in order. A gentle keyboard game with scoring, completion, and restart.', de: ['Münzpfad', 'Sammle sechs Wegpunkte der Reihe nach. Tastaturspiel mit Punkten, Abschluss und Neustart.'], zh: ['金币小径', '按顺序收集六个目标。包含键盘移动、计分、通关和重新开始。'], tags: ['collect', 'keyboard', 'score'], features: ['Rhai', 'Input map', 'Score', 'Restart'], difficulty: 'beginner', setupMinutes: 5 },
  { id: 'checkpoint-sprint', category: 'game', name: 'Checkpoint Sprint', description: 'Reach eight checkpoints before the 25-second timer expires; restart and improve your route.', de: ['Wegpunkt-Sprint', 'Erreiche acht Wegpunkte vor Ablauf von 25 Sekunden; starte neu und verbessere die Route.'], zh: ['检查点冲刺', '在25秒内到达八个检查点；重新开始并优化路线。'], tags: ['timer', 'race', 'checkpoints'], features: ['Rhai', 'Timer', 'Score', 'Restart'], difficulty: 'beginner', setupMinutes: 6 },
  { id: 'slalom-run', category: 'game', name: 'Slalom Run', description: 'Weave between alternating hazard islands to collect six ordered flags.', de: ['Slalomlauf', 'Umrunde abwechselnde Gefahreninseln und sammle sechs Fahnen in Reihenfolge.'], zh: ['回转挑战', '绕过交替排列的危险岛，按顺序收集六面旗帜。'], tags: ['slalom', 'hazard', 'keyboard'], features: ['Rhai', 'Hazards', 'Score', 'Restart'], difficulty: 'intermediate', setupMinutes: 7 },
  { id: 'orbit-dodge', category: 'game', name: 'Orbit Dodge', description: 'Collect the outer ring while avoiding two moving hazards on crossing orbits.', de: ['Orbit-Ausweichen', 'Sammle den äußeren Ring und weiche zwei Hindernissen auf kreuzenden Umlaufbahnen aus.'], zh: ['轨道闪避', '收集外环目标，躲避两条交叉轨道上的移动障碍。'], tags: ['orbit', 'moving hazards', 'arcade'], features: ['Rhai', 'Trigonometry', 'Score', 'Restart'], difficulty: 'intermediate', setupMinutes: 8 },
  { id: 'target-circuit', category: 'game', name: 'Target Circuit', description: 'Navigate a figure-eight checkpoint course against a 20-second clock.', de: ['Zielparcours', 'Bewältige einen Achterkurs mit Wegpunkten innerhalb von 20 Sekunden.'], zh: ['目标环赛', '在20秒内完成八字形检查点赛道。'], tags: ['circuit', 'timer', 'arcade'], features: ['Rhai', 'Timer', 'Score', 'Restart'], difficulty: 'intermediate', setupMinutes: 7 },
  { id: 'hazard-crossing', category: 'game', name: 'Hazard Crossing', description: 'Cross three moving hazard lanes and reach the finish; every collision ends the attempt.', de: ['Gefahrenkreuzung', 'Überquere drei bewegte Hindernisspuren bis zum Ziel; jede Kollision beendet den Versuch.'], zh: ['危险穿越', '穿过三条移动障碍通道到达终点；每次碰撞都会结束本轮。'], tags: ['crossing', 'moving hazards', 'arcade'], features: ['Rhai', 'Hazards', 'Win state', 'Restart'], difficulty: 'intermediate', setupMinutes: 8 },
  { id: 'domino-cascade', category: 'test', name: 'Domino Cascade', description: 'Twenty upright dominoes and a moving striker expose contact propagation and sleeping.', de: ['Domino-Kaskade', 'Zwanzig Dominosteine und ein bewegter Stoßkörper zeigen Kontaktübertragung und Ruhezustände.'], zh: ['多米诺连锁', '二十块竖立骨牌与移动撞击球展示接触传递和休眠。'], tags: ['domino', 'physics', 'sleeping'], features: ['RigidBody2D', 'Contacts', 'Continuous collision'], difficulty: 'beginner', setupMinutes: 5 },
  { id: 'pyramid-stack', category: 'test', name: 'Pyramid Stack', description: 'A 28-body pyramid demonstrates settling, mass, friction, and solver stability.', de: ['Pyramidenstapel', 'Eine Pyramide aus 28 Körpern zeigt Ruheverhalten, Masse, Reibung und Solver-Stabilität.'], zh: ['金字塔堆叠', '28个刚体构成的金字塔展示静止、质量、摩擦与求解器稳定性。'], tags: ['stack', 'physics', 'stability'], features: ['RigidBody2D', 'Friction', 'Sleeping'], difficulty: 'intermediate', setupMinutes: 6 },
  { id: 'restitution-gallery', category: 'test', name: 'Restitution Gallery', description: 'Six equal balls fall from the same height with restitution increasing from zero to one.', de: ['Rückprall-Galerie', 'Sechs gleiche Kugeln fallen aus gleicher Höhe mit Rückprallwerten von null bis eins.'], zh: ['弹性系数展厅', '六个相同球体从同一高度落下，恢复系数从零逐步增加到一。'], tags: ['restitution', 'bounce', 'materials'], features: ['EllipseCollider2D', 'Materials', 'Gravity'], difficulty: 'beginner', setupMinutes: 4 },
  { id: 'friction-ramp', category: 'test', name: 'Friction Ramps', description: 'Four separate ramps compare sliding blocks with low through high friction.', de: ['Reibungsrampen', 'Vier getrennte Rampen vergleichen gleitende Blöcke bei geringer bis hoher Reibung.'], zh: ['摩擦斜坡', '四条独立斜坡比较从低到高摩擦系数的滑块。'], tags: ['friction', 'ramp', 'materials'], features: ['Rotated collider', 'Friction', 'RigidBody2D'], difficulty: 'intermediate', setupMinutes: 6 },
  { id: 'pendulum-row', category: 'test', name: 'Pendulum Row', description: 'Five independently anchored distance-joint pendulums begin displaced from equilibrium.', de: ['Pendelreihe', 'Fünf unabhängig verankerte Distanzgelenk-Pendel starten aus ausgelenkter Position.'], zh: ['单摆阵列', '五个独立锚定的距离关节单摆从偏离平衡的位置开始运动。'], tags: ['pendulum', 'joint', 'constraints'], features: ['DistanceJoint2D', 'Gravity', 'Constraints'], difficulty: 'intermediate', setupMinutes: 7 },
  { id: 'billiards-break', category: 'test', name: 'Billiards Break', description: 'A cue ball strikes a ten-ball rack inside a four-wall zero-gravity table.', de: ['Billard-Anstoß', 'Eine weiße Kugel trifft zehn Kugeln auf einem Tisch mit vier Banden ohne Schwerkraft.'], zh: ['台球开球', '母球在无重力的四边围栏球台内撞击十球阵列。'], tags: ['billiards', 'impulse', 'collision'], features: ['EllipseCollider2D', 'Restitution', 'Zero gravity'], difficulty: 'beginner', setupMinutes: 5 },
  { id: 'gravity-fountain', category: 'test', name: 'Gravity Fountain', description: 'Twenty-four balls launch with distinct velocities, tracing ballistic arcs into a catch basin.', de: ['Schwerkraft-Fontäne', '24 Kugeln starten mit unterschiedlichen Geschwindigkeiten und folgen Wurfbahnen ins Becken.'], zh: ['重力喷泉', '24个球体以不同初速度发射，沿抛物线落入收集池。'], tags: ['ballistics', 'velocity', 'gravity'], features: ['Initial velocity', 'Gravity', 'Contacts'], difficulty: 'beginner', setupMinutes: 5 },
  { id: 'shape-poster', category: 'scene', name: 'Shape Poster', description: 'A composed geometric poster with layered shapes and editable world text.', de: ['Formenplakat', 'Ein geometrisches Plakat mit geschichteten Formen und bearbeitbarem Welttext.'], zh: ['几何海报', '由分层几何形状和可编辑世界文本组成的海报。'], tags: ['shapes', 'poster', 'composition'], features: ['ShapeRenderer2D', 'TextRenderer2D', 'Sorting'], difficulty: 'beginner', setupMinutes: 4 },
  { id: 'neon-garden', category: 'scene', name: 'Neon Garden', description: 'Three colored point lights illuminate a symmetric geometric garden in low ambient light.', de: ['Neongarten', 'Drei farbige Punktlichter beleuchten einen symmetrischen Garten bei schwachem Umgebungslicht.'], zh: ['霓虹花园', '三盏彩色点光源在低环境光下照亮对称的几何花园。'], tags: ['lighting', 'neon', 'rendering'], features: ['Light2D', 'Ambient light', 'Shapes'], difficulty: 'beginner', setupMinutes: 6 },
  { id: 'particle-fireworks', category: 'scene', name: 'Particle Fireworks', description: 'Five color-coded particle fountains demonstrate velocity spread, lifetime, and fading.', de: ['Partikelfeuerwerk', 'Fünf farbige Partikelfontänen zeigen Geschwindigkeitsstreuung, Lebensdauer und Ausblenden.'], zh: ['粒子烟花', '五座彩色粒子喷泉展示速度散布、生命周期与渐隐。'], tags: ['particles', 'fireworks', 'effects'], features: ['ParticleEmitter2D', 'Lifetime', 'Color fade'], difficulty: 'beginner', setupMinutes: 5 },
  { id: 'rain-room', category: 'scene', name: 'Rain Room', description: 'A wide rain curtain falls behind a simple architectural silhouette using explicit sorting.', de: ['Regenraum', 'Ein breiter Regenvorhang fällt hinter einer einfachen Silhouette mit expliziter Zeichenreihenfolge.'], zh: ['雨幕房间', '宽幅雨幕通过明确的绘制顺序落在简洁建筑剪影后方。'], tags: ['rain', 'particles', 'sorting'], features: ['ParticleEmitter2D', 'Sorting', 'Composition'], difficulty: 'beginner', setupMinutes: 5 },
  { id: 'starfield', category: 'scene', name: 'Starfield Drift', description: 'Three layers of drifting stars compare particle speed, size, and depth composition.', de: ['Sternenfeld', 'Drei Schichten wandernder Sterne vergleichen Geschwindigkeit, Größe und Tiefenwirkung.'], zh: ['漂移星空', '三层漂移星粒比较速度、大小和纵深构图。'], tags: ['stars', 'particles', 'space'], features: ['ParticleEmitter2D', 'Layering', 'Velocity'], difficulty: 'beginner', setupMinutes: 5 },
  { id: 'orbit-gallery', category: 'scene', name: 'Orbit Gallery', description: 'Six scripted shapes orbit a central star at different radii and angular speeds.', de: ['Orbit-Galerie', 'Sechs geskriptete Formen umkreisen einen Stern mit verschiedenen Radien und Winkelgeschwindigkeiten.'], zh: ['轨道画廊', '六个由脚本控制的形状以不同半径和角速度绕中心恒星运行。'], tags: ['orbit', 'script', 'animation'], features: ['Rhai', 'Transform2D', 'Trigonometry'], difficulty: 'intermediate', setupMinutes: 7 },
  { id: 'sprite-wall', category: 'scene', name: 'Sprite Wall', description: 'Twenty-four tinted instances share one embedded sprite to demonstrate asset reuse and sorting.', de: ['Spritewand', '24 eingefärbte Instanzen teilen ein eingebettetes Sprite und zeigen Wiederverwendung und Sortierung.'], zh: ['精灵墙', '24个着色实例共享一个内嵌精灵，展示资源复用与排序。'], tags: ['sprites', 'atlas', 'reuse'], features: ['SpriteRenderer2D', 'Tint', 'Shared asset'], difficulty: 'beginner', setupMinutes: 5 }
] as const

export type AddedTemplateId = typeof TEMPLATE_ADDITIONS_26_11[number]['id']
